### ISSUE TITLE
Blood Bag causes kick

### ISSUE THREAD

**Issue by Ender917** [DayZMod/DayZ#1]
I've heard reports that blood transfusions are causing issues. After attempting to give a friend a transfusion, I was kicked for "Public variable value restriction 150"

Server log here:

11.06.2013 03:52:01: Josh (108.204.235.37:2304) 32021dd1f3841b0df8084b2e33b84129 - Value Restriction #150 "remExField" = [<NULL-object>,<NULL-object>,"loc","titleText","Transfusion in progress, remain still...","PLAIN DOWN"]

**Comment by R4Z0R49** [comment]
This is a filter update its already been fixed

**Comment by jriesen** [comment]
FYI, I just encountered this issue on a public hive server, latest beta and DayZ version.  Doesn't seem to be fixed?

**Comment by jriesen** [comment]
My bad, I guess this is a server configuration problem (BattleEye configuration or sometimes obsolete mission/server files), gotta take it up with the admin.
