### ISSUE TITLE
be filters

### ISSUE THREAD

**Issue by fgw-** [DayZMod/DayZ#10]
is it intended to log usage of the following variables:

setvariable.txt
1="temperature"

publicvariable.txt
1="PVDZ_plr_LoginRecord"

btw: should i findings or questions related to be filters here, or in the forums over at dayzmod.com?
have seen somebody from here responded to an be filter issue regarding bloodbags ...

**Comment by facoptere** [comment]
setvariable.txt : most verbose SV have been commented out already. Other SV are for admin convenience. But you are right, temperature is not the most useful one.
publicvariable.txt : loginRecord is a PV logged on purpose, it's quite useful and not verbose.

Admins can comment out all rules that begin with "1" in SV and PV filters.

Bloodbags should be fixed.
