### ISSUE TITLE
Vehicles MH6J_DZ and HMMWV_DZ are still missing loot

### ISSUE THREAD

**Issue by bittedanke** [DayZMod/DayZ#100]
Entries for MH6J_DZ and HMMWV_DZ from object_spawns.sql are missing quatity numbers for contained loot:

```
(53278043, 'MH6J_DZ', '[122,[10137.868,12049.376,-6.1035156e-005]]', '[[[],[]],[["1Rnd_Smoke_M203", "7Rnd_45ACP_1911", "30Rnd_556x45_StanagSD", "200Rnd_556x45_M249", "FoodCanPasta", "15Rnd_W1866_Slug", "5x_22_LR_17_HMR", "15Rnd_9x19_M9SD", "17Rnd_9x19_glock17", "100Rnd_762x51_M240", "6Rnd_45ACP", "8Rnd_9x18_Makarov"],[]],[["DZ_Backpack_EP1"],[]]]', '[["motor",1],["elektronika",1],["mala vrtule",1],["velka vrtule",1]]', '', NULL),
(25522943, 'HMMWV_DZ', '[0,[13441.056,12003.912,4.5776367e-005]]', '[[["AK_47_M"],[]],[["PartWoodPile", "ItemBandage", "HandGrenade_west", "6Rnd_45ACP", "ItemEpinephrine", "8Rnd_B_Beneli_74Slug", "HandChemBlue", "8Rnd_B_Beneli_Pellets", "PartEngine", "17Rnd_9x19_glock17", "ItemTent"],[]],[["DZ_CivilBackpack_EP1"],[]]]', '[["palivo",1],["motor",1],["karoserie",1],["wheel_1_1_steering",1],["wheel_1_2_steering",1],["wheel_2_1_steering",1],["wheel_2_2_steering",1]]', '', NULL);
```

**Comment by R4Z0R49** [comment]
looks ok.

**Comment by bittedanke** [comment]
How does 
...[[["AK_47_M"],[]],[["PartWoodPile...
looks ok, when it should look like
...[[["AK_47_M"],[1]],[["PartWoodPile...
?

All items for these two entries are missing the quantity numbers!  Once I enter numbers these two vehicles no longer spawn empty. 

All other entries from object.spawns.sql have these numbers on the contained items.
Example:

(89226080, 'UH1H_DZ2', '[60,[11279.154,4296.0205,0]]', '[[[], []], [["ItemSodaMtngreen","ItemSodaMtngreenEmpty"], [1, 2]], [[], []]]', '[["motor",1],["elektronika",1],["mala vrtule",1],["velka vrtule",1]]', '', NULL),

->

... [["ItemSodaMtngreen","ItemSodaMtngreenEmpty"], [1, 2]], ...

Or did you mean the you fixed it?

**Comment by Skaronator** [comment]
Ah alright, we will fix it.
Thanks
