### ISSUE TITLE
Spawn location selection doen't work on my private server

### ISSUE THREAD

**Issue by managu** [DayZMod/DayZ#103]
Hi,

I have a private server on HFB servers i have enabled  spawnselection

In init.sqf 

dayz_spawnselection = 1;

but doesn't work  

does it change anything?

thanks for you help

**Comment by sharkiller** [comment]
spawnselection work. you should talk to your server provider to check the files.

**Comment by Skaronator** [comment]
Spawnselection doesnt work with the reality server hive btw.

**Comment by empside** [comment]
It working if you change HiveExt.dll from "genderselect" folder.
