### ISSUE TITLE
Request to use DayZ code for DayZRP

### ISSUE THREAD

**Issue by Rollese** [DayZMod/DayZ#105]
Hello!

I would like to ask permission to use and modify DayZ code in the following files: dayz_code, dayz_anim, dayz_server, dayz_sfx and dayz_communityassets for use on DayZRP servers (www.dayzrp.com). I will include all DayZ Credits in the mod folder, all modified files and on our download page as well as recreate a new issue post every 3 month requesting continued use of all assets for all future releases I make. Thank you for your consideration.

**Comment by Skaronator** [comment]
You must include all Dayz Credits and recreate a new issue post requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested. If you fine with the this info just reply or if you have any other questions regarding the license plz reply.

**Comment by Rollese** [comment]
I accept these terms.

**Comment by Skaronator** [comment]
Alright thanks.
