### ISSUE TITLE
Siphon fuel from cows, chicken, infected, survivors

### ISSUE THREAD

**Issue by fedediss** [DayZMod/DayZ#108]
Me and my mate just discovered that you can choose the "siphon fuel" command from survivors, infected, animals, while carrying a empty jerrycan... Sadly, it says "Chicken does not have enough fuel to siphon"
i link a screenshot http://cloud-2.steampowered.com/ugc/612777796715151620/2F88FBDA0B019939CC48258A10344A619F357437/

**Comment by dlatz** [comment]
And you can siphone fuell from cars without hose.

**Comment by Skaronator** [comment]
This has been already fixed, thanks for the report!
