### ISSUE TITLE
Rotate the tent/camo net command doesn't work

### ISSUE THREAD

**Issue by fedediss** [DayZMod/DayZ#109]
Keys Q and E to rotate the camping tent / camo net don't works at all... Both keep the same orientation

**Comment by wolf-van-eden** [comment]
By me work fine^^. Maybe it doesnt work on all positions. But it works to when you try to put it in a tree^^

**Comment by AlbyBDPK** [comment]
It works on your lean left/right buttons, if you rebound them then you will have to use whatever you have them set to instead.
