### ISSUE TITLE
SetPos Count Restriction

### ISSUE THREAD

**Issue by dayz-herbert** [DayZMod/DayZ#11]
People are getting kicked for this SetPos Count Restriction, the current restriction in place for SetPos are as follows:

5 "" !"FunctionsManager" !"Shot" !"z_doctor" !"z_hunter" !"z_new_villager1" !"z_new_villager2" !"z_new_villager3" !"z_new_villager4" !"z_new_worker1" !"z_new_worker2" !"z_new_worker3" !"z_new_worker4" !"z_policeman" !"z_priest" !"z_soldier_heavy" !"z_soldier_pilot" !"z_soldier" !"z_suit1" !"z_suit2" !"z_teacher" !"z_villager1" !"z_villager2" !"z_villager3" !"z_worker1" !"z_worker2" !"z_worker3" !"zZombie_Base"
5 "  "

When checking the .log file for SetPos, people are still getting kicked for when there are multiple instances within the logs for any of the above class names.

**Comment by facoptere** [comment]
"Count" is not related to filter lists. It's a parameter in your battleye config (where you can find RConPassword, MaxPing, etc).
You have to setup MaxSetPosPerInterval, maybe with the same value as MaxCreateVehiclePerInterval.

**Comment by dayz-herbert** [comment]
Thank you, yes we found it earlier.
For anyone else with this issue it is within the BEServer_active_91a.cfg under your BattlEye folder.

**Comment by icomrade** [comment]
BEServer_active_91a.cfg is a variation of BEServer.cfg -- meaning BEServer.cfg is the normal file name. The file name is randomized on startup of the server and set back to normal on shutdown, you need to restart your server for these changes to take hold.
