### ISSUE TITLE
cars disappear

### ISSUE THREAD

**Issue by wolf-van-eden** [DayZMod/DayZ#110]
I have my vehicles stored separately. Resp. helicopter and I then left the game. The heli was nowhere to be found. neither in the whole nor use away on his spawn point.
No other player may have taken the helicopter because no one has the password for the server.
Also, I was driving to the nearest gas station and drove on. Saved and went on to foot. The client smeared off and start again after I was at the gas station and my car stored on the site.

Also the other tack from post 91, I can only confirm.

**Comment by wolf-van-eden** [comment]
All cars and choppers disappear with all things inside

**Comment by facoptere** [comment]
public hive? it's a common issue with the public hive.

**Comment by wolf-van-eden** [comment]
Cars every day deleted but i have no public hive. I can drive my car the day. I can make server restarts. Its all ok but next day all cars disappear.

**Comment by icomrade** [comment]
It sounds like an issue with your hive extension setup or database, verify setting in hiveext.ini are correct, and that the database user has permissions to read from all necessary table. Also if you are using an outdated version of the hive you must update it, official hive or third party.

If this does not help then comb through your .RPT and look for errors, errors may occur when loading vehicles if one is corrupt in the database, also please ensure that your instance ID is the same in your mission as the DB. operating 2 separate IDs on one database will work but vehicles/players will change according to your active ID.
