### ISSUE TITLE
Request to use 1.8 code for Dayz Overwatch

### ISSUE THREAD

**Issue by scrumbee** [DayZMod/DayZ#113]
I would like permission to use the DayZ mod code in DayZ Overwatch

I will include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future releases I make.

I fully understand the limitations of editing only the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx & dayz_comunityassets.

**Comment by Skaronator** [comment]
You don't need to recreate a new issue as long the license is still Active. 
DayZ Overwatch AKA scrumbee - 02/07/2013 << Thats fine
