### ISSUE TITLE
The new invetory

### ISSUE THREAD

**Issue by KG7854** [DayZMod/DayZ#114]
Hello, when you press "G" the inventory is hard to see, it looks really cartoonish and not very cool. Can you change it back to the old one or make a new one that looks like the old one, and then give us an option what one we want to choose? Because just looking at the new inventory system it make me not want to ever play DayZ again. Just my opinion and wanted to voice it so maybe someone here who has control of it can change it up a bit to be easier to see and use.

**Comment by R4Z0R49** [comment]
Thanks for your feedback but i don't think we will see it change anytime soon.

**Comment by icomrade** [comment]
Not to mention that the original gear menu does not have a carry slot. It's just not possible to use the standard one.
