### ISSUE TITLE
Tripwire Grenade can not be created from required components

### ISSUE THREAD

**Issue by oldsher** [DayZMod/DayZ#115]
1 String, 1 Wood PIle, 1 Duct Tape and 1 M67 Grenade, won't craft anything.
In file TrapTripwireGrenade.hpp from dayz_code.pbo you see 
{"HandGrenade_west","CfgMagazines",1}
but M67 Grenade class name is "HandGrenade_West"

**Comment by AlbyBDPK** [comment]
Fix in testing now.
