### ISSUE TITLE
Some issues, falling from heli, glass wont break at hospital.

### ISSUE THREAD

**Issue by hannemaster** [DayZMod/DayZ#116]
Hi,

first issue I encountered was when me and my friend were flying in the Huey. I was in the back seat(next to driver) when I switched to gunner seat I fell from the helicopter. 

When I was at the hospital at Berezino I emptied 2 mags with my m4 cco sd and was not able to break the window.

**Comment by Skaronator** [comment]
Both are issues with Arma 2 and the Serverperformance itself.

**Comment by icomrade** [comment]
Yeah I kind of figured that in high desync/lag instances switching seats in a helicopter would probably drop you from it. I need to find a secure way to prevent this from happening. As for the windows you must shoot them out on the corner windows, the ones at the left or right walls.
