### ISSUE TITLE
Tents Not Removing From DB After Packing

### ISSUE THREAD

**Issue by seaweeduk** [DayZMod/DayZ#120]
I packed a couple of tents last night, a few hours later the server restarted and the tents were back in place + I had two tents in my inventory. This is under Reality. 

There is also a tent saving issue, there's a fix posted on opendayz but it would be nice if we could get it fixed in the default code. I had enough of tent dupers more than a year ago!

**Comment by R4Z0R49** [comment]
I'm not seeing any issue with any of them ?

DB removes on pickup and item saves when the player get's close,opens gear or hits save.

Ill do some more testing when i get back on sunday

**Comment by seaweeduk** [comment]
I think it may have been an isolated incident, possibly connected to database sync although it was over 30 minutes before the server restart that I packed them. I tested a couple more and can't replicate it either since. 

I was having problems with tents not saving till I made this change - http://opendayz.net/threads/fix-tent-saving-issues-for-1-8-reality-hive.14107/
