### ISSUE TITLE
Bodies disappearing after kill

### ISSUE THREAD

**Issue by artopaper** [DayZMod/DayZ#121]
Bodies from other persons just disappear when u shoot them.

I.E.

i was lying behind a living guy, i shot him dead, wanted to loot him, but his body just disappeard, but its said "man" when i was scrolling but there was nothing left on the ground.....

**Comment by Skaronator** [comment]
Did this happens every time?

**Comment by icomrade** [comment]
Bodies disappearing is connected to aborting too early, I.e. before returning to lobby automatically. If the player alt+f4 there is nothing we can do about it.

**Comment by artopaper** [comment]
i clicked like his gear, to get his stuff and then his body disappeared, so it wasnt instantly after killing him

**Comment by facoptere** [comment]
There is a bug here. server_onPlayerDisconnect is called few secondsafter server_playerDied, however the corpse is not there. Apparently there is no "alt-F4" or early abort.
