### ISSUE TITLE
FPS Drops From Planes

### ISSUE THREAD

**Issue by seaweeduk** [DayZMod/DayZ#122]
One of the things players complain about a lot on my server is huge FPS drops when someone is in a plane and circling them whilst they are trying to loot etc.

I think its connected to zombie agro can this be disabled again? They agro even when a plane is miles away and really high up and obviously lose interest anyway once it has passed over.

**Comment by R4Z0R49** [comment]
We should be able to just disable the plane from the agro system.

**Comment by seaweeduk** [comment]
That would be great, I tried a patch myself last night in player_alertZombies.sqf but I was still drawing agro so I wait for you guys to update and hopefully and learn something

**Comment by seaweeduk** [comment]
status: wontfix D:

**Comment by R4Z0R49** [comment]
We dont need a fix we have one but it cant be released until the next main patch hotfix's are just that to correct an issue with the current changes.  Alert was never edited and needs a hole new system to be added and then new testing
