### ISSUE TITLE
GPS more common then Compass

### ISSUE THREAD

**Issue by dlatz** [DayZMod/DayZ#124]
Me and my friends have some dificulty finding compass, since 1.8 i havent find one, but found 30 GPS.

P.S.

Can you guys make numbers on compass a little biger?

**Comment by AlexAFlorov** [comment]
maybe problem is u can't see it on ground cos it have own green model?

**Comment by dlatz** [comment]
well i played 1.7.1 and i know how the compass look like, if thats what you think?

**Comment by dlatz** [comment]
found the first one yestarday in shop since 1.8 relese.

**Comment by RedPyr4mid** [comment]
Same issue for me, found 2 GPSs and not a single compass since 1.8 release.

**Comment by R4Z0R49** [comment]
Compass spawns in 5 Locations. (Hunting,Castle,Supermarket,InfectedCamps,HeliCrashEAST)
GPS spawns in 2 Locations. (Military,MilitarySpecial)

**Comment by Skaronator** [comment]
R4Z0R49 said the fact already

```
Compass spawns in 5 Locations. (Hunting,Castle,Supermarket,InfectedCamps,HeliCrashEAST)
GPS spawns in 2 Locations. (Military,MilitarySpecial)
```
