### ISSUE TITLE
Request to use/utilize DayZ 1.8 code in DayZed

### ISSUE THREAD

**Issue by cyrq** [DayZMod/DayZ#125]
I would like to ask for permission to use the DayZ Mod code in my fork called DayZed

I will include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future release i do and im willing to backport code/models/sfx/animations to the official if requested.

Understand that im only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create you must seek BIS/Deans permission to edit any other pbo.

**Comment by AlbyBDPK** [comment]
The name may cause confusion to players and we do suggest that it be changed prior to public release. However, permission is granted as long as the license conditions are followed.

**Comment by cyrq** [comment]
I agree with the licence conditions.
