### ISSUE TITLE
Tents not being updated

### ISSUE THREAD

**Issue by iaretechnician** [DayZMod/DayZ#127]
When you create a tent you are able to insert gear initially. AFTER the server restarts, any items removed or added are not saved to the database.   So after the first restart, the tents will spawn every restart with whatever gear was initially stored in them.

This is related to https://github.com/DayZMod/DayZ/issues/120  and was said to be fixed by http://opendayz.net/threads/fix-tent-saving-issues-for-1-8-reality-hive.14107/

**Comment by Skaronator** [comment]
Do you use Reality Serverfiles or our offical serverfiles?

**Comment by empside** [comment]
If you using Reality, check this: http://opendayz.net/threads/fix-tent-saving-issues-for-1-8-reality-hive.14107/#post-75991
