### ISSUE TITLE
Request to use DayZ 1.8 code DayZ Banjaxed

### ISSUE THREAD

**Issue by nickhiker** [DayZMod/DayZ#128]
I would like to request permission to use and modify the following files: dayz_code, dayz_anim, dayz_server, dayz_sfx and dayz_communityassets. I understand that other pbos are forbidden due to license issues and tools used to create and that I must first seek BIS/ Dean Halls permission to edit any other pbo.

This will be for a mod called DayZ Banjaxed.

I will include all DayZ Credits in the mod folder  as well as recreate a new issue post every 3 month requesting continued use of all assets for all future releases I make. 

In turn if there is anything within DayZ Banjaxed that you would like to port back into the main community mod, you're of course welcome to whatever you like.

Thank you for your time. 

Nick

**Comment by Skaronator** [comment]
alright ty
