### ISSUE TITLE
fa_coor2str

### ISSUE THREAD

**Issue by empside** [DayZMod/DayZ#129]
Hello! I would like to talk about function "fa_coor2str" in "fa_hiveMaintenance.sqf". I think it's not issue but it will be rather if you change this:

_res = format["%1 [%2:%3]", _town, round((_pos select 0)/100), round((15360-(_pos select 1))/100)];

to this:

_res = format["%1 [%2:%3]", _town, floor((_pos select 0)/100), floor((15360-(_pos select 1))/100)];

It will be correct mapping of the square.

Sorry for my Bad English. Thanks!

**Comment by Skaronator** [comment]
Thank you
