### ISSUE TITLE
1.8.0.1 FILL JERRY CAN ISSUE

### ISSUE THREAD

**Issue by fazmond** [DayZMod/DayZ#131]
I know im early but I just posting about the fuel tanks not giving the option to fill jerry cans

my guys were wondering if you needed a hose or its just another bug

we got helis waiting for refuel :)

just to add its just the patch we installed we did not download a new mission file as it didn't say it was updated for this patch on the log

**Comment by R4Z0R49** [comment]
just tested with both 20l and 5l no issues.

**Comment by fazmond** [comment]
its defo not working on our server you can fill cars but its when you goto the BIG FUEL container it has no option to fill the can 

can you confirm if you need to download a new mission file ?

**Comment by R4Z0R49** [comment]
You Dont.

I just tested this myself with both the 20l and 5L fuel cans from the nwaf. I was able to refuel without any issues.

**Comment by fazmond** [comment]
its not just me all my guys cant get the fill jerry can option to work either
were these new jerry cans or ones you had before the patch ?

**Comment by R4Z0R49** [comment]
Without more info not sure what to say you reported we tested and got different results.

Restart the server and try again. restart clients and try again.

It might be part of the spawn system delays we have been seeing.

**Comment by fazmond** [comment]
yep server has restarted all clients restarted , BE scripts updated and still the same thing 

I updated the server using the SERVER FULL INSTALL 

Problem persists if you can connect to our server and try it UK 367 8bitgamers

**Comment by R4Z0R49** [comment]
Can we get a pic of the fuel station your trying to get fuel from and location

**Comment by fazmond** [comment]
NE airfield not working . Staroye and Zelenegorsk and other not working and station at 104064
also tried both 5 and 20L can both don't work

**Comment by R4Z0R49** [comment]
Ok i've found the issue it looks like someone edited the the fuel tank list without testing all the fuel stations the larger airport points don't seem to be working but the smaller points are working as they should be.

**Comment by fazmond** [comment]
ok glad to of helped :)
will there be a fix for this soonish

**Comment by R4Z0R49** [comment]
Considering the hotfix isn't out to the public it will be part of the hotfix.

**Comment by R4Z0R49** [comment]
K issues have been resolved and new files uploaded waiting or final approval and release.
