### ISSUE TITLE
SERVERHOSTERS FTP FULL SERVER INSTALL GIVING WRONG DAYZ VERSION

### ISSUE THREAD

**Issue by fazmond** [DayZMod/DayZ#134]
Hi im back just thought you might like to check into your 
Serverhosters ftp files

I update our server with the full server install 
Dayz commander showed that it was 1.8.0.1 but when trying to connect to it 
it says that im running the incorrect dayz version

NOW BEFORE YOU START NOTE
my client is updated ok and could join other servers with the version 

so I decided to update the server also through dayzcommander and restarted it
and the server works fine

which is leading me to believe that the wrong files might be uploaded to your FTP 
http://serverhosters.dayz.nu/latest/1.8.0.1/
well at least for the full server install

**Comment by R4Z0R49** [comment]
Just downloaded. version show as        version = "1.8.0.1";

No issues.

**Comment by fazmond** [comment]
yes please read above
it shows as version 1.8.0.1 EVEN IN DAZCOMMANDER IT SHOWS THE SERVER RUNNING 1.8.0.1 
BUT on connecting to a server that is INSTALLED USING THESE FILES there is a problem and kicks you back to the lobby screen.

to test this you will need install these files to a server and try to connect to it.

**Comment by R4Z0R49** [comment]
Just check your rpt file of the client it should say why.

However i am downlaoding to test now

**Comment by fazmond** [comment]
our server is up and running now with ppl on otherwise I would see if I could reproduce this error

**Comment by R4Z0R49** [comment]
Downloaded the @dayz for the client
Downloaded the @server for server

installed both.
Connected to server and playing fine no errors in joining.

**Comment by fazmond** [comment]
ok it was the @Server-1.8.0.1-Full.rar 

maybe will just have to wait and see if anyone else has the issue thanx for looking thou.

**Comment by facoptere** [comment]
I did setup my servers with @Server-1.8.0.1-Full.rar and no issue.

**Comment by R4Z0R49** [comment]
K np Fazmond and thanks Facoptere.

There is a loot issue we know about a stupid local build issue :-(

**Comment by fazmond** [comment]
ok so just updated the server using the NEW 1.8.0.2 SERVER FULL
updated my client 
same issue gave me incorrect version when trying to launch the game

AGAIN I had to launch dayzcommander and do an update on the server install 

even though after copying the files from the zip and launching dayzcommander , it detected server only running 1.8.0.1 so there has to be something wrong with the files in that zip somewhere 

this isn't me being stupid or copying the files in the wrong place I can assure you 

Im pretty sure somethings not right with that zip

**Comment by fazmond** [comment]
so after updating only the server with dayzcommander 
and not touching my client im able to connect to it and are both running the same version

there has to be something wrong with the zip! id put a lot of money on it !

**Comment by R4Z0R49** [comment]
Both myself and faco tested the @server files last night. All the files are built at the same time from the same working directory.

Both of us got the same result,

Ill monitor see if others report the same issues.

ty

**Comment by facoptere** [comment]
No problem with 1.8.0.2 too. But I use my own tool to unrar, put in lower case and copy filenames in the right folders.

Maybe the problem is in your tools (dayzcommander, FTP client or server).
Check also that there is only 1 version of each file on the Addons folders, sometimes several versions can co-exist in the same folder because of a mix of  lower/upper cases in filenames.

**Comment by fazmond** [comment]
well its only the last 2 updates I had a problem with and im justing using winrar 4.20 32bit to extract the files.
not using any ftp client just clicking the link @ http://serverhosters.dayz.nu/latest/ 
opening not saving then extracting as ive always done. 
just annoying as I want to prove theres something not right but my server has ppl on it and I just want to keep it running instead of trying to replicate this again
