### ISSUE TITLE
Request to use Dayz Code

### ISSUE THREAD

**Issue by Sharkking** [DayZMod/DayZ#135]
I would like to ask for permission to use the DayZ Mod code in my "uptodate Taviana" project. It is a framework to keep Taviana Map up2date with the latest dayz code. 
dayz_code.pbo, dayz_anim.pbo  and dayz_server.pbo are the only files to be changed

I will include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future release i do and im willing to backport code/models/sfx/animations to the official if requested.

Understand that im only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create you must seek BIS/Deans permission to edit any other pbo.

**Comment by Skaronator** [comment]
kk thanks you, can you also include your modname? Or is it simple Tavi?

**Comment by Sharkking** [comment]
it is simple Tavi as of now.

**Comment by Skaronator** [comment]
alrighty
