### ISSUE TITLE
1.8.02 loot problem

### ISSUE THREAD

**Issue by jackthenipper** [DayZMod/DayZ#138]
THIS GAME IS AWESOME!

ok and then the bad thing.
in this 1.8.02 update
there is this problem that when you spawn there is no loot enywhere.
not even empty tin cans.. nothing. when you run to another town/city..
it´s empty too.

every server where i go is this same problem and every one is talking about it in eny server where i go.

one server restarted when i was there and this time there was loot but it was so small.
i spawned near kamehka next to this factory where usually this building is loaded whit cans of food. usually axe or crowbar. and plenty of other stuff.
this time there was enginepart and flare...
well. i started running to nearest city. there is this one town and there is
one food can and bandage,
then its this military tent place where is one box of painkillers epipen and shotgun ammo.. not ammos.. ammo.. 1... 
when i get to big city and im about to die in thirst.
its nearly empty. shop has empty tin can and snickers bar on the floor...
some houses totally clean...
ok but my point is. when you die and respawn there is no loot at all!
absolutelly nothing!
and im sorry if this issue was already here. :(

**Comment by R4Z0R49** [comment]
The issue has nothing to do with loot spawning its the bias system we use. Have a look in your RPT file and search lines starting with SpawnCheck.

Your rpt file can be found %appdata%../local/

**Comment by Fluxley** [comment]
I've been seeing issues with no loot spawning too, on occasion i'll enter an area and find nothing at all.
my client rpt shows W.holders: 0/80.

i can link my rpt if you like.

**Comment by R4Z0R49** [comment]
Just means the bias hasn't spawned any loot. I think whats happening is we tag the building no matter if the bias allows loot or not. Ill change this around and only tag once the building has spawned loot. See if that improves the chances.

**Comment by R4Z0R49** [comment]
Flux jump on skype plz.

**Comment by ggregory84** [comment]
I'm encountering the same issue on my server, as 1.8.0.2 claims to allow admins to change bias - where can I find this and how can I edit it?  I have entire towns spawning NOTHING

**Comment by R4Z0R49** [comment]
1.8.0.2 claims to allow admins to change bias.

Not sure where you get this info.

**Comment by ggregory84** [comment]
either way, no matter what I do to my server I'm still having buildings spawn NOTHING at all for long periods of time, players are just leaving the server and I can't tell if this is a bug or how it's meant to be

**Comment by R4Z0R49** [comment]
We dont know its being debuged but atm we just are not 100% sure whats going on.

**Comment by ggregory84** [comment]
awesome, thanks for the reply, but others are experiencing it?

**Comment by R4Z0R49** [comment]
Yea others are we just cant find the issue just yet,

**Comment by ggregory84** [comment]
that's a relief - been thinking it was me all this time as it's not plastered all over forums

**Comment by ggregory84** [comment]
anyway we can be of help? bleeding players here

**Comment by AlbyBDPK** [comment]
The issue has been found, I am writing a fix for it now.

**Comment by ggregory84** [comment]
I love you and want to bear your children...

**Comment by ggregory84** [comment]
what was causing it?

**Comment by R4Z0R49** [comment]
We are broadcasting a diag_ticktime to all clients so what we have now is that the second person to spawn needs to wait 15mins PLUS the difference between his diag_tickTime and whoever set it. that could be hours or could actually be instant if the second person had been playing on another server for awhile and just swapped servers.

**Comment by ggregory84** [comment]
so is it the INTENT that entire buildings/areas spawn nothing at all for hours on end?

**Comment by AlbyBDPK** [comment]
No. That would be stupid. Also I said we have a fix for the issue...

**Comment by ggregory84** [comment]
didn't mean to offend, was just curious! thank you for your work, it is very much appreciated!

**Comment by betz0r** [comment]
this is fixed. loot spawns now as  R4Z0R49 described in his post. first not much but other players joining areas are spawning loot after different time. guess it works now. great work guys, thx!
