### ISSUE TITLE
Watermark is not displayed

### ISSUE THREAD

**Issue by lWmPl** [DayZMod/DayZ#14]
Watermark is not displayed on my private server. I typed "LastHC" in Server Name but in game inscription is missing.

**Comment by Silentspy** [comment]
Can you please send me your mission file either through mediafire or ge.tt

**Comment by lWmPl** [comment]
http://yadi.sk/d/c54nZ9S05lQya - click blue button. :)

**Comment by Silentspy** [comment]
try now!

**Comment by lWmPl** [comment]
Try what? Create new mission on Silentspy?

**Comment by Silentspy** [comment]
Yes :P not sure what else to think!

**Comment by lWmPl** [comment]
Ok. Just a few minutes.

**Comment by lWmPl** [comment]
Ok, watermark now work. But i have some problem with autentification. When i start server first time and try to login, i cant pass autentification, and dedicated server crash.

**Comment by R4Z0R49** [comment]
What @hive system are you using ?

**Comment by R4Z0R49** [comment]
As Issues is now done ill close open another for the auth issue.

**Comment by lWmPl** [comment]
I use server pack by Pwn0zor. And autentification problem with server crash was only onсe, when i start server first time! Now all work normal. Thx for such damn quick help! :)
