### ISSUE TITLE
Ingame date is froze on August 3, 2013

### ISSUE THREAD

**Issue by lWmPl** [DayZMod/DayZ#143]
HiveExt.ini:

[Time]
;Possible values: Local, Custom, Static
;You cannot use Static on OFFICIAL Hive, it will just revert to Local
Type = Static
;If using Custom type, offset from UTC in hours (can be negative as well)
;Offset = 0
;These 2 settings only apply if using Static type (Custom date/time on every server start)
;The value (0-24) to set the Hour to, if commented or empty then the hour won't be changed
Hour = 13
;The value (DD/MM/YYYY) to set the Date to, if commented or empty then the date won't be changed
Date = 10.10.2013

But in game date is August 3, 2013

**Comment by R4Z0R49** [comment]
Time is forced to this date to give full moon nights. We will provide a setting to disable this option at on the next patch

**Comment by lWmPl** [comment]
Can i disable this now? Or just change date?

**Comment by R4Z0R49** [comment]
removed last msg. It seems github don't like that format not sure why.

You need to to edit the server.bpo

system/server_montor and server_cleanup search for 
_date1 = [2013,8,3,_hour,_minute]; 
and change to
_date1 = [_year,_month,_day,_hour,_minute]; an

**Comment by lWmPl** [comment]
And HiveExt.ini settings will work as it should?

**Comment by R4Z0R49** [comment]
should do long as its not using the offical database.

**Comment by lWmPl** [comment]
No, i use private db. Thx for such quick help!

**Comment by lWmPl** [comment]
And its work! Thx again!

**Comment by SURT78** [comment]
Is incorrect:

You must sign the front of each variable _
Example: _year _month

**Comment by lWmPl** [comment]
Yep, I see code.
