### ISSUE TITLE
DAYZ 1.8.0.2  ITEM DUPE

### ISSUE THREAD

**Issue by coria16** [DayZMod/DayZ#144]
when a player disconect and reconect some items are duplicated in the inventary .

![dupe1](https://f.cloud.github.com/assets/5659130/1310140/d4f47366-31eb-11e3-98c4-d23198fcc8a3.jpg)
![Uploading dupe2.jpg . . .]()
![dupe3](https://f.cloud.github.com/assets/5659130/1310163/62db3d9a-31ec-11e3-8b5c-3eb0bc43e634.jpg)

**Comment by R4Z0R49** [comment]
Get us info about the servers your playing on. without more info closing.
