### ISSUE TITLE
1.8.0.1 and 1.8.0.2 is not available on Steam

### ISSUE THREAD

**Issue by hhrhhr** [DayZMod/DayZ#145]
> Right click Arma2: DayZ Mod, select properties.
> When the window pops up go to the "BETAS" tab
> Now Select 1.8.0.2 in the drop down box.

only 1.8:

![dayz_1 8 0 2_not_aviable](https://f.cloud.github.com/assets/966048/1310373/09b194cc-31f0-11e3-9c12-2cb1bca42b36.png)

**Comment by R4Z0R49** [comment]
They are no longer moved to the own sub section the main branch should always be the latest version from what im being told.
