### ISSUE TITLE
Humanity is not increasing

### ISSUE THREAD

**Issue by dlatz** [DayZMod/DayZ#146]
Im playing on one private server, which has the signature for forums/sites where you can see how much humanity you have, zombies kill count, play time. Now i notice that the humanity is not increasing after blood transfusions, or increases very little (for 2-3 blood transfusions im getting cca 150 humanity). On the other hand a notice that when others players kill someone their humanity decreases, so i think that this cant be issues with server signature, but im might be wrong.

**Comment by Fluxley** [comment]
There was a new system introduced a while ago, now the amount of humanity gained is dependent on the amount of blood given. i think its 25 humanity per 1000 blood.

**Comment by dlatz** [comment]
if that so, close

thx :)
