### ISSUE TITLE
Request to use DayZ content and code in DayZ Arbon

### ISSUE THREAD

**Issue by mc-kun** [DayZMod/DayZ#148]
I would like to ask for permission to use the DayZ Mod code in my mod DayZ Arbon

I will include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future release i do and im willing to backport code/models/sfx/animations to the official if requested.

Understand that im only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, 
MFG Armin

**Comment by Skaronator** [comment]
kk ty
