### ISSUE TITLE
Siphon unlimited fuel from old bike

### ISSUE THREAD

**Issue by ghost** [DayZMod/DayZ#150]
You can siphon an unlimited amount of fuel from an old bike. Simple fix below:

in fn_selfactions.sqf

Line 67 add: _isBike = _cursorTarget isKindOf "Old_bike_TK_INS_EP1";

Change line 166 to:

if ((_hasFuelE20 or _hasFuelE5) and !_isZombie and !_isAnimal and !_isMan and !_isBike and _isVehicle and _canDo and !a_player_jerryfilling and (fuel _cursorTarget > 0) and (damage _cursorTarget < 1)) then {

**Comment by Skaronator** [comment]
Thanks
