### ISSUE TITLE
DayZ: Hard Corps - Permission Request

### ISSUE THREAD

**Issue by SgtMaC** [DayZMod/DayZ#152]
DayZ Dev team,

As the project lead, I would like to request permission to use the 1.8 and future versions as the core to our Add-on Pack. The purpose of this version is to supplement our communities Mil-Sim gaming requirements, in conjunction to our MSO, via ACE/ACRE/DayZ. This mod is now being reactivated from its dormant state.

We agree to terms and conditions and will include all credits. We understand that only the 5 authorized add-ons can be modified.

Respectfully,

Sgt MaC
www.survivaloperations.net

**Comment by Skaronator** [comment]
You must include all Dayz Credits and recreate a new issue post requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested. If you fine with the this info just reply or if you have any other questions regarding the license plz reply.

**Comment by SgtMaC** [comment]
Skaronator,

Understood, we agree with all acceptable use terms. We will also reissue another request in three months time.

Thank you,

Sgt MaC
