### ISSUE TITLE
DMR/SVD reloadTime incorrect

### ISSUE THREAD

**Issue by Gews** [DayZMod/DayZ#158]
Both these weapons have been artificially "balanced" by increasing reloadTime to 0.5, something which completely goes against the supposedly realistic nature of the mod and the game/sim it was based on.

This is a poor solution that doesn't make sense - these weapons are semi-automatic. If these weapons need to be balanced, the balancing should be achieved by other means than changing absolute statistics (ie, rate of fire).

Instead of altering reloadtime, the following should be considered:

-change recoil values (more muzzle jump, kick back, and slower re-centering)
-change dexterity (make the weapon much clumsier and unresponsive in CQC)
-make the DMR scope fixed at 10x, rather than adjustable from 3-10x
-change weapon rarity (if a weapon is end-game good, it should be RARE)
-change ammunition rarity

Any or all of the above solutions would be a better solution that would not alienate people like me who need weapons to have "realistic" values.

**Comment by R4Z0R49** [comment]
Thanks for your input we will look over the configs when we get some time to do so.

**Comment by R4Z0R49** [comment]
It might be quicker to just do the changes and send them over. I'm not sure when we will be able to revisit the sniper changes or have time to do consent tests on them.
