### ISSUE TITLE
Crafting is funny

### ISSUE THREAD

**Issue by kichilron** [DayZMod/DayZ#159]
Currently when I'm trying to craft a sepsis bandage it gives the error "Missing 2 Rags", while in reality I have them and use them, and also the Comfrey leaves needed - but in the end I only get 2 bandages and no sepsisbandage while the comfreyleaves remain in the inventory.
Also - when trying to craft a Beartrap with a grenade I end up with the Tripwire and still have the beartrap in the inventory

**Comment by kichilron** [comment]
More information:

http://youtu.be/oA_-c3ww8z8

**Comment by R4Z0R49** [comment]
Ill look into this soon as i can.
