### ISSUE TITLE
Server Spawn Issues

### ISSUE THREAD

**Issue by dzrno** [DayZMod/DayZ#16]
My server has not been spawning zombies or loot since the update. I have no idea how to fix or start fixing this.

**Comment by icomrade** [comment]
What server? Did you try manually updating your server's hive extension? if not try manually doing it if you can.

**Comment by MattzFiber** [comment]
Like he said. This seems to be only on your server so far, most are running fine

**Comment by dzrno** [comment]
Dayzarmageddon is the first part of the servers name. And no I didn't update the hive manually, how do I do that?

**Comment by icomrade** [comment]
Via an FTP client if you have access, or better yet use Remote Desktop if you can, it will be a bit easier. Please download the SERVER FULL package and overwrite you @hive and @dayzmod folders in your ArmA 2 OA root. Also please update your server to the recommended beta.

http://dayzmod.com/forum/index.php?/topic/129843-dayz-mod-177-patch/

You must also update your mission file, your server ID is in the mission file name, IE dayz_1307.chernarus.pbo:
http://www.silentspy.net/utility/dayz/mission-generator/

Update your filters from here:
https://github.com/DayZMod/Battleye-Filters

Note: if you do not have at least FTP access you will need to contact your host.

**Comment by dzrno** [comment]
My server is hosted by dayz.st. Does that change anything?

**Comment by icomrade** [comment]
You may be better off contacting your host as this issue happens on a select few servers, it may be linked to low server FPS.
