### ISSUE TITLE
Usage Request: DayZ Japahto

### ISSUE THREAD

**Issue by Hertizch** [DayZMod/DayZ#167]
Requesting permission to use DayZ Code base version 1.8.0.3 in my new mod DayZ Japahto.

I agree to all licence conditions and will supply full DayZ credits, and the understanding to only edit these 5 main pbo's; dayz_code, dayz_anim, dayz_server, dayz_sfx and dayz_comunityassets.

I will re-request a new permission every 3 months.

Thank you! :)

EDIT: Changed the name as I changed the map :)

**Comment by Skaronator** [comment]
You must include all Dayz Credits and recreate a new issue post requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested. If you fine with the this info just reply or if you have any other questions regarding the license plz reply.

**Comment by Hertizch** [comment]
I do agree to your terms!
Thank you :)
