### ISSUE TITLE
Permission request for own mod

### ISSUE THREAD

**Issue by X00LA** [DayZMod/DayZ#168]
Hi,

I´m planning a DayZ mod called DayZ-Legends.
The plan is a complete translation into the German language and of course some extensions.
I have read and agree to the permissions of course.
I have found some issues in the translation in the stringtable.xml´s. If you want, you can have the correctly translated files for the original mod.
Of course I will translate all the other scripts.

As I said, I have read the permissions and accept them fully.

I hope I get from you the permission to edit the necessary files.

With best regards,

Superstes

**Comment by Skaronator** [comment]
Alrighty

```
I have found some issues in the translation in the stringtable.xml´s. If you want, you can have the correctly translated files for the original mod.
```

And sure, add me in skype (Skaronator)
