### ISSUE TITLE
Equipping skin whilst looting a vehicle crashes Arma

### ISSUE THREAD

**Issue by Papzzz** [DayZMod/DayZ#17]
Pretty much as the title states.

If you are looting a vehicle or looting any loot pile, tent etc and attempt to wear any skin/clothing, Arma will crash. The crash only occurs in this scenario, e.g. whilst still looting/accessing a vehicle. Switching skins whilst not looting a vehicle etc works perfectly fine.

I havent been able to narrow down the exact cause of the crash but the last "diag_log" in my client RPT shows it hits player_switchModel.sqf and then crashes just after the following;

"Swichtable Unit Created. Equipment:"

The error is "Exception code: C0000005 ACCESS_VIOLATION at 00D7407C".

**Comment by Papzzz** [comment]
Ok, as an update to this, ive just been doing some testing to ensure this was definitely an issue.

I did the following;

I added the old code from 1.7.6.1 for "player_switchModel" back. 
I added "dayz_spawnPos = getPosATL player;" back into "variables"

After doing the above, equipping the skins works fine and doesnt crash Arma whilst looting a vehicle etc.

Reverting the 1.7.7 code back causes Arma to crash again.

I think the cause is down to these lines in player_switchModel;

_newUnit    = _group createUnit [_class,getMarkerPos "respawn_west",[],0,"NONE"];

AND

//Switch the units
    _createSafePos = [(getMarkerPos "respawn_west"), 2, 100, 0, 1, 20, 0] call BIS_fnc_findSafePos;
    _oldUnit setPosATL [_createSafePos select 0, _createSafePos select 1, 0];
    _newUnit setPosATL _position;

**Comment by facoptere** [comment]
which beta patch version is it?

**Comment by Papzzz** [comment]
Beta patch 103419

**Comment by icomrade** [comment]
This is fixed and will be included in the next patch.
