### ISSUE TITLE
Request for Dayz Licence to use for Own Mod ( Dayz Devine)

### ISSUE THREAD

**Issue by Livion** [DayZMod/DayZ#176]
Here a short explaination about what Dayz Devine is:

We currently are in the Alpha Version, and will release soon more information about what we are going to be using in our MOD.
 For those who are new and dont know who we are, We are creating a NEW MOD for Dayz, Dayz Devine. We focus more on the roleplay instead of having people run around and shooting eachother without any purpose. In here we will be whitelisting our server once we are ready to go to release the alpha to the public.
 This means that you dont do stuff you usualy do in the regular Dayz. Here you scavange around, Try find other survivors and build yourself a Base Camp to hold yourself off against the Zombies, Bandits and the Insurgents. If you are in need of any aid or you cannot handle it on your own anymore you can go to one of the 3 FOB's in the game where you will be provided with support of the US Military and Coast Guard. If you are a player that plays frequently and gets rated as a good player you are able to have a choice to join the US Military. This doesnt mean that any new players dont have the chance to play with the Staff Members on the US Military, Once you are rescued by an EVAC of the US Military you will be given a choice to go back to Chernarus or remain with us at the US Fleet on sea. What will you become? Survivor? Even a bandit? Become a Soldier who takes care of any left alone Survivors? Or do you even become an Insurgent who choose to Rob survivors or even plan an attack against the US Military?

So hereby i am asking if we are able to use the 5 Main Dayz Pbo's.
Regards, Dean.

**Comment by R4Z0R49** [comment]
You must include all Dayz Credits and (re)create a new issue post requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested.

You all only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create.

DayZ must not be used within the mod name.

**Comment by Livion** [comment]
But it is a MOD for Dayz as Dayz Overwatch?

**Comment by R4Z0R49** [comment]
And your credits will clearly show that. No need to have it in your name also :-)

**Comment by Livion** [comment]
Wich means?

**Comment by R4Z0R49** [comment]
We are requesting new mods to stop using the Dayz name.

**Comment by Livion** [comment]
Well thats why we are asking to use the tools and get hte licence for our new Dayz Mod.
