### ISSUE TITLE
database function pMain not working on startup?

### ISSUE THREAD

**Issue by dethica** [DayZMod/DayZ#177]
after updating my database with your "full.sql" file, I can't start the server anymore.

ERROR 1318 (42000) at line 1: Incorrect number of arguments for PROCEDURE hivemi
nd.pMain; expected 1, got 0

commandline:
C:\Games\MySQL\bin\mysql --user root --password=root --host=127.0.0.1 --port=3316 --database=hivemind --execute="call pMain()" 

I think this Git should really include generic startup bat files, to make updating servers a bit less disorienting. I haven't hosted dayz for half a year, and this is the result - an out of date database which no longer works with the latest dayzmod.
(latest working was 1.7.7.1)

**Comment by thevisad** [comment]
The Full.sql file is not an update file, it is a SQL dump of the functioning database. After not working with DayZ for a half year, you should not have attempted to "upgrade" a database, rather start with a fresh database. Wipe your DB and then start over and your issues will be gone.

**Comment by dethica** [comment]
I did wipe the database. Deleted all the tables and functions. It should work, but it doesn't. The SQL executed fine, but server refuses to work with it. I have no idea what is causing it, google-fu didn't help much either. I wouldn't post here otherwise.

**Comment by thevisad** [comment]
There is currently nothing wrong with any of the SQL files, we setup servers all the time with the schema that is in this. Please verify that your MySQL installation is 100% up to date, download uninstall and reinstall and make sure to remove your old databases (c:\programdata\mysql)
