### ISSUE TITLE
Usage Request: Endworld

### ISSUE THREAD

**Issue by TraderJoe** [DayZMod/DayZ#179]
Hello, I would like to use Dayz 1.8.0.3 code for a new mod I am working on. I will agree to the terms and conditions along with make a new forum post every three months for permission to use the files in future mod updates. I agree to give credit to the orginal creators and I agree to edit the 5 main Pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets and no others.
Finally the name of the mod is Endworld.

**Comment by R4Z0R49** [comment]
http://www.bistudio.com/community/licenses/dayz-mod-license-share-alike

The new license is now here.
