### ISSUE TITLE
Camo skin doesnt save onto player.

### ISSUE THREAD

**Issue by zombiefood** [DayZMod/DayZ#18]
Hello, I am not sure if it is the server i play on, but my skin didn't save onto my character, but the civilian clothes i had  after wearing the camo was still in the car where i had left it. I'll try to test this more in the coming week to see if this is still an issue

**Comment by R4Z0R49** [comment]
- [FIXED] - Changing clothes while in a gear menu of a pile/vehicle/tent will no longer crash your game
