### ISSUE TITLE
request licence for dayz mod on thirsk

### ISSUE THREAD

**Issue by scottieo321** [DayZMod/DayZ#180]
Hi guys wanting to get permission for a licence to use dayz version 1.8 and above hotfixes. Also wanting to know if there is permission available to edit the dayz_equip as it is needed when adding in new skins and new items for names and what not. I agree to include all credits and edit only files that I am allowed if equip is not allowed then I will find another way of adding things in if it's possible. Thanks.

**Comment by Wargog** [comment]
You have permission to edit anything you want, just not porting to other games, read the license, Google "DayZ Share Alike"

**Comment by Skaronator** [comment]
https://www.bistudio.com/english/community/licenses/dayz-mod-license-share-alike
