### ISSUE TITLE
Shooting bug

### ISSUE THREAD

**Issue by dustyg0** [DayZMod/DayZ#181]
Ive tried everything the specs on my computer is fine so I definitely know theirs nothing wrong with my computer.  I used to be able to play the mod without any issues but now I cant shoot without my game freezing to the point where it doesn't even close out I have to force shutdown on my computer to even close the game. Once again the game freezes only when I shoot..so I can be running around picking stuff up I can even shoot a unloaded gun "makes the click no bullet in gun sound" so soon as I load the ammo in it and fire boom it freezes I dont even here the gun go off... PLZ HELP

**Comment by dustyg0** [comment]
I tried shooting on the arma 2 game and it works....I even reinstalled arma2 and tried shooting in dayz and it freezes instantly..wtf

**Comment by redradman123** [comment]
@dustyg0 where did you download Dayz from?

**Comment by emestee** [comment]
Bind shoot to a keyboard key. If this stop happening then this has something to do with your mouse.
