### ISSUE TITLE
Requesting permission to use DayZ "assets" for a roleplay DayZ Mod named Uprising

### ISSUE THREAD

**Issue by TurkishSoap** [DayZMod/DayZ#182]
I will and agree to include all Dayz Credits and (re)create a new issue post requesting continued use of all assets for all future release you I will be willing to backport code/models/sfx/animations to the official if requested.

I understand that I am only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create.

I understand that DayZ must not be used within the mod name.

Regards, TurkishSoap

**Comment by thevisad** [comment]
This is no longer required as there is now a DayZ license, you must follow the rules on this license post. 

https://www.bistudio.com/english/community/licenses/dayz-mod-license-share-alike
