### ISSUE TITLE
Hatchet Dissapearing from dead body 1.8.1

### ISSUE THREAD

**Issue by fazmond** [DayZMod/DayZ#186]
It Seems that why I died and went to get back my body the hachet was gone from the body, and I know this wasn't taken from a player as I was the only one on my server.

**Comment by R4Z0R49** [comment]
Thanks for reporting we have this already being looked into.

**Comment by R4Z0R49** [comment]
The items on your back fall to the ground testing and in live games shows this as working.

**Comment by R4Z0R49** [comment]
Going to leave this open pending more detailed info.

**Comment by R4Z0R49** [comment]
No new reports closing
