### ISSUE TITLE
Server Listing as 1.8

### ISSUE THREAD

**Issue by fazmond** [DayZMod/DayZ#188]
In Dayz commander the server version is coming up as 1.8 and not 1.8.1 , 
and its not just my server all the servers are showing as 1.8 so prolly needs a look into

**Comment by kichilron** [comment]
DayZCommander has been updated today. Make sure to close DZC and reopne it, as it's showing properly for me as well as the download is available now.

http://imgur.com/vWfeszX.png

**Comment by fazmond** [comment]
Seems to have fixed as the guy has released an update for dayzcommander
