### ISSUE TITLE
upgrade of the tent or stash disappears after relog the player to the server

### ISSUE THREAD

**Issue by djpajty** [DayZMod/DayZ#189]

**Comment by R4Z0R49** [comment]
We need info from the server host. There is too many variables in place

**Comment by djpajty** [comment]
Hi.
Sorry for the short message yesterday.
I just wanted to say that upgrade menu (of the tent or stash) disappears when I am upgrading (not last upgrade) tent or stash, relog to server again, and when i log back in, i can't continue upgrading.
i hope you understand :) quite hard to explain
Thanks
DJ

**Comment by kichilron** [comment]
What server were you playing on?

**Comment by djpajty** [comment]
i was playing on my private server.
193.34.145.90:2302

**Comment by kichilron** [comment]
Make sure the DB is updated and working as intended, as that is more than likely the problem.

In Testing everything worked fine and the Hive seems to be working as well. Please note that we're not officially supporting private hive packages.

**Comment by djpajty** [comment]
Hi
There is not our DB problem, but user problem. Everything is saving to DB correctly. but players mentioned the problem stated above.
thanks

**Comment by djpajty** [comment]
Hi
I've tested it and it's working fine now
I think it was problem on our side
sorry for disturbing
Thanks
