### ISSUE TITLE
Vehicles respawns

### ISSUE THREAD

**Issue by dlatz** [DayZMod/DayZ#19]
Hi,

After server restart completely destroyed vehicles respawns on the same spot where they explode, in the last saved status.

**Comment by facoptere** [comment]
Could I get you server RPT logs?

**Comment by dlatz** [comment]
Nope sry :( 

Server is not mine, its a public server connected to the hive where I play. Here is a IP if that helps 80.242.152.220:2322 

Now I don't know maybe is that problem with vehicles only on this server, I really don't know I have not tested other public servers to see if they have the same problem.

Situation 1
I was driving a S1203 van and crash in bus station, bus station collapses, and vehicle explode. But after the restart a S1203 van was stuck inside of bus station with all gear inside the van.

Situation 2
Found exploded Ural in the forest, after server restart i come back to see the truck, truck was there. I check the status of the truck, by scrolling mid mouse, wheels, glass, hull is on 90%, and on the list was no status for engine and fuel tank. But when i get in the drivers seat engine was read, after i get out, the truck gets immediately on fire and explodes and after another server restart truck is again there.

**Comment by facoptere** [comment]
Problem fixed.

**Comment by dlatz** [comment]
Well, that was fast, nice work!
