### ISSUE TITLE
Blood Regeneration

### ISSUE THREAD

**Issue by DrTyler** [DayZMod/DayZ#190]
I was scrolling through the server list and I find a server entitled "Vanilla DayZ" so I joined and within a few minutes, to no surprise, I get attacked by a zombie and I look over at my blood meter and I'm regenerating blood. I tested this several times afterward and it continued to happen so my question to you is **Is blood regeneration over time something that is in the game now?** I looked over the update documentation and found nothing about this.

**Comment by R4Z0R49** [comment]
correct. its in the change log.
