### ISSUE TITLE
Medium stash building

### ISSUE THREAD

**Issue by djpajty** [DayZMod/DayZ#191]
Hi
Yesterday i've tried to build medium stash and I've used 2 sandbags, but instead small stash was built.
I've tried the same with 1 sandbag and small stash was built again.
Is it a bug or is it meant to be like that?
Thanks
DJ

**Comment by R4Z0R49** [comment]
Build the small stash then upgrade it to medium and above

**Comment by djpajty** [comment]
Thank you for the quick reply.
i was just trying to say, that it's taken me 2 sandbags to build 1 small stash.
thought it's a bug
Thanks

**Comment by kichilron** [comment]
There are no medium stashes to build anymore. You start with the smallest one and then upgrade them. You can only start with the smallest.

**Comment by djpajty** [comment]
That's great idea. what i'm trying to say, how many sandbags should be used to build it? 1 or 2? because when i've had 1 i could build it and when i've had 2, i've build it, but used both of those sandbags. see video https://www.youtube.com/watch?v=erJ-tm_HFEM
Thank you

**Comment by R4Z0R49** [comment]
it should be 1 but there is an issue where if you have two it will use them.

**Comment by djpajty** [comment]
Nice. i was trying to say that :)
Thanks

**Comment by kichilron** [comment]
Fixed.
