### ISSUE TITLE
Food System Update

### ISSUE THREAD

**Issue by CarlitosCMIF** [DayZMod/DayZ#192]
This is my first report, but i want to help to make this game better.
Last nigth i played for the first time after the patch and i have to say that i love the new food/drink/blood system... but it seems that it´s not working properly because before server restart my thirst and food were half for like an hour and they didn´t move while i eat or drank... after the restart they shown almost empty... i think they are not updating quite good, maybe it was a server issue... just trying to bring something to the table.

**Comment by R4Z0R49** [comment]
We are looking into this issue.

**Comment by R4Z0R49** [comment]
We be leave the issue has been resolved for the next patch.
