### ISSUE TITLE
Spawn Selection and Full Moon Nights

### ISSUE THREAD

**Issue by lWmPl** [DayZMod/DayZ#193]
Hi again!
1.8.1
I disable spawn selection in "init.sqf", but in journal spawn selection is "true".
I cant find full moon option so i use that advise: https://github.com/DayZMod/DayZ/issues/143. And ofcourse in journal full moon is "true" too.
So can you tell me where full moon option exactly and how i can change "true" on "false" in journal, to not confuse players?

**Comment by R4Z0R49** [comment]
add this into your mission init.sqf

dayz_ForcefullmoonNights = true; //true = full moonnight, false = full night tme

**Comment by lWmPl** [comment]
@R4Z0R49  You dont understand. I need to off spawn selection and full moon, and change it values in ingame journal from "true" to "false".
spawn selection is now off. about full moon im not sure. i add "dayz_ForcefullmoonNights = false". but both options in journal still "true".

**Comment by R4Z0R49** [comment]
Ill look into it if the above isn't working then its a bug.

**Comment by R4Z0R49** [comment]
Ok seems its an issue within the journal switch command, It's fixed for the next release.

**Comment by lWmPl** [comment]
Ok! Thx!
