### ISSUE TITLE
Bloodbags

### ISSUE THREAD

**Issue by JusticeRequiem** [DayZMod/DayZ#195]
Bloodbags seem to have a glitch to them where they will not work. This has happened multiple times since the 1.8.1 patch. it seems either the bloodbag will give no blood at all, or the transfusion will stop working after 1k blood has been recieved.
- eating/relogging does not help
- it might be connected to being in and/or leaving cars

**Comment by R4Z0R49** [comment]
Can you tell me what version the beta is your using ?

**Comment by JusticeRequiem** [comment]
http://cloud-3.steampowered.com/ugc/778308779319650264/D910CD86680DDEEA89B27342A1DB2BC7BF5B794B/

Several people I've been playing with have had the same issue

**Comment by R4Z0R49** [comment]
Yea your going to need to update the beta to the newest beta 1.63.11255 is having a ton of server issues. If the server is having issues everything using a PVS will have issues also this includes bloodbags. So rather go back to http://www.arma2.com/downloads/update/beta/ARMA2_OA_Build_103718.zip

or upgrade to the newest version.

Just make sure the server you play on is updated or has gone back to 103718

**Comment by JusticeRequiem** [comment]
Downloading this patch gives this error message;
"The version of ArmA2 OA (1.63)
is more rescent than this patch version (1.62)."

**Comment by icomrade** [comment]
-noPatchCheck

**Comment by R4Z0R49** [comment]
We have also had reports of the infistar anti-hack system servers run are effecting action menus.

Its being looked into.

**Comment by 0Skydive0** [comment]
I was just having this problem today when trying to bloodbag a survivor with the correct blood type and even trying to use O- blood.  Would not work no matter what we tried and I even tried using an admin tool I wrote in to restore the survivor's health and that would not work.

Running 1.8.1 / 112555 on my server.

**Comment by R4Z0R49** [comment]
There is an issue with the lowblood var not reporting correctly we are aware of this and it has been fixed for the next version due Monday.
