### ISSUE TITLE
Running twice as fast: 1.8.1

### ISSUE THREAD

**Issue by TIC321** [DayZMod/DayZ#196]
While running without any items, clicking G while sprinting makes you run twice as fast.

**Comment by R4Z0R49** [comment]
https://github.com/R4Z0R49/DayZMod/commit/9d86eb18390e54fba18d5c0e3467b97d74c2f406

https://github.com/R4Z0R49/DayZMod/commit/599b9a050571c7480f6115662ed06d302813559d

We have two fix's inbound for this. Waiting on testers feedback
