### ISSUE TITLE
Upgrading stash to level 4 kicks you from the server BE create vehicle restriction #0

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#197]
I've been playing on US242 which is on Arma 2 beta 112555.  I'll make a small stash, and start upgrading it.  I'll get it to level 3, but every time I try to apply the 4th upgrade, BattleEye kicks me for create vehicle restriction #0 and the stash permanently disappears.

**Comment by kichilron** [comment]
This is a serverside-problem with the BattlEye-Filters. Please contact the Server-Owner / -Admin and tell them they should update to the newest version to be found here:

http://forums.dayzgame.com/index.php?/topic/139058-battleye-server-filters-for-dayzmod-18/

**Comment by bchawke** [comment]
Done.  Thanks.
