### ISSUE TITLE
Error "DomeTentStorag3"

### ISSUE THREAD

**Issue by markusua** [DayZMod/DayZ#199]
dayz_code.pbo/init/variables.sqf
line 49 - DayZ_SafeObjects = ["Land_Fire_DZ", "TentStorage","TentStorage0","TentStorage1","TentStorage2","TentStorage3","TentStorage4","StashSmall","StashSmall1","StashSmall2","StashSmall3","StashSmall4","StashMedium","StashMedium1","StashMedium2","StashMedium3", "StashMedium4", "Wire_cat1", "Sandbag1_DZ", "Fence_DZ", "Generator_DZ", "Hedgehog_DZ", "BearTrap_DZ", "DomeTentStorage", "DomeTentStorage0", "DomeTentStorage1", "DomeTentStorage2", "DomeTentStorag3", "DomeTentStorage4", "CamoNet_DZ", "Trap_Cans", "TrapTripwireFlare", "TrapBearTrapSmoke", "TrapTripwireGrenade", "TrapTripwireSmoke", "TrapBearTrapFlare"];

**Comment by R4Z0R49** [comment]
Can we get the hole error and on what server your getting it on.

**Comment by markusua** [comment]
it's a typo, or it should be? file dayz_code.pbo/init/variables.sqf version 1.8.1
"DomeTentStorag3" or "DomeTentStorage3"

**Comment by R4Z0R49** [comment]
Got it and fixed. Thanks
