### ISSUE TITLE
translation into different languages

### ISSUE THREAD

**Issue by markusua** [DayZMod/DayZ#200]
it is not a bug but a request) to translate new titles and menus in different languages ​​so far only in English there

**Comment by kichilron** [comment]
If you change the language of your ARMA 2 OA it will change the language of almost everything ingame, as we're always doing 4-5 languages for everything.

```
    <Key ID="STR_ACTIONS_DROP">
        <English>Drop</English>
        <Russian>Выбросить</Russian>
        <Spanish>Tirar</Spanish>
        <Czech>Odložit</Czech>
        <French>Lâcher</French>
        <German>Fallen lassen</German>
    </Key>
```

**Comment by markusua** [comment]
menu on the left, when to drink hands the word "drink" in English

**Comment by kichilron** [comment]
Fixed - Thank you.

**Comment by markusua** [comment]
I'll write a couple of corrections translation in the Russian version

**Comment by kichilron** [comment]
Please do. We currently have noone translating it. Do you know where you find the information you need?

**Comment by markusua** [comment]
yes I know in stringtable.xml

**Comment by ArfourFoulkesayke** [comment]
Do you need help for other languages as well? I could offer a hand (or tongue) for German.

**Comment by kichilron** [comment]
Damn Germans. :-/

Anyone that wants to help, please add me on Skype - I don't think I will be able to go over the German bit myself anyway (not in a timely manner).

**Comment by markusua** [comment]
got a lot of text, collected in a text file
http://rghost.ru/56334526

**Comment by AlexAFlorov** [comment]
what date is release planned?  
i hope i'll find time to check rus stringtables

**Comment by markusua** [comment]
I have collected in the file where you need to correct a translation

**Comment by kichilron** [comment]
Please add me on Skype, if you want to contribute with Translations further on.

**Comment by kichilron** [comment]
Translations have been done for German and Russian.
