### ISSUE TITLE
Hatchet Breaking Chances, Too High? (1.8.2/124879) 12_June_2014

### ISSUE THREAD

**Issue by JimmyChew** [DayZMod/DayZ#203]
Need to test this more, but I had 2 of 2 hatchet breaks when harvesting wood.  I'll get a stack of hatchets and see if I can recreate it more.

**Comment by kichilron** [comment]
That's statistics. Theoretically it can happen 1.000 times in a row upon first use.

Definitely need to test more.

**Comment by JimmyChew** [comment]
Did some testing.  Seems there are two routes of harvesting wood.  One (at a tree) and one (in forest, near tree).  They yield different results.  "In forest near tree" automatically harvests 12 units, uses significant food/drink, and breaks hatchets extremely frequently. 

Video: http://www.twitch.tv/jimmy_chew/c/4455388

**Comment by R4Z0R49** [comment]
See how the new system goes.
