### ISSUE TITLE
Zed Always Pulls Player Off Open Vehicle

### ISSUE THREAD

**Issue by meshguru** [DayZMod/DayZ#204]
In player_zombieAttack.sqf, in previous versions, a code segment ran thus:

```
        if ((_chance % 4) == 0) then {
            _openVehicles = ["ATV_Base_EP1", "Motorcycle", "Bicycle"];
            {
                if (_vehicle isKindOf _x) exitWith {
                    player action ["eject", _vehicle];
                };
            } forEach _openVehicles;
        };
```

In 1.8.1, "forEach" has been changed to "count", rendering the value of _x undefined and the expression meaningless.

**Comment by R4Z0R49** [comment]
_x is still correct. The only real difference between count and foreach is the index foreach has.

But thanks.

**Comment by meshguru** [comment]
Whoops! Sorry to waste your time. I do *not *remember seeing that syntax
under count; and it's not in my notes. Just a side-of-the-head-slap that
says I need to look at the BIscripting wiki to check for updates when I
find something I don't recognize.

thanks!
- ep
