### ISSUE TITLE
HIVE DEAD ?

### ISSUE THREAD

**Issue by fazmond** [DayZMod/DayZ#206]
I think you need check the hive again lost connection to it this morning and I see other servers down atm also

**Comment by kichilron** [comment]
We're aware of it and working on resolving it, thank you for reporting.

**Comment by R4Z0R49** [comment]
Info has been passed on we have no access to the hive server.

**Comment by fazmond** [comment]
surely it wouldn't take much to pay for a database and in the next patch link it to your own ip :)so you get control :)

**Comment by thevisad** [comment]
@fazmond if it was that simple we would have done it a long time ago.

**Comment by fazmond** [comment]
only thing I see not being simple is the time it takes to copy, the db will prolly have to go offline for a while, so that ppl don't lose their stuff inbetween the transfere, but seeing the have can now go down for a couple of days at a time and long delays till it can get restarted , id rather wait till it gets sorted so if a problem arises someone can quickly get on the case .  the actual copy and patch of the dayz mod is actually very easy

**Comment by NonovUrbizniz** [comment]
The hive is owned and controlled by BI. It's complicated like a Facebook relationship not technically.
