### ISSUE TITLE
Hive Just DIed Again 

### ISSUE THREAD

**Issue by fazmond** [DayZMod/DayZ#208]
Hive Deaded 13:45 uk time

not just my server but other servers too

**Comment by thevisad** [comment]
We do not handle the hive aspect, that is handled by another team.

**Comment by fazmond** [comment]
that team needs a kick up the butt !

**Comment by fazmond** [comment]
whos in charge and how do we let them know this is re-donk-u-las !

get me their info so I can pester them about it !

**Comment by R4Z0R49** [comment]
When you find out let us know.
