### ISSUE TITLE
Red smoke (smoke grenade) 

### ISSUE THREAD

**Issue by vinyljunkie** [DayZMod/DayZ#209]
I get reports of red smoke appearing at stashes, medboxes and helicrashes. Visible to other players aswell. 

1.8.1 
125548

No alterations to code or additional scripts, pure vanilla.

**Comment by R4Z0R49** [comment]
We dont have anything in dayz that does this. Sorry

**Comment by vinyljunkie** [comment]
Ok, thanks. Then it must be infistar AH causing it. Glad I posted here first.

Thanks!
