### ISSUE TITLE
players sometimes spawn in debug mode

### ISSUE THREAD

**Issue by DrClaw-** [DayZMod/DayZ#21]
Ever since updating to 1.7.7 i have noticed many servers especially hosted with dayz.st or any custom servers, private hives, etc having spawn issues
i have played on many different ones including the server i moderate on and have had serious spawn complications where players tend to spawn in debug whether they just logged in or died and logged back in

i have to restart the server a few times to get folks out yet the problem resurfaces later with new players logging in and spawning in debug

**Comment by R4Z0R49** [comment]
From the info we seem to be getting try updating your mission file but disable the antiTP script.

http://www.silentspy.net/p/dayz-mission-generator/

just tick the box to disable the antiTP.

**Comment by DrClaw-** [comment]
thanks for reply, been busy and i have let the owner of server know and this has not work it seems
