### ISSUE TITLE
1.8.2 BE filters

### ISSUE THREAD

**Issue by lWmPl** [DayZMod/DayZ#210]
Kicks by:

addmagazinecargo:
#2 "ItemSodaPeppsyEmpty"
#2 "ItemSodaLirikEmpty"
#2 "ItemSodaFrankaEmpty"
#2 "ItemSodaPeppsy"
#2 "ItemSodaSacriteEmpty"
#2 "ItemSodaLirik"

addweaponcargo:
#2 "ItemDIY_wood"

**Comment by facoptere** [comment]
Should be fixed there: https://github.com/DayZMod/Battleye-Filters/pull/102
You can update your filters from github --> https://github.com/DayZMod/Battleye-Filters/archive/Release_1.8.2.zip

**Comment by lWmPl** [comment]
and some new kick by "createvehicle":

#0 "WoodenFence_1_foundation"

**Comment by facoptere** [comment]
Thanks

**Comment by lWmPl** [comment]
#0 "WoodenFence_1_foundation"

![94ec76f3e726bbad3232b784bd9d5881](https://cloud.githubusercontent.com/assets/4685503/4099019/740e1cf6-3045-11e4-92f7-3a8ba3e816c6.jpg)

![82943928333a9bc42502818d129ff440](https://cloud.githubusercontent.com/assets/4685503/4099020/7a5ca6e0-3045-11e4-8648-a95296fe5322.jpg)

**Comment by facoptere** [comment]
can you confirm you are using the last version of the filters I updated yesterday?

**Comment by lWmPl** [comment]
nope. 4 days ago i update filters, after that i got this bug-report, post them here and immediately updated filters one more time just in case. :)
so i check this problem now and reply here.

**Comment by facoptere** [comment]
Ok this building system is a bit tricky to filter. I am working  on it this morning.  There will be another update.

**Comment by lWmPl** [comment]
it would be nice if date of last changes displayed correctly in github. becouse date is much easier to check for updates.

**Comment by facoptere** [comment]
Ok I just updated the filters
and also I added the last modification made in filters in the README at bottom of the github page.
