### ISSUE TITLE
Dayz 1.8.2 Weapon Sway / Exhaustion bug

### ISSUE THREAD

**Issue by Borges80** [DayZMod/DayZ#212]
Character is being fully exhausted and generates maximum weapon sway from merely moving, prone to crouch, or running a few steps. Video is posted below.

https://www.youtube.com/watch?v=x6EHWt0AUOs&feature=youtu.be

Footage taken from server US 388

Arma2 version: 125548
Dayz version: 1.8.2

**Comment by R4Z0R49** [comment]
Video is useless.

https://www.youtube.com/watch?v=c-H0WVzliNc

Much better example.

**Comment by Borges80** [comment]
I posted a more detailed video.

**Comment by R4Z0R49** [comment]
it's ok the sniper ones displays the issue perfect thanks.

**Comment by Borges80** [comment]
No problemo

**Comment by Borges80** [comment]
No problemo

**Comment by R4Z0R49** [comment]
Resolved http://www.twitch.tv/r4z0r49/b/562179985.
