### ISSUE TITLE
Model for Woodfence and Metalfence repostitions when upgrading

### ISSUE THREAD

**Issue by dayzjarhead** [DayZMod/DayZ#214]
Upgrading the wooden- and metal fence causes the model to reposition when upgrading from level 3 to level 4 (The step when the supporting beams are added? Dunno if this is the correct step).

I think this is caused by a wider base of the upgraded model in relation to the worldspace position.

**Comment by R4Z0R49** [comment]
k Thanks

**Comment by ghost** [comment]
cheers mate.

**Comment by ghost** [comment]
I thought, I elaborate a little bit more with the mighty power of GFX.
![unbenannt-2](https://cloud.githubusercontent.com/assets/5417798/4098758/bdc28b30-3035-11e4-8ebd-68bedf82c2c4.jpg)

**Comment by R4Z0R49** [comment]
Yea its already a known issue we just need to move the model back by 0.2 i think it was.

**Comment by ghost** [comment]
So my assumption is correct?

**Comment by kichilron** [comment]
We were testing out different systems for the issue of it shifting about, which is why this must have been lost in the process of creating this system.
I will make sure to check this out as soon as I am back again.

**Comment by facoptere** [comment]
it's fixed in 1.8.3. "autocenter=0" for all models.
