### ISSUE TITLE
Probability of getting destroyed

### ISSUE THREAD

**Issue by nixaw** [DayZMod/DayZ#217]
The chance for water bottle and hatchet to break down while using (boiling water, chopping wood) is anoyingly high. I can imagine you can add any random damage "feature" but in which world can you destroy a water bottle just by pouring water from a can? Or using matches (at least 20 matches in the box) and for making one fireplace my idiotic avatar uses 15 of them? This drives me mad because my character is even more dumb then real me which I thought cannot happen in the game. Same thing with repairing broken water bottle / hatchet = using the WHOLE tape to fix a hole in a water bottle, this is harsher than reality. Thank you and please consider not adding further features like - your hunting knife blow up while cutting animal flesh or you lost a screw driver from your toolbox because your character is obviously an idiot. Lastly - I can´t seem to find any way to download 1.8.2 client. Nothing on dayz commander. Please consider adding a link in the forum post.

**Comment by ghost** [comment]
Update with Steam or use the @DayZ mod from the serverfiles here: 
http://forums.dayzgame.com/index.php?/topic/206360-dayz-mod-182/

**Comment by nixaw** [comment]
Thankk you kind sir.

**Comment by kichilron** [comment]
We are testing out a new function for probability and we're unsire about the results. In theory it should be less than 5% - but as statistics and randomness decides, it can very well happen that your hatchet breaks 10 times in a row upon first use.

That is randomness and can't be prevented.

We will look into further testing the chances with the future update, however.

**Comment by nixaw** [comment]
Then, I guess, Iam the lucky one :D. I would say in 1 in 3 uses of both hatchet and water bottle It will break. It is only based on my experrience with around 10 - 20 pieces of both mentioned.

**Comment by kichilron** [comment]
No more issues since change over to rnd-function. Cleanup & Closed.
