### ISSUE TITLE
Crafting woodpiles works only sometimes

### ISSUE THREAD

**Issue by BobbusInteruptus** [DayZMod/DayZ#219]
This happens when you want to craft woodpiles from planks. Very often the woodpile is just not in your inventory or somewhere near your character, although it says "you crafted woodpiles". 
While playing, we discovered that it works sometimes when you are near a car or a campfire. It never worked when not in a forest.
While building my stashes i could never get woodpiles from logs/planks, so i just used the ones i find. The thing is, as soon as i had a medium stash and was near it, the crafting of woodpiles worked everytime. It also seems ther are some sweetspots where it just worked, according to one of my friends.

Greetings,
Bobbus_Interuptus for dayzjarhead.de

**Comment by kichilron** [comment]
If you can provide more detailed information about what you mean that you sometimes can't get woodpiles, that would be perfect.

I am sort of lost by what you mean that it sometimes doesn't work, I will however take another look at the system.

**Comment by BobbusInteruptus** [comment]
No problem, here are my observations, latest versions from DayZ and ARMA 2.
Server is DayZ Vanilla Hardcore

The first time was in a forest north of Cherno, neede some woodpiles. I chopped down a tree, got a log, made it to planks and than tried to get woodpiles. I got a message that i succesfully crafted them, but i had no piles in the inventory or on the ground. Tried it a few times, but didnt work.

Next day, one of my friends told me he can make woodpiles, but only when near a campfire or a car. He said just try it until it works, maybe 1 of 5 times. I tried it myself in my base near my car and a campfire with 15 logs, but couldnt get a single woodpile. So i visited my friends base and tried again crafting piles and it worked. But being near a car didnt work for me, but being near a medium stash did.

Later that day, i took some piles from my friend, went to my base and started upgrading my stashes to medium size. When the first one was build i tried crafting piles again. Chopped some logs, crafted the planks and than woodpiles. Now it works everytime, as long as i´m near my medium stashes. 

I also did some testing. 
Coordinate 063 054 on the open field and in the forest: crafting piles worked, even away from stash or  car.
Coordinate 064 060 and 063 059 in the forest: no wood piles
Coordinate 063 061 open field: didnt work either.

It seems it has also something to do with the area you are in.

**Comment by kichilron** [comment]
Alright, that will help - I will take a look into that as soon as I am back.

As far as the Hatchet breaking goes - did you take that into account? That your Hatchet has a chance of breaking whilst chopping? It might very well be possible that your hatchet broke, but you didn't notice, as there is no different icon in the inventory for it.

If your hatchet is broken, you can't chop up logs to planks and piles anymore.

**Comment by BobbusInteruptus** [comment]
Just checked. No broken hatchet during testing.

**Comment by facoptere** [comment]
Crafting code is more reliable now in 1.8.3. There is some weird behaviour in the latest ArmA2OA engines: you can't use a global variable as a mutex to determine that an action is in progress. Now I am using the current animation state of the character and it's working well.
