### ISSUE TITLE
Server not loading anything from the hive

### ISSUE THREAD

**Issue by crazykid1297** [DayZMod/DayZ#22]
Hello,

I have a strange problem with my official hive server running 1.7.7/103718. The hive starts, and nothing loads, and it begins spamming "MISSION: File needs updating" in my RPT logs.

Example:

2013/06/16,  7:39:53 "HIVE: Starting"
2013/06/16,  7:39:53 "MISSION: File Needs Updating"
2013/06/16,  7:39:53 "DEBUG FPS  : 1.26693"
2013/06/16,  7:40:41 "STARTING LOGIN: ["128586182",B 1-1-A:1 (PLAYER 1) REMOTE]"
2013/06/16,  7:40:41 "LOGIN ATTEMPT: "128586182" PLAYER 1"
2013/06/16,  7:40:42 "LOGIN LOADED: B 1-1-A:1 (PLAYER 1) REMOTE Type: Survivor1_DZ"
2013/06/16,  7:40:44 "LOGIN PUBLISHING: B 1-1-B:1 (PLAYER 1) REMOTE Type: Survivor2_DZ"
2013/06/16,  7:41:03 Warning: z\addons\dayz_communityassets\models\compass.p3d:0 Error while trying to generate ST for points: 863, 853, 852
2013/06/16,  7:41:04 "MISSION: File Needs Updating"
2013/06/16,  7:41:05 "MISSION: File Needs Updating"
2013/06/16,  7:41:06 "MISSION: File Needs Updating"
2013/06/16,  7:41:07 "MISSION: File Needs Updating"

The spam just goes on and on, and none of our tents are at our base coords. And it would appear that no vehicles are loading as well. 

I have also regenerated my mission file a couple of times using the silentspy.net generator.

**Comment by icomrade** [comment]
Did you actually overwrite you servers mission file with the new one? clicking generate will only create it and download it to your PC, you have to update the server manually, in the MPMissions folder obviously.

**Comment by crazykid1297** [comment]
Yes. I had to revert back to the mission file before the latest one to get the hive to load our tents, vehicles, etc.

**Comment by AlienXAXS** [comment]
Ignore the below, i accidentally looked at the 1.7.6.1 source - damn only having 2 hours sleep while @ DreamHack

According to the code paths, if you do not have onPauseScript defined in your description.ext file of your mission (which should come with the PBO that the link makes, i assume) it will throw this error out every 1 second into your RPT as you have seen.

The code that should be inside the description file is:
onPauseScript = "\z\addons\dayz_code\compile\player_onPause.sqf";

Mine appears right after enableItemsDropping = 0;

Hope this helps.

**Comment by R4Z0R49** [comment]
You havent updated your server.bpo.

This msg is a 1.6.1 msg.

**Comment by crazykid1297** [comment]
But I did update all of my files. I would not have posted here if I hadn't.

**Comment by icomrade** [comment]
Delete all DayZ server and DayZ client mod folders, download the 1.7.7 server full and overwrite everything that you are prompted to (besides your cfgDayZ -- server profile -- folder). Update your beta to 103718, and replace your mission file with the latest one from the mission generator.

I can only tell you what the log messages show us, and they show us that your server has been improperly updated.

**Comment by facoptere** [comment]
And keep in mind that only DayZ files should be in dayz mod folders. Don't keep old backup files in the same folders.
