### ISSUE TITLE
Campfires, an improvement?

### ISSUE THREAD

**Issue by dayzjarhead** [DayZMod/DayZ#220]
Campfires can only be crafted from woodpiles and matches.

Player should be able to craft a campfire from Wooden Logs, Sawn Planks and Woodpiles, using matches.

Maybe add a permanent large campfire to the crafting logic (using 3 units of any wood and 2 units of rough stones). It would be a nice addition to a survivor camp. You light it up using matches. The cold campfire stays as permanent model in the world and can be deconstructed, leaving rough stones.

**Comment by ghost** [comment]
Is this even the right place to post such ideas?

**Comment by kichilron** [comment]
As taken from the public announcement on the Forum:

The ideal place to post bugs is:
https://github.com/DayZMod/DayZ/issues
Please make sure they are listed to the DayZ project. Feature requests can also be made through this system.

GitHub actually is the perfect place to post this, as some of our Devs do not read the Forum regularly.

**Comment by ghost** [comment]
Alright... blind man being blind. ;) In fact, we have a lot more of this in store, so we keep it coming over time.

**Comment by R4Z0R49** [comment]
We have a few ideas to follow on for camps to help with the base building system.

**Comment by ghost** [comment]
Cool! Looking forward to see it! :)

**Comment by kichilron** [comment]
Should be possible to craft from anything now. Cleanup & Closed.
