### ISSUE TITLE
Food storage... idea

### ISSUE THREAD

**Issue by dayzjarhead** [DayZMod/DayZ#221]
Greetings, valued devs.

A big part of playing DayZ is gathering supplies, hunting and foraging.

Players tend to put huge amounts of meat, raw or cooked, into stashes and tents. Those foods don´t perish and are basically stored forever.

Maybe there could be a logic, that represents 4 basic states of decay of meat:

Raw meat:
- fresh (1 day) 
- well hung (2 dayz)
- peculiar (3 days)
- rotten (5 days)

Cooked meat:
- fresh (2 days) 
- well hung (3 dayz)
- peculiar (4 days)
- rotten (6 days)
# 

How to preserve meat?

Introducing the cooling stash... it´s basically a normal stash, but with cooling abilities as our forefathers have been using it for millennia.

Constructing a Cooling Stash: 
- normal stash materials
- Rope, Stones, Crate
  ... can be upgraded as usual to provide more storage
# 

What is the benefit of a Cooling Stash?
- raw and cooked meat get a +5 to the deteriorating value
# 

What else?
- maybe reduce the spawning values of canned food, so people need to go hunting.
- there could be a new item "Salt", combined with meats, the det. value gets an additional +5
# 

Oh, and what if a desperate survivor munches on rotten food?
- raw/fresh: 
  "This fresh piece of meat tastes bloody and makes you gag a little."
  (normal nutrition values apply)
- raw/well-hung: "This day-old piece of meat tastes chewy."
  (normal nutrition values apply, 5% chance of infection)
- raw/peculiar: 
  "This day-old piece of meat tastes strange and mushy. You can barely swallow it."
  (1/2 nutrition values apply, 10% chance of infection)
- raw/rotten: 
  "This is old piece of meat smells rotten an disgusting."
  (1/3 nutrition values apply, 20% chance of infection)

---
- cooked/fresh: 
  "This fresh piece of meat tastes delicious." 
  (normal nutrition values apply)
- cooked/well-hung: 
  "This day-old piece of meat tastes good." 
  (normal nutrition values apply)
- cooked/peculiar: 
  "This day-old piece of meat tastes strange and mushy. You can barely swallow it."
  (1/2 nutrition values apply, 5% chance of infection)
- cooked/rotten: 
  "This is piece of meat smells rotten an disgusting and makes you throw up." 
  (1/4 nutrition values apply, 15% chance of infection)
# 

Gameplay value:
- gathering, preserving and storing food is elevated to a real gameplay factor. People need to take care of their supplies.

**Comment by ghost** [comment]
And what if a survivor cooks rotten food...?

Status change:
raw/fresh ---> cooked/fresh
raw/well-hung ---> cooked/fresh
raw/peculiar ---> cooked/well-hung
raw/rotten ---> cooked/peculiar

**Comment by fazmond** [comment]
Then you want to be able put food in the pvc boxes to extend life

**Comment by ghost** [comment]
True! A usage for the useless PVC box!

**Comment by R4Z0R49** [comment]
As much as this would be good a2 has no way to track inventory so adding date/timestamps to items wont be possible.
