### ISSUE TITLE
Destructibility of wooden fences (1.8.2)

### ISSUE THREAD

**Issue by Wraithe** [DayZMod/DayZ#223]
Is there a plan to make wooden fences destructible? Currently, every phase of a WoodenFence is impervious to any kind of damage, from a Ural at 40 kph to 3 satchel charges. If there is a longer term plan I just didn't turn up while searching, that's fine, but I just wanted to address it before the party got really rolling.
(I LOVE the vision of the new build system - hands down, far better than the one we'd been implementing)
Using 1.8.2

**Comment by Wraithe** [comment]
A thought - would it be possible to make Wooden Fences "destroyable" like a tent? That would actually be kind of cool. Same requirements Matches, jerry can, big pillar of smoke and flame....:)
Also that would help distinguish them from, say, a metal fence, which couldn't be destroyed that way.

**Comment by IgiCodes** [comment]
I've actually discovered through testing that they are actually destructible.
They just don't possess a destruction model so they just make a big boom and sit there like nothing happened.
However, if you restart your server after it "explodes" you'll see that it has actually disappears.

**Comment by Wraithe** [comment]
lgirisujin: So they do! I hadn't even thought to try that. Thanks for the info!

**Comment by kichilron** [comment]
#355 Deconstruct is planned, Destructibility is yet to come (or maybe not) - Cleanup & Closed.
