### ISSUE TITLE
WoodenFence_1_foundation Possible Nuisance Item (1.8.2)

### ISSUE THREAD

**Issue by Wraithe** [DayZMod/DayZ#224]
Currently the "WoodenFence_1_foundation" requires only two items to build and requires no consumables.
Issues:
1: This creates an "area denial" item for vehicles that requires very little time to create and no resources.
2: Cannot be removed, other than by the creator building it all the way up to WoodenFence_1 and disassembling.
3: Since they're indestructible (see https://github.com/DayZMod/DayZ/issues/223), they can used to create "traps" for vehicles on roads. (I haven't tested hitting one at 130 kph in a Gaz, but a Ural at 40Kph lost a tire)

**Suggested Solution**: Change the WoodenFence_1_foundation model to be non-obstructing. (ie: not block vehicles or need to be vaulted over), this would potentially fix issue: https://github.com/DayZMod/DayZ/issues/225 as well.

**Comment by facoptere** [comment]
Main problem is that it needs no resource, not even a first wood log or iron beam.
I saw that players were drawing some funny things with foundations;
http://www.youtube.com/watch?v=KpM7Ba7kBm4&feature=youtu.be

Will be fixed in 1.8.3. Some material will be needed, and you won't be able to vault over.
Construction will be forbidden on roads and around large buildings.

**Comment by Wraithe** [comment]
Yeah, the lack of required consumables is my major concern. My players haven't gotten to pictures, yet. :)
So, good that in 1.8.3 it will need consumables/materials and blocking from certain areas.
You won't be ABLE to, or you won't NEED to vault over them?(**Edit:** _By "them", I mean the "WoodenFence_1_foundation"_) I'm really hoping it's the latter. If they block vehicles as well as players - that's a big potential problem.
I checked the rolling changelog, and there's nothing in there about any of this.

**Comment by facoptere** [comment]
so basically you don't like fences.

**Comment by Wraithe** [comment]
I LOVE fences, as noted in https://github.com/DayZMod/DayZ/issues/223, I love the new build system, but if we (server admins) end up tearing stuff people spent hours to put up 2 months from now because it's become abusive, I'd rather head that off now, and just make it harder to abuse.

Example: If the fence foundation is indestructible(which it is as of 1.8.2), and you can't cross it with a vehicle (you can't), and if in 1.8.3 you can't vault it...why build an actual fence? I now have an area denial item, that you can't see as easily as a full fence, so I can keep people out of areas OR use them outside of a fortified (fenced) area to force an attacker into corridors where I can cut them apart with defensive fire, since there's nothing they can use for cover.

Finally, it just seems silly to have these lumps on the ground that I can't drive/walk over. The next stage of the fence (the Frame) is lower than most of the fences you can vault over in DayZ.

I personally, think the solution is to make the "WoodenFence_1_foundation" class simply not be an obstacle at all. That seems to me, that it would solve the problems outlined above.
