### ISSUE TITLE
Packing a dome tent is not working

### ISSUE THREAD

**Issue by DayZCC** [DayZMod/DayZ#227]
Packing the standard tent works just fine but when trying it on the dome tent the option to "Pack Tent" doesn't even show up.

**Comment by KPanicEKS** [comment]
you cannot rest at dome tents either.

**Comment by DayZCC** [comment]
Yes that to, I can't remember if you are able to burn then either but don't think so.

**Comment by kichilron** [comment]
Thus will be looked into shortly

**Comment by R4Z0R49** [comment]
This is a known issue thanks.

**Comment by KPanicEKS** [comment]
@DayZCC if I remember correctly you can only burn them down with the 5L fuel cans. I will try to test later today

**Comment by DayZCC** [comment]
@M0tzilla Yeah I know, but have never gotten the option on dome tents, only the regular tents

**Comment by facoptere** [comment]
fixed in 1.8.3
