### ISSUE TITLE
Roadblocks do not render in time

### ISSUE THREAD

**Issue by crazykid1297** [DayZMod/DayZ#23]
Hello,

While my group and I were driving our vehicles around the map, a few of us had trouble rendering the roadblocks. When the roadblocks are not being rendered neither are the collision boxes, so you can drive right through the area they are supposed to be in (until they render).

One of our drivers crashed head-on into one because it literally "popped" into the game right in front of his vehicle. And later on, it happened to me as well, it just rendered right in front of our only other vehicle, resulting in another crash.

I've seen this problem in previous builds but now it seems to be a lot worse so I thought I'd post about it.

Thanks for reading.

**Comment by R4Z0R49** [comment]
We are looking into this issues its part of the FPS issue.

**Comment by facoptere** [comment]
You were on which road and using which vehicle?
How many hours were you playing when this happened?

**Comment by MattzFiber** [comment]
I can comment that this normally happens on a hill and the player is not in Los of the barrier so it is not rendered. Then the player at a speed and low fps comes flying into it or through it since it isnt loaded in time

**Comment by crazykid1297** [comment]
It was happening on too many roads with multiple vehicles, and it did not seem to matter how long the server had been up / hours played. It happens regardless. I guess if you had to test somewhere for this the best place would be on the coast (as usually it's the most laggy place).

**Comment by facoptere** [comment]
I tested with an helicopter at 200 km/h. No issue. I think it depends on the hardware too.
Fix I pushed : distance is auto-adaptative according to player speed. Your gameclient has 6 more  seconds to spawn the wrecks/garbages now.

**Comment by crazykid1297** [comment]
Still having this problem in patch 1.7.7.1, not sure if you were able to include the fix, could you please clarify?

**Comment by facoptere** [comment]
Yes it should according to github.

**Comment by MattzFiber** [comment]
Seems to work well here too.
