### ISSUE TITLE
Cannot apply sepsis bandages to other players

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#232]
We make a habit of crafting all bandages with comfrey leaves to make sepsis bandages, but have realized that we'll get into a jam if we need to bandage a fellow player that is knocked unconscious and bleeding as you cannot apply sepsis bandages to other players.  For now we make sure to carry at least one regular bandage in our inventory as well.

**Comment by HeroSmurf** [comment]
Modified + Added Code to apply Sepsis Bandage and Wipes to other players. 

Can I commit the code into the GitHub so you can see the changes?
If so what branch would you like me to use?

If not here are the files : 

stringtable.xml
http://pastebin.com/Xcxs8Bbv
    - Dialogue Text : Wipe Wounds, Use Sepsis Bandage
    - Added Translations for Spanish, Russian, French, German etc

Below Files : 
http://dayzknights.com/smurf/code/1.8.3-FixWipesBandages.zip

Added necessary call backs and event handlers. 

dayz_code\medical\bandage.sqf
dayz_code\medical\wipes.sqf
dayz_code\medical\publicEH\medSepsisBandaged.sqf (new)
dayz_code\medical\publicEH\medWipes.sqf (new)

dayz_code\init\compiles.sqf
dayz_code\init\publicEH.sqf
dayz_code\compile\fn_damageActions.sqf
dayz_server\compile\server_sendToClient.sqf

**Comment by HeroSmurf** [comment]
Due to size of update and lack of time this update will not be in 1.8.4. 
I'll submit a pull request when 1.8.5 work begins/is open.

**Comment by HeroSmurf** [comment]
We ok with adding this? Code is pre 1.8.4.1 but I can dust it off and resubmit to you. 
Ready for the pull?

**Comment by R4Z0R49** [comment]
Sepsis bandage should already be done wipes I'm not to worried about.

**Comment by R4Z0R49** [comment]
Wipes are not really a live changing system you can just as easy give the player the wipes.

Where bandages are a life saving system ie can mean the difference if knocked out.
