### ISSUE TITLE
Blood can increase beyond 12000 limit (1.8.3)

### ISSUE THREAD

**Issue by Detoeni** [DayZMod/DayZ#233]
Seen on fr130 on 11/12 October
I had seen my blood level pushed just over the 12000 by a dozen or so points as part of normal blood regeneration from canned food two or three times after taking a small amount of damage from z hits. 
I let my hunger drop to near flashing red, while being just under full blood and then cooked two mutton chops and had eaten them, letting the full three arrow regen pass before taking the next. This pushed my blood level up to 12693.

![2014-10-12_00002](https://cloud.githubusercontent.com/assets/8584071/4626700/2f1ced54-5384-11e4-9f38-42a4dd0a1931.jpg)

**Comment by kichilron** [comment]
Does it reset back to 12,000 at some point, though? Other than being damaged?

**Comment by Detoeni** [comment]
will have to check, I logged out just after this.
Just found a screen shot I took after eating the first mutton, that took my blood to 12652, so I may have been over 12000 before eating the first bit

**Comment by Detoeni** [comment]
Just a thought thinking back...
I had been moving east along the south coast on a quad, found a truck just beyond electro, swapped my gear over. Got attacked by a few z's while I was doing that, after checked blood, was 11###. then drove to gorka and stopped to drink, got hit again getting back into truck. Drove to a stash (about ten mins) and unloaded truck and then cooked meat.
Is being in the vehicle counting as resting and just adding to blood?

**Comment by Detoeni** [comment]
logged back in and blood was at 12781, had another mutton this went up to 12800 and remained there. got hit by a few z's, bleed once I was hit under 12000, blood dropped to about 11000ish, had one mutton, and one can which pushed me back to 12024. going from 12800, back to 12024 was outside of vehicle.

**Comment by R4Z0R49** [comment]
ok yea it looks like the checks have been removed with the revamp of some of the systems.

**Comment by Detoeni** [comment]
played on the watermarked 1.8.3 build, blood looked to be set to 12000 on login and would return to 12000 after a few seconds when pushed beyond normal limit

**Comment by R4Z0R49** [comment]
Yea i added a quick fix to reset the blood if its over. However the system should not be allowing blood to go over the max amount so for now this isn't fixed and needs more work.

**Comment by facoptere** [comment]
fixed in current dev code.
