### ISSUE TITLE
1.8.3 - going unconscious while driving a vehicle

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#235]
If your character goes unconscious while in the driver's seat of a vehicle (UAZ in my case), you get ejected from the vehicle and get a permanent hourglass and blurred vision (the latter if post processing is on).  You are then bugged until re-logging.  Other effects are that you cannot access the journal or your inventory once you're back in the car, and pressing F keys brings up the command menu on the left side of the screen like earlier versions of DayZ.

Video:
https://www.youtube.com/watch?v=RFqongNlguU

**Comment by facoptere** [comment]
fixed in current dev code
