### ISSUE TITLE
1.8.3 - Long respawn timer for zeds?

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#236]
My friend and I were testing on the 1.8.3 server and we met up at NEAF.  After killing the zombies we stayed in the area and it was completely devoid of zombies for several minutes.  I didn't time it with a stopwatch but I'd say for 5 minutes or so the journal was showing zero zombies on the server (we were the only two).

**Comment by KPanicEKS** [comment]
From my initial testing it seems like the zed spawn distance has also been lowered to ~100m.. someone please confirm?

**Comment by R4Z0R49** [comment]
That was lowered some time ago. Due to ppl moaning about the zeds range

**Comment by facoptere** [comment]
I can't see the issue in the OP. The guys killed all the zeds in the area and so...?
