### ISSUE TITLE
1.8.3 - weapon sway/exhaustion

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#237]
I know this was a hot button issue for 1.8.2.  The fix has definitely removed the excessive sway (THUMBS UP!!!), but it has gone so far the other direction that there is no effect of exhaustion or sway at all now.  You can run 100's of meters, snap up a sniper rifle, and immediately pull off a perfect shot.  This will turn Chernarus into a huge version of Counter-Strike's AWP map I'm afraid: https://www.youtube.com/watch?v=fd0u2ZRZpaE&t=14s

In pre-1.8.2 versions of DayZ, there _was_ weapon sway/exhaustion after jogging/running, but it settled down fairly quickly.  Examples:
https://www.youtube.com/watch?v=stTkrP7VJQ8&t=5m40s - Heavy breathing and weapon sway for about 8 seconds after jogging
https://www.youtube.com/watch?v=cJ3cV79GZU4&t=11m42s - Heavy breathing and weapon sway for 5 seconds after crouch jogging
https://www.youtube.com/watch?v=cJ3cV79GZU4&t=14m49s - Inaccurate shooting on zombie and player due to weapon sway (and lack of skill!) after running

**Comment by R4Z0R49** [comment]
Yea i know about this already the weapon sway was a quick fix to be release in a hotfix that never happened due to a few reasons.

Once the dev branch is up on steam we can start to fix these.

**Comment by KPanicEKS** [comment]
from my test in 1.8.2 I'm spawning zed at 250m. Personally I think it should be 500m or even 750m as it's too easy to see where ppl are by zed in the immediate area.. Take for instance the NE airfield. You can be at the barracks and there will not be zed at the ATC. Or you can be at the ATC and not have any zed at the hangers or barracks. It's a flawed system to be honest. It tells people in the area fairly accurately  where you are.

**Comment by R4Z0R49** [comment]
The problem is the FPS the zeds will become to spread out and you will need more to cover such a big area somthing arma isn't going to handle very well.

**Comment by KPanicEKS** [comment]
can it be a server side variable then?  So that way server owners with more power at their disposal can edit accordingly..

**Comment by R4Z0R49** [comment]
maybe

**Comment by kichilron** [comment]
Fixed.
