### ISSUE TITLE
no message for "fill jerry can" if you try to refuel full vehicle 

### ISSUE THREAD

**Issue by Detoeni** [DayZMod/DayZ#239]
Seen with 20lt jerry cans - not tested 5lt
If you fill a vehicle until only one can will completely refill, make sure you have two full jerry cans in inventory and then fill vehicle to full, still next to the vehicle mouse wheel again and the "refuel # with 20lt of fuel" will appear and can be selected. Once selected no animation happens and user will no longer get prompt to "fill jerry can" at fuel tanks.

**Comment by facoptere** [comment]
Can't reproduce the issue.

**Comment by Detoeni** [comment]
just got it again on fr130, this is always with the v3s. I'll grab another vehicle and see if I still get the problem. Also once I've lost the "fill jerry can" message I can no longer pick up hatchets

**Comment by facoptere** [comment]
could you describe better the issue. What I understand:
1/ you have 2 full jerrycans and a vehicle that needs a refill
2/ you can pour the first jerrycan to the vehicle tank and the vehicle tank is full now
3/ you can pour the second jerrycan using the menu, but there is no message/animation (and yes or no the jerrycan is still in the inventory? if not, it's an issue)
4/ then you can not siphon the vehicle (or use tanks at fuel stations?) using any empty jerrycan, and it's an issue.

Please complete the interrogations above.

**Comment by Detoeni** [comment]
1 - Yes
2 - Yes, but after first can is used, I stay next to vehicle and keep menu open. I have one full and one empty can in inventory.
3 - Yes, after I have poured I still have one full and one empty can in inventory.
4 - I have to option to siphon from truck at step 3, but do not get that option after that.

**Comment by facoptere** [comment]
ok it's fixed, thanks!
- "refuel vehicle" menu is hidden while a refill is in progress
- fixed the refill state so that further siphons/refills are enabled
