### ISSUE TITLE
Vehicle repair still unstable

### ISSUE THREAD

**Issue by crazykid1297** [DayZMod/DayZ#24]
Hello,

I was with one of my group members, and we had our UAZ. It had been crashed in a town, so we retrieved it, and made a lot of repairs however they didn't seem to apply correctly.

The colors of the parts that were damaged did not return to green after being repaired. The vehicle was damaged so badly from the crash that it's skin was set to have bullet holes / dents, etc. 

The repair list did not show the parts we had repaired, meaning they were fully repaired, but none of the parts on the HUD were green. We restarted our server to see if it would be fixed. But then it exploded.

Thanks for reading, if you need logs please tell me which log to look in and I'll send them.

**Comment by facoptere** [comment]
Part damage is set by the vehicle owner. The owner is the last player who was in the vehicle as a driver, or the server if player logged off or if the server is restarted and nobody get in.
I would like RPT logs from the owner and also server RPT.

**Comment by crazykid1297** [comment]
Done, logs here: http://www.mediafire.com/?rr8vedcm4d4tlwz

I was the owner (the last person to drive it) and I performed all of the repairs myself. I'm not sure if my logs go back as far as last evening because they do get spammed quite often, but I hope this helps.

**Comment by facoptere** [comment]
I can't help you well since repair is not logged on client, only damages. I fixed that.

All traces I get on server side are quite strange, since all parts of a vehicle are repaired in the same second. As if a cheater was there:

``` javascript
2013/06/18,  6:40:00 "z\addons\dayz_code\compile\veh_handleDam.sqf _this:[241c2080# 1055204: uaz.p3d,"glass1",0] vehicle:UAZ_CDF#4759321 part:"glass1" current_part_damage:0. Returned damage:0"
2013/06/18,  6:40:00 "z\addons\dayz_code\compile\veh_handleDam.sqf _this:[241c2080# 1055204: uaz.p3d,"glass2",0] vehicle:UAZ_CDF#4759321 part:"glass2" current_part_damage:0. Returned damage:0"
2013/06/18,  6:40:00 "z\addons\dayz_code\compile\veh_handleDam.sqf _this:[241c2080# 1055204: uaz.p3d,"glass3",0] vehicle:UAZ_CDF#4759321 part:"glass3" current_part_damage:0. Returned damage:0"
2013/06/18,  6:40:00 "z\addons\dayz_code\compile\veh_handleDam.sqf _this:[241c2080# 1055204: uaz.p3d,"glass4",0] vehicle:UAZ_CDF#4759321 part:"glass4" current_part_damage:0. Returned damage:0"
2013/06/18,  6:40:00 "z\addons\dayz_code\compile\veh_handleDam.sqf _this:[241c2080# 1055204: uaz.p3d,"wheel_2_1_steering",0] vehicle:UAZ_CDF#4759321 part:"wheel_2_1_steering" current_part_damage:0. Returned damage:0"
2013/06/18,  6:40:00 "z\addons\dayz_code\compile\veh_handleDam.sqf _this:[241c2080# 1055204: uaz.p3d,"motor",0] vehicle:UAZ_CDF#4759321 part:"motor" current_part_damage:0. Returned damage:0"
2013/06/18,  6:40:00 "z\addons\dayz_code\compile\veh_handleDam.sqf _this:[241c2080# 1055204: uaz.p3d,"karoserie",0] vehicle:UAZ_CDF#4759321 part:"karoserie" current_part_damage:0. Returned damage:0"
2013/06/18,  6:40:00 "z\addons\dayz_code\compile\veh_handleDam.sqf _this:[241c2080# 1055204: uaz.p3d,"palivo",0] vehicle:UAZ_CDF#4759321 part:"palivo" current_part_damage:0. Returned damage:0"
2013/06/18, 10:52:45 "z\addons\dayz_code\compile\veh_handleDam.sqf _this:[21a750c0# 1055204: lada.p3d,"wheel_1_4_steering",0] vehicle:Lada2#4759322 part:"wheel_1_4_steering" current_part_damage:0. Returned damage:0"
2013/06/18, 10:52:45 "z\addons\dayz_code\compile\veh_handleDam.sqf _this:[21a750c0# 1055204: lada.p3d,"wheel_2_4_steering",0] vehicle:Lada2#4759322 part:"wheel_2_4_steering" current_part_damage:0. Returned damage:0"
2013/06/18, 10:52:45 "z\addons\dayz_code\compile\veh_handleDam.sqf _this:[21a750c0# 1055204: lada.p3d,"wheel_1_3_steering",0] vehicle:Lada2#4759322 part:"wheel_1_3_steering" current_part_damage:0. Returned damage:0"
2013/06/18, 10:52:45 "z\addons\dayz_code\compile\veh_handleDam.sqf _this:[21a750c0# 1055204: lada.p3d,"glass1",0] vehicle:Lada2#4759322 part:"glass1" current_part_damage:0. Returned damage:0"
2013/06/18,  6:40:00 "z\addons\dayz_code\compile\veh_handleDam.sqf _this:[24142080# 1055206: lada.p3d,"sklo predni P",0] vehicle:Lada2#4759322 part:"sklo predni P" current_part_damage:0. Returned damage:0"
2013/06/18,  6:40:00 "z\addons\dayz_code\compile\veh_handleDam.sqf _this:[24142080# 1055206: lada.p3d,"sklo predni L",0] vehicle:Lada2#4759322 part:"sklo predni L" current_part_damage:0. Returned damage:0"
2013/06/18,  6:40:00 "z\addons\dayz_code\compile\veh_handleDam.sqf _this:[24142080# 1055206: lada.p3d,"wheel_1_4_steering",0] vehicle:Lada2#4759322 part:"wheel_1_4_steering" current_part_damage:0. Returned damage:0"
2013/06/18,  6:40:00 "z\addons\dayz_code\compile\veh_handleDam.sqf _this:[24142080# 1055206: lada.p3d,"wheel_2_4_steering",0] vehicle:Lada2#4759322 part:"wheel_2_4_steering" current_part_damage:0. Returned damage:0"
2013/06/18,  6:40:00 "z\addons\dayz_code\compile\veh_handleDam.sqf _this:[24142080# 1055206: lada.p3d,"wheel_1_3_steering",0] vehicle:Lada2#4759322 part:"wheel_1_3_steering" current_part_damage:0. Returned damage:0"
```

About exploding vehicles: all your UAZs are in bad shape (damage 90%), and may explode on restart. I will rewrite the vehicle spawn on restart to avoid that. The problem is in which order we declare damaged parts to ArmA engine when we setup a vehicle.

**Comment by crazykid1297** [comment]
Very interesting. Thank you for looking into the issue, I appreciate the effort.

Edit: I want to clarify that there is only one UAZ_CDF on my server, there is only one other Red UAZ (I believe the lada).

**Comment by facoptere** [comment]
yes, I assumed you were talking about UAZ_CDF.

**Comment by facoptere** [comment]
crazykid1297:  with this 1.7.7.1 version, do you think than the issue is fixed?

**Comment by crazykid1297** [comment]
It would appear so. Vehicles are re-spawning correctly when destroyed. For the vehicles we do have they seem to be repairing correctly also, and loading correctly on server restarts. I'll post back here if any more issues occur, but I believe it's safe to close this issue.

**Comment by facoptere** [comment]
thanks!
