### ISSUE TITLE
Resolved: Bug: wood piles doesn't appear to gear when chopping sawn planks

### ISSUE THREAD

**Issue by B73** [DayZMod/DayZ#241]
Resolved: wasn't bug from mod, but anti-hack system.

Chop wooden log > sawn planks > wood pile

Game says I made successfully wood piles, but they can't be found in gear, or ground. Had plenty of room for wood piles, so spare space isn't the issue. Restarted Dayz mod, tried again and this time managed to make couple wood piles. Little bit later bug again, can't make wood piles. Restarted Dayz mod, didn't work this time. Can't get rid of the bug.

Bug appeared first time 25.10. 2014, although heard another player having same problems some weeks ago.

**Comment by facoptere** [comment]
Choping trees is more reliable in 1.8.3.
