### ISSUE TITLE
1.8.3a - Quick transition from 3rd person crouched to ADS results in incorrect camera position

### ISSUE THREAD

**Issue by Detoeni** [DayZMod/DayZ#242]
This has only been seen today and I have yet to repro out side of the one hour time period where it was first seen, but given the nature of the bug I thought getting a report in might be best as I am unsure when I'll be able to get back on to try getting repro steps.

Each time it happened I was moving from sprint to crouched run to stopped ASD, firing then changing position again with the same moves. About 20% of transitions to ADS resulted to my camera moving to an position off set from the scope, the camera would then enter an orbiting path centered on the scope but still offset.

I have also been using ADS without issue whilest standing still, dropped out of ADS and then returned and had the same issue show.

See two attached images taken about 5 seconds apart. Camera will snap to top or bottom of orbit and then move along the arch. After about 10 seconds the camera will snap to the correct position behind the scope. 
![2014-10-26_00002](https://cloud.githubusercontent.com/assets/8584071/4784210/f9204f6a-5d48-11e4-9133-223959d59613.jpg)
![2014-10-26_00001](https://cloud.githubusercontent.com/assets/8584071/4784211/f920db4c-5d48-11e4-8070-66f52e80f8cd.jpg)

Quickly coming out and going back into ADS will fix or it will return to the problem state.

**Comment by facoptere** [comment]
Your character is sick and need some painkiller. I know it's not obvious because an icon is missing to show the pain.

**Comment by Detoeni** [comment]
Ah, that's what happens when you drive into a lamp post now. :)

That is not quite what I was expecting, the change log describes the effect as : dizziness (very slow shake cams), during 15 seconds every 90 seconds (in average)
There was no noticeable camera shake, also I think the camera offset in ADS is too great. If you zoom in with a gun which has a 3d scope like the m4a3 while in this state you can get some very bad looking camera positions which look to move your head within the scope. 
Also the camera angle can be a bit extreme, a few times it felt like the gun was pointing over my head. 
I feel the effect atm does not inform the user of there medical state, the hud should be used to reinforce the visual effect. 
I think if the strength of the "dizziness" was reduced to about 20% or by an amount that stops the poor scope/cam placement would help, as would a small amount of shake/ tremor with a greater amount of shake in ADS.
The snap camera movement at the end needs a smoother transition.
When I next get on I'll turn on PP and see how it feels in 1st person.

**Comment by facoptere** [comment]
a very slow shake is what you are experiencing. I could have added "very very very slow", but the idea is there. The snap at the end can't be avoided.

**Comment by Detoeni** [comment]
You can add very very very slowly, but if you need to tell me its there, then something must be amiss.
In first person its not too bad, but a small shake is still needed imho.
Just seen a bigger problem which is guns that use 2d scopes like the dmr and cz. The sway/dizziness is next to nothing and it would not stop me from taking and making shoots out to 200m's.
I like most of the new stasis effects added, although the hunger thirst ones could be a bit more pronounced, but this pain one just does not cut it atm and given you can force your self out of it by spamming ADS means that where as before you needed to have painkillers to function, now you can do with out.

**Comment by kichilron** [comment]
Feature, not bug. Cleanup & Closed.
