### ISSUE TITLE
Solution: Gates aren't upgradable

### ISSUE THREAD

**Issue by IgiCodes** [DayZMod/DayZ#243]
It seems looking at a gate doesn't result in the upgrade action appearing.

Found the solution fairly quickly:
dayz_code\compile\fn_upgradeActions.sqf

line 27 has an if statement that checks if the cursor target iskindof "DZ_buildables".
The gates don't actually inherit from "DZ_buildables", they inherit from "Land_Gate_IndVar2_5".

I did a quick and easy fix and just added a 'or' to the if statement to check if iskindof "Land_Gate_IndVar2_5" as well as "DZ_buildables".

Probably a better way of doing it but this works and it's 2am ;)

**Comment by facoptere** [comment]
Gates are not buidables item for now. Only fences.

**Comment by IgiCodes** [comment]
I presumed as much, looking forward to future updates on the build system.
It would be nice to have it fully working without having to but a couple hours work into it :P

**Comment by facoptere** [comment]
I am closing this ATM.
