### ISSUE TITLE
Solution: Highest tier gates don't animate.

### ISSUE THREAD

**Issue by IgiCodes** [DayZMod/DayZ#244]
The highest tier gates of both metal and wood don't animate or show the "open" action.

I've solved this by recreating the class for them and making them inherit from MetalGate_1 and WoodenGate_1 respectively. The difference is that the highest tier gates are actually inheriting from the "House" class whereas MetalGate_1 for example inherits from "Land_Gate_IndVar2_5".

Example: http://hastebin.com/raw/alicovomuh

**Comment by facoptere** [comment]
I am closing this ATM.

**Comment by IgiCodes** [comment]
Quick addition, I forgot that inheriting from the 1st gate class inherited the Upgrade sub-class. So you need to overwrite that in the new class or instead of inheriting from the 1st class, inherit from a 'base' class instead that doesn't include the sub-classes for interactions.
