### ISSUE TITLE
Solution: Disassembling metal fences or any type of gate doesn't produce a box with required materials.

### ISSUE THREAD

**Issue by IgiCodes** [DayZMod/DayZ#245]
Boxes for the wooden fences are the only ones defined. As such, disassembling metal fences or any kind of gate will result in all your materials being lost and the object deleted.

I've personally created boxes that contain all the materials for each stage of metal fence and both types of gates; and then added them to the "Disassembly" class of each of them.

Here's an example (I've also modified the required materials for the fences/gates so that's why the contents of the boxes are different to what you might expect):

Gate Class: http://hastebin.com/raw/ewiweteyob
WoodenGateBox4: http://hastebin.com/raw/oteyizaqav

**Comment by facoptere** [comment]
there isn't any box in 1.8.3
