### ISSUE TITLE
Personal Bloodbags -- No Type Checking

### ISSUE THREAD

**Issue by cmkb3** [DayZMod/DayZ#246]
Whole Blood bags do not check for type compatibility -- instead they only work if your type exactly matches the type of the bag. This is easily fixed by mimicking the current regular blood bag code. Not sure if this is working as planned?

Arma 2 OA 1.63.125548  DayZ 1.8.2

**Comment by facoptere** [comment]
Whole blood bag should only works for yourself, since the blood is not filtered.
You can't do a transfusion to another player using a wholebloodbag.

**Comment by cmkb3** [comment]
Ah, ok. Not entirely familiar with blood transfusions. Closing.

**Comment by icomrade** [comment]
Whole blood bags are useful for players with the same Rh AND blood type as you, they only give 4k blood. Unless something changed since I wrote that bit. Technically you could give it to somebody else, but being an exact match is an extremely slim chance.

```
_bloodBagWholeNeeded = "wholeBloodBag" + _bloodType + _rhVal;
```
