### ISSUE TITLE
1.8.3b - Misleading message when cutting down trees

### ISSUE THREAD

**Issue by Detoeni** [DayZMod/DayZ#247]
I am not sure when this changed but I have noticed that trees that I have been able to cut down in the past no longer allow me to do so. Also seeing that some users on the Infected.fr forums have mentioned the same, I though I'd investigate.
In the past you had to be next to a tree and in woodland to get a log pile, now there were a few exceptions to this, one if a wooded area was too small or narrow it would not count as woodland, the other main one was Beech trees never worked (not sure of the type but they look like Beechish to me).
In the attached image: 
Panel 1 we have a mid sized beech type tree which is not in woodland. I can harvest timber from this with out issue.
Panel 2,  we have small, mid and large beech type trees at the edge of woodland. The two smaller ones can be harvested with out issue but the larger one gives the message “you need to be near a tree and in woodland to harvest”. 
Panel 3, we have small, mid and large conifer, again the small and mid can be harvest but the larger one can not. The larger one can not be harvested regardless of how deep into woodland it is. This larger conifer tree used to give log piles without issue in older versions of the mod so long as it was within woodland.
Panel 4, This large Beech type tree is deep within woodland but gives the user the “you need to be near a tree and in woodland to harvest”.
The message “you need to be near a tree and in woodland to harvest” is misleading as it does not reflect current behavior. As it now looks that only smaller and mid size trees can be harvested should the message not be changed to something like “there is no tree near by that is suitable to harvest” as the woodland part of the old message no longer seems applicable.
![timber](https://cloud.githubusercontent.com/assets/8584071/4872660/eddd0e32-61ed-11e4-8f73-e8fc5ccb615e.jpg)

**Comment by facoptere** [comment]
agreed. in fact all trees with the red X "do not exist for the mod", i.e when we request the engine to give all things around the players, we have everything (foodstep, dragonflies, dead leaves...) except the tree in front of the player. It's a bug of the Chernarus map. 
The best is to display an icon when the tree is harvestable and when the user is holding the hatchet.
