### ISSUE TITLE
1.8.3b - Camo nets are being cleared when owner is still alive

### ISSUE THREAD

**Issue by Detoeni** [DayZMod/DayZ#249]
Put one up _I think_ last week end and placed a tent under it. Tent is still there, Camo net was removed today.

**Comment by facoptere** [comment]
Maybe it's the cleanup system on the hive side:
#Remove camonets whose owner has been dead for 1 day

The last track I have for your camonet is this one:
2014-11-01 13:07:47 HiveExt: [Information] Result: ["OBJ","413","CamoNet_DZ","51",[345,[8018.95,11071.6,0]],[],[],0.0,0.0]

Maybe you died after that and so the camonet has been removed.

**Comment by Detoeni** [comment]
I've not died......yet

**Comment by facoptere** [comment]
Congratulation.
Nobody destroyed your camonet, so it's a hive maintenance event that did it.

**Comment by Detoeni** [comment]
no worries, just had a user accident so was wondering whats the life of a tents, stashes and constructions after user dies? also do the tents/stashes stay active if I keep using them. Its been a while since I looked at the clean up script so I am unsure of the times/settings.
