### ISSUE TITLE
1.8.2 Traps Re-appearing

### ISSUE THREAD

**Issue by MercianUK** [DayZMod/DayZ#251]
I have recently noticed, that when traps are laid and then picked up/taken, they re-appear on server restart. A player can do this after every restart and accumalate traps. I thought it was maybe the server I played on, so I went to another server to confirm.
This has happened on two DayZ "vanilla" servers.
The traps used were:
Smoke
Grenade
Bear

**Comment by facoptere** [comment]
It should be fixed in 1.8.3. I will close this ticket, please reopen it when you have the isssue again (with version 1.8.3).
