### ISSUE TITLE
Rough stones

### ISSUE THREAD

**Issue by Jbird206** [DayZMod/DayZ#253]
Where to find these? 

Also, with a DIY metal, what's all needed for the making of the fence?

Is the bench, shack and fortress buildable?

**Comment by facoptere** [comment]
Is the bench, shack and fortress buildable? > no, only fences, as stated in the changelog. I don't know what the bench is good for. The different models exist though, but  I don't think they can spawn.

**Comment by Jbird206** [comment]
And the stones?

**Comment by facoptere** [comment]
I let you find them, usually at the trains and ruins.
But if you are using the Steam version, the stones do not spawn so much, you have to use the latest Release Candidate version using my installer.

**Comment by Jbird206** [comment]
Ok thanks. Currently stuck on loading screen, spawning items... Is the message.

**Comment by facoptere** [comment]
yes it has been fixed already, as soon as someone picked a plant, others can't join.
