### ISSUE TITLE
Tape Use (1.8.2)

### ISSUE THREAD

**Issue by Gogoo51** [DayZMod/DayZ#254]
Like mentioned before, the tape in 1.8.2 has one use which is a bit extreme, i was hoping to pitch the idea (like the knife and the matchbox) to have uses.
 for example:  6 total "points"

   A hatchet takes 3 points to fully repair and 2 points to make a "temporary Hatchet" that can't be used for melee and has a 15% more of a chance of braking when used.

   A water bottle will take 2 points to fully repair and 1 points to make a temporary bottle that can only restore 750 thirst  and also have 15% more chance of of braking when boiling the water.
 Hopefully these changes can be made by 1.8.3

**Comment by facoptere** [comment]
decay mecanism, or considering any item as a magazine is very complicated to achieve with Arma2 OA and the current Hive. You won't see it in dayzmod, but maybe on another mod for ArmA3.
