### ISSUE TITLE
1.8.3b - Metal fence building and dismantaling both give back logs

### ISSUE THREAD

**Issue by Detoeni** [DayZMod/DayZ#255]
Construct metal fence to stage 3 and the two logs used in an earlier build stage are returned. If the metal fence is upgraded again (stage 5 in my repro) and then dismantled the user will get another two logs back with all the other fence parts.

**Comment by facoptere** [comment]
yes it's more convenient to make apear the wooden logs every time if you want to move the fence.
it's not a big deal because wooden log are not a rare asset
