### ISSUE TITLE
Problem with object spawn

### ISSUE THREAD

**Issue by lWmPl** [DayZMod/DayZ#256]
From 1.8.2 update my private server have some unpleasant bug: rarely after reboot objects(vehicles, tents, stashes) doesn't load from db. What could be a reason?

**Comment by facoptere** [comment]
you mean 1.8.3?

**Comment by lWmPl** [comment]
No. 1.8.2. I'm just a humble and didn't dare write about this. :-D And now it's happening more often.

**Comment by lWmPl** [comment]
Today its happend again. There is HiveExt.log from server start ---> https://docviewer.yandex.ru/?url=ya-disk%3A%2F%2F%2Fdisk%2FHiveExt.log&name=HiveExt.log&c=5471a02c7a92

**Comment by thevisad** [comment]
This is a known issue with the Hive itself, it occurs randomly and only fix is to reboot the server. This is not an issue with the DayZ project itself.

**Comment by lWmPl** [comment]
ok... and any advice how fix that? this bug come with 1.8.2, so there must be some solution.

**Comment by thevisad** [comment]
The bug has always been present, I have code based on 1.7.7 and it happens there. If you look in the logs it typically says something about already being initialized. This is built into the hive itself and is a check to verify that you are not trying to reinitialize the server. Every once in a while, there is an issue with this check. It's intermittent, so it's very difficult to debug and I have not be able to catch an event in our hive during debug to date.

**Comment by thevisad** [comment]
I have also seen this occur when there is a bad vehicle in the table causing a crash of the hive query, causing it to return nothing to the server. Verify your vehicle lists in the database.

**Comment by R4Z0R49** [comment]
It can also happen when a client connects to the server during startup. If the client crash's so does the hive and it blocks objects being spawned. Its been an issue for a long time.

**Comment by lWmPl** [comment]
ok gays, thx. i will try to fix this problem and if i find some specific patterns of this be sure to let you know.
