### ISSUE TITLE
Oil Barrels Graphic Glitch 1.8.3

### ISSUE THREAD

**Issue by TIC321** [DayZMod/DayZ#257]
http://steamcommunity.com/profiles/76561198053581344/screenshot/28474501086975834

**Comment by GeryonTom** [comment]
I've noticed that it happens on US434 but on FR129 the barrels don't render at all.  Facoptere did you prevent them from rendering?

**Comment by R4Z0R49** [comment]
Issue is now fixed. The model was holding an incorrect rvmat causing the problem.

**Comment by LinusLeonard** [comment]
Could you direct me to the commit that fixed this? I can't seem to find the issue-commit-connection.

**Comment by kichilron** [comment]
The DayZ Mod Repository was private / invisible for the longest time and only recently switched to public again.
You will not be able to see in any case.

**Comment by LinusLeonard** [comment]
Oh ok, for some reason I thought it had always been open-source. So just to make things clear, if we've forked 1.8.3 to make our own "mod of the mod", we won't be able to apply a fix for the graphic glitch until 1.8.4 is released?
