### ISSUE TITLE
Refueling issues.

### ISSUE THREAD

**Issue by AVendettaForYou** [DayZMod/DayZ#26]
Upon trying to refuel a vehicle it takes about 2-3 minutes just to get the refuel option, usually the save vehicle option overwrites the refuel option on my server. Have tested and confirmed myself.

**Comment by crazykid1297** [comment]
I have not had that specific issue, but I had an issue where "Fill Jerrycan" would not appear when holding empty cans and looking at a tank after I had refilled them a couple of times.

**Comment by ghost** [comment]
If you have an antihack script on your server you may need to search for 's_player_fillfuel'
and somewhere in the same line add ',s_player_fillfuel5,s_player_fillfuel20'
Note that there is a comma that separates each player action, and at the end there is no comma, also do not include the '' quotes.

**Comment by marceldev89** [comment]
Is this still an issue?
