### ISSUE TITLE
Make blunt melee weapons have a chance of knocking players out

### ISSUE THREAD

**Issue by GeryonTom** [DayZMod/DayZ#264]
Either a small chance to knock the player out or maybe an automatic knock out that doesn't result in a death when it's a head hit.

This will add an additional dynamic of a non-lethal way to disable a person.  Helps heros and non-kos bandits.

**Comment by Lukethero** [comment]
Possibly add more blunt weapons due to baseball bat and possibly the crowbar beeing  the only blunt melee weapons. Reason why I say possibly crowbar is because it is relatively sharp on the end. Maybe add a police baton and or frying pan for less blood damage and more knockout chance or length.

**Comment by TIC321** [comment]
With how the player swings the melee weapons, the crowbar is quite deadly if you hit someone in the head with it. It wouldn't only knock them out, it'd crack their skull and kill them. It's a metal object. A baseball bat should have a possibility of knocking someone out or killing them.

**Comment by R4Z0R49** [comment]
This should be in for 1.8.7
