### ISSUE TITLE
Suggestions for 1.8.4

### ISSUE THREAD

**Issue by TIC321** [DayZMod/DayZ#265]
Suggestions below.

*An ability to pour out water in bottles which may be helpful in times where you don't have matches to boil water.

*Using junk loot to continue the life of fire. (such as rags, gauze, cards)

*A way to sleep in tents; such as this ;) https://www.youtube....h?v=ajHJIuaBN1k (This has a lot of potential with the snoring)

*Viewing achievements from diary.

*Possibility of removing status icons and replace them with sounds(Such as stomach growling when hungry)

*A way to access player's gear while in the surrender stance.

*Implement radios that would allow us to talk to players throughout server ;) http://i.ytimg.com/v...xresdefault.jpg

**Comment by R4Z0R49** [comment]
Hi Tic, Can you separate these into issues one by one.
