### ISSUE TITLE
Bear Trap  1.8.3

### ISSUE THREAD

**Issue by reddogg1** [DayZMod/DayZ#266]
Place Bear Trap  select Arm trap
 will not arm

will also dupe itself if you try to place it on a road then cancel 
this happen in front of Hospital in Electro

**Comment by KPanicEKS** [comment]
confirmed bug in build 1.8.3.a216b06

**Comment by R4Z0R49** [comment]
Really no idea what's been done to them they will have to be shelved for a time.

**Comment by craftfortress** [comment]
Yes confirmed, bear traps are not arming

**Comment by R4Z0R49** [comment]
Fixed.

**Comment by craftfortress** [comment]
=]

**Comment by HeroSmurf** [comment]
=]
