### ISSUE TITLE
Server crashes on player load

### ISSUE THREAD

**Issue by tpbcnote** [DayZMod/DayZ#27]
I use DayZCC, upgraded to beta patch 103718 and DayZ version 1.7.7, but the server is crashing after a player clicks Ok from the lobby and begins to load. If I replace the DatabaseMySql.dll with the old one from 1.7.6.1 then the server will work and all mods work fine. However with the new .dll downloaded with the 1.7.7 files this continues to happen, and here is the error thrown out when the server crashes:

Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: arma2oaserver_1.exe
  Application Version:  1.62.103.718
  Application Timestamp:    51682563
  Fault Module Name:    DatabaseMySql.dll
  Fault Module Version: 0.9.14.0
  Fault Module Timestamp:   50f1ba27
  Exception Code:   c0000005
  Exception Offset: 0000a14d
  OS Version:   6.1.7601.2.1.0.272.7
  Locale ID:    1033
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

**Comment by MattzFiber** [comment]
This is a issue regarding your server pack not yet supporting the new patch. Use the packs forum to find help and information on it
