### ISSUE TITLE
Cancel Item Stash/Sand wall bug 1.8.3

### ISSUE THREAD

**Issue by fazmond** [DayZMod/DayZ#270]
Upon trying to build a stash or a sand wall  if you try to cancel it will still drop the object in place , the gear of the stash is usable , but the items do disappear upon a server restart.

so if you were to fill the stash with gear you would lose it

this is repeatable as the materials don't get used and someone could spam them down. (atleast till a server restart)

**Comment by R4Z0R49** [comment]
Tested this out but was unable to recreate this problem. Closing till more info from others come in.
