### ISSUE TITLE
Cancel build fence not resetting - 1.8.3

### ISSUE THREAD

**Issue by Thisnameisnottaken** [DayZMod/DayZ#272]
Cancel build wooden/metal fence keeps option to cancel build , the complete option doesnt return
untill server restart 
While with dirt stash it does reset the cancel build option ,  but the option to complete still appears in menu (without rightclick on sandbag) to build a "fake" dirt stash (its in the game but not saved to the database)
Managed a few times to reset it (put the sandbag on the ground~pick it up again) so can build a "real" dirt stash , but it doesnt work all of the tries

**Comment by R4Z0R49** [comment]
Dupe post https://github.com/DayZMod/DayZ/issues/270
