### ISSUE TITLE
DayZ 1.8.3 Known Bug List

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#275]
These bugs are the ones I have experienced thus far in my hours of play in 1.8.3. If I am missing any, feel free to say it and I will add it to the list. Note that these are not all the bugs present on dayZ, just the big ones introduced in the most recent patch.
1. Church bells ringing continuously and everywhere. - Fixed
2. Bloodbags working rarely to none of the time (heard reports of some players getting it to work some of the time). When trying to apply bloodbags it says bloodbag canceled due to player movement, even if the player is completely still. - Need more info
3. Only evergreens giving wood when trying to chop wood. -- Known issue
4. Knockout system even more bugged than before. Player continues the actions they were taking part in, even after knocked out. Worst part is if you are knocked out you can spam get up and easily continue playing even while knocked out. -- In the middle of being updated with new effects
5. No zombies spawning, especially when server pop is high. Almost 100% sure this is due to decreased zombie max. Try and increase to 500 - 1000. - Known issue 
6. No exhaustion gained whatsoever. - Known issue, fixed
7. Oil barrel texture glitch.. - Known issue, fixed
8. When trying to construct entities, if the action is canceled, an uninteractible model stays. This at least happens with camping tents, but if it happens with camping tents, I am sure it will occur with others. - Known issue
9. Empty tin cans and soda cans not appearing after the content has been consumed. For the can to appear you have to either be on a preexisting loot pile or be interacting with one. -- New issue seperate
10. When player spawns in a wrong akin will e displayed on the character, regardless of their humanity. Sometimes bandits will be displayed as a survivor or a survivor as a bandit. I have not heard of any hero problems, but this is understandable due to the small amount of them. This problem seems to fix itself after a certain period of time or once their humanity is updated. -- Need more info
    
    ```
                                     -Unconfirmed By Me-
    ```
11. Having more than 1 matchbox in your belt = all but 1 disappear. (Reported by B73) -- Need more info

**Comment by bchawke** [comment]
I've experienced most of these too.  9) is a feature I brought this up as a bug in 1.8.2 (you could gather dozens of blood bags of the wrong type and continually administer them to a friend to boost humanity while he's passed out).  https://github.com/DayZMod/DayZ/issues/230#event-186652297

6) is a temporary solution to the exaggerated that was experienced in 1.8.1 and they are working to get it back to how it should be.  7) has been solved for the next patch.  As for 10), I haven't had a problem with dropping empty tin cans beyond the occasional event where nothing appears which has always been the case.  I recommend being on a flat surface outdoors and not moving until you see a can appear on the floor, or start a loot pile before eating.

**Comment by TIC321** [comment]
There's also an issue with not picking up backpacks with people around you.

Is this a feature to prevent duping?

**Comment by kichilron** [comment]
You can't pick up Backpacks when people are within a certain radios - this is to prevent duping.

**Comment by kichilron** [comment]
1: Known and fixed.
2: Need more information, best would be with as much information as possible in a new Issue on here.
4: Most likely down to Serverload, video would be nice.
6: It was disabled for now, due to a lot of complaints about it being too high. Should be fixed in next build.
7: Known / Fixed.
8: Known.
9: Intentional, to prevent farming with wrong bloodtypes. Not really nice to apply wrong bloodbags, thus no Humanity is awarded.

**Comment by Lukethero** [comment]
@kichilron I was not looking to post a detailed explanation of each bug. I am well aware of the exhaustion status and other bugs and know what bugs the informed community knows of. I am Just simply to put rest to those. If you would like me to post a detailed analysis on any of these, I could, just not the purpose of this particular thread.

**Comment by Lukethero** [comment]
@kichilron for #4 I do not have a video capture device.... But I could send screenshots, but I suggest you try it out for yourself.

**Comment by B73** [comment]
I noticed
a) rangefinders spawned to dead corpse (human player, he didn't have them before he died)
b) you can gear burning campfire and get wood from it to your inventory

I also suspect rangefinders spawned to my stash (don't remember having them more than 1, but had 2 suddenly). Friend of my said he had SVD in his hands before he logged off, but after logging in it turned into FN FAL.

Also FPS dropped in this patch, got warning when opening map (low fps warnings) and in game FPS goes as low as 18 in misty days (clouds). In town areas FPS flips around 15-30, in woods around 30-40. Got quad core Intel Q9450 (http://ark.intel.com/products/33923/Intel-Core2-Quad-Processor-Q9450-12M-Cache-2_66-GHz-1333-MHz-FSB), 4 GB RAM and Geforce 570 GTX. Before patch had twice better FPS, in same server. Friend of my also said FPS decreased, but didn't give any readings - just said he noticed it right away.

**Comment by R4Z0R49** [comment]
a, Sounds like something the server has set. We don't give anything to dead bodys.
b, This isnt a bug you can take wood from the fireplace and also add it to make the fire last upto 20 mins at a time.

FPS drop can be a hole host of issues from server to client. We will look into this

**Comment by R4Z0R49** [comment]
Pressed bloody close in place of comment sorry.

**Comment by B73** [comment]
Having more than 1 matchboxes in belt = all but 1 disappear. Had one with 5 matches left, other with 4 left. Soon one disappeared, leaving only 1 matchbox to toolbelt.

**Comment by Lukethero** [comment]
Will make sure to add that b73

**Comment by Lukethero** [comment]
@bchawke @bchawke  @B73 @R4Z0R49 @kichilron 
Updated.

**Comment by R4Z0R49** [comment]
Not sure what that post is for but ok. All but one of the current listed items have already been listed in github. Your welcome to go over all the issue and add the one's missing but we have no need to have duplicate versions.

**Comment by Lukethero** [comment]
@R4Z0R49 Okay, I am going to separate 4 and 9 out. I am looking through posts and cannot find a post for 4 already out there. If there is an I missed it, just feel free to delete or close it.I will work on getting more info on the individual topics as well.
