### ISSUE TITLE
Some feature suggestions

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#276]
- Make players choose their blood type.  The blood type identifier in is a nice addition (don't have to write it on a pad of paper anymore), but it would be great if it were still a game to figure out the blood type using the chart.  Any way that we could be forced to click on the blood type we think it is from the results, and _that_ is what ends up next to the blood icon (even if it is incorrect)?
- Bring back the canteen.  It's definitely more realistic to find plastic water bottles littering the apocalypse, but I find I was actually quite attached to the military canteen.  Any way it can be brought back, but only found at military loot locations?  And could it give you more hydration due to a larger volume?
- Bring back the low blood effects.  I definitely like the "dizziness" associated with dehydration and pain, and the color/saturation effects with damage and gunfire work well, but currently when low on blood there's no sense of urgency.  I REALLY liked that in the past, when really low on blood, you were shaking/shivering, desaturated, and made the panic noises when near zombies.  I've noticed the panic noises only work some of the time now when low on blood.
- Not sure if it was intentional or not when adjusting the unconscious state, but my player simply goes prone now (and sometimes spins in a circle).  I really liked the animations of going unconscious from before

Side question: I forget, is there a way for me to add labels to my posts to designate "suggestion" vs "issue", etc, or is it up to the mods/devs to add them?

**Comment by R4Z0R49** [comment]
- I havent managed to look at this yet i know the blood type was added to the UI but it should only really show if you have used the blood testing kit. - Ill take a look at this soon as i have a bit of time.
- Hum i guess we can add the canteen back shouldn't do any harm.

The other issues are related to effect changes i know faco has been redoing alot of them. 

Labels i think might only be for mods of the github account. Let me look into that

**Comment by bchawke** [comment]
Thanks for the response!  Just to clarify, as it is supposed to, the blood type is only added to the UI _after_ you use a blood test kit.  That is working properly.  My comment is that having that part automated is too easy and it negates the fun mini-game of comparing the chart to your test results to determine your blood type.  I think it would be cool if you were required to click on the appropriate row on the chart that corresponds to your test results, at which point that blood type will appear in your UI (even if you choose the wrong one).  This requires some effort to figure it out and it can be difficult because sometimes it's hard to tell whether the sample agglutinated (clumped) or not.  Once or twice in 1.8.1/1.8.2 I've had to retake a blood test to be sure I wrote down the results correctly.

Thanks again for all the hard work!

**Comment by R4Z0R49** [comment]
Ok i see add that to its own issue and see if you can add labels to the issues now. (they should be on the right hand side)

**Comment by Lukethero** [comment]
I am not so sure I would like the water bottles remved..... It is a more realistic alternative. I would think it would be cool if you could add the canteen back and make it a military spawn. Make it better than water bottles in how you do not need an empty tin can to boil it and it is a little to no chance for the canteen to be broken. @R4Z0R49 @bchawke

**Comment by Lukethero** [comment]
@bchawke @R4Z0R48 Also I do not like the idea of choosing your bloodtypr because it will allow for humanity farming with o- and o+ beeing able to accept basically everything.

**Comment by bchawke** [comment]
@Lukethero, you need to read posts a bit closer before replying.  ;) First, I never recommended removing the water bottles.  I recommended adding canteens back in but limiting them to military spawns and having them be better than water bottles, which is the same thing you are suggesting.

Second, nobody recommended choosing your own blood type.  I am recommending that the player is required to decipher their blood test and click on the blood type that they think it says rather than it automatically popping up.  The blood type they choose will show in their UI whether it is correct or not.  So, for example, if a player's blood type is A- but they read the blood test as A+ and click on A+, then it will display their blood type as A+ in the UI (but it is actually A-).  Later, they might need a transfusion, and someone with an O+ blood bag will say "here, you can take this...", but then the transfusion fails because the first player had misread the blood test.

Something to add to this suggestion is having the ability to re-test with another blood test kit to correct the error.

**Comment by Lukethero** [comment]
Yeah I see what you were saying, it was just worded awkwardly. And by adding back canteens I assumed you were saying adding them back in and replacing the old one. Sorry for the assumptions and misunderstanding.
