### ISSUE TITLE
Zombies are little to no threat again

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#277]
With the combination of nerfing the zombies in 1.8.2 and the faster sprint with no exhaustion of 1.8.3, zombies present very little threat in the game again.  Even if you aggro an entire town worth of zombies all you have to do is sprint in a straight line and you lose them in seconds.  Is there a balance between 1.8.1 and 1.8.3 that will bring back the challenge but not deter beginners from playing?  My suggestions:
- Bring back the longer hit range from 1.8.1 for normal and viral zeds so they can hit you when you're running
- Bring back the higher damage scale for normal zeds
- Bring back the higher headshot damage multiplier from 1.8.1 but only for viral zeds
- Introduce a 3rd tier of zeds, ("easy" zeds?), that are the same damage/speed/hit range stats of the 1.8.3 normal zeds, and spawn only these zombies at towns close to the coast.

I'm not sure if you can easily separate coastal towns from ones further inland in zed spawn parameters rather than having residential, castle, military spawn points, but it would be great if the further inland/North you went the zombies were more difficult.  This would maintain a significant challenge for veteran players, but allow newer players to learn the ropes without getting too frustrated and quitting.  It has been an ongoing complaint about DayZ mod that the zombies are "no threat", but anytime they are buffed in any way there are a multitude of complaints about them being OP.  Maybe something like this could be a good compromise.

**Comment by R4Z0R49** [comment]
Until we bring back in the exhaustion in the next patch its best not to really touch the zeds. Until then at least.

Thanks
