### ISSUE TITLE
An option to pour out water in water bottles.

### ISSUE THREAD

**Issue by TIC321** [DayZMod/DayZ#281]
I believe this is an important thing we should be able to do since sometimes we might not want to risk capturing water from an infected lake and so forth. :)

**Comment by R4Z0R49** [comment]
Yep good idea should be easy to add.

**Comment by ebayShopper** [comment]
in 1.8.7+
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_code/actions/player_emptyContainer.sqf
