### ISSUE TITLE
picking item off the ground with full inventory

### ISSUE THREAD

**Issue by KPanicEKS** [DayZMod/DayZ#285]
Certain items that allow you to pick them up directly (bypassing inventory screen) will erase the item that was in your inventory instead of placing it on the ground in front of you. 

e.g., My main inventory is full but I find a DMR mag on the ground. If I move my crosshair over the mag on the ground I get the option to pick it up and drop something from my inventory. If I execute the task it will pickup the DRM mag but the item that was replaced in my inventory disappears and never shows back up on the ground, effectively wiping  it..

**Comment by ebayShopper** [comment]
already fixed
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_code/actions/object_pickup.sqf#L69-L88
