### ISSUE TITLE
Running through rain decreases temperature.

### ISSUE THREAD

**Issue by TIC321** [DayZMod/DayZ#288]
As of now, running through rain throughout Chernarus doesn't have any decrease in temperature. I'd like to think temperature should be as important as hunger and thirst. I hope we can see further tweaks for this.

This should encourage others to start building camps/bases or altogether just staying indoors and trying to find those heat packs ;)

**Comment by R4Z0R49** [comment]
This already happens but the temp you gain from running adds :-(
