### ISSUE TITLE
Destroy tents  - Fire is only seen by player that started it.

### ISSUE THREAD

**Issue by KPanicEKS** [DayZMod/DayZ#289]
If I destroy a tent using a jerry can the fire can only be seen by me. Other players cannot see the inferno or smoke associated with the fire I started. 

Dome Tent was used for testing.

**Comment by KPanicEKS** [comment]
confirmed in build 1.8.3.a216b06

**Comment by R4Z0R49** [comment]
Should be fixed hopefully next build
