### ISSUE TITLE
DMR Spawn Rate is Inconsistent and Too High

### ISSUE THREAD

**Issue by seaweeduk** [DayZMod/DayZ#29]
You have removed the 50 cal snipers which is great, should have a long time ago. The spawn rate on the DMR however is still way too high in my opinion and inconsistent.

For example

Military locations (the most common) 0.03
Heli crashes 0.04 and 0.06
military special (RAREST LOOT POINTS) 0.02

This seriously makes no sense at all DMR's are ridiculously common still. I have run a loot table with no 50 cal sniper rifles on my hive since Decemeber last year. I only spawned them in military special and I used 0.01. Maybe you think this is too harsh but I still don't see how the current percentages make sense. They are easier to find at the most common loot locations (military and helicrashes) even 0.03 is too high now this gun is the top tier sniper.

**Comment by R4Z0R49** [comment]
K Thanks

**Comment by seaweeduk** [comment]
Thanks for the constructive and informative response

**Comment by R4Z0R49** [comment]
I'm sorry i thought you where giving your opinion.

**Comment by seaweeduk** [comment]
Maybe if you paid attention to people reporting things instead of acting like an asshole you would have fixed this sooner Raz0r
