### ISSUE TITLE
some suggestions; skins, backpacks and care packages

### ISSUE THREAD

**Issue by Skydog4** [DayZMod/DayZ#292]
- can the various survivor skins be brought back to the game? now there's only one which looks like a bandit skin from afar. Also why not add a couple more lootable skins? just a few of them that are already in ARMA 2 and make them as rare as camo skins and ghillie suits
- how about some more variety in backpacks? Why not bring back the ALICE pack which was cool looking and add to it one or two more slots than the survival acu pack but make it a bit more rare but still able to spawn (right now it's totally gone)? Also the rarity and large size of the big coyote backpack kind of merits upgrading its storage capacity? Why not two more slots than the Czech backpack?
- what's up with the care packages which were introduced in 1.8.1? They almost don't exist anymore and when you do find it there's like one can of food there and maybe a transfusion kit. So why not make them spawn more and with more "survival loot" like bloodbags and food?

**Comment by R4Z0R49** [comment]
1, No reason we cant your more then welcome to bring them in.
2, Soon as i can remember what the actual name was ill take a look i don't remember removing it and if we did it must have been for a reason.
3, Care packages are still ingame the loot is random based on what one version spawns in (Server owners also control this)

**Comment by Detoeni** [comment]
in the test branch I never saw the ALICE pack at a building spawn, _think_ I saw it once at an infected camp. Don't remember seeing the British and the mid sized camo back pack at all.
From my experience Care packages spawn thier loot over a much wider area now which does make it very hard to find anything in the grass unless they spawn med boxes.

**Comment by R4Z0R49** [comment]
dayz_spawncarepkgs_clutterCutter set this to 2 in your mission/init, Loot spawns 10/20 meters away

**Comment by Skydog4** [comment]
Hmm, what do you mean I'm welcome to bring them (skins) in? You mean as a server owner? Unfortunately I don't own a server, I was just wondering can they be introduced to the Vanilla game for all the servers, like soldier clothing was introduced in the 1.8.1 patch?

**Comment by Lukethero** [comment]
I am in agreal with skins.... Also maybe add acouple of Cov skins that spawn in appartments and such. The problem might occur in distinguishing bandits from survivors and heroes. Maybe make it so it changes your skin varying on your humanity. This is wishful thinking.... But it would be a nice edition.

**Comment by R4Z0R49** [comment]
@Skydog4, Your welcome to find the good skins add all the backpack proxies and make a pull request so there added into the code.

**Comment by bchawke** [comment]
@Skydog4 does have a good point about the variety of survivor skins.  Was removing the other colors of vests/shirts/pants intentional?  Also, side question, my friends and I noticed that the color of survivor skin seemed to be client side.  Is it possible to sync the player's survivor skin color with the server so other players see the same color?

**Comment by R4Z0R49** [comment]
I really have no idea what skins your talking about as far as i know only the female skin was removed awhile ago?

**Comment by bchawke** [comment]
Really?  As long as I've been playing DayZ mod (about 2 years) the basic survivor skin had a few basic color variations.  http://i.imgur.com/plBCMV6.png  It would randomly select the color when you loaded into the game as a survivor, even just on relogging without dying.  The upside to this was sometimes you lucked out and had the dark clothing and would blend in better.  The downside is your color wasn't synced to the server, so how you looked on your own screen could differ from how other players saw you.  This became a bit confusing when trying to call each other as a squad.

Currently, the only survivor skin in the mod is the light blue shirt with beige vest.  This is a bummer because you stand out quite a bit more like the bandit skin, especially at night.

**Comment by R4Z0R49** [comment]
I'll have to look into that as far as I remember no skins should have been removed. As for the skin colour that could be an arma issue. Soon as I have some time ill check into that

**Comment by bchawke** [comment]
Cool, thanks!

**Comment by R4Z0R49** [comment]
ok it looks like we do a check for humanity to make sure the players have the correct models on login this is what's causing the players to always have the default Survivor2 skin.

I'll see if i can change it around before the next patch to bring in the old survivor skins as well.

**Comment by Lukethero** [comment]
@R4z0R49 how would one go about adding proxies for the backpacks? I know little about texturing for OA so detail would help.

**Comment by R4Z0R49** [comment]
You would be best to contact someone who does models or try to google it.

**Comment by R4Z0R49** [comment]
changed humanity system to support the 3 random survivor skins

https://github.com/DayZMod/DayZ/commit/0c75c3305e596f6f20a6b626b0a072b1442e6bf8

Needs testing.

**Comment by Lukethero** [comment]
Googled it.... Nothing real helpful. I would really like to contribute to the work going on here but sadly I do not know a moddler. I will look for one though and see what I can find.

**Comment by R4Z0R49** [comment]
http://forums.bistudio.com/showthread.php?104891-Making-custom-modelled-configured-backpacks&p=1712575&viewfull=1#post1712575

**Comment by Lukethero** [comment]
Thanks

**Comment by Lukethero** [comment]
Also, would you happen to know if the padlocks beeing implemented are going to be able to lock précis ting gates?
