### ISSUE TITLE
Please, fix the side checking (dayz_code\Configs\CfgVehicles\Skins.hpp)

### ISSUE THREAD

**Issue by denisio** [DayZMod/DayZ#296]
AI bots need the "east" side, but the dayz 1.8.3 limited by "west" and "civillian" only.

class Eventhandlers {
local = "_z = _this select 0;" \n
   "if ((!isServer and !isNull _z) and {(side _z != west and side _z != civilian)}) exitWith { " \n
   "PVDZ_sec_atp = [ 'wrong side', player ]; publicVariableServer 'PVDZ_sec_atp'; deleteVehicle _z; };";
   // note: the character switch to civilian side when the player quits the game and the locally goes to the server.
};

dayz_code\Configs\CfgVehicles\Skins.hpp

**Comment by R4Z0R49** [comment]
You can change it ?

the development build is on github just change the branch. Not really sure why this exists to start with ill need to ask faco whats it been added for.

**Comment by denisio** [comment]
Yes, I can. 

Can you explain to me how to repack pbo files with "dayz.bikey" or "dayz_code.pbo.dayz.bisign" ?
I think that this need a private key...

**Comment by R4Z0R49** [comment]
You have to create your own key. Dayz's key is not public.

**Comment by kichilron** [comment]
If you need the keys just for testing / developing on your own server, simply disable the signaturecheck in your server.cfg

No point in having to rebuild including the keys everytime you change a tiny bit of cide.
