### ISSUE TITLE
Tents duping

### ISSUE THREAD

**Issue by entspeak** [DayZMod/DayZ#3]
I ended up with 2 tents while trying to pitch a tent on a laggy server and got a 3rd while trying to pack up the two I ended up putting down in the same spot.

**Comment by echo5rom3o** [comment]
I can confirm this also happened with me as well. Place one tent down, 2 appear, pick one up and place it down, 2 more appear.

**Comment by R4Z0R49** [comment]
What @hive is this?

**Comment by echo5rom3o** [comment]
Public, server name US 1154

**Comment by R4Z0R49** [comment]
ty

**Comment by entspeak** [comment]
I had this on US 3279... public.

**Comment by R4Z0R49** [comment]
I can not recreate this.

**Comment by MattzFiber** [comment]
I have seen this, it happens with lag and you try place a tent twice, you spam it and it creates 2, although I have not been able to recreate on the new patch.

**Comment by icomrade** [comment]
I can confirm this and have fixed it as well as similar methods of duping. Included in next patch.
