### ISSUE TITLE
Tents & Stashes getting cleared in Cleanup

### ISSUE THREAD

**Issue by SpudmanWP** [DayZMod/DayZ#30]
It seems that tents are getting cleared out in the cleanup script.

<code>DELETE
FROM Object_DATA
USING Object_DATA, character_data
WHERE Object_DATA.Classname = 'TentStorage' OR Object_DATA.Classname = 'StashSmall' OR Object_DATA.Classname = 'StashMedium'
AND Object_DATA.CharacterID = character_data.CharacterID
AND character_data.Alive = 0
AND DATE(character_data.last_updated) < CURDATE() - INTERVAL 4 DAY;
</code>

<code>
DELETE
FROM Object_DATA
WHERE Classname = 'TentStorage' OR Classname = 'StashSmall' OR Classname = 'StashMedium'
AND DATE(last_updated) < CURDATE() - INTERVAL 7 DAY
AND Inventory = '[[[],[]],[[],[]],[[],[]]]';
</code>

<code>
DELETE
FROM Object_DATA
WHERE Classname = 'TentStorage' OR Classname = 'StashSmall' OR Classname = 'StashMedium'
AND DATE(last_updated) < CURDATE() - INTERVAL 7 DAY
AND Inventory = '[]'; 
</code>

The issue is missing parenthesis around the three "OR"s

-------------------------------  Here is it fixed  --------------------

<code>DELETE
FROM Object_DATA
USING Object_DATA, character_data
WHERE (Object_DATA.Classname = 'TentStorage' OR Object_DATA.Classname = 'StashSmall' OR Object_DATA.Classname = 'StashMedium')
AND Object_DATA.CharacterID = character_data.CharacterID
AND character_data.Alive = 0
AND DATE(character_data.last_updated) < CURDATE() - INTERVAL 4 DAY;
</code>

<code>
DELETE
FROM Object_DATA
WHERE (Classname = 'TentStorage' OR Classname = 'StashSmall' OR Classname = 'StashMedium')
AND DATE(last_updated) < CURDATE() - INTERVAL 7 DAY
AND Inventory = '[[[],[]],[[],[]],[[],[]]]';
</code>

<code>
DELETE
FROM Object_DATA
WHERE (Classname = 'TentStorage' OR Classname = 'StashSmall' OR Classname = 'StashMedium')
AND DATE(last_updated) < CURDATE() - INTERVAL 7 DAY
AND Inventory = '[]'; 
</code>

--------------------  I rewrote it as a single delete query --------------------

<code>
DELETE
FROM Object_DATA
USING Object_DATA, character_data
WHERE Object_DATA.Classname IN ('TentStorage','StashSmall','StashMedium')
AND Object_DATA.CharacterID = character_data.CharacterID
AND Inventory IN('[[[],[]],[[],[]],[[],[]]]','[]')
AND (
(character_data.Alive = 0 AND DATE(character_data.last_updated) < CURDATE() - INTERVAL 4 DAY)
OR
(character_data.Alive = 1 AND DATE(character_data.last_updated) < CURDATE() - INTERVAL 7 DAY)
);
</code>

**Comment by R4Z0R49** [comment]
Thanks ill get this added.
