### ISSUE TITLE
Camonets

### ISSUE THREAD

**Issue by dayzjarhead** [DayZMod/DayZ#300]
Why not make them removable by the owner?
- removing a camonet by the owner puts the item back in inventory.
- if inventory is full, put the item on the ground

**Comment by R4Z0R49** [comment]
The plan is to add one at some point

**Comment by ghost** [comment]
Is this maybe just a matter of modifying player_packTent.sqf?

**Comment by R4Z0R49** [comment]
aye and then then adding an action

**Comment by ghost** [comment]
I´ll give it a shot tonight. Maybe I can contribute a little.

**Comment by ghost** [comment]
Hm. For some reason I can not select the CamoNet_DZ as target...

> _istypeCamo = (_cursorTarget isKindOf "CamoNet_DZ");

fails... 

Any suggestions?

**Comment by kichilron** [comment]
Add a loop to display your current target. 

Try to find the camonet as a target. It's almost impossible, hence why it's not in at the moment.

Remember the wires being extremely hard to get as target as well? That is an ARMA-issue.

**Comment by ghost** [comment]
Oh yeah, the wires. I use inifstar to show my current target. 

I guess, there is no class CamoNet_DZ_base ?

Hmm... maybe one can put a invisible helipad below the camonet on contruction, check for proximity of helipad and camonet and then delete both.

**Comment by kichilron** [comment]
There has to be a bassclass, it is just an issue with getting it as the cursortarget.

A helipad won't help, you may as well just check the proximity for camonet. But that puts A LOT of stress on the client. Not recommended.

This is most likely the reason we haven't done it yet.

**Comment by ghost** [comment]
Is there a better way to check for proximity? Maybe checking, if the player is INSIDE the bounding box?

**Comment by kichilron** [comment]
The thing you need to keep in mind for this (and the reason it would be putting the client under a lot of stress) is this:

the cursortarget can only be one thing at a time. However - nearby objects can be thousands of things. If you're trying to iterate over those it's going to cause a lot of stress.

**Comment by ghost** [comment]
Yeah I see. So basicly it is down to modifying the model itself to make it more accessible, right?
