### ISSUE TITLE
Matches spawn but disappear when picked up

### ISSUE THREAD

**Issue by Chianti** [DayZMod/DayZ#302]
Matches spawn, but are not added to the inventory when picked up.
They just disappear.

This may be peculiar to the server I play on.
Can anyone confirm this behaviour?

**Comment by R4Z0R49** [comment]
No new info on this ill close until more info is sent in. Thanks

**Comment by KPanicEKS** [comment]
this is happening when players has 2 or more matchboxes in their inventory. Since the player cannot hold 2 of the same tool, it easy easy to delete an item unless they always start the fire with the matchbox containing the least amount of matches.

**Comment by Chianti** [comment]
Thanks for the reply M0tzilla. The two matchbox issue was reported in the DayZ forum, and is being looked at. Unfortunately that is not the problem raised here. I think problem I've reported is specific to the server that I play on.
