### ISSUE TITLE
Being able to rest in other tents

### ISSUE THREAD

**Issue by TIC321** [DayZMod/DayZ#305]
Would it be possible to rest in all tents instead of the owner?

**Comment by KPanicEKS** [comment]
I like this suggestion as well. But if so, make the chance of curing
infection much much lower so that you actually have to rest for 5 - 10
minutes. That way you are putting yourself at risk if you use someone
else's tent.

**Comment by Borges80** [comment]
I like this idea has well. Just don't make the cure chance too high..antibiotics are hard enough to find as it is.

**Comment by ebaydayz** [comment]
Done:
https://github.com/DayZMod/DayZ/commit/e647be13c1b5990ad96715c403e1f5a16f042f23

Cure chance set to half what you get at your own tent.
