### ISSUE TITLE
1.8.3.a216b06 - Comfrey plants trigger looping gather anim

### ISSUE THREAD

**Issue by Detoeni** [DayZMod/DayZ#307]
when you enter the trigger area for the gear icon the player is forced into a looping gather anim - only way to get free is to find camera angle that does not show gear icon and wait for anim to end. Leaves can not be collected

**Comment by R4Z0R49** [comment]
This is my fault i added an animation to the top of the gather i didn't read the hole script and wasn't aware it had been changed in the way it has.

**Comment by Detoeni** [comment]
issue is still present in 1.8.3.100aa50-DEV-Full

**Comment by R4Z0R49** [comment]
Ok thanks i thought id fixed that issue already.
