### ISSUE TITLE
1.8.3.a216b06 - can not boil water at fire place

### ISSUE THREAD

**Issue by Detoeni** [DayZMod/DayZ#308]
as above - get cook food option which works fine
the empty tin can I have is not one I've used before. I _think_ its empty stroganoff or empty potatoes.

**Comment by R4Z0R49** [comment]
Ok it looks like potatoes have never been added to that system. i've updated that now.

https://github.com/DayZMod/DayZ/commit/9b4465441e3950ff761d9805cab482564d9420cd

**Comment by Lukethero** [comment]
@R4Z0R49 I believe this might have been mentioned before but I will say it anyways. For all the canned goods added in 1.8.3, there is no script for dropping the empty cans after you have eaten from them.

**Comment by R4Z0R49** [comment]
Ok soon as someone can point out a list of them ill add.

**Comment by HeroSmurf** [comment]
Hey Lukethero, 

I'll send you the lists and you can compare. 
Texting you on teamspeak now.

**Comment by Detoeni** [comment]
Should this be fixed in 1.8.3-1facc9e? Ran into it last night

**Comment by HeroSmurf** [comment]
Not yet; 

Someone (Luke volunteered) has to do the grunt work of finding which ones aren't in the Boil/Output list. Small list to add; big list to compare.

He frequents a teamspeak I'm on. I'll bug him.

**Comment by Detoeni** [comment]
not a worry if its being worked on, just wanted to check as I though the stuff you guys was looking into was just the drop function
