### ISSUE TITLE
Zombie difficulty...

### ISSUE THREAD

**Issue by jaydt183** [DayZMod/DayZ#31]
Hi,

Just been reading this:
http://dayzmod.com/forum/index.php?/topic/140274-so-zombies-are-just-a-nuisance-again-in-1771/

And it seems there are two sets of people. One who wants the zombies to be crazy and a challenge and the others who want it easy.

Why not add an if statement around the zombies hit values etc so if the server was set to Veteran the zombies would be really difficult but if the server was set to Recruit difficulty it would make the Zombies less of a threat.

That way the server admins could set the difficulties and the users could then just pick the type of server they wish to play on.

What do you think?

**Comment by R4Z0R49** [comment]
Its a nice idea but we will continue to build DayZ on a hole and not cater to an easy, medium, hard system. DayZ Should be brutal in all aspects.

Thanks.
