### ISSUE TITLE
1.8.3.a216b06 - Gate issues

### ISSUE THREAD

**Issue by Detoeni** [DayZMod/DayZ#312]
1. Placing ghost is first shown as snapped to slope but gate is built vertical.
2. Only owner gets the option to break down but if used gets “break down canceled” message.
3. If a vehicles is driven into gate, vehicle and driver take damage but there is audio for the impact.
4. Gates can still be interacted with after being satchel charged (should one charge be enough to destroy it?).
5. Gate did not save on restart*.
6. Fences are snapping to a point on the gate that leaves about a 1 foot gap on each side.
   ![2015-01-07_00002](https://cloud.githubusercontent.com/assets/8584071/5649497/49858866-968e-11e4-8742-eac3fa273866.jpg)
7. if the owner does not have a sledge hammer and the try to break down gate they get message that they need a toolbox.

*vehicle contents are not saving on the test server atm, but a tent I built was seen after a restart (content state unknown).

**Comment by R4Z0R49** [comment]
Walls,Gates have no other way to break in then the ones we have said so really no point driving stuff into them or using c4 or anything else.

We dont run the test server from what im being told they do not run default server setups so saving i cant really control.
