### ISSUE TITLE
1.8.3.a216b06 - Gather stone message missleading 

### ISSUE THREAD

**Issue by Detoeni** [DayZMod/DayZ#314]
If the game is going to give more than a single stone a message is shown.
"1 pile of stones has been successfully mined. Still to go 3"
then for the next stone gathered you get 
"2 pile of stones has been successfully mined. Still to go 3"

**Comment by KPanicEKS** [comment]
also, the spelling of the word "mind" should be fixed to "mined"

**Comment by Detoeni** [comment]
my mistake, it is correct in game

**Comment by R4Z0R49** [comment]
Ok ill updated that text to remove the current minded so only left will show.
