### ISSUE TITLE
1.8.4 testing: wrong blood type still heals; possible humanity issue

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#315]
m0tzilla, myself, and our squad were testing 1.8.4 the other night and we did some blood transfusion testing.  A major bug right now is that the wrong blood type will still heal the person receiving the transfusion.  He'll pass out at the end of the transfusion like he's supposed to, though.  The person giving the transfusion will only receive humanity points if they give the correct blood type, so that's working properly.

**Comment by R4Z0R49** [comment]
Removed the humanity save stuff the server is not a default setup.

Ill take a look at the blood again.

**Comment by R4Z0R49** [comment]
ok made sure the bad blood isnt sent to the player.
