### ISSUE TITLE
Code: Skinned Player Humanity

### ISSUE THREAD

**Issue by HeroSmurf** [DayZMod/DayZ#316]
Killing Military Skinned Players fully decreases humanity.
IE The "Unlawful combatant" or "accidental murder" Code. 

Suggested Code change "Functions/misc/fn_damageHandler.sqf"
_accidentalMurder = (_model in ["Sniper1_DZ","Soldier1_DZ","Camo1_DZ","Skin_Soldier1_DZ"]);

Suggested Code : Please check lines 30 through 64
http://pastebin.com/nysRef3H

Survivors can easily change back into their civilian clothing and blend in with the normal population; otherwise Article 4 

Lines 36 and 46 are redundant

**Comment by Lukethero** [comment]
Big problem since the beginning of dayZ, good to see someone is addressing it. Thanks Smurf!
