### ISSUE TITLE
Blood restoring to full when logging back in 1.8.3.100aa50

### ISSUE THREAD

**Issue by vinyljunkie** [DayZMod/DayZ#317]
Hey, this has happened to me once on my own server (DayZ Europa running 1.8.3) and now kichilron's test server running 1.8.3.100aa50.

Symptoms:
I logged out last night with about 7600 blood and when logging back in today I was at 12000. Nice surprise but something might be wrong.

I've had reports about this from players on my server as well. 

Thanks!

**Comment by kichilron** [comment]
Can you give us more informationen about when this is likely to happen? Did you stay on over the course of a restart?

Was your blood full when logged in? IE: Logged in full blood -> lost blood whilst playing -> logged out -> logged back in with full blood again?

**Comment by vinyljunkie** [comment]
Hello, I did not stay over the course of a restart. As I remembered it this happened after me logging on and off some times in a row. Playing-->lost blood-->logged off and back in a couple of times sitting in a barn--->logged off--->came back the next day--->full blood.
