### ISSUE TITLE
Code: (Fix) Login only as Survivor2_DZ On Death

### ISSUE THREAD

**Issue by HeroSmurf** [DayZMod/DayZ#319]
Fix for https://github.com/DayZMod/DayZ/issues/293
"Hero/Bandit skin is gone after a hero/bandit dies and respawns. He is stuck with survivor skin unless we fix it in the database."

Bug/Behavior: 
player_monitor.fsm assigns Survivor2_DZ (male) and SurvivorW2_DZ (female) on login. 
The skin is not reset unless invalid. Below code resets according to humanity values. 

Suggested change to server_playerLogin.sqf
Code snippet : http://pastebin.com/tMBMWvcw

I have checked the order in which skins are set. 
This code will return the other 2 Male Skins by randomizing the reset of Survivor2_DZ on reset
If the Survivor's humanity is bandit or hero level the appropriate skin will be set. 
Female Survivors are also accounted for. 

Note: Please check that I am pulling Humanity properly using _playerObj (first active line of code)

**Comment by HeroSmurf** [comment]
EDIT: humanity value not being passed to playerLogin.sqf prevents this fix from being effective. 
Thanks to Carl for his feedback!

So now I'm debugging the player_spawn_2.sqf working on Line 19's 
"[player,0] call player_humanityChange;" which would be an in-game switch.

**Comment by R4Z0R49** [comment]
To save your trying to work out whats going on 

```
_magazines = call player_countMagazines; //magazines player;

if ( (_playerUID == dayz_playerUID) && (count _magazines == 0) && (count (magazines player) > 0 )) exitWith {cutText [localize "str_actions_switchmodel_fail", "PLAIN DOWN"]; diag_log("SwitchFailed");};
```

Is why the humanity isnt working player_countMagazines is running before it should be blocking the gear UI from loading.

**Comment by HeroSmurf** [comment]
Thanks that probably saved me 4-6 hours. :+1: 

Is it a matter of giving the UI time to load/setup? 

:notebook_with_decorative_cover:  So; lines 63 through 73 currently work. 
They are the 10-20 minutes a player currently must wait to turn back into Bandit/Hero. 
Less time if they are running/moving; More time if they are stationary or being sneaky. 

<pre><code>
    if (_speed > 0.1) then {
        _timeOut = _timeOut + 1;
    };
    if (_timeOut > 150) then {
        _humanity = player getVariable ["humanity",0];
        if (_humanity < 1) then {
            [player, round(_timeOut / 10)] call player_humanityChange;
        };
        _timeOut = 0;
    };
</code></pre>

Which reminds me :bug: https://github.com/DayZMod/DayZ/issues/328 :bug: Falling out of vehicles Bug

I didn't realize running/movement was the key to humanity gain over time. 
If you intended it to be a deep meaning of running from your past (bad deeds) kudos; if it was unintentional, just lie and say you were making a forest gump reference. 

:athletic_shoe: http://youtu.be/QgnJ8GpsBG8?t=5m25s :smile: 

:bulb: 
what about using the dead/unused _timer10 
on line 75 "player_spawn_2.sqf" 

10 seconds in, we do a 1 time check:

<pre><code>
    if ((diag_tickTime - _timer10) > 10 && _modelChecked == false) then 
    {
        [player,0] call player_humanityChange;
        _modelChecked = true;
        _timer10 = diag_Ticktime;
    };
</code></pre>

Then again ...
Requesting/Loading humanity into server_playerLogin is out of the question?

**Comment by bchawke** [comment]
Any updates on this issue?  I don't see it in the 1.8.4 change log.  This bug has completely broken playing at the coast as a survivor as a hero, as you cannot distinguish survivors from bandits.

**Comment by R4Z0R49** [comment]
The issue hasn't been fixed yet.

**Comment by Veltro-pm** [comment]
I may have a temporary fix, but it needs to be tested on a slower computer.

This doesn't work:
sleep 1;
dayz_slowCheck =    [] spawn player_spawn_2;

But this does:
_tmpFix = [] spawn { sleep 1; dayz_slowCheck = [] spawn player_spawn_2; };

This might be an indication that something after this spawn needs to be ended before the code executes. As a matter of fact a lot of code lines have been moved around in player_monitor.fsm since the last version (maybe allowDamage or enableSimulation, i don't know...).
If the bug can't be found in time then maybe this can be used as a temporary fix as well.

**Comment by Veltro-pm** [comment]
I have two doubts about the changes in player_humanityChange.sqf and also in HeroSmurf's code snippet:

_maleSurvivorSkinsArray = ["Survivor_DZ","Survivor1_DZ","Survivor2_DZ"];
_skintoApply = [] select(random(count _maleSurvivorSkinsArray));

1) I'm not sure but to me it looks like you are selecting from an empty array and the random value is not floored. Example from https://community.bistudio.com/wiki/random:

_array = ["apples", "pears", "bananas", "M16"];
_random = _array select floor random count _array;

2) Survivor_DZ is the base class for Survivor1_DZ and Survivor2_DZ. It does not have "model" defined. So I wonder if this class should be used as a skin or is ment to be used as a base class only?

**Comment by HeroSmurf** [comment]
1) Should be fine; remember to remove base survivor class. 
2) That's true; so also change the old code found in "player_humanityChange.sqf" which references the base class. Line 38 

Good luck with your tests.
