### ISSUE TITLE
Tent placement bugged

### ISSUE THREAD

**Issue by VidKo** [DayZMod/DayZ#32]
In the newest patch the tent placement is bugged, and you get error messages:
- the area is not 100% flat
- there is an object in the way (even if there is enough space)
- you are standing in the water (although you are at least 40m away from nearest water).
- you are turned 90 degrees and the tent is set in the open somewhere and not where you want to place it.

Can also provide screenshots and coordinates if necessary.

**Comment by facoptere** [comment]
coordinates?

**Comment by VidKo** [comment]
For example: 134,032  some 40-50m north of Black Lake, you get the message that you're in the water.
Picture: http://shrani.si/f/3g/dv/3R0zwica/arma2oa-2013-06-16-16-49.jpg

**Comment by MattzFiber** [comment]
Can you say how many people were on the server at the time? This might be something to look into but has not been reported alot

**Comment by VidKo** [comment]
Regarding the You're in the water problem: no idea. But I tried it on different servers and it's the same on all of them. Also, I believe it has something to do with the altitude on which the water level is. The areas where the error is displayed are on the same altitude or below of the water level. Area a bit south, which is closer to the black lake doesn't have the problem.

Otherwise, settings for tent placement are too strict and render the tents useless (is this intentional?)

**Comment by facoptere** [comment]
Congratulation, you found the unique position on the map which is below the lake level (-0.7 meters).
I don't think this justifies to remove the tent check.
I will try to check if player is further global lake size, but since its shape is uneven the result won't be amazing.

**Comment by facoptere** [comment]
OK I have a fix.

![arma2oa 2013-06-20 18-11-25-77](https://f.cloud.github.com/assets/2677695/682414/b6b1e29e-d9c6-11e2-8eff-1cac2263a645.jpg)
