### ISSUE TITLE
Cancelling building tents, tents remain on the ground

### ISSUE THREAD

**Issue by VidKo** [DayZMod/DayZ#320]
I was trying to set up a tent, but it was in a spot where there wasn't a possibility to build  (no "Complete building" option) so I pressed "Cancel building" but the tent remained on the ground and it was accessable. The tent in my inventory remained.

Duping does not occur as there is no option to fold and pickup the tent.

After restart, the tent was gone from the ground. The glitch can still be misused.

**Comment by R4Z0R49** [comment]
Server? version?

**Comment by VidKo** [comment]
DayZ Europa server
1.8.3

**Comment by bchawke** [comment]
I can confirm this.  Exact same thing happened to me on US434 1.8.3 vanilla 2 nights ago.  All the details were the same except I didn't return to the spot later to see if the tent was still there.

**Comment by R4Z0R49** [comment]
Yea not really sure whats going on it was all changed in 1.8.3 some for the better other areas for the worst. ill try taking a look see whats going on.

**Comment by SgtRockerJC** [comment]
Yes, this i can confirm still happening in my private server "Unforgiven - Vanilla Dayz, 1.8.3, JJAZE Gaming" same situation as Vidko.

**Comment by LinusLeonard** [comment]
Seems to be happening with sandbags and small stashes too.

**Comment by kichilron** [comment]
Should already be fixed.

https://github.com/DayZMod/DayZ/commit/a500f19a156de427d2a4f3262568de136c2327a7

**Comment by LinusLeonard** [comment]
Yep, fix seems to be working fine :)
