### ISSUE TITLE
Falling out of Vehicles : Humanity Change over time

### ISSUE THREAD

**Issue by HeroSmurf** [DayZMod/DayZ#328]
:notebook: This is only a noticeable problem because Bandits (70-80% of skins) are loading in as Survivors and then changing within 20 minutes. 

Currently if you pass the threshhold for changing from survivor to bandit or vise versa upon any humanity change (_timeOut 150 based on _speed) you will undergo a model change regardless if you are currently in a vehicle. 

:bulb: Suggested code fix : 

"player_switchModel.sqf" 
Line 13-14

<pre><code>
if (vehicle player != player) exitWith {cutText [localize "str_player_fail_skinhumanitychange", "PLAIN DOWN"]};
</pre></code>

Add to "stringtable.xml"

``` xml
<Key ID="str_player_fail_skinhumanitychange">
<English>Humanity Update: Your skin will update when you are safely on the ground. </English>
<German>Die Menschheit Update: Ihr Kostüm wird aktualisiert, wenn Sie auf dem Boden sind sicher.</German>
<Russian>Человечество обновление: Ваш костюм будет обновлять, когда вы находитесь в безопасности на земле.</Russian>
<Spanish>La humanidad Actualización: Su traje se actualizará cuando se está a salvo en tierra.</Spanish>
<French>Changer l'humanité: Votre costume mettra à jour lorsque vous êtes en toute sécurité sur le terrain.</French>
<Czech>Lidstvo Změna: Váš kostým bude aktualizován, když jste bezpečně na zem.</Czech>
</Key>
```

:bulb:  Then again this may become annoying; a message coming up every 10-15 minutes. Perhaps no warning is necessary. Only an exit on line 13

**Comment by Veltro-pm** [comment]
I would not change it there, but change player_spawn_2.sqf line 67-73 instead (code untested):

```
if (_timeOut > 150) then {
    _humanity = player getVariable ["humanity",0];
    if (_humanity < 1) then {
        if (vehicle player != player) then {
            [player, round(_timeOut / 10)] call player_humanityChange;
        } else {
            _humanity = _humanity + round(_timeOut / 10);
            player setVariable["humanity",_humanity,true];
        };
    };
    _timeOut = 0;
};
```

**Comment by HeroSmurf** [comment]
I liked your way of doing it better and then I opened the code and realized I had commented out that exact way after building it the same way myself with a ladder check. :P 

Soooo... My thought for doing it in modelChange is if there are any other calls to change the skin on a ladder or in a vehicle (not just the "gain humanity over time" timer) we end up solving 1 behavior instead of the root bug.

**Comment by Veltro-pm** [comment]
Understand what you mean, but the skin change is not retriggered, which happens only in this specific case. In case there would be code in place that checks if the player has the correct skin all the time then I would also do it that way. But not now because the risk is that a skin change will not happen at all because there is no periodic check. It is actually too bad that humanity and skin change are not seperated into two different sub-systems. This is why I think that a piece of code that solves the problem directly is probably better for now.

**Comment by HeroSmurf** [comment]
Since we only change the model within "player_switchModel.sqf"; it would have been better to do the check there; where the switch occurs. It would have prevented other potential bugs like being on a ladder and slow updates/lag from damageActions.
