### ISSUE TITLE
Survivor Spawning Issue

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#329]
A huge bug that I do not see mentioned here is the big where you spawn in with survivor skin, regardless of your humanity. This problem is fixed once the players humanity is updated, and the proper skin is put on. This does not seem like a big issue but it is very frustrating for friendly players who think they have spotted a survivor just to find out that it is a bandit who has not changed skins yet.

Reposted for ditrect reference. I know this has been fixed but should help with changelog and fix reference.

**Comment by HeroSmurf** [comment]
Oops; beat you to it Luke. Was impatient since I was already researching it. My bad. 

https://github.com/DayZMod/DayZ/issues/319
