### ISSUE TITLE
Call pMain with parameter 1.

### ISSUE THREAD

**Issue by CraftLourens** [DayZMod/DayZ#33]
Please help me :)
CALL sp_name([parameter[,...]]) - Syntax 5.7 version
CALL pMain([WhatHere?[WhatHere?]])

**Comment by fgw-** [comment]
your instance number goes in there. as i use instance number 1, it looks like 
call pMain(1)
in my environment.

but i get the following error when calling     pCleanupOOB.sql

Procedure execution failed
1366 - Incorrect decimal value: '' for column '' at row -1

the statement
        IF (intNorth = 0) THEN
            SELECT CONVERT(@North, DECIMAL(16,8)) INTO intNorth;
        END IF;
fails. not able to figure out why, so i just commemnted out the call to pCleanupOOB.sql in pCleanup.sql

**Comment by CraftLourens** [comment]
Okay,thanks,i try it.
