### ISSUE TITLE
Tank traps can't be build on roads and bear traps doesn't work

### ISSUE THREAD

**Issue by B73** [DayZMod/DayZ#330]
Tank traps can't be build on roads and bear traps doesn't work. Noticed it today, on vanilla server using latest version of the mod.

You can build tank traps to fields etc. but not on the road. Bear traps doesn't activate, they appear on the ground unarmed.

And, when trying to make a tent or tank trap it shows on screen even if cancelled. I saw many unbuild tents and tank traps around me, they were all canceled but still appeared and I could gear tents. They do disappear when I log off or run away some distance. When making tent other players won't able to see it, only when build and ready.

**Comment by VidKo** [comment]
I can confirm that tanktraps cannot be built on roads (dirt or paved) which renders them useless. They also cannot be built near the walls although they should.

**Comment by R4Z0R49** [comment]
Bypass added to spawn on roads.

https://github.com/DayZMod/DayZ/commit/964b8b79c3a4f46dd2fee95dd485d4d0a4ca00b9

**Comment by R4Z0R49** [comment]
https://github.com/DayZMod/DayZ/commit/e5b679cd5d456dbcddbbd285180e5c8d6b51abe1

Fixed traps.
