### ISSUE TITLE
M9 SD reload issue.

### ISSUE THREAD

**Issue by thcNox** [DayZMod/DayZ#332]
This one has been around for awhile. The M9 SD won't reload a fresh magazine. e.g. if you have 2/15 in your current magazine and two full mags, If you reload nothing will happen. Character will do the reload animation but you will still have the 2/15 mag in your gun.

**Comment by VidKo** [comment]
Can confirm. This bug has been around for a while.

**Comment by kichilron** [comment]
Have you tried recombining them?

**Comment by AsFoxy** [comment]
Fixed internally.
