### ISSUE TITLE
Crossbow Parts

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#337]
With 1.8.4 bringing out all these attachments and customization for the crossbow, it would be cool to be able to craft one. In the crafting menu, it says you are able to craft one using a stock and string and arms. I checked the loot tables, and they are not there. Were they forgotten, or have they just not been implemented or built?

**Comment by R4Z0R49** [comment]
{"Crossbow_Stock","weapon",0.03},

is in the tables but it looks like we missed the equip_Crossbow_Kit id have to check my notes but im thinking your able to make that item.

Let me take a look on that one.

**Comment by R4Z0R49** [comment]
Fixed

**Comment by Lukethero** [comment]
Beeing added in hotfix @R4Z0R49 ?

**Comment by R4Z0R49** [comment]
It was added in 1.8.4
