### ISSUE TITLE
Backpack eating ammo.

### ISSUE THREAD

**Issue by entspeak** [DayZMod/DayZ#34]
When placing a weapon in the backpack, the game automatically pulls in all of that weapons ammo.  If there's no room for it, the pack destroys it.  No way to work around this except to drop the ammo on the ground before placing the weapon in the backpack.

**Comment by MattzFiber** [comment]
The ammo or any other item that is dropped out of a backpack will be put on the ground around if it is fill, like it does with vehicles

**Comment by entspeak** [comment]
Ah... but isn't there a way to prevent the ammo from being automatically put into the backpack if it doesn't fit?  I seem to recall it used to just take the weapon and only the ammo that fit... leaving the others where they are in the inventory.
