### ISSUE TITLE
Body temperature drops even while running 1.8.4

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#340]
It's been mentioned on the forums already and Razor has responded but I wanted to officially open the issue here.  Temperature drop works properly now, but movement does not warm the player up.  The result is that as soon as it gets cold in-game, you rapidly lose body temp and the only way to regain it is heatpacks or fireplaces.  Considering the limited supply of heatpacks and matches, players are in a constant state of hypothermia.

**Comment by R4Z0R49** [comment]
Yea, there's a quick fix on the fourms

**Comment by VidKo** [comment]
We have the hotfix running on dayz europa server. Temperatures are still dropping massively while running. It's like we're playing in a -50 degrees environment.  It's unplayable in the evening/night at current state.

**Comment by R4Z0R49** [comment]
Check to make sure you have it set correct. Other reports are saying its now fixed. But waiting on more info.

**Comment by R4Z0R49** [comment]
Reupdated. Waiting on hotfix
