### ISSUE TITLE
Heli crash sites spawn civilian zombies 1.8.4

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#341]
The earlier bug of zombies not spawning at crash sites was definitely fixed, but civilian zombies spawn instead of military zombies.

**Comment by R4Z0R49** [comment]
Oh hum let me check on that one ty

**Comment by R4Z0R49** [comment]
Yea the configs show pilot ill take a look when I'm at home

**Comment by R4Z0R49** [comment]
All mill zeds have been effected

**Comment by R4Z0R49** [comment]
Ok i've found the issue and will upload to github in a sec.
