### ISSUE TITLE
1.8.4 jerry can refuelling bugged

### ISSUE THREAD

**Issue by VidKo** [DayZMod/DayZ#342]
Scenario:

2-6 empty jerrycans in your inventory. You klick on option refuel jerry can. You receive the message: 2-6 jerry cans refuelled. Actually only one jerry can in your inventory was refuelled.

 If you want to refuell another jerry can you have to step back away from the fuel tank so the menu disappears and step to the fuel tank again so the new menu with the option refuel jerry can appears again.

**Comment by R4Z0R49** [comment]
Ok ty ill see if I can fix this with the hot fix.

**Comment by kichilron** [comment]
If I remember correctly this may actually be my fault.

**Comment by ericandersen** [comment]
@kichilron :+1:  That man is keeping it :100: 

Just curious; can you just revert 4b7e4cc64eee0386e634264675a8048f69bda40f and re-release 

Or do you need to push this with the rest of "dayz_1337.chenarus.pbo" ?

**Comment by R4Z0R49** [comment]
Should be able to include in a hotfix with the temperature changes.

**Comment by R4Z0R49** [comment]
Ok i've reset this back to refill all its a bit too tedious trying to do one by one.
