### ISSUE TITLE
1.8.4 Aim Crossbow Texture

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#345]
The aim sight for at least the Xbow is a little messed up. Not sure if this applies with he other guns this connects to. http://cloud-4.steamusercontent.com/ugc/27356143496918866/9AFBB44F4CCA71480DC92D999D55AF4CA24757FA/

**Comment by R4Z0R49** [comment]
ok looks like it may be a binarize issue. i'll check it out

**Comment by R4Z0R49** [comment]
Looked over this going to call it a feature :-) crap in the scope from being on the ground.
