### ISSUE TITLE
Database Load Issue

### ISSUE THREAD

**Issue by fazmond** [DayZMod/DayZ#348]
hi guys your prolly aware of this problem but if not i'd like to bring it to your attention

so when the server is loaded its in a wait state for someone to join
then when someone connect is start doing the game loading and then connects to the data base to start reading it into the memory and then the game starts 

the problem is where if the player disconnects before the data base is finished loading then its stops reading in the info from the data base
and the game starts

players still have their inventor but none of the tents or cars will be loaded on tot the server

The only way to fix this is to shutdown the server and restart it and ensure the first person connecting waits until the data base is fully been read and the game starts.

hope I explained this well enough maybe someone knows a way of the server being able to load in the mission file with no player connected. that would sort this problem out.

**Comment by R4Z0R49** [comment]
Yea this is an old one.

**Comment by fazmond** [comment]
old but is there a work around or anything we can do about this ?

**Comment by kichilron** [comment]
We have not yet had found a way to be able to fix this.

It'll be a tricky one either way if you think about it, as the object-stream is being interrupted whilst loading. Might have to do with the extension and noone's worked on that for a long time.

**Comment by R4Z0R49** [comment]
Takes too long to get the dll passed off to be changed. You have seen how many loops i have to go over just to release the pbo's. :-(
