### ISSUE TITLE
1.8.4.1 temp in journal

### ISSUE THREAD

**Issue by lWmPl** [DayZMod/DayZ#349]
In config "dayz_temperature_override = false", but in journal "Temp: 42/Disabled".

**Comment by R4Z0R49** [comment]
Yea true/false is changed to disabled/enabled in the journal.

Just so ppl can see temp is enabled or disabled.

**Comment by lWmPl** [comment]
you dont understand. i set "dayz_temperature_override = false" but in journal temp is disabled.

**Comment by kichilron** [comment]
No, the temperature override is disabled....

Do you think a clearer text is needed?

**Comment by R4Z0R49** [comment]
Oh ok sorry my bad i misread what you typed it should say enabled. 

true = Disabled,
False = Enabled.

Thanks ill fix this now.

Fixed - https://github.com/DayZMod/DayZ/commit/d751accb40cb7d25cb91cf9474dc6134cb4455c9
