### ISSUE TITLE
Wooden Gate Issues

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#350]
1 Gate break in- Gates are impossible to be broken into. Only the owner has the option to break into  the gate. 

2 Tools- When trying to break into the gate without a sledgehammer, it says you need a toolbox. In addition, when you try to break into a gate, and you fail, it does not give you a message when your tool breaks.

**Comment by R4Z0R49** [comment]
1 - Ok yea i see the issue.

2 - ok yep see the issue.

You other one has been spilt into a new issue as its not a bug but a feature we plan to have soon the combination lock is done we just need time to add it.
