### ISSUE TITLE
Wooden Gate Clan Access

### ISSUE THREAD

**Issue by R4Z0R49** [DayZMod/DayZ#351]
Permission to gates - This is not really an issue as much as it a really necessary feature. Currently the owner of a gate has the option to lock and unlock the gate. This is very troublesome for clan members who want to get into their base, but cannot due to the builder not being online.

**Comment by R4Z0R49** [comment]
This is being sorted with a combination padlock.

**Comment by fazmond** [comment]
I haven't found a padlock at all what controls the spwan of them ?

**Comment by kichilron** [comment]
Currently still _being sorted_. Not done yet.

**Comment by fazmond** [comment]
sorry I read that the gates were fully working can you please confirm if locks are in or out in this patch ?

**Comment by R4Z0R49** [comment]
Faz, gates are working but there can only be locked by the owner for now. You must find a padlock.

**Comment by fazmond** [comment]
ok thanx for the confirmation its just I spent the whole day looking with other players on the server and found nothing can you gie me some idea of where to look  ?

**Comment by fazmond** [comment]
ALSO they can not be deconstructed

**Comment by Flamberg** [comment]
Hello fazmond,

you might try searching/dungeoncrawling in some castle cellars :-)

**Comment by R4Z0R49** [comment]
@fazmond - it hasn't been added yet.

**Comment by fazmond** [comment]
I also couldn't lock my gate so is that in the game yet cause if your read the comments above it would lead you to believe this is the case

**Comment by R4Z0R49** [comment]
Only the owner of the item can lock. pretty sure you asked this already.

**Comment by fazmond** [comment]
not me I cant only option is to open or upgrade

**Comment by fazmond** [comment]
ok so my guys still aint found a padlock on the server and we been loot cycling the castles so now I want some proper information about the padlocks please 
where they spawn exactly
what chance are they of spawning 
what is controlling the spawn of the locks

**Comment by kichilron** [comment]
Same thing it always was. Pure chance. It's all maths and there is theoretically thechance that you will never find one, even if you keep searching. 

Other than that: the repository does have a searchfunction and I just found it on my phone. 
https://github.com/DayZMod/DayZ/blob/047ce30d6db540b5f309ff8a14a7425951057ffa/SQF/dayz_code/Configs/CfgLoot/CfgBuildingLoot.hpp
