### ISSUE TITLE
Humanity reset after death 1.8.4.1

### ISSUE THREAD

**Issue by dayzjarhead** [DayZMod/DayZ#352]
When dying having a negative humanity, it is reset to 2500.

Shouldn´t it stay at the level as before?

**Comment by R4Z0R49** [comment]
it should do yes.

**Comment by ericandersen** [comment]
What server were you on?
What humanity did you have?

Can you explain the damage that occured to you/from you?
Can you go on another killing spree to test it again :)?

I've died as both survivor and bandit on 1.8.4 and 1.8.4.1 without issue.

**Comment by ghost** [comment]
I´m using infiStar. So maybe there is an issue there. I´ll test without infiStar asap.

**Comment by HeroSmurf** [comment]
@dayzjarhead bingo

**Comment by R4Z0R49** [comment]
Is this a infistar issue?

**Comment by ghost** [comment]
dunno yet... need to test it.

**Comment by vinyljunkie** [comment]
This might very well be the database schemas. If you die and login after the next restart your char have been reset. This is because the db schemas that come with the mod move all dead players to character dead as a cleanup procedure. Atleast we had that problem.

**Comment by ghost** [comment]
Testing with/without infiStar tonight.

**Comment by kichilron** [comment]
Has been going on for a whiel now and has to do with how the DB works.

When a player dies and then logs out and the DB is being cleaned before he logs back in there may be an issue with the cleanup. When a player is dead, the character's being moved to a the _dead table and this is being cleaned up before he logs back in, the Humanity is gone.

**Comment by R4Z0R49** [comment]
If thats the case witch i dont think it is. just remove the movement system in pcleanup.

BEGIN 
#Last ran
    update event_scheduler set LastRun = NOW() where System = "pCleanup";

#starts outofbounds cleanup
        CALL pCleanupOOB();

#remove damaged objects
        DELETE
                FROM object_data
                WHERE Damage = 1;

#remove empty tents older than seven days
        DELETE
                FROM object_data
                WHERE (Classname = 'TentStorage%' or Classname = 'StashSmall%' or Classname = 'StashMedium%')
                        AND DATE(last_updated) < CURDATE() - INTERVAL 7 DAY
                        AND (Inventory = '[[[],[]],[[],[]],[[],[]]]' or Inventory = '[]');     

#remove barbed wire older than two days
        DELETE
                FROM object_data
                WHERE Classname = 'Wire_cat1'
                        AND DATE(last_updated) < CURDATE() - INTERVAL 2 DAY;

#remove Tank Traps older than fifteen days
        DELETE
                FROM object_data
                WHERE Classname = 'Hedgehog_DZ'
                        AND DATE(last_updated) < CURDATE() - INTERVAL 15 DAY;

#remove Sandbags older than twenty days
        DELETE
                FROM object_data
                WHERE Classname = 'Sandbag1_DZ'
                        AND DATE(last_updated) < CURDATE() - INTERVAL 20 DAY;

#remove Traps older than five days
        DELETE
                FROM object_data
                WHERE (Classname = 'BearTrap_DZ' or Classname = 'TrapBearTrapFlare' or Classname = 'TrapBearTrapSmoke' or Classname = 'Trap_Cans' or Classname = 'TrapTripwireFlare' or Classname = 'TrapTripwireGrenade' or Classname = 'TrapTripwireSmoke')
                        AND DATE(last_updated) < CURDATE() - INTERVAL 5 DAY; 

#remove incomplete fence's after 1 Day  
        DELETE
                FROM object_data
                WHERE (Classname = 'WoodenFence_1_foundation')
                        AND DATE(last_updated) < CURDATE() - INTERVAL 1 Day;  

#remove incomplete fence's after 3 Dayz  
        DELETE
                FROM object_data
                WHERE (Classname = 'WoodenFence_1_frame' or Classname = 'WoodenFence_quaterpanel' or Classname = 'WoodenFence_halfpanel' or Classname = 'WoodenFence_thirdpanel')
                        AND DATE(last_updated) < CURDATE() - INTERVAL 3 Day; 

#remove dead players from data table
        DELETE
            FROM character_dead
            WHERE Alive=0
                AND DATE(last_updated) < CURDATE() - INTERVAL 30 Day; 

#Remove Bad Data
       DELETE
            FROM object_data
            WHERE Classname = '%_base';  
END

**Comment by R4Z0R49** [comment]
Closing for now. lets see if any other reports come in.

**Comment by ghost** [comment]
Just tested it. It in fact IS an infiStar issue...

**Comment by R4Z0R49** [comment]
rgr thanks :-)
