### ISSUE TITLE
More descriptive strings for the new attachments 1.8.4.1

### ISSUE THREAD

**Issue by Flamberg** [DayZMod/DayZ#353]
Hi,

the text strings for the new attachments should be more descriptive. We need to be clear which attachment can be used with which weapon. At the moment Belt, Scope, Flashlight and CCO seem to cause most confusion.

Could the creator of the attachments clear up which weapons should be allowed with those, co I can update the stringtable?

Thank you.

**Comment by R4Z0R49** [comment]
For now dont worry too much about these. We have 2 different sets of weapons and 2 different sets of attachments. 

One set of weapons can use attachments the others cant.
One set of attachments are for pacific weapons, the other can be used with multiple weapons.

If anyone is having an issue right click and attach you will be given a msged if it dont fit :-)
