### ISSUE TITLE
large bases crashing people in choppers (EMP)

### ISSUE THREAD

**Issue by fazmond** [DayZMod/DayZ#354]
ok so if you have a fairly large base the problem arises when a person is flying in to the base it willk cause them to get a memory error and crash them out the game, we are calling it the EMP bug :)

I think its to do with the way the  game loads in the level of detail of the walls and were thinking its also to do with it the fact because they are moving in so fast that all the data is sent to them to quickly.

if you need any more information please ask 

THERE IS ALSO A ITEM DUPLICATING ISSUES (PLEASE MESSAGE ME IF YOU WANT MORE INFO ON THIS)

**Comment by R4Z0R49** [comment]
Check in your db and look for objects with _base next to them let me know if you find any.

**Comment by fazmond** [comment]
yes MetalFence_base and woodenFence_base there is a lot of them

**Comment by R4Z0R49** [comment]
Ok they should not exist. i think they are from the last update.

**Comment by R4Z0R49** [comment]
https://github.com/DayZMod/DayZ/commit/e62c8924df9c12b52a4ea55d8bc0073ddaf5032e

I've got to see whats causing this but for now update your server.pbo.

**Comment by fazmond** [comment]
yer it is I will remove them and see if any come back

**Comment by fazmond** [comment]
just to let you know WoodenFence_base is a recent object its date stamp was fron less than 2 days ago so for some reason my server is still creating these , using the latest server files 

deleting them from our DB removed players bases from the game so I cant just remove them that easy

so this still seems to be in the game and we have over 500 entrys for this in our data base

**Comment by R4Z0R49** [comment]
I'm looking into this issue.

What i do know _base items for fences are set to private they should not be allowed to spawn ever so removing from your DB wont have any effect ingame.

And if somehow they are rename them all too WoodenFence_1

class MetalFence_base: DZ_buildables
{
    scope = 1;
    canbevertical = 1;
}; 

class WoodenFence_base: DZ_buildables
{
    scope = 1;
    canbevertical = 1;
};

These are taken from 1.8.4.1 as you can see they have no model and they are set to private (scope =1) so this must be a legacy issue from 1.8.2/3

**Comment by fazmond** [comment]
OK SO A QUICK UPDATE FROM ME
I removed all that WoodenFence_base and MetalFence_base from the data base there were 250+ entrys.

It Seems to have fixed the issue so far with the EMP crashes, shooting someone through the wall, overflowing staches and we didn't get a crash so that's all good so far.
I will update if I think theres any more problems relating to this.

and I also don't think the server is creating these _base currently but will keep an eye out if any more appear THANX FOR THE HELP.

**Comment by R4Z0R49** [comment]
We are aware of this issue and are working to correct it. #333
