### ISSUE TITLE
Adding more clothing or removing clothing from corpses possible?

### ISSUE THREAD

**Issue by VidKo** [DayZMod/DayZ#358]
Is it possible to add more clothing? Like russian army, chernarus army, some civilian...?

And a possibility to remove clothing from someone dead? Like having a chance to destroy while trying it?

**Comment by R4Z0R49** [comment]
If someone wonts to make a list of the models i dont mind adding them as long as there not silly.

**Comment by kichilron** [comment]
I did some work on that for a lot of variety, we had to remove it again because of issues with the backpacks. Most models don't have backpack-proxies, so that the backpack wouldn't show up.

That's the reason they were removed again, but if you take a look at the code you will still see some remnants here and there.

**Comment by R4Z0R49** [comment]
Yea that's correct i remember id have to find someone to do backpack proxy's on the models.

**Comment by Lukethero** [comment]
Will see if I can continue working on backpack proxies, worked on it a few weeks ago but gave up. Maybe I will be able to find it out this time.

**Comment by reen624** [comment]
I can give you models, we used to implement them on our server and therefore tested all one by one, which s*cked hard. I got a list of workin and cool ones.

**Comment by reen624** [comment]
Soldier_AT_PMC
 --> looks like a experienced specialized survivor

Soldier_Bodyguard_AA12_PMC
 --> looks like a douchbag cop from movies (overwrites specific head-skin)

Soldier_Bodyguard_M4_PMC 
 --> looks like a hardened guy  (overwrites specific head-skin)

TK_Soldier_Officer_EP1
--> looks like head of a bandit crew

Theese should work with backpacks and causes no errors ingame. Tested on 183 

had more skins, have to look them up

**Comment by Dienark7** [comment]
Whats the status on making clothes removable from corpses? Do we want to add this? I think it's a nice idea.

**Comment by R4Z0R49** [comment]
No we dont wont this.

**Comment by R4Z0R49** [comment]
No idea why i closed.

Remove from corpse is a no go but adding other skins is possiable.

**Comment by kichilron** [comment]
We had manymany clothes in at some point, but if they don't have a proxy for backpacks it's not worth it.

If you have someone capable of doing the models, go ahead.

**Comment by Dienark7** [comment]
Feels like a shame not being able to take say a Ghillie Suit off a dead sniper, especially seen as clothing is somewhat rare. But if you feel it doesn't benefit the game I understand. 

More skins would be awesome, hopefully we can get some skins that show backpacks :)
