### ISSUE TITLE
1.8.4.1 - A+ Blood bags not working.

### ISSUE THREAD

**Issue by PBL123** [DayZMod/DayZ#359]
People with the blood type A+ cant recieve blood from the bloodbag type A+ but other bags seem to work like the O-. So far only people with A+ or maybe the A+ bloodbag are not working

**Comment by R4Z0R49** [comment]
If the persons blood is returning an RH factor of
false (Meaning AB Type Blood) then they can only use "bloodBagANEG","bloodBagONEG". 
true (Meaning A Type Blood) then they can use "bloodBagAPOS","bloodBagANEG","bloodBagONEG","bloodBagOPOS"

If i remember correct anyway.
