### ISSUE TITLE
9x19mm damage must be raised

### ISSUE THREAD

**Issue by Gews** [DayZMod/DayZ#36]
1.7.7 reverted to the old damages for pistols... mostly:

.45 ACP = hit 9
9x18mm = hit 6

However the 9x19mm has been left unchanged, and the Makarov is doing over twice as much damage... contrary to real life.

9x18 Makarov, 95gr at 1050 ft/s = 233 ft-lb energy
9x18 Parabellum, 124 gr at 1150 ft/s = 364 ft-lb energy
.45 ACP, 230 gr at 850 ft/s = 370 ft-lb energy

9x19mm Parabellum is significantly more powerful than 9x18mm Makarov - 9x19mm hit should be changed to 7.

Leaving the 9x19mm unchanged is not only unrealistic, but has also unbalanced weapons such as the Glock and the M9 (it's better to take a Makarov now) and the MP5 (it's better to take a Bizon).

The old ArmA damages had been patched for a reason - they didn't make sense! 

In any case, 9x19mm damage must be "bumped". I hope to see this change soon as it is a very quick fix to a fairly obvious problem.

**Comment by MattzFiber** [comment]
Everything has to be balanced. This is a low priority

**Comment by Gews** [comment]
Low priority - perhaps. However this has unbalanced things at the moment.
