### ISSUE TITLE
1.8.4.1 Loot Issues

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#361]
1. Loot Respawn- Loot resplendent is way too active. I do not know the exact distance at which they respawn, but I can go from bottom of breezing supermarket loot up, go to top supermarket and go back down and loot is respawned. Can 
   repeat this step dozens of times till I have all basic loot. Just set it back to 1.8.3, good balance and made looting harder.
2. Too Many Attachments- Right now attachments are in basically every loot table. Not only are they super common, they are super useless. To fire a silenced weapon you need Sd ammo, which can basically only be found at military spawns. Had many people put a suppressor on their m9 or mak just to find they made a worthless piece of metal. This is especially troubling because you cannot take attatcmemts off and are stuck with it. I think aim and camp attachments are a little more usefull and should be kept at the current spawn rate, just remove it from residential spawns, or at least decrease it.
3. Knockout Darts- Little too rare as it is. They can only be found at military barracks, that by the time you find it you have graduated from your Wimpy little close range crossbow that you found in a barn, to a full auto long range knockout beast mk48. Xbows require skill to use and will lose to a m16 almost every time. Knockout darts are really great for players who want to at friendly, so why not encourage a little friendly gameplay? Would be cool to find these things spawn in residential and industrial buildings. Also another fix that people I have talked to like is either adding a new plant or adding anew purpose for Sepsis plants.

**Comment by kichilron** [comment]
Double Post

#362
