### ISSUE TITLE
1.8.4.1 Loot Issues

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#362]
1. Loot Respawn- Loot respawn is way too active. I do not know the exact distance at which they respawn, but I can go from bottom of Berezin supermarket loot up, go to top supermarket and go back ldown and loot is respawned. Can repeat this step dozens of times till I have all basic loot. Just set it back to 1.8.3, good balance and made looting harder.
2. Too Many Attachments- Right now attachments are in basically every loot table. Not only are they super common, they are super useless. To fire a silenced weapon you need Sd ammo, which can basically only be found at military spawns. Had many people put a suppressor on their m9 or mak just to find they made a worthless piece of metal. This is especially troubling because you cannot take attatcmemts off and are stuck with it. I think aim and camo attachments are a little more usefull and should be kept at the current spawn rate, just remove it from residential spawns, or at least decrease it.
3. Knockout Darts- Little too rare as it is. They can only be found at military barracks, that by the time you find it you have graduated from your wimpy little close range crossbow that you found in a barn, to a full auto long range knockout beast mk48. Xbows require skill to use and will lose to a m16 almost every time. Knockout darts are really great for players who want to be friendly, so why not encourage a little friendly gameplay? Would be cool to find these things spawn in residential and industrial buildings. Also another fix that people I have talked to like is either adding a new plant or adding a new purpose for sepsis plants. Make it so you can craft it with a bolt to make a knockout bolt. This also makes sense realistically because the plant might have a "seditive effect." In summary, adding this would add a skill based way to fight and allow friendly gameplay to flourish.
4. Military Guns- This is more of a dream, but it would be cool to have a little bit more of civilian weapon battle zombie apocalypse theme going. Basically, if you walk into a firestation you are almost GAURENTEED a m4 or an ak with ammo, especially with how easy loot respawns. Maybe dial down the amount of high grade weapons you can find here and maybe add some Mosins and Enfields and boost weaker gun spawns like the the mp5. Also so fire stations do not become pointless to go to, decrease the spawns of the guns at barns and such. Heard a lot of people complain about people not going up north to gear up, and this is a good way to fix it.

NOTE: Much of this is opinionated, but opinions based apron many community members I have talked to. If you disagree with anything I have said, PLEASE speak out and say what is wrong, I might be totally off on these issues.

**Comment by Lukethero** [comment]
Also if I am spot on on a issue, please encourage and show that these ideas are wanted from the rest of you guys too.

**Comment by R4Z0R49** [comment]
1, Loot wasn't changed in 1.8.4 at all this issue was part of all the changes in 1.8.3 there is another issue in github about it. #310. Its waiting for the designer of the system used in 1.8.3 to fix but looks like ill end having to fix it :-(
1. why not just ask for a way to remove attachments? but yea that should be next on the list. #363
2. We might make them craft-able at some point.
3. get me the models and ill replace the others.

**Comment by Lukethero** [comment]
Yep on the first one... Meant back to 1.8.2. This should be a high priority fix This probably. Number 3 there... Yes please.. Even just plopping them in some tables would be good enough for me. And for number 4, models for what? All those guns already have models and are already in the game. Gonna split into separate issue for some.

**Comment by Lukethero** [comment]
@R4Z0R49 Yeah not sure what you mean by models.... All the guns are already in the game...
