### ISSUE TITLE
1.8.4.1 Knockout Darts Spawn

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#365]
These are a little too rare as it is. They can only be found at military barracks, that by the time you find it you have graduated from your wimpy little close range crossbow that you found in a barn, to a full auto long range knockout beast mk48. Xbows require skill to use and will lose to a m16 almost every time. Knockout darts are really great for players who want to be friendly, so why not encourage a little friendly gameplay? Would be cool to find these things spawn in residential and industrial buildings. Also another fix that people I have talked to like is either adding a new plant or adding a new purpose for sepsis plants. Make it so you can craft it with a bolt to make a knockout bolt. This also makes sense realistically because the plant might have a "seditive effect." In summary, adding this would add a skill based way to fight and allow friendly gameplay to flourish.

Split issue from #362

**Comment by Skydog4** [comment]
Yes, yes! Great idea. I think adding craftable knockout darts should be one of the priorities to decrease the KoS that happens almost everytime when players meet. And how about some kind of a craftable knockout trap as well? I think these things would really help to increase friendly gameplay which is badly needed.
Restraining players would also be a very nice addition but it's probably impossible in the Arma 2 engine?

**Comment by Lukethero** [comment]
@Skydog4 Good to hear I am not alone on this. A restraint system persay might be a little hard with the Arma 2 engine, but maybe a way to just plant the player in place like knockout would not be too impossible.
