### ISSUE TITLE
1.8.4.1 Doors/Doorways causing damage to player.

### ISSUE THREAD

**Issue by thcNox** [DayZMod/DayZ#366]
So since the patch (1.8.4) Me and folks in my squad has noticed that you now can easily break your legs or even die when using doors or even when crawling through an open doorway.

**Comment by kichilron** [comment]
Can you give us more information about that?

Can you reproduce the issue?

**Comment by R4Z0R49** [comment]
This was my fault i disabled the system we use to stop this happening. I was going over all the non damage system we have in dayz and forgot to readd the system once i was done.

**Comment by Lukethero** [comment]
Any way you could release a quick fix for server admins via server side? On 
numerous occasions, me and many others I knowhave broken their legs from something ridiculous, like going prone.
