### ISSUE TITLE
Adding a thermos to the game possible?

### ISSUE THREAD

**Issue by thcNox** [DayZMod/DayZ#367]
I would like to suggest adding a thermos to game now that the we have a functioning weather system. Using the thermos you could possibly be able to boil water and brew some Coffee or Tea.

I'm thinking this will add a more natural alternative source of heat than heat packs while perhaps not as powerful. I also believe a lot of players will appreciate the RP aspect of being able to sit around a campfire and brew your own Coffee/Tea.

edit: I'm not sure if this "issues" section is the right place for suggestions like the above. If not please direct me in the right direction, thanks in advance.

**Comment by ghost** [comment]
Me likes. 
Water + Cooking Pot (finally) + Fire + Tea Bag = Hot Tea in Pot (drinkable)
Water + Cooking Pot + Fire + InstaCoffee = Hot Java in Pot (drinkable)
Thermos + Hot Tea/Hot Java = portable and drinkable

**Comment by HeroSmurf** [comment]
Me likes.

Coudn't resist chiming in

**Comment by R4Z0R49** [comment]
Get me a model and np without the model its not possible.

**Comment by thcNox** [comment]
I am a game developer with artist skill-set so I could knock out a model however I am not familiar with the arma engine, its needs and workflow so I would have to research whats required, perhaps you have any good sources for this. 

Also the design of the actual game play would have to be finalized so I know exactly what models are needed.

**Comment by TheGrandma** [comment]
thcNox if you need some documentation on how to work on your models to use them in the arma engine, I can give you some infos on Skype: a.brunelli.mb

**Comment by R4Z0R49** [comment]
Grandma, would be the best person to msg about that stuff.

**Comment by thcNox** [comment]
I'll dedicate some time to this this weekend and I'll try and get in contact with Grandma
