### ISSUE TITLE
1.8.4.1 temperature system bugs/flaws

### ISSUE THREAD

**Issue by VidKo** [DayZMod/DayZ#368]
on top of most of buildings you're gaining temperature, even when rain is falling on you. Also, in some buildings (like southern crane in Chernogorsk and southern cranes in Elektrozavodsk) you're losing temperature, even if you're inside. Also, you're losing temperature in a helicopter if you're flying above water.

**Comment by R4Z0R49** [comment]
3rd one should be fixed the others will need to be looked at.

**Comment by VidKo** [comment]
Also you lose the temperature when driving boats. I wouldn't mind losing the temperature in the PBX, but the small boat and fishing boat should raise your temperature when using them as you are protected from most of the rain, wind and water spray.

**Comment by R4Z0R49** [comment]
Its the same issue.  When you in a vehicle the becomes the player so the surface still works the same sea has no vehicle  check its been fixed so little point in naming every vehicle it don't work for. Its fixed water is effected only when not in a vechile.
