### ISSUE TITLE
Trouble Installing 1.7.7.1

### ISSUE THREAD

**Issue by intangible831** [DayZMod/DayZ#37]
Everytime I try to install the OA Beta they have you download on Dayzmod, it tells me "Wrong CD Key". It then tells me "Bad Version" when I launch the game. I've corrected this issue twice now and i'm wondering if there is a way around this. When I try to join servers it tells me I need to download the 1.7.7.1 version because i'm running 1.7.7. I've tried both Six & Commander. Commander tells me i'm running an old version of Arma but gets an error when trying to update it. I can't join any new servers, please help if you can.

**Comment by MattzFiber** [comment]
This is not a DayZ error but it has to do with your regitry. Lauch the base game from steam and it will re add your key to the registry and it could fix your error
