### ISSUE TITLE
Bugs in 1.8.4.1 (and wishlist for the future)

### ISSUE THREAD

**Issue by B73** [DayZMod/DayZ#374]
First of all, many thanks for you guys for the mod development. I really like it, so as tens of thousands others :)

Some bugs I have experienced in 1.8.4.1 (vanilla server)
1. combining m24 to DMR (or vise versa) sometimes vanishes all m24 and DRM clips from gear. Only ammo in backbag remains.
2. sometimes all gear (except main weapon in hand and stuff in backbag) is lost when entering the game.
3. sometimes axe (secondary weapon, in back) disappears when picking gun from the ground.
4. when eating canned food empty tin cans sometimes disappear instead of appearing on the ground (need to carry empty tin can in gear always, just to be safe)

My wishes for the future:
1. backbags to stashes (also could craft backbags like stashes from small to large?)
2. weapons would take weapon slots in tents/stashes, not matchbox, hunting knife, etool, binocular etc. (small stashes would be enough to stash matches, hunting knifes etc. basic items)
3. mosin rifle is the only weapon that can spawn as broken - why not all weapons? need to keep weapons in good condition would be nice also (they would need percentage condition and some kind of spare parts tho)
4. items stay on the ground as long as character who put them there is alive and server isn't restarted
5. biplane could be shot down by shooting it (hull or engine damage or both)
6. choppers would drop easily when fired upon, like 1-2 shots with Enfield to the gas tank (there is no such thing now I assume) would explode chopper and few shots to main rotor would make it drop (even with small caliber weapons, < 7.62 I mean)
7. all vehicles would need repairs once awhile (even normal driving will lower condition percentage, maybe engine and hull)
8. character's temperature wouldn't drop so fast as nowadays, and when inside building temperature would rise faster (maybe also colder up north than south?)
9. ability to cut meat with axe/machete also, and hunting knifes could be sharpened
10. achievements player gets would be shown in journal (like 3 x steady aim etc.) and they would be explained somewhere (documentation?)
11. other players could read journals from dead bodies and dead bodies would remain until server restart or hidden by some player (maybe humanity from hiding bodies?)
12. zombie kills in journal would be displayed by numbers
13. zombies would be tougher, more damage and/or huge chance for infection when hit by zombie (spawn radius could also be more, nowadays only function zombies seem to have is telling players that other players are close to same location)
14. matchbox could contain more than 5 matches
15. lots of different clothes (no to bandit/hero skins), players looks are quite universal now :)

**Comment by Lukethero** [comment]
10 and 11 are some preety original ideas... I like em.

**Comment by R4Z0R49** [comment]
My wishes for the future:
1. Possible i guess not sure what it will add.
2. This is an arma system we can change without changing everything to magazine slots :-( (then we get useless boxs in the ui and other issues).
3. Its the only weapon its been added too. If someone has time to go over all the others go for it :-) other wise it will happen as and when we can.

4.This would have a huge impact on performance of the server.
5. it can be shot down.
6.They can be shot down.
7. hum interesting let me think about that one.
8. this is a work in progress in a mod that's alpha. (it will change with each update)
9. Could do
10. already planned.
11. Was planned along time ago when the journal got added if anyone has time to have a go sure try.
12. I thought i did show at the bottom of the kills pages let me check that one.
13. its controlled by the server admins now.
14. match box system was changed in 1.8.2 to something i didnt wont it will be changed back to the previous version.
15. already brought up in another issue with reasons why we havent yet.

Thanks

**Comment by Lukethero** [comment]
@R4Z0R49 Uhhh... Maybe it cannot. Shot a biplane up with 2 AKM mags and a shit ton of stanag on numerous locations on the plane a few weeks back, and it had no effect on it whatsoever. Maybe I needed a bigger bullet than the AKM?

**Comment by R4Z0R49** [comment]
or better aim biplane have the same weekness as every other vehicle. We even documented this back when we removed 50 cals.

**Comment by Lukethero** [comment]
No it was point blank while it was parked. I even got in to check the damage.

**Comment by B73** [comment]
Yep, can't damage biplane by shooting. You can sometimes see smoke trail coming from biplane like it would be damaged somehow, but it isn't. We call it flying tank nowadays.

And choppers then... several DRM shots to main rotor and they're still on the air. Would prefer 5 shots, max. Even with AK or Enfield :) It would make them vunerable > have to fly higher to avoid hits. Nowadays they're like tanks, fly very low hunting other players and finding hidden tents/vehicles on the ground. Choppers could be aimed for those who want to move fast from place A to place B (looting heli crashes is most common), not for those who use it to hunt flying very low because there's no actual fear being shot down.

And journal.. my personal record is almost 8000 zombie kills with one living character, so looking zombie kills from journal isn't nice if there's dozens of pages listing kills. Only 1 page with numbers only would be better :D

**Comment by kichilron** [comment]
6 shots is all it takes...

http://youtu.be/mP_Z1NEOAuU

**Comment by B73** [comment]
6 shots near to standing still target. In real situation you might have CCO SD and you try to drop chopper from 100-150 metres above. Or with AK. I guess 6 shots with CCO SD doesn't drop chopper in real situation. I'd prefer hull damage drops chopper also :)

Btw, what happens when player jumps from heli/plane with parachute and lands to base not his/her? Goes there with evil plans on his/her mind, but can he/she get out of there thru gate with backbag full of stolen goods?
