### ISSUE TITLE
Death/Kill Message Request 

### ISSUE THREAD

**Issue by fazmond** [DayZMod/DayZ#376]
would love this feature to be added and give the server admins an option to have It on or off in the server configurations.

the video below shows a system where the message is displayed as a pop up on the right hand side of the screen and I think its quite a simple thing to do.

https://www.youtube.com/watch?v=GCzwS1GkIG0

This would also help us greatly while admining the server because we've had situations where a hacker has teleported everyone and killed them but couldn't tell what player it was fast enough to do much about it .

there is a thread here if you wish to have a gander
http://opendayz.net/threads/kill-messages-death-messages.9158/

**Comment by R4Z0R49** [comment]
This has been requested a few times. The answer is no sorry death msgs will not be added by us.
