### ISSUE TITLE
Unrealistic body temperature

### ISSUE THREAD

**Issue by Flamberg** [DayZMod/DayZ#377]
Hello!

The body temperature values that are shown in journal are very unrealistic. They start at 42°C and then go lower and lower to something like 30°C.

It may be worth changing the starting temperature to something like 37°C and then use decimal fractions to go down (maybe 0,5 fractions?).

Note that a temperature of 35°C or less is considered as hypothermia, above 37,5°C as hyperthermia. The temperature of 42°C is life-endangering; such people are near death.

**Comment by R4Z0R49** [comment]
Its a new system we have just got working the values will be tweaked in time.

Remember the mod is just an alpha. We work on in our spare time

**Comment by Flamberg** [comment]
Yes, sure thing! I just wanted to have it logged, so that it is not forgotten :-)

And I completely understand, I do it in my spare time as well :-)

**Comment by R4Z0R49** [comment]
Temperature system has seen some improvements for 1.8.8
