### ISSUE TITLE
Base gates and walls are useless...

### ISSUE THREAD

**Issue by dayzjarhead** [DayZMod/DayZ#378]
... until the "getting through the wall when getting out of a vehicle"-glitch isn´t fixed. 

There is no way for an admin to ban people for this if you don´t catch them in the act.

So, building them takes a whole lot of time and is basicly useless because your base gets raped anyways. [/rant]

**Comment by R4Z0R49** [comment]
Rant closed.

**Comment by R4Z0R49** [comment]
As much as the is an issue in not going to spend time dealing with rants. Tank traps are the best way to deal with this.

**Comment by ghost** [comment]
Yeah sorry. Had to vent somewhere. 

I think I saw some script in Epoch which deals with this issue.

**Comment by R4Z0R49** [comment]
Yea, there's a few ways I can think of

**Comment by Lukethero** [comment]
Agreed on how this needs to be fixed. Tank traps are a good fix right now, problem is they dissapear after a few restarts. Any way you could remove the cleanup scripts on them? Easy server side fix, maybe the server admins could just fix it themselves.

**Comment by ghost** [comment]
I pretty much removed the tent, sandbag and tanktrap cleanup because it tends to upset players when they find their stuff being removed. I rather zoom around the map and clean certain areas manually.

I just head an idea for a fix. I´m no scripter, though. Maybe you could determine the distance to a wall/gate and force the cheater to get out of the car on the other side. Dunno if this proximity check is a heavy hit on the performance...

**Comment by MercianUK** [comment]
Simply adding a 45 degree log support on the outside of the fence, as well as inside would solve this problem. (just a thought)

Tested, at the moment, you can get inside a base through a wall but not from inside to outside. 

My reasoning for this:

I would agree (not ranting) with Dayzjarhead that rataionally thinking this does the rendered base building concept near useless, As just placing sandbags and tank traps aorund the walls of the base is only a temporary guard and  they despawn too quickly, placing them on "never despawn" would only fill the server with spammed tt's and Sandbags. As the cleanup would be over ruled. The argument of simulation could be used, i would love to park my car in the garage and glitch through into my living room (sarcasm for humour).
A few regulars refuse to start building becasue of this issue. Why spend hours/days planning/collecting and building a base when all a player needs to do is to drive up to the walls and simply get out of a vehicle. Simply dismiss this, and the one of things that brings people back to the mod, will basically fail.

**Comment by R4Z0R49** [comment]
You both know how to create an issue. Plz do so without the rants.

**Comment by ghost** [comment]
Oh, I think we got quite past the ranting, just exchanging ideas here.

**Comment by Lukethero** [comment]
Can admins implement this code or is it untested? @R4Z0R49

**Comment by R4Z0R49** [comment]
Not really but the patch will be out Monday so get testing.
