### ISSUE TITLE
Humanity

### ISSUE THREAD

**Issue by PBL123** [DayZMod/DayZ#379]
Not sure if this is just on this server but right now when a player get -2000(or -2500 not sure) and get the bandit skin the journal still registers them as a survivor until they reach -5000.

I tested this with a friend and after giving bloodbags i turned into a survivor in bandit cloathes under -5000 points.

This also affects the gameplay because if you kill one of these survivors in bandit cloathing you will sitll lose humanity. This has happened to me also.

**Comment by kichilron** [comment]
This has been an issue with the Journal for a long time. We don't currently have someone doing interface-stuff, sadly. 

Humanity in general needs a rework.

**Comment by R4Z0R49** [comment]
I'll take a look soon as I can pinned down with work atm.

**Comment by R4Z0R49** [comment]
https://github.com/DayZMod/DayZ/commit/405bf5c01707d9043b72c3edf8d481be3dc6ea83

Fixed.
