### ISSUE TITLE
Endless Death

### ISSUE THREAD

**Issue by koolgamer** [DayZMod/DayZ#380]
When you join a new server you start playing for a bit then it crashes and when you come back on you are in a endless death until server restarts.

**Comment by R4Z0R49** [comment]
Contact the server owner he should be able to reset the db.

**Comment by ghost** [comment]
Sounds like an old infiStar issue...

Solution could be here... http://opendayz.net/threads/problems-with-infistar-and-dayz-mod-1-8-3.21272/
