### ISSUE TITLE
Game close by it self if receiving any damage near wood fences

### ISSUE THREAD

**Issue by endreu1** [DayZMod/DayZ#382]
Whell.. IF im stuck in wood gate or fences, or i get shot near it  game will just close by it self. Event if i blowing my self with an charge, samee thin. Game closes then starting it and rejoin. Woodfence blowed, but i don't have ANY damage made.
I'l hope you will try to fix it
THX.

**Comment by R4Z0R49** [comment]
This issue has been fixed. Waiting for pl to test.

**Comment by MercianUK** [comment]
This may be related to Client Crashes #333, The problem has disappeared since a workaround cleanup for the issue, until the removal of fences, then it returns. Tested last night. A cleanup event can be created on server restart.

**Comment by R4Z0R49** [comment]
Fix should already be in the development branch found on steam.
