### ISSUE TITLE
 SD mags wont fit in unsilenced STANAG gun

### ISSUE THREAD

**Issue by LO0TC1F3R** [DayZMod/DayZ#384]
As the title suggests, I was not able to load STANAG SD mags into an unsilenced STANAG gun. Relogging did not change that and when transferring the gun into a stash the mags were not automatically transferred either. Naturally now I am wondering if that was a bug or if changes were made so that SD mags only go into SD weapons.

**Comment by R4Z0R49** [comment]
Sd mags only go into sd weapons

**Comment by Lukethero** [comment]
@R40R49 That is not how it has always been. You could put SD mags in an m4 or whatever, the round would only be silenced to zombies though. Honestly don't bother fixing it though, bigger stuff to tackle.

**Comment by kichilron** [comment]
This changed in 1.8, I think. Must be about 1.5 years ago?

**Comment by KPanicEKS** [comment]
I think all M16 variants allow SD ammo expect the m16 ACOG. Not sure about
the m203 as I rarely use that weapon.

**Comment by R4Z0R49** [comment]
@Lukethero i didn't say it had always been like that. I just said they only go into sd weapons for the best part some weapons still allow the use of them.
