### ISSUE TITLE
20a57cf - adding attachment drops weapon at feet

### ISSUE THREAD

**Issue by Detoeni** [DayZMod/DayZ#385]
I thought that when I had done this before the weapon was returned to the slot...
Upgraded an m4a1cco with camo, new item spawned at my feet.

**Comment by R4Z0R49** [comment]
its one of the old type attachments they will be removed soon. But not sure how there spawning at your feet.

**Comment by vinyljunkie** [comment]
Hey Detoni, are you running infistar?

**Comment by Detoeni** [comment]
I think the server I was on is. This one http://www.gametracker.com/server_info/209.0.142.106:2352/

**Comment by R4Z0R49** [comment]
No further reports.
