### ISSUE TITLE
"Wait for host" When Esc key then back in DayZ menu.

### ISSUE THREAD

**Issue by Juri3D** [DayZMod/DayZ#386]
DayZ Mod problem
""""""""""""""""""""""""
I get a "Wait for host" and when I press Esc key then back I'm back in the DayZ menu.
According to DayZ Standalone forums this means I have a connection to the server.
But I can't see servers when refreshing the server list in DayZ or DayZ Launcher. I have tried disabling my firefall and router, just connecting directly to my ISP Router instead. Nothing changes.
I tried reinstalling DayZ four times, nothing.
I tried reinstalling Arma II OA without result, then Arma II, no result there neither.
I tried a different profile in the game, still nothing.
I really need help, I can't get back in DayZ Mod.

Thanks for reading this post!

Have a nice day!

Sincerely,
Juri

**Comment by R4Z0R49** [comment]
What version are you running?

Load dayz and go to the menu the version will be shown in the bottom right hand side.

**Comment by Juri3D** [comment]
Version 1.63.125548
@DayZMod 1.8.4.1

**Comment by R4Z0R49** [comment]
What version is the server your trying to join?

**Comment by Juri3D** [comment]
1.8.4.1 / 12
But I can't connect to any server. And in the Arma II DayZ Multiplayer menu, I can't see any servers. The list is empty.

**Comment by R4Z0R49** [comment]
Make sure the the drop down box in the bottom right hand side says internet and hit refresh.

Make sure you have no filter options selected.

**Comment by Juri3D** [comment]
Yeah, I tried that many times before. Nothing happened.

**Comment by R4Z0R49** [comment]
Not 100% sure then if you unable to see any servers it might be a firewall issue. Try one of our servers by using the remote button and entering 198.24.156.194:2302.

**Comment by Juri3D** [comment]
As I said before, I tried shutting down the firewall. It did nothing.
I tried remote connect to that IP with the port number but it didn't work.
My Windows 7 firewall is disabled and I'm using Zonealarm, and it doesn't help turning it off.

**Comment by R4Z0R49** [comment]
Did you try using remote?

**Comment by Juri3D** [comment]
Yes, many times. It doesn't work. The list is just empty and nothing happens.

**Comment by R4Z0R49** [comment]
Yea really no idea then the server list is an arma 2 system its nothing to do with the mod we dont change it in anyway.

**Comment by Juri3D** [comment]
Ok, but I reinstalled Arma II and OA. :/

**Comment by Lukethero** [comment]
Are you trying to launch the game using Dayz mod or are you using operation arrowhead to try and get the in the servers, or are you using some kind of launcher?

**Comment by Juri3D** [comment]
I'm using DayZ thou DayZ Launcher.
I tried starting DayZ with Steam but it doesn't do any difference.
