### ISSUE TITLE
1.8.4.1 - Problem with Gear, Vehicle not showing on map - at Database OK

### ISSUE THREAD

**Issue by iFear** [DayZMod/DayZ#387]
There is an incompatibility with some new items, when they are put in a vehicle.
This Vehicle is not showing on the map after restart, but is still in the database, if you put out some new items it will show on map. I thought I have found the item, that causes the problem, but when I only put this one item in another car, it works.... 

This is the Vehicles Gear (UralCivil) with the Problem:
[[["AK_74","m16a4_acg","Mosin_Nagant","glock17_EP1","AKS_74_kobra","Makarov","MeleeHatchet","Crossbow_DZ","LeeEnfield","revolver_EP1","MeleeBaseBallBat","MeleeCrowbar","ItemDIY_wood","AKS_74_U","MeleeMachete","UZI_EP1","Mk_48_DZ","Sa58V_EP1","AK_47_M","Colt1911","MP5SD","M240_DZ","M4A1","M4A1_Aim","M1014"],[2,2,5,3,1,1,1,2,2,3,1,2,1,1,1,2,1,1,1,1,1,1,1,1,1]],[["bloodBagAPOS","bloodBagBPOS","20Rnd_762x51_DMR","8Rnd_9x18_Makarov","ItemPlank","equip_duct_tape","ItemFuelcan","ItemJerrycanEmpty","PartGlass","5x_22_LR_17_HMR","equip_nails","Attachment_FL","2Rnd_shotgun_74Pellets","HandRoadFlare","emptyBloodBag","ItemEpinephrine","ItemPainkiller","Skin_Survivor2_DZ","15Rnd_9x19_M9","equip_lever","ItemCards","equip_string","equip_rag","ItemWire","SmokeShell","SmokeShellGreen","Quiver","WoodenArrow","10x_303","8Rnd_B_Beneli_74Slug","ItemSodaLirik","15Rnd_W1866_Slug","bloodBagBNEG","ItemSodaLemonade","ItemSodaSacrite","75Rnd_545x39_RPK","Attachment_M4A1_Aim","Mosin_Nagant_Ammo","30Rnd_9x19_MP5SD","17Rnd_9x19_glock17","ItemTent","ItemWaterbottle","Attachment_M4A1_Aim_camo","ItemSandbag","30Rnd_556x45_Stanag","HandGrenade_West","6Rnd_45ACP","100Rnd_762x51_M240","30Rnd_762x39_SA58","SmokeShellRed","30Rnd_762x39_AK47","Attachment_M4A1_AIM_SD_camo","Tranquiliser_Bolt","ItemHeatPack","PartVRotor","equip_gauze","ItemMorphine","bloodBagOPOS","transfusionKit","bloodTester","Attachment_M9Silencer","FoodCanBakedBeans","bloodBagABPOS","bloodBagONEG","PartGeneric","FoodCanUnlabeledEmpty","SmokeShellYellow","ItemTankTrap","HandChemRed","PartWoodPile","equip_metal_sheet","equip_1inch_metal_pipe"],[2,2,11,5,2,2,2,1,9,3,2,1,2,2,6,1,4,3,3,1,1,2,2,3,2,2,2,1,1,1,1,3,1,1,1,1,2,6,2,4,1,6,1,3,12,5,7,2,1,1,1,1,1,1,1,1,7,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]],[["DZ_Patrol_Pack_EP1"],[1]]]

If you put out the last 9, it will work, but if you put this 9 items in another car, the other car is still working.... I'm very confused, I think some of the new items are not comatible to others...
I got the same problem with an V3S some days ago.

**Comment by R4Z0R49** [comment]
My guess is the vehicle is too full and the limits might need to be lowered a little on the bigger vehicles.

**Comment by iFear** [comment]
Yeah this could be... because I can't figure out a problem with the items self, they are all working when you put some of them in an other car,

EDIT: maybe you can test that (you could take the sample on the top)? I think its the number of different items, not how often an items is in there. I've had the same problem yesterday. I wonder, because I've never seen that problem before

**Comment by R4Z0R49** [comment]
No real time to test but it sounds like your just adding too many items there is an upper limit for the array being used.
