### ISSUE TITLE
When people relog they duplicate.

### ISSUE THREAD

**Issue by Djwceend** [DayZMod/DayZ#39]
Hello,

When people relog on oure server there charachter will duplicate.
Does somebody know what the problem of this can be?

We are running on 1.7.7.1

**Comment by R4Z0R49** [comment]
We need more info about the server.

**Comment by Djwceend** [comment]
We already solved the problem.

Thanks anyway :)!

**Comment by AVendettaForYou** [comment]
Could you tell us how you fixed this issue?
