### ISSUE TITLE
Cannot transfuse players that have not taken a blood test - 1.8.4.1

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#391]
In 1.8.4.1 we have run into an issue a few times where we'll transfuse a player with a popular blood type such as O+ and it will knock them out.  Later, after taking a blood test, they'll have a blood type that is compatible as a recipient for O+.  After taking the blood test, we'll try transfusing O+ again and it works.  I'm only using O+ as an example, we're not sure what blood types this is a factor with and we haven't had a chance to properly test it.  It seems, though, that currently a player that has not taken a blood test cannot receive a transfusion of ANY blood type without passing out.  Maybe someone with a test server can try this out.

**Comment by R4Z0R49** [comment]
Yea i think its the new default behavior brought in with 1.8.3. Ill need to check but yea im not that happy with the blood bag system at all and i think the hole system needs a rethink. It's on my never ending todo list.
