### ISSUE TITLE
Usefulness of weapon attachments

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#392]
I think something along the lines of this may have been brought up before, so I apologize if this is redundant.

The new weapon attachment system that is being implemented is great, but has very little usefulness currently due to a couple of factors.  I have seen very few players take advantage of it.  Here's what I think is contributing to this:

1) Very particular upgrade path: this may be due to engine/coding issues that are way above my head, but I've noticed attachments fit very specific weapons requiring almost and upgrade path to work, such as M4A1 > M4A1 camo > M4A1 camo CCO > M4A1 camo CCO silenced.  It would be awesome if you could attach a silencer, ACOG, or aim sight to any M4A1 or any rifle with the necessary rails rather than having to have a particular model.  Also the inability to remove attachments is a bummer.  It would be fantastic to remove an AIM sight from an M4 and add it to an M14 that spawned with only iron sights.

2) Very limited SD ammunition spawns and the inability to use non-SD ammo in silenced guns.  So, I'll find a silencer for a Makarov or an M9 which is _fantastic_!  ...But then I'll roam for hours with no SD ammo for either of those guns.  I'll search and search, and the only place I have a good chance of finding it is when it spawns right next to...you guessed it...a Makarov SD or M9SD pistol!  This honestly has rendered the silenced pistol attachment system useless.  It would be great if a) pistol SD ammo spawned in a variety of places like Stanag SD does and b) you could use non-SD ammo in an SD gun but it still fired fairly loud.  In real life a silencer will still silence the actual shot of supersonic ammo, but the cracks will still be present because it is supersonic.  Not truly silenced, but you can use supersonic ammo in a gun with a silencer.

3) Fairly high spawn rate of weapons with attachments.  I think that the attachment system would suddenly become VERY valuable if the spawn rate of M4A3 CCOs, M4A3 SDs, M9SDs, Makarov SDs, etc were significantly reduced.  As it currently stands people pass up spawned weapon attachments 99% of the time because it's much easier to find an M4A3 CCO SD then to find the right attachments that fit the right rifle.

Hopefully this is helpful feedback.  The attachment system has a lot of promise and will be a great addition to DayZ mod once it's fleshed out!

**Comment by R4Z0R49** [comment]
I see you only made comments about the old system nothing about the new system from the mosin.

**Comment by R4Z0R49** [comment]
1, We can only use attachments on weapons we have models for ie the m4 does not have ACOG site this is why we dont have that option. If someone provides the models and a real update path i can add them without any hassle. Check the mozin out that is using the new system as it has a better upgrade path then other weapons from arma.
1. Zed hearing is based on the weapon sound not the bullet it fires. So firing an SD weapon with none SD rounds would give an SD sound hence the reason it was removed in the first place maybe a some point we can swap this around but im not sure bullets hold any kind of radius system we can use meaning we might have to dig every class of ammo out and create or own.
2. Spawn rates are all over the place just now until i can sit down for a few hours to just look at spawn rates not really a hole lot i can do its one of them system that needs a ton of love to look over not something you do after a 15 hour shift on nights :-(. If someone else wont's to take a look at them there more then welcome to.

**Comment by bchawke** [comment]
From your initial response it sounds like you're taking offense to my input.  I'm sorry.  I'm not criticizing the game or failing to acknowledge the work that's been put into it; I'm trying to provide helpful feedback/input in the only way I know how so that I can contribute to forward progress in the mod.  I don't know the first thing about coding or video game art design so unfortunately I cannot help in those areas.

I was making comments on the M4/M16/M14 picatinny rail system that incorporates the AIM CCO sight, ACOG scope, and flash light.  I was also referring to attaching silencers to M4s and pistols.  Sorry I didn't distinguish that system from the Mosin attachment system.  I'm happy for the implementation of the attachment system with the Mosin it's a great addition to the game.

In the end, I guess my overall point is that while the M4/pistol attachment systems are a great addition, nobody is using them right now because it's much easier to find a spawned gun with all the attachments already added, and SD pistol ammo spawns predominantly next to SD pistols.

**Comment by R4Z0R49** [comment]
No offence is being taken at all. I was just pointing out you mentioned only the old system nothing about the new one. My typing skills plus being half asleep don't always help.

**Comment by R4Z0R49** [comment]
SD ammo spawns pretty much every single building in the map.

https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_code/Configs/CfgLoot/CfgLoot.hpp#L7
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_code/Configs/CfgLoot/CfgLoot.hpp#L19
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_code/Configs/CfgLoot/CfgLoot.hpp#L20

and if we take a look here

https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_code/Configs/CfgLoot/CfgBuildingLoot.hpp

look for {"","ammo",0.10}, This will spawn the top link ammo array based on weights for each building its attached too.

Number 3 should be resolved. 1 will only be resolved with new models.

**Comment by paradigmArchitect** [comment]
Just so this isn't completely lost in obscurity, someone made a weapon upgrade system and would probably be happy to share it. I noticed you mentioned not having an option to upgrade M4 to acog, so here is a video of it being done: https://www.youtube.com/watch?v=FLgS7bBK_q8

visual overview: https://www.facebook.com/shadowofchernarus/photos/a.1466673476905715.1073741828.1466399730266423/1479767735596289/?type=1

code: http://download.mbnq.pl/arma2/scripts/mbnq_wpSys.sqf

**Comment by R4Z0R49** [comment]
Bloody close comment.

M4 was just an example. We can only use what we have available to us.

**Comment by AsFoxy** [comment]
I recently made a collection of models specifically for Dayz. Still in the process of making it presentable though. Basically i have models for all weapons currently in game with all combinations of applicable attachments. Posting this on my phone away from home. If you guys are at all interested i can probably make a presentable build for sunday.

**Comment by R4Z0R49** [comment]
Sure ill take a look :-)

**Comment by R4Z0R49** [comment]
Closed due to weapon overhaul.
