### ISSUE TITLE
Development - Add Maintenance system to base items. 

### ISSUE THREAD

**Issue by R4Z0R49** [DayZMod/DayZ#396]
1. upkeep for the fences
2. downgrade fences on missing upkeep.

**Comment by R4Z0R49** [comment]
Layout.
1. Each fence section is checked if it hasn't been updated within 7 days the fence is tagged for Maintenance.
2. For each 3 days after the fence has been tagged the fence will start to downgrade foreach 3 consecutive days its left in maintenance mode.
3. once the fence has been downgraded to foundation level 3 days after the object will be removed.

So a level 7 fence once upgrade would take 7 days to become active in maintenance mode. For each 3 days after this it will be downgraded. for each 3 days leading upto 36 days the fence will continue to be downgraded until the fence is no more.

Level7 Fence (Fully upgraded)
7 days to become added to Maintenance Mode.
- 33 days for downgrade of each section.
- 3 days to be removed from db.
  == 43 days total if neglected.

**Comment by R4Z0R49** [comment]
Todo.

Maintenance Mode visual sign.

**Comment by Lukethero** [comment]
Seems a little rough on the maitrnance time... If you were to go on vacation your walls would be screwed. Maybe up it to 2 and a half weeks or so till the degrade occurs. Not sure an upkeep system is needed, but if you think it is necessary, that is up to you.

**Comment by R4Z0R49** [comment]
The initial time can be changed by admins. But we have to include some kind of degrade system just to clean up for players who leave servers months ago and all that we still need to think about performance to some degree.

Your walls would be level 5 by the time you return after 2 weeks if they where level 7 to start with.

**Comment by skigoggles** [comment]
I thin kits worked just fine for fences. I've watched a base degrade over a month when I player didn't come back. The only thing left was the gate - they do not degrade.
