### ISSUE TITLE
3, Usefulness of weapon attachments

### ISSUE THREAD

**Issue by R4Z0R49** [DayZMod/DayZ#397]
Fairly high spawn rate of weapons with attachments. I think that the attachment system would suddenly become VERY valuable if the spawn rate of M4A3 CCOs, M4A3 SDs, M9SDs, Makarov SDs, etc were significantly reduced. As it currently stands people pass up spawned weapon attachments 99% of the time because it's much easier to find an M4A3 CCO SD then to find the right attachments that fit the right rifle.

**Comment by Lukethero** [comment]
Would help to increase spawn chance SD ammo for the mentioned pistols here. I am aware they spawn most places, but a very slight increase would not hurt.

**Comment by R4Z0R49** [comment]
Im looking into it, been playing for about an hour now not really seen to many big issues some silly little tidy up bugs. But SD ammo has been brought up during this game play.
