### ISSUE TITLE
pCleanup suggestion - dead players

### ISSUE THREAD

**Issue by nsonP** [DayZMod/DayZ#399]
In 1.8.4 a new routine was added in the pCleanup to remove dead players. This would in some scenarios cause a free humanity reset if a player logged out after death and waited until the restart. Then if he logged back in again and he would be back at 2500 humanity.
The current pCleanup is running below query:

**Insert INTO character_dead SELECT \* FROM character_data WHERE Alive=0;**
And then:
**DELETE FROM character_data WHERE Alive=0;**

What we did to overcome above scenario was to add our own query to the bottom of pCleanup that will:
1.  Move back the last dead character to the character_data table.
2.  Deleting the same from character_dead so that we don’t get icrements issue within the table later on.

```
#Move latest dead character from character_dead --> character_data
Insert 
    INTO character_data
    select * 
    from character_dead
        where characterid in
            (select cid from (select playeruid, max(characterid) cid from character_dead cd group by playeruid) maxcids)
            and alive = 0;

#Delete last character from character_dead to make sure we dont get increments issues.
DELETE  
    from character_dead
        where characterid in
            (select cid from (select playeruid, max(characterid) cid from character_dead cd group by playeruid) maxcids)
            and alive = 0;
```

i did notice that you have changed the pCleanup routine for 1.8.5 but what i like with our solution is that it will keep the character_data fairly clean and 'small'. I guess there is a way to do it all in one query but didnt really have time to figure out a good way of doing it.

**Comment by R4Z0R49** [comment]
ill look into this a try to find a better solution all round.

thanks.
