### ISSUE TITLE
slow connect/login

### ISSUE THREAD

**Issue by fgw-** [DayZMod/DayZ#4]
installed 1.7.7.7 (beta 103718) on my testserver. the connect/login process is definitely slower than before!
there are several retries when attempting to authenticate.

here are the lines from the rpt file:

 0:08:17 "HIVE: Starting"
 0:08:18 "HIVE: Local Time set to [2012,6,6,10,8]"
 0:08:18 "HIVE: trying to get objects"
 0:08:18 "HIVE: found 57 objects"
 0:08:18 "HIVE: Commence Object Streaming..."
 0:08:18 "HIVE: got 57 objects"
 0:08:18 "DEBUG FPS  : 1.1251"
 0:08:21 "STARTING LOGIN: ["1847554",B 1-1-A:1 ([RaZe]fgw) REMOTE]"
 0:08:21 "Login cancelled, server is not ready. B 1-1-A:1 ([RaZe]fgw) REMOTE"
 0:08:23 "STARTING LOGIN: ["1847554",B 1-1-A:1 ([RaZe]fgw) REMOTE]"
 0:08:23 "Login cancelled, server is not ready. B 1-1-A:1 ([RaZe]fgw) REMOTE"
 0:08:25 "STARTING LOGIN: ["1847554",B 1-1-A:1 ([RaZe]fgw) REMOTE]"
 0:08:25 "Login cancelled, server is not ready. B 1-1-A:1 ([RaZe]fgw) REMOTE"
 0:08:27 "STARTING LOGIN: ["1847554",B 1-1-A:1 ([RaZe]fgw) REMOTE]"
 0:08:27 "Login cancelled, server is not ready. B 1-1-A:1 ([RaZe]fgw) REMOTE"
 0:08:51 "STARTING LOGIN: ["1847554",B 1-1-A:1 ([RaZe]fgw) REMOTE]"
 0:08:51 "Login cancelled, server is not ready. B 1-1-A:1 ([RaZe]fgw) REMOTE"
 0:09:06 "STARTING LOGIN: ["1847554",B 1-1-A:1 ([RaZe]fgw) REMOTE]"
 0:09:06 "Login cancelled, server is not ready. B 1-1-A:1 ([RaZe]fgw) REMOTE"
 0:09:20 "VEHICLE OBJ OID#47(V3S) at factory [131:83], damage=0.155, fuel=0.405"
 0:09:20 "VEHICLE OBJ OID#48(GAZ Limo) at Grishino [62:50], damage=0.155, fuel=0.405"

 ...

 0:09:26 "CLEANUP: INITIALIZING CLEANUP SCRIPT"
 0:09:26 "z\addons\dayz_server\compile\fn_bases.sqf found a nice spot at Berezino [113:64](9)"
 0:09:27 "Infected Camps: Loot spawn at 'Camp2_Small:[11314.9,8977.28,0]' with loot table '["WeaponHolder_ItemFuelcan","object",0.03]'"
 0:09:27 "Infected Camps: Loot spawn at 'Camp2_Small:[11327.4,8984.14,0]' with loot table '["ItemWatch","generic",0.05]'"

...

 0:09:32 "z\addons\dayz_server\compile\fn_bases.sqf: found 3 camps spots in 5 sec."
 0:09:34 "z\addons\dayz_server\compile\fa_antiwallhack.sqf: 14 buildings patched with 87 objects"
 0:09:36 "STARTING LOGIN: ["1847554",B 1-1-A:1 ([RaZe]fgw) REMOTE]"
 0:09:36 "LOGIN ATTEMPT: "1847554" [RaZe]fgw"
 0:09:36 "LOGIN LOADED: B 1-1-A:1 ([RaZe]fgw) REMOTE Type: Survivor1_DZ"
 0:09:37 "LOGIN PUBLISHING: UID#1847554 CID#71 PID#3([RaZe]fgw) as Survivor2_DZ should spawn at Wilderness [150:59]"
 0:09:37 "ERROR: server_playerSync: Cannot Sync Player [RaZe]fgw [71]. Position in debug! [-18697.6,25815.3,0]"
 0:10:06 "DEBUG: needUpdate_objects=[184610c0# 1055256: lr_covered_soft_baf.p3d,18277040# 1055262: atv.p3d,17fd4100# 1055270: atv.p3d,17fbb040# 1055272: atv.p3d,1c586080# 1055301: mi_8mt.p3d,1c4b7040# 1055307: lr_covered_soft_w_baf.p3d,1c176080# 1055324: tt650.p3d,1bf0d0c0# 1055328: atv.p3d,1bdbd0c0# 1055341: atv.p3d]"
 0:10:06 "HIVE: WRITE: "CHILD:306:49:[["glass1",1],["glass2",1],["glass3",1],["motor",0.8],["palivo",0.8],["wheel_1_1_steering",1],["wheel_1_2_steering",1],["wheel_2_1_steering",1],["wheel_2_2_steering",1],["sklo predni P",1],["sklo predni L",1],["karoserie",1],["wheel_1_4_steering",1],["wheel_2_4_steering",1],["wheel_1_3_steering",1],["wheel_2_3_steering",1],["glass4",1]]:0.155:""
 0:10:06 "HIVE: WRITE: "CHILD:306:52:[["karoserie",0],["motor",0.8],["palivo",0],["wheel_1_1_steering",0],["wheel_1_2_steering",0.1],["wheel_2_1_steering",1],["wheel_2_2_steering",0]]:0.739:""
 0:10:06 "HIVE: WRITE: "CHILD:306:56:[["karoserie",0],["motor",0.8],["palivo",0],["wheel_1_1_steering",0],["wheel_1_2_steering",0.1],["wheel_2_1_steering",1],["wheel_2_2_steering",0]]:0.703:""
 0:10:06 "HIVE: WRITE: "CHILD:306:57:[["karoserie",0],["motor",0.8],["palivo",0],["wheel_1_1_steering",0],["wheel_1_2_steering",0.1],["wheel_2_1_steering",1],["wheel_2_2_steering",0]]:0.703:""
 0:10:06 "HIVE: WRITE: "CHILD:306:73:[["glass1",0.962],["glass2",1],["glass3",0.938],["glass4",1],["glass5",0.914],["glass6",1],["NEtrup",0],["motor",0.638],["elektronika",1],["mala vrtule",0.638],["velka vrtule",1],["munice",0],["sklo predni P",0],["sklo predni L",0]]:0.642:""
 0:10:06 "HIVE: WRITE: "CHILD:306:76:[["glass1",1],["glass2",1],["glass3",1],["motor",0.8],["palivo",0.8],["wheel_1_1_steering",1],["wheel_1_2_steering",1],["wheel_2_1_steering",1],["wheel_2_2_steering",1],["sklo predni P",1],["sklo predni L",1],["karoserie",1],["wheel_1_4_steering",1],["wheel_2_4_steering",1],["wheel_1_3_steering",1],["wheel_2_3_steering",1],["glass4",1]]:0.621:""
 0:10:06 "HIVE: WRITE: "CHILD:306:84:[["engine",0],["sklo predni P",0],["sklo predni L",0],["karoserie",0.639],["palivo",0.639],["Pravy predni tlumic",1],["Pravy zadni tlumic",1]]:0.645:""
 0:10:06 "HIVE: WRITE: "CHILD:306:86:[["karoserie",0],["motor",0.8],["palivo",0.8],["wheel_1_1_steering",1],["wheel_1_2_steering",1],["wheel_2_1_steering",0.016],["wheel_2_2_steering",0]]:0.639:""
 0:10:06 "HIVE: WRITE: "CHILD:306:93:[["karoserie",0],["motor",0.8],["palivo",0.8],["wheel_1_1_steering",1],["wheel_1_2_steering",1],["wheel_2_1_steering",0.016],["wheel_2_2_steering",0]]:0.739:""
 0:10:26 "CLEANUP:TOTAL 12 LOOT BAGS"

login succeeds every time, but it takes longer than with previous versions ...

**Comment by R4Z0R49** [comment]
First login is always slower now. Its to make sure the server is fully loaded.

**Comment by fgw-** [comment]
just came back to report my observations, but you were faster ...

yes, i realized this happens just on first login. subsequent logins are fine!

**Comment by facoptere** [comment]
1'20" delay for a server to start is pretty fast.

**Comment by fgw-** [comment]
facoptere: well, not complaining about the server start time. this usually happens not that often. some time a day usually. i was worried about the messages on the client stating authentication retry for several times. the entries in the log

0:08:21 "STARTING LOGIN: ["1847554",B 1-1-A:1 ([RaZe]fgw) REMOTE]"
0:08:21 "Login cancelled, server is not ready. B 1-1-A:1 ([RaZe]fgw) REMOTE"

made me feel uncomfortable too. but as this happens just to the first player on first connect after restart and also this is intended behavior, im fine with it.

btw. although my server is running a 3.3GHz dualcore with 8GB mem i think this will be more than enough power for testing purposes with most of the time just one or two players. also my client is connected directly via lan. so i didnt expect any connection delays from this side ...

but as said before, as its intended its ok ...
