### ISSUE TITLE
Packing/Unassembling common Items : Base Griefing

### ISSUE THREAD

**Issue by HeroSmurf** [DayZMod/DayZ#400]
:+1:  I'm impressed with the bases going up on Vanilla servers and the LACK of griefing/glitching that is taking place. Kudos on a simple system; it's an overwhelmingly positive addition. That's coming from a non-base man myself. 

Griefing (though limited) is happening for various reasons; most can be prevented by the base planner (and ain't that cool?!) double walls, heli drop capture areas (you get stuck in a box in the middle if you try to parachute). Again. Cool. 

The griefing is unfortunately on the rise. 
Before it gets crazy let's fix/add the removal/packing of easy to find/easy to assemble items. 
These are temporary throw-up/take-down items like tents. 

Tank Traps & Camo Nets
In the last 72 hours I've heard 4 cases of d-baggery occuring at very well thought out bases. 

Tank Traps should be salvagable with a chance of failure 
(or just restored to being able to remove them) 

Camo Nets should be packable like a tent. 

Cannot be removed (should be targetable, scroll, toolbox / sledgehammer required etc) 
When destroyed are not cleaned up (understandable if damaged)

Too much work to add the context menus etc? Let's just re-add the cleanup to get camo and tank traps; worst case the demolition department can clear up any griefed bases :)

**Comment by HeroSmurf** [comment]
I'm happy to write/build a pull request with the necessary changes if all the current contributors (faster more access) are busy.

**Comment by R4Z0R49** [comment]
Tank traps and camo nets should already be cleaned up. Let me look into that one.

Camo nets cant be packaged just now its a bug with the model ill see if i can get it replaced from the arma 2 sample pack.

Tank Traps,SandBags should be salvageable with a chance of failure? not sure what you mean but i think your talking about picking them back up like tents?

**Comment by HeroSmurf** [comment]
You got it. Like tents (ish)

For Tank and Camo no matter the original owner you should be able to break them down. 

Tank Traps used to be able to be removed by anyone with a toolbox. 
I remember playing engineer and clearing the road etc :). 

More info you don't need to read. 

Tank Traps should be salvageable with a chance of failure (more info). 
Like removing tires from a car. 

Example : Blocking a road
You can place as many tank traps as you want without failure.
When you go to break them down/remove them from the road you have a % chance they will be converted to a lootable item.

**Comment by R4Z0R49** [comment]
K ill take a look into them should be pretty easy to add. The camo net on the other hand is going to be more if a pain but leave it with me

**Comment by R4Z0R49** [comment]
Started work on a dismantle system not really happy adding a fail chance but having tools break i think fits a little better.
Still unsure if the original creators should be able to remove without the need to dismantle.

**Comment by HeroSmurf** [comment]
Nice. 

Yeah; fail chance isn't as important as giving cleanup power to the common man :)

98% of the reason for this would be to allow the removal of base grief-related junk
2% is being able to throw down and pick back up common buildable items.
