### ISSUE TITLE
Dayz + rMod2.1

### ISSUE THREAD

**Issue by NPG-Soul** [DayZMod/DayZ#405]
Explanation of the problem:
When running Dayzmod + rMod2.1 all zombies get insta deleted after they get
spawned due to the evenhandler attached to the zombie.

File: Zeds.hpp
Code:
class Eventhandlers {
        init = "_this call zombie_initialize;";
        local = "_z = _this select 0;" \n
                "if ((!isServer and !isNull _z) and {(side _z != civilian)}) exitWith { " \n
                "PVDZ_sec_atp = [ 'wrong side', player ]; publicVariableServer 'PVDZ_sec_atp'; deleteVehicle _z; };" \n
                "if (!(_this select 1)) exitWith {};" \n
                "if (isServer) exitWith { _z call sched_co_deleteVehicle; };" \n
                "[(position _z), _z, true] execFSM '\z\AddOns\dayz_code\system\zombie_agent.fsm';";
    };

Error: 
Bad conversion: array
Error in expression <(count _targets == 0) then {
_objects = nearestObjects [_agent,["ThrownObjects",>
  Error position: <nearestObjects [_agent,["ThrownObjects",>
  Error 0 elements provided, 3 expected
File z\addons\dayz_code\compile\zombie_findTargetAgent.sqf, line 26

**Comment by kichilron** [comment]
This is not an issue directly related to DayZ and thus we can't do anything about it. 

It'll be far too time consuming trying to offer support for each mod out there. 

You're most likely better off asking on a Forum.

**Comment by NPG-Soul** [comment]
it used to work until 1.8.3 came and the eventhandler whas updated.
rMod is dead and wont be updated
