### ISSUE TITLE
When i start server 1.8.4.1 server and connect him console close with error "Include file z\addons\dayz_code\gui\mod.paa not found"

### ISSUE THREAD

**Issue by hekut146** [DayZMod/DayZ#409]
Please help start with this parametrs:
start .\Expansion\beta\arma2oaserver.exe -mod=Expansion\beta;Expansion\beta\expansion;ca;@hive;@dayz -name=cfgdayz -config=cfgdayz\server.cfg -cfg=cfgdayz\basic.cfg -profiles=cfgdayz
when i connect i see this error "Include file z\addons\dayz_code\gui\mod.paa not found"  and arma 2 oa console crash, and when i see expansions in game i see this error but game not cloase

**Comment by R4Z0R49** [comment]
Have you included the @dayz folder and all the files/folders to the server?

**Comment by hekut146** [comment]
sure, i download in this trade http://forums.dayzgame.com/index.php?/topic/220556-dayz-mod-hotfix-1841/

**Comment by R4Z0R49** [comment]
Does your client also have the @dayz files. what are you using to launch the game?

**Comment by hekut146** [comment]
Yes, @dayz (and pbo files in @dayz\addons) folder on the my arma oa folider, i can enter to the servers, but if i open arma 2 oa and go to expansions and click dayz i see this error but game don't close

**Comment by R4Z0R49** [comment]
Strange ill take a look next time i'm in-game i don't think i've every tired that way.

Try to use dayz_launcher http://dayzlauncher.com/

**Comment by hekut146** [comment]
and i have mod.paa (36,9 kb (37 816 bite) in dayz_code.pbo, thx for answer i try, now i redownload arma 2\arma 2 oa.. this programm is analog of dayz commander and i needs to download dayz in this programm?

**Comment by R4Z0R49** [comment]
You can use steam as well

**Comment by hekut146** [comment]
i redownload arma 2, arma 2 oa, arma 2 oa beta absolution and arma 2 dayz mod in steam and verify in DayZLauncher and i have this error..

**Comment by hekut146** [comment]
sorry i added server.cfg in cfgdayz at 1.8 dayz server and added dayz_1337.chernarus.pbo in folider dayz_1337.chernarus and i see wait server and update battleye text i download dll file BEServer.dll at http://www.battleye.com/downloads/ and put Expansion\BattlEye\

**Comment by hekut146** [comment]
sorry i need to change 
template = dayz_1.chernarus;
to
template = dayz_1337.chernarus;

and i see this error 19:10:59 Database(0): [Warning] Could not connect to MySQL database at 173.208.122.66: Can't connect to MySQL server on '173.208.122.66' (10061), retrying in 1 seconds
but i set 192.168.1.3 in HiveExt.ini

i need to write
;Port = 3306
or
Port = 3306
in HiveExt.ini

Now i see this error:
2015-04-19 20:32:16 HiveExt: [Information] HiveExt ce45a1f7524c
2015-04-19 20:32:17 Database: [Information] Connected to MySQL database 192.168.1.3:3306/dayz client ver: 5.5.28 server ver: 5.5.38-0ubuntu0.14.04.1
2015-04-19 20:32:17 Database: [Information] Connected to MySQL database 192.168.1.3:3306/dayz client ver: 5.5.28 server ver: 5.5.38-0ubuntu0.14.04.1
2015-04-19 20:32:17 HiveExt: [Information] Method: 307 Params: 
2015-04-19 20:32:17 HiveExt: [Information] Result: ["PASS",[2015,4,19,20,32]]
2015-04-19 20:32:17 HiveExt: [Information] Method: 302 Params: 1337:
2015-04-19 20:32:17 Database: [Error] Error 1146 (Table 'dayz.Object_DATA' doesn't exist) in MySQLQuery SQL: 'SELECT COUNT(*) FROM `Object_DATA` WHERE `Instance` = 1337 AND `ObjectUID` <> 0 AND `CharacterID` <> 0 AND `Datestamp` < DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 6 DAY) AND ( (`Inventory` IS NULL) OR (`Inventory` = '[]') )'
2015-04-19 20:32:17 Database: [Error] Error 1146 (Table 'dayz.Object_DATA' doesn't exist) in MySQLQuery SQL: 'SELECT `ObjectID`, `Classname`, `CharacterID`, `Worldspace`, `Inventory`, `Hitpoints`, `Fuel`, `Damage` FROM `Object_DATA` WHERE `Instance`=1337 AND `Classname` IS NOT NULL'

.sql files i import in db
Could you please put a dump of the database?
my db - dayz have empty object_data table only structure
i have information only 
object_spawns 94 
object_classes 59 
event_scheduler 6
and procedures 4

**Comment by hekut146** [comment]
seriously? i need to rename table object_data to Object_DATA? omg..

**Comment by R4Z0R49** [comment]
its Linux we don't support it at all.

**Comment by hekut146** [comment]
mysql server in unix system

**Comment by R4Z0R49** [comment]
Linux support is not something we have really added on the private hive files you will need to adjust as needed.

**Comment by hekut146** [comment]
i start server in windows but i have ubuntu and mysql server in this OS (ubuntu) please how to spawn vehicles i think to run pMain procedure but i run this and see "null 0 strings"

**Comment by R4Z0R49** [comment]
You run pmain but as i've said we don't support linux so i have no idea what effects it will have and i cant test atm.

**Comment by hekut146** [comment]
What? and here OS when i run procedure she was create in Object_DATA table stings with vehicles and game read information in db and profit i use phpmyadmin and mysql database where does the operating system performs a procedure mysql server

**Comment by R4Z0R49** [comment]
id say speak with a server admin for the exact differences i don't know them or google it. All i know is ppl who run linux have to modify the files a little to work.

**Comment by hekut146** [comment]
ok, thx
