### ISSUE TITLE
Zombies glitching through walls (1.7.7.1)

### ISSUE THREAD

**Issue by IceBeam** [DayZMod/DayZ#41]
Sometimes zombies are either stuck in walls or are able to go through them. In barns they are usually stuck in walls, but in apartment houses, sheds, wooden houses and other residential buildings and castles they just walk through them. It happens on any server I join. I will post more videos if I get more than 20 FPS in the game.

Server: Moscow #84 - PRIVATE (1.7.7.1/Beta 106400) | ALLDAY | 3rdP:on | CH:off | Tags:off - mo84.ru
Version of the server: 1.7.7.1; Beta: 106400; Hive: mo84.ru
Version of the game: 1.7.7.1; Beta: 103718

Location on the map: a barn in Prigorodky (Coordinates: 080 119)

Video: http://www.youtube.com/watch?v=CBToHeQn5xs

**Comment by R4Z0R49** [comment]
This is an engine limitation and will always happen.

Thanks
