### ISSUE TITLE
Food consumption rate too demanding. Suggestion: Cannibalism 

### ISSUE THREAD

**Issue by Dienark7** [DayZMod/DayZ#410]
Hello all, i'm not sure if this is the correct place to leave feedback on features but I felt this is likely one of the best places to get the feedback to you all.

Me and a group of others have noticed that with the introduction of 1.8.4+ Food consumption needs to be extremely high in order to survive, up to a point where a lot of us don't have time to do anything else, even in sessions where all 3-5 of us are playing and just looking for food we sometimes still die to hunger when we have all hands on deck hunting, checking supermarkets and trying to acquire things like fishing rods. 

I and others feel that in this version of the mod it leaves little time for anything else and still has the potential of dying anyway, which certainly encourages the mentality of "ill just kill myself and you cover my body" which certainly plays against the games merits when that becomes the easiest option.

This post is written in two parts, one being could the rate that people need to eat be reduced and/or can the feature of cannibalism be added to the game?

Cannibalism is certainly something seen in many zombie horrors of the current era and could very well be a viable strategy to staying alive, this can obviously come at many risks such as high chances of infection (like any other animal in the game) and maybe a huge humanity loss for eating another player, even if you did not kill them. 

Obviously if this was further developed there is options of things done in the standalone like madness from eating other humans and such, but that's obviously just a far out suggestion.

I would go ahead and have a go at this myself if nobody is interested and i'm given the para miters that you guys would want (i.e. humanity loss from it, infection chances ect ect..) and obviously I don't have any 3D modeling experience so it would just be the code.

Any way, just some suggestions with some offers also, let me know what you all think.

-D7

**Comment by Dienark7** [comment]
It should be noted that I wrote this at 7am after being up all night, sorry for the terrible grammar and various title changes.

**Comment by R4Z0R49** [comment]
I don't see any reason why it cant be added we would need to keep it along the same lines as SA

**Comment by Dienark7** [comment]
Awesome, like I say if its low in your guys priority list ill go ahead and work on the scripting side of it as I have some extra time on my hands at the moment.

**Comment by Lukethero** [comment]
Eehh, edging towards banditry KOS tactics again. I do not think cannibalism is really needed to "fix food." I actually like how it is right now, I can see how some changes might be wanted, but nothing as durastic  as cannibalism is needed. Has maybe just boosting the values of canned food been considered? Possibly a few edible plants beeing added at max.

**Comment by Dienark7** [comment]
I have mentioned various reasons why this should be implemented Luke that you seem to have not addressed, as people who are strictly bandits and live off other players this patch has become much more challenging, as I mention in my original statement many Zombie horrors movies and TV shows depict cannibalism and a lot of people who play like to be able to explore all options they see in TV related to their game play. Seen as Razor has authorized it i'm going to continue my work on the script.

**Comment by KPanicEKS** [comment]
Just don't forget to program in negative player modifiers into your script.
Eating humans should come at some cost.

**Comment by Dienark7** [comment]
Will probably be something along the lines of a 1500 humanity hit and if you eat an infected human you are guaranteed infection if eaten raw, not sure if the same should apply to cooked meat though.

**Comment by KPanicEKS** [comment]
1500 per "steak"?

Also if the player is infected with sepsis that should carry over
regardless if cooked or not. Tainted meat is tainted meat.

**Comment by Dienark7** [comment]
1500 When the player hits the "Gut Human" scroll option, do you think it should be more? I want it to be a big humanity hit but not so ridiculous that it would stop an almost dying hero to eat a corpse they might find for instance.

And yeah you are probably right, the infection should go through cooked meat, I mean this isn't just any regular infection after all. 

Alternatively 800 for gutting, and something like 400 per chunk of meat.

**Comment by bchawke** [comment]
Cannibalism seems like an interesting thing to add if done right, but the hunger system isn't nearly as hard as you're describing.  If you eat a can here and there and kill animals when you see them it's fairly easy to stay nourished.  What you're describing sounds like the result of everyone in your group neglecting the hunger meter until it's blinking and you're losing blood, THEN trying to eat your way back to health.  That is an uphill battle.  It you plan ahead more it's not nearly as difficult as you describe.

**Comment by Dienark7** [comment]
Trust me @bchawke all of us recognized the significance of hunger in DayZ's current form and are not neglecting it at all, its a case of if the server is high populated and people are killing the animals at a fast rate and the canned food in markets really doesn't keep you on your feet long.

**Comment by Lukethero** [comment]
@Dienark7 I agree with BC, food is not all that hard. I am not opposed to canibalism, probably should come withsome downsides, I was just saying it is not all that necessary, but all power to you for more features.

**Comment by bchawke** [comment]
@Dienark7 I play on the most populated vanilla server in the US.  It's not as hard as you're describing.  You and your group need to adapt and learn how to cope like everyone else.  The group I play with runs into a hunger issue from time to time but we're always able to solve it with some hunting and looting, and we have _plenty_ of time to engage in PvP, find vehicles, repair choppers, raid bases, etc.  You may be passing up too many loot spots.  People tend to forget that canned food and other items spawn on front porches of houses, by dog houses, outhouses, under awnings, etc.  The market isn't the only place to find food.  If you stop in every town and eat a can of food or two, and kill an animal whenever you see one and hang onto the meat, you'll have very few problems staying nourished.  Honestly you should edit the title of the thread to just "Suggestion: Cannibalism" as hunger is not an issue.

**Comment by ghost** [comment]
This. Best method of coping with hunger is hunting. Chop some cows and you´re done.

**Comment by Dienark7** [comment]
@bchawke Seen as this is my thread ill keep the title as it is thanks.

**Comment by KPanicEKS** [comment]
Lol @sven, take a chill pill man, Bchawke raises some very valid points and
just because this is "your" thread doesn't mean he can't make a suggestion
that you change the title. SMG...

Also, if cannibalism is added there should be a negative attribute applied
when the player eats the meat as well. Otherwise squads will just have the
bandits do the dirty work of gutting the "meat".

**Comment by Dienark7** [comment]
@M0tzilla I think you raise a valid point with the meat consumption, it will mean I need to create another script for the button when people consume it but I can just make it the same as the current one I guess with the humanity change. 

And for the record i'm perfectly calm, just not very appreciative of someone telling me to change the title of my thread because they don't think something is a problem, well that's wonderful that he thinks its fine, but I wouldn't go into his threads and say "nah that's not what I think, change the title to this".

Any who, thanks for the suggestion m0tzilla.

**Comment by ericandersen** [comment]
I prefer hunting and scavenging to survive. 

This additional in my opinion would not be a beneficial one.

**Comment by Lukethero** [comment]
@sven The point of github is to put it in a sommunity enviornment and for people to fix and or suggest fixes. That being said, the title BC suggested is more descriptive to what the purpose is and would make it easier for people to find and reference in the future.

**Comment by Dienark7** [comment]
@Lukethero The title is representing the reason I have suggested cannibalism, or alternatively to bring attention to the rather large consumption rate required to survive. Seen as my post references both cannibalism and the consumption rate required it would be weird for me to remove/change the title.

I shan't talk about this any further as this is getting really stupid and their is clearly a difference is opinions, and that's wonderful but the way you are attempting to get it across is not constructive.

**Comment by R4Z0R49** [comment]
[Updated] - Food consumption rate has been slowed down to give a better balance.

I'll see how this plays out in the next dev build and go from there see how the tinned food look
