### ISSUE TITLE
Dayz mod crashes Allocator: F:\Steam_games\steamapps\common\Arma 2 Operation Arrowhead\dll\tbb4malloc_bi.dll and Fault address:  77D1AE33 01:0002AE33 C:\Windows\SysWOW64\ntdll.dll

### ISSUE THREAD

**Issue by hekut146** [DayZMod/DayZ#411]
when i start server and whe 1-5 min remadind server crashes and i see this error when i start default arma 2 oa missions

**Comment by R4Z0R49** [comment]
You need to add the 
tbb.dll
tbbmalloc.dll
DatabasePostgre.dll
DatabaseMySql.dll
in your root arma 2 OA folder.

**Comment by hekut146** [comment]
i have this files, if i don't drop this files server don't start and this files need in \Arma 2 Operation Arrowhead\ but error write \Arma 2 Operation Arrowhead\dll\ no tbbmalloc.dll error write is tbb4malloc_bi.dll
