### ISSUE TITLE
Please help, don't work procedures in mysql in ubuntu, server install windows 7

### ISSUE THREAD

**Issue by hekut146** [DayZMod/DayZ#413]
When i use pMain procedure in phpmyadmin with:
qualifier - root@127.0.0.1
name - i 
type- int
function null
value null

See:
SET @p0 =  '';

CALL `pMain` (
@p0
);

Result:
null

Please help

**Comment by hekut146** [comment]
why closed?

**Comment by R4Z0R49** [comment]
ubuntu is not supported as i've already said you will need to find a linux admin and look over what needs to change for linux. I have no access to a linux system to even check

**Comment by hekut146** [comment]
mysql ubuntu = mysql windows
procedure use mysql, there is no difference on what system use procedure

**Comment by hekut146** [comment]
and i istall now mysql windows and vehicle no spawn too

**Comment by ghost** [comment]
Have you provided the correct instance id for the procedure to call?

**Comment by hekut146** [comment]
qualifier - root@127.0.0.1
name - i 
type- int
function null
value null

i know is id 1337, but don't know how to white in procedure and where..

**Comment by hekut146** [comment]
now i install db 1.8 in 1.8.4.1 and procedures in 1.8 work in 1.8.4.1 but default intranse is 1 when i rewrite in db i see vehicles in game

**Comment by ghost** [comment]
that´s what I do, when I set up a new server... change the instance id in the init.sqf to whatever I desire (mostly to "1"). You have to set the instance ID in the DB accordingly. Then you call the pMain with the value of the instance ID. Bam. Done. Check your object_data table. If it is populated with items (vehicles that is), you´re ready to go.

**Comment by hekut146** [comment]
if i use 1.8.4.1 procedure she (procedure) don't add vehicles in object_data..

**Comment by hekut146** [comment]
dayzjarhead you have skype or teamviewer? you could not see what I'm doing wrong?

**Comment by ghost** [comment]
This is basicly MySQL one on one... the pMain procedure will only touch DB entries with the correct instance value, which you provide in as value when calling pMain.

On my Windows console it looks like this...

c:\mysql\mysql.exe --user=XXX --password=XXX --host=127.0.0.1 --port=3306 --database=dayz_vanilla --execute="call pMain(1)"

**Comment by hekut146** [comment]
if i use in windows mysql i see dublicate error but object_data in empty in ubuntu i see null resultat if i use procedure

**Comment by hekut146** [comment]
sorry in windows mysql in db 1.8 procedure work but 1.8.4.1 in windows and ubuntu don't work

**Comment by hekut146** [comment]
please help

**Comment by ghost** [comment]
Sorry, I´m super busy at the moment...

You can jump on my TS on Thursday night... www.dayzjarhead.de

When I´m there, my name is taikonaut.

**Comment by hekut146** [comment]
ok thx can i write if i very bad speak english?

**Comment by ghost** [comment]
yeah sure... english, german... whatever.

**Comment by hekut146** [comment]
I think I understand the problem the problem is case-sensitive, corrected procedures now throws an error:
duplicate entry '2' for key 'primary'

**Comment by ghost** [comment]
Then you seem to have an inconsistency in your datebase. This should not happen with a fresh setup. (and it should not happen with a running system either)

**Comment by kichilron** [comment]
Do you have any knowledge of MySQL whatsoever?

If not, that is the issue here. It is not recommended trying to work with it if you have no knowledge anyway.

**Comment by hekut146** [comment]
Very low

**Comment by hekut146** [comment]
now when i use pMain dead people delete in Character_DATA and going to Character_DEAD vehicles don't spawn

**Comment by hekut146** [comment]
need i set MapID valve in Object_SPAWNS table?

**Comment by kichilron** [comment]
Seeijg as you seem to have more issues with SQL than DayZ I suggest you take this to a Forum (forums.dayzgame.com) or talk to Jarhead in detail. 

This is nothing that works over GitHub.
