### ISSUE TITLE
"Drag body" when a player is unconscious results in a non-playable state.

### ISSUE THREAD

**Issue by vinyljunkie** [DayZMod/DayZ#414]
Hey.

If a player becomes unconscious and another player drags his body, the unconscious player ends up in a non-playable state when the unconscious timer runs out. Some actions can still be done like switching weapons but it shows no animation. It seems to work to hurt the player and bandage them to make them come out of the un-playable state. Another player reported they managed to pitch a tent they had in inventory and select the rest option and then stop resting to get out of it.

1.8.4.1

**Comment by Lukethero** [comment]
Confirmed, I think I have a friend with video proof if needed.

**Comment by bchawke** [comment]
Agreed.  We tranq darted a player a couple weeks ago, and tried to drag him.  He was stuck in that position and couldn't get up.  We came back to him several minutes later with a vehicle.  He was able to enter the vehicle when we pulled up next to him.  It reset his status and he was able to exit the vehicle and continue on.  I can provide video if needed.

**Comment by R4Z0R49** [comment]
Ok ASfox will look into this one see if he can see whats going on.
