### ISSUE TITLE
New 1.8.5 link not working

### ISSUE THREAD

**Issue by linkstril** [DayZMod/DayZ#419]
When I click the full client download it takes me to a page not found. Hospital PVP Serer

**Comment by CoftSock** [comment]
You can get it off steam also

**Comment by linkstril** [comment]
Where would I do that?

**Comment by linkstril** [comment]
Like where on steam.

**Comment by R4Z0R49** [comment]
in steam just search dayzMod

**Comment by R4Z0R49** [comment]
The links seems to be working ok for me

**Comment by linkstril** [comment]
It says "you are running the incorrect version of DayZ please reinstall and try again"

**Comment by linkstril** [comment]
Any suggestions?

**Comment by R4Z0R49** [comment]
What server are you trying to connect too?

**Comment by linkstril** [comment]
Its fixed. But thank you!
