### ISSUE TITLE
Waiting for character to create.

### ISSUE THREAD

**Issue by tim1256** [DayZMod/DayZ#42]
First login works fine. If I abort and log back in I either get stuck on Waiting for character to create or I spawn in debug. If I then kill my own character in the database I can log back in again.

The server is running at DayZ.st on 1.7.7.1

Error's I have in RPT file:

18:44:12 Error in expression <layerObj getVariable["combattimeout",0] - time;
diag_log format["Player UID#%1 C>
18:44:12   Error position: <- time;
diag_log format["Player UID#%1 C>
18:44:12   Error Generic error in expression
18:44:12 File z\addons\dayz_server\compile\server_onPlayerDisconnect.sqf, line 21
18:44:12 Error in expression <layerObj getVariable["combattimeout",0] - time;
diag_log format["Player UID#%1 C>
18:44:12   Error position: <- time;
diag_log format["Player UID#%1 C>
18:44:12   Error Generic error in expression
18:44:12 File z\addons\dayz_server\compile\server_onPlayerDisconnect.sqf, line 21
18:44:12 Client: Remote object 4:14 not found
18:44:12 Client: Remote object 8:0 not found

**Comment by R4Z0R49** [comment]
server_onPlayerDisconnect.sqf, We are already aware of this and it has been fixed for the next patch

**Comment by tim1256** [comment]
Thanks for the response I really aprreciate the time you are puting into this mod.

But the fact my players can't login after they logout once because they get stuck on Waiting for character to create is a known bug? And there is nothing I can do untill you release the next update?

And for some reason relogging sometimes duplicates your character.
