### ISSUE TITLE
Hatchet break chance too high perhaps

### ISSUE THREAD

**Issue by CoftSock** [DayZMod/DayZ#421]
Currently its at a 40% chance and if we are looking at some sort of realism in the chance of a hatchet breaking whilst chopping a tree it would be slim. maybe change to a 30% chance of it breaking? if youre worried about to much wood being harvested for bases perhaps then make Hatchet spawns rarer?

**Comment by R4Z0R49** [comment]
if im not mistaken 0.04 is 4% not

0.01 = 1%
0.05 = 5%
0.10 = 10%
0.50 = 50%
1.00 = 100%

but let me check that system when i get home

**Comment by CoftSock** [comment]
if ([0.04] call fn_chance) then {
      _breaking = true;

i get where youre saying 0.04 is 4% and so forward. but its definitely a 40% chance of breaking, does get frustrating

**Comment by kichilron** [comment]
Can you specify how 0.04 is indeed 40% and not 4% - other than your subjective feeling?

**Comment by R4Z0R49** [comment]
Its 4% per attempt as i explained above. 

you can even check out the code used using the below link :-)

https://github.com/DayZMod/DayZ/blob/Stable/SQF/dayz_code/actions/player_chopWood.sqf#L108

However i might change this to be a flat 4% every time you right click the axe to chopwood.

**Comment by Detoeni** [comment]
the last base i built on the test server had about 10 fence panels took about 6 hatchets to get all the wood needed which imho was not too bad. Similar size bases I've built before had used more hatchets (about ten or so) but given the volume of timber, even that did not seem too unreasonable.

**Comment by CoftSock** [comment]
isnt it the same as Loot ie 0.01 is a 10% chance so 0.04 is 40% there is no way that hatchets are currently at a 4% chance of breaking. Hard to believe some loot has a 1% chance of spawning if 0.01 is 1%

**Comment by R4Z0R49** [comment]
You can see the scripts its just simple maths take a look yourself.

**Comment by kichilron** [comment]
This isn't a competition, but the code speaks for itself.

I was merely interested in whether you did some tests to confirm or not, so that we could potentially fix it. 0.01 = 1% is elementary school maths, really.

**Comment by CoftSock** [comment]
i understand the maths but its just that i must have to be the most unluckiest person for my hatchets to break like crazy if it really is 4%
 ill even make a video

**Comment by R4Z0R49** [comment]
Ill take a look later today it should be 4% that don't mean we don't have an error some place. I'll take a look to see.

**Comment by R4Z0R49** [comment]
ok just had a quick look and got another dev to verify and it is indeed 4%

(floor(0.04 \* 100) > floor(random 100))

Random 100 < 4 or 4 > Random 100 Should give the exact same true/false result.
