### ISSUE TITLE
foundation disassembly

### ISSUE THREAD

**Issue by Jbird206** [DayZMod/DayZ#423]
sometimes during disassembly, fence will completely disassemble, leaving foundation. foundation disassemble sometimes fails and upon retrying, says Foundation already disassembling"

**Comment by R4Z0R49** [comment]
The only time i think this can happen is if the player starts moving before the end. But ill take a look soon as i get 5

**Comment by CoftSock** [comment]
happened to me the way i got it to fully dissemble is to upgrade it one level then go disassemble and it works

**Comment by R4Z0R49** [comment]
Closed wrong one

**Comment by R4Z0R49** [comment]
I need to get a little more info on this the object looks like its working as it should for me.

**Comment by thcNox** [comment]
This has happened to me several times even though I've taken great care not to move. Upgrading once and then disassemble again is a nice workaround. Noticed that it has never happened to a foundation that I had put up in the same session.
