### ISSUE TITLE
Self Bloodbag script interfering with gate locking function.

### ISSUE THREAD

**Issue by Jbird206** [DayZMod/DayZ#424]
perhaps you have less than a concern towards scripts when it comes to the mod. But we are having issue with this on our dayz (original)mod server. To me, it appears as if this outdated script is interfering with the action menu. The self-BB script also conjures up the drink option bug of ?1.8.3. Any insight would be appreciated.

**Comment by R4Z0R49** [comment]
1.8.3 is outdated so no idea sorry.
