### ISSUE TITLE
vehicle spawn location - vehicle stuck

### ISSUE THREAD

**Issue by Detoeni** [DayZMod/DayZ#425]
the old hatchback spawn at 019 061 is now spawning a uaz. Uaz is taller than hatchback and is getting stuck on the buildings collision mesh and cant be moved from under the porch at the side of building
Issue seen on the server running the new vehicle setup:
http://www.gametracker.com/server_info/108.174.57.161:2302/

**Comment by AsFoxy** [comment]
I'm unable to reproduce that. I'm able to drive a UAZ under it just fine. If it happens again please take a screenshot or a video and post it here.

**Comment by R4Z0R49** [comment]
Yea seen a few new locations with bouncing vehicles. I'll update when i can

**Comment by Detoeni** [comment]
Just run across this again with the suv, which is in its normal spawn. In both cases one wheel was 95% condition, while the others were much less damaged, but still red. I'm wondering if that even though the wheel model is still shown, weather the game thinks its in a state that is broken- hence the vehicle cant be moved.

With both the uaz and suv there was no noticeable bouncing which I have seen before.

**Comment by R4Z0R49** [comment]
Nothing is wrong with the numbers 95% is flat anything over 85% is damage and unusable

**Comment by AsFoxy** [comment]
So in fact there is no problem with the the vehicles being stuck but instead they just spawned in unusable condition?

**Comment by Detoeni** [comment]
yep. although I think folks may get confused as this is quite different from the old behaviour where a wheel vanished once it was un-useable. 
Any chance that a text message could be shown if vehicle is tried to be moved with a wheel in this state along the lines of "you have a flat tyre"?

**Comment by R4Z0R49** [comment]
foxy, seems like this is nothing more then understanding the damage values. However there are a few vehicles that bounce ill try getting some photos next time im playing see if i can track the issue down.

Detoeni, The hud for the vehicle should show red this is bad and needs to be fixed.

**Comment by Detoeni** [comment]
no worries, if you can do that, it would be a lot better.

**Comment by R4Z0R49** [comment]
It should already be done look at the repair menu it should be red or look at the top left while in a vehicle it should give a general idea how bad the vehicle is.

**Comment by Detoeni** [comment]
top left is not a good guide as it shows the average for all wheels. 
The repair menu is showing red for both working and flat wheels on the vehicles I've looked at so far. let me go grab some screenies.....

**Comment by R4Z0R49** [comment]
Yea the repair menu is your best gauge anything over 85% is bad nothing changed on that its always been the same.

The average for all wheels should still be pretty readable.

~The best gauge you can have is get in and try to drive does nothing or starts to spin the wheel is knackered look at the repair menu,

**Comment by Detoeni** [comment]
no problem, I just don't remember ever seeing a wheel model attached to a car when it could not be used.

**Comment by R4Z0R49** [comment]
I like the system but we still have a long way to go with it.

The fact the wheels still show but are flat seems a much nicer touch also when you salvage you see the wheel removed fully.

Like a say its experimental just now so we still have bugs
