### ISSUE TITLE
Exit vehicle near base wall message popping up for everyone

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#426]
We were playing on 434 yesterday and the message that tells you that you cannot exit a vehicle near a base wall popped up on all of our screens at the same time.  I'm assuming someone on the server was attempting this and it sent the message to all the clients instead of just him.  Popped up twice within a minute or two for everyone I was playing with.

**Comment by R4Z0R49** [comment]
Hum its just a normal cuttext system its not a global command. The only item i can think of is the event handler is running for everyone in the vehicle.

I'll look into it.

**Comment by HeroSmurf** [comment]
Video link of the bug 
https://youtu.be/xkUroKAQIHQ

Just like Bullet (BC) says
Not necessary to watch other than to confirm we weren't interacting/getting out of/near any vehicles. 

We were spread out.

**Comment by R4Z0R49** [comment]
Yea i think you missed the point. Have you all been in that vehicle? within that session CutText is not a global command it only runs for the one player. So im thinking at some point in your session everyone got into the same vehicle activating the antiwall system. Hence the reason it poped up for everyone.

**Comment by R4Z0R49** [comment]
All i need to know is if you all entered the same vehicle at some point ?

**Comment by KPanicEKS** [comment]
When I received this message I had not entered a vehicle at all during that
session. The message popped up randomly it seemed a couple times spread out
over 10 minutes.

**Comment by R4Z0R49** [comment]
Hum thats even more wired that eventhandler should only work when you enter a vehicle.

**Comment by HeroSmurf** [comment]
Same for me ; When I received this message I had not entered a vehicle at all during that
session.

**Comment by thcNox** [comment]
We had this happen yesterday on Dayz Europa, Everyone on teamspeak reported they saw the message and I believe most of them had not used a vehicle.

**Comment by R4Z0R49** [comment]
yea rgr im looking into the issue

**Comment by R4Z0R49** [comment]
yea im a dumbass this is fixed silly mistake
