### ISSUE TITLE
Suggestion: make player actions abortable

### ISSUE THREAD

**Issue by VidKo** [DayZMod/DayZ#428]
Suggestion: make actions for cooking, chopping wood, gutting animals abortable, the same as bandaging.

**Comment by R4Z0R49** [comment]
They should all already have an interrupt system. I'll check next time im ingame.

**Comment by R4Z0R49** [comment]
Cooking = a single animation the more raw meat you carry the more your locked into the animations.
Wood Cutting = Has an interrupt system just hold any movement key. Soon as the animation is finished you should break the loop.
Gutting = Is a single animation being run so no interrupt is possible.

We could start breaking into the middle of animations but for whats its worth i think we handle them well as they are.

Thanks
