### ISSUE TITLE
Players stuck on creating character/aborting and coming back and body is duped.

### ISSUE THREAD

**Issue by AVendettaForYou** [DayZMod/DayZ#43]
Since the update to 1.7.7.1 alot of the player base on my server are having issues with being stuck on creating character including myself, it will stay on that until the timer hits 30 then go to a black screen then will be stuck in debug. To solve this we had to completely delete all profile and survivor unique_id's as well as anything tied to that players ID in the Database. The issue after we did that is they would abort and come back in and a duplicated body would be in place of where that person logged out. I have had the issue myself and have reproduced it multiple times.

**Comment by tim1256** [comment]
Exactly the same problem! Thought it was just me.

**Comment by thevisad** [comment]
Question, are you guys just using dayzmod or using Reality/another mod pack?

**Comment by AVendettaForYou** [comment]
Dayz.ST and using DZC to join

**Comment by thevisad** [comment]
Yes but is it Reality or Vanilla DayZMod?

**Comment by thevisad** [comment]
#42

**Comment by AVendettaForYou** [comment]
#42 is the issue we're having but with duping bodies when aborting and coming back in. and the database shows as bliss.

**Comment by thevisad** [comment]
https://github.com/thevisad/DayZ-Private-master/issues/233
https://github.com/thevisad/DayZ-Private-master/issues/236

**Comment by thevisad** [comment]
FYI Reality is the new name for Bliss, they still use the old database name, but are now using Reality base.

**Comment by tim1256** [comment]
AVendettaForYou anychance you are using the BlurGaming Anti-Hack?

**Comment by AVendettaForYou** [comment]
Hangender's which is the same

**Comment by tim1256** [comment]
Could you add me on skype: timhoeve
I think I figured out what the problem is. Or atleast part.
