### ISSUE TITLE
Are there any 3d artists for some more zed models?

### ISSUE THREAD

**Issue by ghost** [DayZMod/DayZ#430]
Hello!
First of all a huge thanks to @R4Z0R49 for your awesome work so far! 

After playing the mod for years I'm really tired of the old zombie skins - they are awesome but...not enough, so maybe we could ask some 3d artists to design some new ones. I'm sure there are some people in the Bohemia Interactive forums or on reddit who could to this job if we would give them some templates.

Regards from Germany

**Comment by R4Z0R49** [comment]
If we get new skins we can add them. Pretty simple :-)

**Comment by thcNox** [comment]
I could maybe have a go at making a new skin or two provided someone can point me towards somewhere I can get my hands on the existing zombie models and skin textures

**Comment by AsFoxy** [comment]
https://community.bistudio.com/wiki/Arma_2_Sample_Models A2SM_Data_APL for models.
https://github.com/DayZMod/DayZ/tree/Development/SQF/dayz/textures for textures.

**Comment by thcNox** [comment]
Thank you Foxy, I'll have a look at those!
