### ISSUE TITLE
Suggestion: Add wells to Elektro

### ISSUE THREAD

**Issue by thcNox** [DayZMod/DayZ#432]
Would it be possible to add a well or two to the Elektro area? The city it self has none atm while a town like Berezino has something like 10 wells in it.

**Comment by CoftSock** [comment]
there is one well just west of the fuel station :)
but heres one i just did if needed
[sqf file here](https://github.com/CoftSock/DayZ-Mod-Additions/blob/master/SmallMapAddons/ElektroWell)
 http://s14.postimg.org/p3kv5sm8v/well_Loc.png

**Comment by KPanicEKS** [comment]
I agree. It would be nice to have one in town also. Standalone has one just
west of the church behind one of the row houses perpendicular to the fire
station.

**Comment by R4Z0R49** [comment]
being looked at atm.
