### ISSUE TITLE
Cooking pot and frying pan to cook things

### ISSUE THREAD

**Issue by ghost** [DayZMod/DayZ#433]
Just two simple items which are required to cook meat and to boil water. 

There is a least a bowl available: Land_Bowl_EP1, http://www.armatechsquad.com/ArmA2Class151656165165341654165165165165f/OA/Objects/smallobj/

**Comment by KPanicEKS** [comment]
-1. We already have a tin can for water boiling and you certainly don't
need a frying pan to cook meat over a fire in real life.

**Comment by thcNox** [comment]
What M0tzilla said, I think there's a danger of over saturating the loot tables with stuff like this. I don't see myself wasting precious inventory space carrying around a cooking pot when I can just pick up a tin can anywhere.

**Comment by ghost** [comment]
Oh, I havent known that a tin can is required for boiling and cooking. Sorry, my fault!
