### ISSUE TITLE
Lock System (WIP)

### ISSUE THREAD

**Issue by R4Z0R49** [DayZMod/DayZ#434]
https://www.youtube.com/watch?v=shei3zCnTYY

**Comment by CoftSock** [comment]
epoch

**Comment by kichilron** [comment]
Very helpful and insightful comment.

**Comment by CoftSock** [comment]
no worries

**Comment by KPanicEKS** [comment]
Looking good guys. Nice UI but I bet some people aren't going to understand
how to open it once the code has been entered. It makes sense to me to pull
on the latch, but then again there are lots of idiots that play dayz so who
knows... One thing that might help is adding a stamped up arrow onto the
latch part where they are suppose to click. Just something there showing
that you can interact with the lock.  That or simply add a button below it
that says pull or something to that affect.

Again, awesome work.

**Comment by HeroSmurf** [comment]
Beautiful. 

suggestion: 
Reverse the drag behavior. 

   9 [8] 7

Drag left to right -> should result in 0 [9] 8

   9 [8] 7

Drag right to left <-  should result in 8 [7] 6

**Comment by R4Z0R49** [comment]
I've tried to make this so no player every stores the access code.

When you unlock a fence the request is sent to the server and the server will respond with true/false depending if the guess was correct or incorrect This is logged to the server so admins can see the attempts. This goes for setting the lock code its sent to the server and the server makes sure the owner of the gate is the only person to be setting the gate.

When you make an incorrect guess the last used code will be remembered on the lock.

My concern with this is how it will handle under load but i guess time will tell.

**Comment by R4Z0R49** [comment]
@M0tzilla, They will learn :-)
