### ISSUE TITLE
1.8.5 glitchy zombie attacks

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#439]
Since 1.8.5 has released, zombies act very strangely in close proximity.  They often run a meter or so past me, swatting at thin air, then turn, swat again, often missing me 3 or 4 times before landing a blow.  Sometimes I stand there for 10 seconds or so while the zombie wiggs out flailing before he does any damage.  The turning and rapid movements during this also makes it very hard to get melee hits on them.  Does this have something to do with this item in the changelog?:

[Updated] - Zed Animations have been moved back to a smooth animation transition from an instant move.

I can upload a video if need be but it will be a day or two before I'll be back at my computer to upload it.

**Comment by R4Z0R49** [comment]
nar dont worry about the video

**Comment by R4Z0R49** [comment]
Answered on the forums.
