### ISSUE TITLE
1.8.5 possible memory leak from bases

### ISSUE THREAD

**Issue by thcNox** [DayZMod/DayZ#446]
So lately I've been spending a lot of time around my base and building  and noticed that after 5-15min it takes longer and longer time to perform actions, such as hatching wood, build walls etc. Starts out with a  2-3 seconds of delay before your characters starts to perform the actions and eventually it will just be impossible to perform any actions forcing a restart.

 This has puzzled me for a couple of days and didn't make the connection to bases until a fellow player said he had the same issues but only when he spent time in his base. Whatever this is it only affects player "actions" there's no noticeable decrease in FPS, or increased bullet delay.

Would love to have some help with this since I do not possess the skill set required to debug it much further on my own, thanks in advance

**Comment by AsFoxy** [comment]
Sounds like scripts running in the scheduled environment that never finish.

**Comment by R4Z0R49** [comment]
You I'm not sure on this issue yet bases have no running scripts. All I can think off is one I the eventhandles are being triggered.

Ill strip the server monitor at the weekend see what I can find out

**Comment by thcNox** [comment]
I forgot to mention that it's that issue seem to get worse the higher your server population is

**Comment by R4Z0R49** [comment]
Yea its all connected. The question is whats causing the issue.

**Comment by Lukethero** [comment]
Yeah noticed this too, would take forever for me to get into the car and for gates to open and close. This might be a helpful bit of info, when it was not responding with the cars and gates, it appeared to other players that the door was closed or that I was in the car. I also realized that this was happening at 1000-2000m away atleast. Not sure if it is a server wide thing or proximity based.

**Comment by thcNox** [comment]
Today I have been playing without the J.S.R.S soundmod which I have been using for the past year. I was able to play 3-4 hours on a full server mostly building in my base without running into these issues with slow actions. 

I remember checking my memory usage when I had the issue and it was at 1.6 GB's while I had around 1.1-1.2 GB's after having just logged in. With J.S.R.S deactivated I logged in with 900 MB so seems it takes roughly 300MB's to run the sound mod. After having logged in and working on my base memory slowly got higher over the next 3 hours until restart and peaked at about 1.350 GB's 

Zikk however reported he had the slow action problem (with sound mod activated) already at about 1.150 GB's but he also started a bit lower at 700MB's.

I'm not sure how the sound mod is affecting this issue but it seems for me that it has practically removed the problem of having to relog every 15 min. I will continue poking around though.

**Comment by R4Z0R49** [comment]
I tested today with a few other admins I was not able to reproduce the issue we have a 10 fence system I sat there for 20/30mins with no change to my actions. I'll keep looking into this see if we can find out what's at fault

**Comment by R4Z0R49** [comment]
I'm going to try and change the base class fences are assigned and see if that has any effect for you guys. However I need an exact way to reproduce the issue everytime so we can test it.

**Comment by CoftSock** [comment]
R4Z0R49 when you tested it how many players where on the server at current and earlier?

**Comment by R4Z0R49** [comment]
There.issue isn't related to players not after 15 mins anyway. We do suffer a delay as time goes on over the 3 hours. But having this issue after 15 mins Somthing else is wrong and with fps still being 60 for the player.

**Comment by thcNox** [comment]
These issues did not appear for me when the server was nearly empty (<10)

**Comment by R4Z0R49** [comment]
there's conflicting info on this. 
1. Delayed actions over a period of time (known issue)
2. Delayed actions when stood in bases for 15/20 mins (jsrs enabled, disabled no issue)

We need to know exactly what ppl are talking about.

**Comment by AsFoxy** [comment]
From what i hear it's actually JSRS causing the problems, though bases might exacerbate it.

**Comment by thcNox** [comment]
I've played some more today without jsrs and still no problem, and this after having the issues for weeks. I'll activate jsrs again see if it occurs again. If it does I'll also play a session or two away from any base with the sound mod activated

**Comment by Lukethero** [comment]
I can confirm that this is not due to JSRS. The previously stated issues occurred and I do not, nor ever have had, JSRS.

**Comment by R4Z0R49** [comment]
so two issues conflicting with whats being said :-(

thcNox, I've played some more today without jsrs and still no problem
Luke, I can confirm that this is not due to JSRS.

**Comment by R4Z0R49** [comment]
So rather this is two different issues or something else is going on. No more base systems can be added until this is resolved.

**Comment by thcNox** [comment]
So after having played lagfree without jsrs for two days I activated the mod again and the problems appeared again, after 2 hours of playing I couldn't chop wood anymore. I will now go north and away from any bases and play for another 2 hours with sound mod activated to see what kind of results I get

Started getting slow at around 1.5 GB's memory and at close to 1.6 GB's actions are near impossible to carry out, they will take a minute to complete or more. JSRS only involvement in this for me might be that it helps push my memory to that critical point. But yeah this is just pure guessing from someone who's not particularly technically minded

**Comment by thcNox** [comment]
So another hour just running around way north of the map not  close to anything but running around the woods, stopping to chop one wood every 15 min to check action responsiveness. After 1 hour the lags were back just as strong as when I was in  my base.  My memory usage was around 1 GB after an hour with the sound mod activated.

**Comment by AsFoxy** [comment]
Was that with or without JSRS?

**Comment by thcNox** [comment]
With

**Comment by R4Z0R49** [comment]
ok so we have been able to recreate this issue with jsrs running every time. We are still trying to get exact details on the cause
