### ISSUE TITLE
1.8.5 trouble accessing dead bodies

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#447]
In the past getting access to a dead player's gear has been tricky at times (especially with the weapon on their back ending up on the ground next to them), and up until now it was usually just a matter of patience looking at different spots and even zooming in just right to gain access.  However, in this patch, I often cannot access a dead player's gear at all.  Logging out and right back in fixes it every time, though.  This made for a bummer of a moment the other night when my teammate got killed a couple minutes before server restart.  I killed his attacker and ran to my buddy's body to get his NVGs out of his inventory, but I could not for the life of me access his gear.  434 locks the server a few minutes before restart so there was no way for me to relog.  RIP NVGs.

**Comment by AsFoxy** [comment]
The carried weapon will go to the body inventory again in the next patch so hopefully that will help in the future.

**Comment by R4Z0R49** [comment]
This isnt a new problem action systems have always been spotty. when we rewrite everything we will look at this.

**Comment by bchawke** [comment]
I hear you.  The reason I posted is because something has made it _MORE_ of a problem than it used to be.  I used to be able to prone/roll/zoom/fidget and eventually get the gear icon and be able to loot, but now I often cannot loot a player at ALL, but it is instantly fixed when I relog.  Thanks for looking into it.
