### ISSUE TITLE
Feature request: slightly shorter day/night cycles

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#448]
Let me start by saying that I'm the FIRST person to say that I absolutely love that DayZ mod exists in a realtime persistent world.  It's one of my favorite aspects of the game.  However, while real time made sense back when 2 million people were playing and there was a few thousand servers of varying timezones on the public hive, things have changed.  A number of people are trying out vanilla mod for the first time on one of the few remaining populated servers, but many express frustration that it's always night for them or always daytime for them because they have a certain window of time to play each day or on the weekends.

A good solution to this that was proposed on Reddit for SA a long while back was to change a full day/night cycle to 19.5 hours instead of 24.  This would still stay true to the harsh real time nature of the game, but allow players to experience a variety of lighting conditions in the mod even if they have a very narrow window of time which they can play the game.  It would be nice if this were a part of the official mod and not just a custom setting by a server, as little changes here and there take them further away from being "vanilla".

**Comment by R4Z0R49** [comment]
this would have a ton of problems ingame for players there's a good number of systems that work in effect with time.
