### ISSUE TITLE
Possible graphical glitch at NEAF

### ISSUE THREAD

**Issue by CCGMichael** [DayZMod/DayZ#451]
Been alerted to graphical glitch at NEAF. Will investigate further to try and find exact cause. Supposedly coming from barracks area: http://redi.me.uk/Pictures/zMm3ROl4.png

**Comment by VidKo** [comment]
someone probably set up a wire fence, as those are known to cause the graphical glitches. Check the server where the glitch was reported if there are any wire fences set up there.

**Comment by AggrOnline** [comment]
same thing happened to me in the tents area in cherno
