### ISSUE TITLE
Fog

### ISSUE THREAD

**Issue by JeeF147** [DayZMod/DayZ#454]
1) Fog

I don't mind a fog + rain that is so intense you can see only 10m in front of you. In fact I think it rather adds a lot of immersion and tension, adds to the gameplay.
However, the feeling lately is that 9 times out of 10 you log in, the fog is restricting your view to 300m or less.
Me and my team had the habit of always carrying a sniper as a secondary weapon, however this fog issue is so frequent that we've been leaving the snipers at the stash.

Suggestion: Make the fog as intense as you want, but set the frequency similar to real life. I'd say around 15-20% of the time is a good start, and we tune more from there.

**Comment by R4Z0R49** [comment]
fixed for the next build
