### ISSUE TITLE
Rate of spawn - 5.56 vs 7.62 weapons

### ISSUE THREAD

**Issue by JeeF147** [DayZMod/DayZ#455]
Seems a bit rare to be able to find AKs and M4s around, much more common to find better weapons. Should be the other way around, AKs and M4s all over the place, the eventual M14 in heli-crashes.

Also, AK magazines come once in every blue moon, mostly only spawns with the weapon.

Suggestion: Increase the spawn rate of small caliber rifles, add possibility of the random stanag/ak magazine in bars or zombies, even if half full, make large caliber weapons heli-crash sites ONLY. Replace the M14/DMR/MK48/M249 spawns from military with G36/M-Variants/AK-variants and other small caliberr rifles.

**Comment by Quackster** [comment]
I just found an AK74 magazine in a barn (the brown one that has a huge open space) so they're not that rare.

This was on my own server as well with just me online, so it wasn't dropped by someone else.

**Comment by R4Z0R49** [comment]
Loot system has been redone for 1.8.7
