### ISSUE TITLE
Weapon attachment suggestion: force animation for delay

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#458]
The new weapon attachments and weapons in 1.8.6 look FANTASTIC, but I fear how OP weapons will become when being able to instantaneously add attachments mid-gunfight.  You can carry an M14 with two scopes and very quickly have both at your fingertips while having plenty of room in your backpack.  A possible nerf to this would be to force an animation (say 15-20 seconds) for adding attachments.  Is it possible to code it so that an animation (say the tent building animation) is called up before the new weapon is made?  If so, a longer animation for attaching something something and a shorter animation for removing attachments would be fairly realistic.

**Comment by AsFoxy** [comment]
Switching between CCO and Holo doesn't seem too OP to me. I've been meaning to add an animation to it, though not one as long as you're suggesting.

**Comment by KPanicEKS** [comment]
After reviewing a few Youtube videos it appears that it takes about 5
seconds to remove a scope and about 5 to 10 seconds to attach one if the
rail system is already installed. Foxy, what sort of delay were you
thinking?

**Comment by AsFoxy** [comment]
It's using the same medic animation as most actions.

https://youtu.be/aSFujx_tSi4

**Comment by bchawke** [comment]
Cool, that looks great.  It's not the attachments I think are too OP, but I was worried that swapping them quickly without a delay would be OP, especially in the case of guns like the M14.
