### ISSUE TITLE
1.8.5 Gate security issue

### ISSUE THREAD

**Issue by thcNox** [DayZMod/DayZ#460]
So I've had a guy glitch through my gates a couple of times by running against it and have a zombie behind him that pushes him through when he gets hit. There's no holes or anything to either side of my gate so I think this should be possible at all gates. I temporarily  solved it by creating a lock with 2 gates so that he can glitch through the first one but not the second one since the zombies do not follow you through the first gate.

**Comment by R4Z0R49** [comment]
This is going to be one system I don't think we can do much with. But ill look into it

**Comment by AggrOnline** [comment]
Just a suggestion : would doubling up on gates and wall not help? or does the zombie follow in as well?
