### ISSUE TITLE
1.8.5 Getting out of vehicles/bikes

### ISSUE THREAD

**Issue by thcNox** [DayZMod/DayZ#461]
Had a lot of trouble with getting out of vehicles around bases. Not close to walls. Sometimes 30/40 meters away. It just puts you back in the vehicle. Sometimes can be countered if everyone but the driver gets out, driver goes into back seat and someone else enter as driver, the original driver can then get out and same goes for the new driver. 

Bikes seems particulay affected by this since if you try and get off the bike in a base you can get off it until you get something like 200m away from the base I found.

**Comment by R4Z0R49** [comment]
I'll look into it but I cant see the extreme ranges get me a video of this happening so I can try finding out what's going on. I've never seen this yet.

**Comment by thcNox** [comment]
I'll see what I can do about a video

**Comment by R4Z0R49** [comment]
Don't worry about this till the next patch in the current stable build there's an issue causing the script to run for everyone.
