### ISSUE TITLE
1.8.6 Dev-edde9c4-Full: SD weapons issues

### ISSUE THREAD

**Issue by connorkrohn** [DayZMod/DayZ#462]
Some of the SD weapons still cannot fire standard (supersonic) ammo:

eg. M4A1_SD_DZ can fire both sd ammo and standard.

however M4A1_CCO_SD_DZ can only fire sd ammo.

Tested with @HeroSmurf .

**Comment by R4Z0R49** [comment]
If you can get a full list we should be able to fix this before the next patch.

**Comment by connorkrohn** [comment]
Ok i'll try and get a full list asap

**Comment by connorkrohn** [comment]
Actually I stuffed up. All the _DZ silenced weapons work fine with both ammo types.

**Comment by thcNox** [comment]
On a somewhat related note, will The PDW SD be implemented ? one of my favorite guns from Epoch =)

**Comment by AsFoxy** [comment]
Not in 1.8.6.
