### ISSUE TITLE
1.8.6 Dev-edde9c4-Full: Tripwire grenade issue

### ISSUE THREAD

**Issue by connorkrohn** [DayZMod/DayZ#464]
Only tested with tripwire grenade:

Armed traps are inconsistent (can't really give more info because its so random) at being set off. Tested with multiple players and traps, sometimes traps could only be set off by one player or everyone but one player. If multiple traps are armed then they can only be set off in a certain order, but the order is different for every player.

Test with @HeroSmurf

**Comment by R4Z0R49** [comment]
In 1.8.2 the hole trap system got.messed up if i get time before the next patch ill try and get them redone.
