### ISSUE TITLE
Nailed baseball bat less effective than normal baseball bat

### ISSUE THREAD

**Issue by Konc** [DayZMod/DayZ#465]
Yesterday I was playing on a server and going to town with a baseball bat, one-shotting zombies. Then I decided to craft a nailed baseball bat and suddenly all zombies take three shots to kill.

Shouldn't it sort of be the other way around, that an "upgrade" to the bat would make it more effective as a weapon?

**Comment by R4Z0R49** [comment]
```
class Bat_Swing_Ammo : Melee {      
            hit = 1;
class BatNailed_Swing_Ammo : Melee {
    hit = 2;
```

They look different config wise. All melee weapons should kill zeds in one shot they only differ for real players

Been over the damage config and noticed "Fishing_Swing_Ammo","BatNailed_Swing_Ammo" have not been added to the melee weapon list.

**Comment by ericandersen** [comment]
The plural of anecdote is data.
