### ISSUE TITLE
1.8.6 Dev-edde9c4-Full: seeing very odd agro behaviour

### ISSUE THREAD

**Issue by Detoeni** [DayZMod/DayZ#466]
Was playing on Kichilrons test server http://www.gametracker.com/server_info/31.186.251.110:2312/ when I saw the following:
ran out of long barn at stary and agroed a z'. he ran off and hid up on tree tents...thought it was just random. running round the tents agroed another z who charged me. I waited until he stopped moving then I took two steps back expecting an attack but none followed and he did not move to follow, from that point on he did not move or react to me. 
switched to none sd ammo and fired into the ground at my feet, two z's agroed but nether could path to my location and stopped reacting once they got to there chosen destination. Fired some more near one (B) to see if I got a reaction and another z pathed to my location, I stepped back, again there was no attack but this time the z ambled off so I sprinted a few steps up to him, he agroed and ran off (A)
![2015-05-21_00002](https://cloud.githubusercontent.com/assets/8584071/7758271/5a4e3c5c-0000-11e5-8652-42a160d220a2.jpg)
I'll jump on again tomorrow and see if I can repro - LMK what info might be of use as this seems quite odd.

**Comment by HeroSmurf** [comment]
Yup; Vinyl had reported something similar 

[![ZombieBehavior](http://img.youtube.com/vi/EWyBgnXyQ8s/0.jpg)](http://www.youtube.com/watch?v=EWyBgnXyQ8s)

**Comment by R4Z0R49** [comment]
Yea this was my fault ignore it.
