### ISSUE TITLE
1.8.5 matchbox fails to drop to 5 count matchbox

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#467]
What is the % chance that a box of matches turns into a box of 5 matches?  I've been using one full box of matches for days now on US434 and have lit several fires but still have a full box of matches.  Am I just super lucky or is something off?  I've lost the sense of urgency to carry an extra box of matches to be able to stay warm and cook food.

**Comment by R4Z0R49** [comment]
12% I think it is.

**Comment by bchawke** [comment]
I know this is closed but I wanted to follow up.  I have yet for a full matchbox to turn into a box of 5 since 1.8.5 released.  either 12% is way too low or something is broken.  1.8.4 was really fun and challenging scavenging for matches to light fires to stay warm.  Perhaps a bit too challenging, but currently matches are way too plentiful.  Somewhere in the middle but closer to pre-1.8.5 would be great.

Thanks!
