### ISSUE TITLE
Why are Cabins not in the game currently?

### ISSUE THREAD

**Issue by CoftSock** [DayZMod/DayZ#469]
I know there's been alot of debate recently with base building and what not, but is it just a case of the crafting/creating files needing to be done? or are the models glitchy? because there are a difference between fortifications and places to have some downtime and i think cabins suit this game more than the 3 meter high walls do

**Comment by R4Z0R49** [comment]
We don't have the models + i cant see what cabins would bring.

**Comment by CoftSock** [comment]
they are sitting in the files?

**Comment by CoftSock** [comment]
Cabin1_stage1
Cabin1_stage1_ghost
Cabin1_stage2
Cabin1_stage3
Cabin1_stage4
Cabin1_stage5
Cabin2_stage3
Cabin2_stage4
Cabin2_stage5
Cabin3_stage3
Cabin3_stage4
Cabin3_stage5

**Comment by R4Z0R49** [comment]
Its a small workshop with a couple different colors.

**Comment by R4Z0R49** [comment]
The shanty house is a big building. Im not sure they would fit into the game at all the fences provide a survival settlement for groups there really to much work for 1 survivor to handle(that's the idea anyway). 

But im undecided hence the reason they have been left in

**Comment by KPanicEKS** [comment]
instead of the shanty's any chance we can discuss the camps and various
statges of camps. I don't remember the thread but remember seeing it and
though that conceptually it was a cool idea.

**Comment by R4Z0R49** [comment]
Open an issue and go for it

**Comment by R4Z0R49** [comment]
https://www.youtube.com/watch?v=UfHp1e49-Rs

Here they are.
