### ISSUE TITLE
Suggestion: Make tool belt items not take up weapon slots in in stashes/tents

### ISSUE THREAD

**Issue by thcNox** [DayZMod/DayZ#471]
Is this possible? It's seems silly to be unable to stash something like a compass or a box of matches due to no weapon slots available.

**Comment by CoftSock** [comment]
if there was a system to turn matches,watches, etools, compasses and maps into "magazines" temporarily and then be able to turn them back to "weapons" it should be for both storage and player gear

**Comment by R4Z0R49** [comment]
New engine is really the only way without wasting tons of resources.
