### ISSUE TITLE
1.8.6 Dev-edde9c4-Full: Herbal Tea recipe has no title in crafting menu

### ISSUE THREAD

**Issue by Detoeni** [DayZMod/DayZ#472]
as above

**Comment by CoftSock** [comment]
just did a pull request then, which should fix it

**Comment by KPanicEKS** [comment]
Not sure if this was mentioned yet, but since it's tea can we have it warm
you up a little also.

**Comment by CoftSock** [comment]
@M0tzilla itd be easy to implement but the drink could be sitting in a storage for 2 weeks which wouldn't be warm or hot. The reason a boiled water bottle was used in the crafting as this type gives no chance of infection. But i do see where you're coming from

**Comment by R4Z0R49** [comment]
Yea no hot or cold stuff we cant track it at all.
