### ISSUE TITLE
1.8.5: Exiting vehicles in/around your base not possible

### ISSUE THREAD

**Issue by VidKo** [DayZMod/DayZ#474]
There is a bug where you cannot exit a vehicle in or near your own base. You get teleported back into the vehicle. It can be 5m away from fences or even 30m. The message "cannot exit vehicles near buildables" does not come up.

Sometimes it helps to switch seats, or that another players sits in as a driver, but not always.

**Comment by R4Z0R49** [comment]
Yes this should have been addressed in the dev build just waiting for more info from ppl testing.

**Comment by VidKo** [comment]
Well, I think i'll have to start testing the dev builds as well :)

Thanks R4Z0R49 for all the good work!
