### ISSUE TITLE
1.8.5. - Pine trees bounding box shielding from shots

### ISSUE THREAD

**Issue by JeeF147** [DayZMod/DayZ#475]
"The bane of my f_cking life_ as someone just described it.

People are starting to realize that they can just sit on pine trees and not get shot, or at least get protected from a large percentage of the shots.

To make matters worse, their guns are sticking out of the pine tree's bounding box, therefore enabling them to shoot back without any harm.

At Europa server, we're constantly experiencing players sitting on pine trees without a care in the world while you spray at them, knowing that they are safe as long as they don't move.

This is far beyond game-breaking, please address this issue, or change the name of the mod to "PineZ".

Thank you.

**Comment by CoftSock** [comment]
Blame Arma 2 or Bohemia not someone who makes a mod from a game.

**Comment by R4Z0R49** [comment]
You will need to contact github about issues we can see them being created but can not do anything with them all we get is 404 errors from your issues. My only other thought would be your banned on github looking at your current post i cant say im too surprised at that one.

Now onto the pine trees this issue isnt a nice one we are bound by license's. we are just not allowed to do some stuff for legal reasons this happens to be one of them.

Edit: not sure how this one is showing up but ill post while i have it open

**Comment by AsFoxy** [comment]
Protip: Aim for their feet. http://i.imgur.com/6Vazmob.png
