### ISSUE TITLE
Morphine humanity bug / Change of original "bandit kill" 

### ISSUE THREAD

**Issue by SgtJan** [DayZMod/DayZ#479]
I have given several players morphine auto-injector within the last few days and checked my humanity score every single time but it didn't increase. Other players reported that they experience the same issue. However giving painkillers, bandages & blood bags does still work and increase humanity score.

Furthermore i'd like to point out that killing a survivor whose bullets hit you first will give you a "Murder" right now and decrease your humanity score.
A couple months ago people used to get a "Bandit kill" and the humanity score remained the same.
Is this an intended change?

**Comment by R4Z0R49** [comment]
ill look into the morphine auto-injector.

Humanity has changed a little and is still buggy we are going to work on this soon.
