### ISSUE TITLE
Helicopter crash site loot not working?

### ISSUE THREAD

**Issue by tim1256** [DayZMod/DayZ#48]
On my server the helicopter crash site loot is still not spawning even tho the 1.7.7.1 patch should work. 

Should this be working?
If yes what are the files I should look into to solve this?

Thanks in advance

**Comment by facoptere** [comment]
the helicopter spawns but not its loot?

**Comment by tim1256** [comment]
Yes they do spawn. But there is no loot.

**Comment by facoptere** [comment]
1/ Could you EXTRACT server RPT logs, lines corresponding to crash sites?
You should get something like this:

``` javascript
2013/06/22,  0:11:04 "CRASHSPAWNER: Starting spawn logic for Crash Spawner"
2013/06/22,  0:11:04 "CRASHSPAWNER: Spawning 'Crashed UH-1Y' with loot table 'HeliCrashWEST' at Black Forest [95:80]"
2013/06/22,  0:11:04 "CRASHSPAWNER: Spawning 'UH-60 Wreck' with loot table 'HeliCrashWEST' at Kozlovka [42:102]"
2013/06/22,  0:11:04 "CRASHSPAWNER: Spawning 'Crashed UH-1Y' with loot table 'HeliCrashWEST' at Grishino [64:49]"
```

2/ Could you change you mission file, and add at the end of init.sqf;

``` javascript
dayz_spawnCrashSite_clutterCutter=3;
```

Then post here a snapshot of an helicrash site?

**Comment by ghost** [comment]
Loot does spawn its just hidden is the grass. The area clearing around the loot isn't working at the moment.

**Comment by facoptere** [comment]
There is not area cleaning by default.
Replace "3" by "2" in dayz_spawnCrashSite_clutterCutter  if you want cleared area around loot.

**Comment by tim1256** [comment]
Just added dayz_spawnCrashSite_clutterCutter=3; to the end of my init.sqf in my mission.pbo . For some reason the loot around my UH-60 crash dropped. But my other choppers have nothing.

13:16:04 "CRASHSPAWNER: Starting spawn logic for Crash Spawner"
13:16:04 "CRASHSPAWNER: Spawning 'Crashed UH-1Y' with loot table 'HeliCrashWEST' at Gvozdno [84:40]"
13:16:05 "CRASHSPAWNER: Spawning 'UH-60 Wreck' with loot table 'HeliCrashWEST' at airfield [52:52]"
13:16:06 "CRASHSPAWNER: Spawning 'Mi-8 Wreck' with loot table 'HeliCrashEAST' at Shakhovka [102:83]"

Screenshot1: http://prntscr.com/1bb7mz
Screenshot2:http://prntscr.com/1bb7sn

**Comment by facoptere** [comment]
It may depend on your parameters.
Is it vanilla pbo? What is your _guaranteedLoot parameter (in server pbo,  file server_monitor.sqf,  line 443 with "server_spawnCrashSite" in it) ?

**Comment by tim1256** [comment]
My server is hosted on DayZ.st and I haven't changed alot so ye I think its vanilla.

```
// [_guaranteedLoot, _randomizedLoot, spawnOnStart, _frequency, _variance, _spawnChance, _spawnMarker, _spawnRadius, _spawnFire, _fadeFire]
[3, 4, 3, (40 * 60), (15 * 60), 0.75, 'center', 4000, true, false] spawn server_spawnCrashSite;
```

**Comment by facoptere** [comment]
I will log when a loot position could not be found and increase the tries.

**Comment by tim1256** [comment]
How do I do that?

**Comment by facoptere** [comment]
It will be in 1.7.7.2. 
You have nothing to do.

**Comment by tim1256** [comment]
Ok in that case thanks for your help and I'll wait for 1.7.7.2 :D

**Comment by tim1256** [comment]
Ok so I tried something again and now I got this:

http://prntscr.com/1bd0d4

I guess that shows where the loot should be spawning even tho it's not :(

**Comment by facoptere** [comment]
Ok so my code works.
I have no idea for the loot not spawning.
