### ISSUE TITLE
Many vehicles being needlessly updated by server_monitor.sqf

### ISSUE THREAD

**Issue by ZBok** [DayZMod/DayZ#481]
Hi,

I run a completely vanilla DayZ server (vilayer - not dedicated). A large proportion of my map's vehicles are having their "last_updated" field reset to sysdate a minute or two after each restart. At first I thought it was an sql routine but it seems as though my server_monitor.sqf is the culprit.

My server_monitor.sqf >>> http://pastebin.com/3N9pzC55

It's not a huge problem, but this issue makes pCleanup much less effective as so many vehicles are having their "last_updated" field reset to sysdate after every restart.

I can't see a pattern in why only some vehicles are affected. Sometimes vehicles that have just been spawned in by the restart are affected and have their last_updated field reset to a few minutes after said restart, but sometimes not - it's a bit weird.

Edit: my threads on other forums regarding this 

http://opendayz.net/threads/vehicle-cleanup-routine-probs-dayz-1-8-5.21859/

**Comment by R4Z0R49** [comment]
Yea this only happens if there's an issue with the location of the vehicle. look at line 90.

But ill add it onto my never ending list of stuff to check out :-)

**Comment by R4Z0R49** [comment]
Sorry keep hitting the close and commit button :-(

**Comment by R4Z0R49** [comment]
Could you do me a favour in your server rpt log look for the lines that update the vehicles and paste one in here i have a feeling your talking about child 306 this is a damage update. Not the position update from server monitor

**Comment by ZBok** [comment]
Right.

I'm seriously bad at coding and probably have no place even posting here with such noob levels of coding ability so I'm not exactly sure what line 90 is doing.

This effect happens sometimes to vehicles that aren't in weird spots - eg I can leave a vehicle in the middle of an empty field, eat some beans, log off, and after restart the last_updated field has been reset to sysdate. But again it's not consistent, sometimes happens sometimes doesn't.

I'll find the log you request now and post it shortly.

**Comment by R4Z0R49** [comment]
Yea my guess is the damage is updating ill look into it.

**Comment by ZBok** [comment]
http://pastebin.com/JTcudUDn

The timestamp corresponds to the time that around 20-30 of my 80odd vehicles were updated so I think it's the right line.

**Comment by R4Z0R49** [comment]
yea CHILD:306 is damage.

**Comment by R4Z0R49** [comment]
So position updates are CHILD:305, Inventory is CHILD:309 and CHILD:303, Damage is CHILD:306.

It looks like the system must be detecting a small update to damage on some of your vehicles the question i guess would be does damage actually change for damage or hitpoints.

**Comment by ZBok** [comment]
I've heard several players comment that their vehicle's hitpoints change over restart, like "what happened to my engine it was green before" or similar but it's hard for me to check. I guess it's related?

**Comment by R4Z0R49** [comment]
Yea hitpoints are part of the damage system.

**Comment by ZBok** [comment]
Forgive my ignorance - is there anything I can do to fix? Not a big deal I can manually cleanup vehicles every few days pretty easily.

**Comment by R4Z0R49** [comment]
Not really but ill look into it.

**Comment by ZBok** [comment]
All good many thanks for your time.

**Comment by R4Z0R49** [comment]
Ok im going to add a system so for the first 5-10 seconds of the servers live damage wont be updated. So only when players interact with vehicles they will update damage

**Comment by ZBok** [comment]
Sounds awesome.

Might be useful to know that these updates occur at around 2 minutes after the vehicles are created.

Oh but I guess that's the pMain creating them way before the server actually comes online right? Anyway just in case it's relevant. Let me know if I can provide any further info pertaining.

**Comment by R4Z0R49** [comment]
[Fixed] - Server child 306 damage updates will no longer be called for each vehicle for the first 10 seconds of the vehicles life.

Issue resolved and included in the 1.8.6 build release hopefully sometime this week.

**Comment by ghost** [comment]
I also had this.
http://forums.dayzgame.com/index.php?/topic/224484-dayz-mod-185/?p=2266791
Deleting the bike was the quick solution.

As I understand, the bike was parked in a quirky position and received damage over and over again. Strangely enough, the damage didn´t go up over time.

**Comment by ZBok** [comment]
Greetings,

Still seems to be happening after 1.8.6.1 is installed. Let me know if you want some logs.

**Comment by R4Z0R49** [comment]
i need logs if you can plz
