### ISSUE TITLE
Dev-b725dcd - Arma 2 squad orders being shown in mod

### ISSUE THREAD

**Issue by Detoeni** [DayZMod/DayZ#482]
First seen in version - Dev-edde9c4

On the current test server and Kich's test server if some one joins that does not have the correct mod version, I will get an arma2 squad order to mount vehicle or rally at a point 29km to my west while they are failing to load in, some times they will get added to my squad and the squad mate icons appear on screen. Not seen this before these two builds.
I am guessing about the wrong versions but the other players always leave a very short time after entering game.
I've not got a screen grab for the rally point, but from the direction and distance it sounds like the old debug loading area where players used to end up on a bad day.
![2015-05-23_00004](https://cloud.githubusercontent.com/assets/8584071/7888256/0f94ad1a-062f-11e5-9fa8-753dd7abb75b.jpg)

**Comment by R4Z0R49** [comment]
it might be the new arma beta ill look into this thanks.

**Comment by R4Z0R49** [comment]
Resolved added to hotfix.
