### ISSUE TITLE
Unable to get crates to write to database 1.8.5

### ISSUE THREAD

**Issue by cikez** [DayZMod/DayZ#484]
I have been using crates that are spawned in from the database to allow my donors to store weapons and such in personal crates and they write to the database. Ever since the USOrdnanceBox was banned I have not been able to get them to work. Do you have a class name that will work with this?

I have tried using AmmoBoxBig but it does not seem to even spawn them or when someone tries to add an item it just disappears from their inventory and does not go into the crate.

Please help! Thanks.

**Comment by R4Z0R49** [comment]
Sorry we dont support donor systems like this.

**Comment by CoftSock** [comment]
Just use tents/stashes?

**Comment by cikez** [comment]
I guess I could but ive just always used ammo crates. Which tent/stash has the most items allowed? Thanks.

**Comment by cikez** [comment]
I finally got the AmmoBoxBig to write to the database but now after about 30 minutes of server restart they disappear. I cannot see any cleanup in the RPT log. Any ideas?
