### ISSUE TITLE
Tents/Stash issues

### ISSUE THREAD

**Issue by AggrOnline** [DayZMod/DayZ#485]
placed a tent but pressed cancel , it cancels the tent and they remained in my inventory however magically a tent appeared in the spot I wanted, when I accessed gear it was full of weapons and items. It must have been someone else's in a different location, 

I then placed another stash under a tree and same thing happened, I pressed cancel when on ghost mode, and my sand bags still in my inventory and the new stash had a lot of gear more than i could carry, I mentioned this to the admin of the server and he told me some players reported that his stash had gone missing, he did not know what causes this issue and told me to report it here..

**Comment by AsFoxy** [comment]
I assume this was in version 1.8.5?

**Comment by AggrOnline** [comment]
Yes correct

**Comment by AsFoxy** [comment]
Could you list the items that were in the tent or stash?

**Comment by AggrOnline** [comment]
what? are you serious now? haha no, this was over a week or so ago! there were AK's and all sorts of different items.

**Comment by AsFoxy** [comment]
Can you then say if there were any Dayz items such as medical items, food, vehicle parts etc. or if it was all weapons and magazines?

**Comment by AggrOnline** [comment]
basic weapons nothing fantastic like DMR or anything, there were about 4 weapons I remember 2 Ak's winchester think the other were pistol, some logs , about 2 cans of food, I would say more essentials than heavy military based, I dont remember seeing vehicles parts or metal no.. hardly any drinks, and maybe one antibiotics and one blood bag of sometype, the rest I don't remember they were low vaule, but enough that it took more than one person or trips to fill up..

**Comment by vinyljunkie** [comment]
Hey, what server is this? Is it running Infistar AH?

**Comment by AggrOnline** [comment]
US 434 and no I don't think they use infistar, although I am not 100% sure on that

**Comment by vinyljunkie** [comment]
No, they don't. It's 100% vanilla. Just wanted to be sure as Infistar isn't compatible with newer versions of DayZ Mod.

**Comment by AggrOnline** [comment]
I have infistar and 1.8.5 server vanilla working on my box at home, the only issue I have with it is BE filters, in what way it isn't compatible and what is the alternative right now?

**Comment by R4Z0R49** [comment]
This is a wired issue when items are first placed they have no read access to the database so its impossible for them to swap data with another built item during a single session.

**Comment by AggrOnline** [comment]
But they were not placed, I cancelled build on ghost mod.trying again with the same refunded items straight after it had happened in other location did not reproduce this.. it seems random at this stage.

**Comment by R4Z0R49** [comment]
Yea the code still has to request the items from the db we have no such system from the place object scripts.

We dont even have any way to add say a weapon even if we wonted too the commands just dont exist in that current script system.

We are looking into this.

**Comment by R4Z0R49** [comment]
We have no other info about this ill leave it up a bit longer for more info.
