### ISSUE TITLE
Fill/Swap ammo from different magazine types for the same ammo type

### ISSUE THREAD

**Issue by GeryonTom** [DayZMod/DayZ#487]
We already have the swap from DMR to M24 5 round clips.  Can we have the ability to swap 5.56 from Stanag Magazines to G36 Mags?  Also between DMR and FN FAL?

**Comment by AsFoxy** [comment]
If you read the patch notes you would know that STANAG and G36 magazines can be recombined in 1.8.6. A redesign of the entire system is also planned for 1.8.7.

**Comment by GeryonTom** [comment]
Ah okay and thank you Foxy.
