### ISSUE TITLE
[Bug Report] Problem with gates

### ISSUE THREAD

**Issue by QuimiQ** [DayZMod/DayZ#492]
I haven't been able to test this thoroughly but I thought I'd let you know:

1.) When upgrade a Gate the code you set get's lost and you have to set a new one

2.) Changing the numbers for the code lock is nerve racking. It seems to sometimes work and sometimes not. If you click too fast nothing happens and sometimes you sometime need to change another digit before you can change the one you actually want to change. It seems really strange to me.

Found those bugs yesterday night on the official DayZ test server. Couldn't test any further bc I should be studying for finals and not playing -.-

**Comment by R4Z0R49** [comment]
1. This is because the fence is removed and a new object placed. I'll look at updating that for the next build.
2. I'll look into this see if we can improve it

**Comment by fazmond** [comment]
not sure if its possible but maybe the abilty to type the number in with a keyboard input, rather than click the wheels that aint exactly 100% perfect when you click it (would be much faster getting in and out
OR 
when a player inputs the correct code it adds their id to the list so that they only get the option to lock or unlock as a quick option , the first person in the array could still have an option to change the code and it should be 3rd down in the list so you don't click it first

**Comment by wriley** [comment]
Some info on the padlock code not saving to hive.

After upgrade from WoodenGate_1 to WoodenGate_2 I have this in the database for the object:

```
    ObjectID: 492
   ObjectUID: 512241241630290
    Instance: 1337
   Classname: WoodenGate_2
   Datestamp: 2015-06-07 15:46:08
 CharacterID: 1287
  Worldspace: [205,[5122.41,12416.3,-0.002]]
   Inventory: [["ownerArray",["76561198094288543"]],["padlockCombination",[]]]
   Hitpoints: []
        Fuel: 0.00000
      Damage: 0.00000
last_updated: NULL
```

Changing the padlock code works as intended in game but code is lost on restart. I see no 309 or 303 method calls in HiveExt.log for the gate object. I do see logged in arma2oaserver.RPT where I set the code or guess incorrectly.

```
15:57:43 "INFO: Kerbo, 76561198094288543 has changed the access code for WoodenGate_2 with [5,4,7,9] at time 1660.74"
15:57:56 "INFO: Kerbo, 76561198094288543 is trying to guess with [1,9,5,9] for WoodenGate_2 at time 1673.56"
15:58:02 "INFO: Kerbo, 76561198094288543 has changed the access code for WoodenGate_2 with [3,3,2,6] at time 1679.22"
15:58:26 "INFO: Kerbo, 76561198094288543 has changed the access code for WoodenGate_2 with [0,7,0,1] at time 1703.69"
15:58:53 "INFO: Kerbo, 76561198094288543 is trying to guess with [9,5,8,6] for WoodenGate_2 at time 1730.35"
15:59:16 "INFO: Kerbo, 76561198094288543 has changed the access code for WoodenGate_2 with [5,5,5,5] at time 1752.99"
15:59:36 "INFO: Kerbo, 76561198094288543 is trying to guess with [5,5,5,5] for WoodenGate_2 at time 1773.73"
```

If I can provide any other info let me know.

**Comment by R4Z0R49** [comment]
ok let me look into that

**Comment by R4Z0R49** [comment]
This issue is a wrong version of the server.pbo installed.

Im going to include a version file inside the server.pbo to help with debugging.
