### ISSUE TITLE
1.8.6.1 Bases being pointless?

### ISSUE THREAD

**Issue by VidKo** [DayZMod/DayZ#494]
Hey guys!

I just got a report from one of our regular players, that some players built a wall near the walls around his base so they were able to jump over.

Shouldn't there be some kind of protection against that, as it renders the bases useless?

**Comment by R4Z0R49** [comment]
Atm no the fences are very much WIP while we test to see how well they play out and what bugs we get. What we need to improve and what we need to remove that being said.

Base camps are freely built we have no limits at all for now players will have to defend there own camps as they see fit. If you cant defend the area your trying to lock down for the live of the server its best not to build one to start with.
