### ISSUE TITLE
1.8.6.1 Base fireplace not permanent and won't stay lit

### ISSUE THREAD

**Issue by VidKo** [DayZMod/DayZ#495]
Hi!

I tried to build some base fireplaces and have two problems with them:
- they are gone after restart
- they won't remain lit

**Comment by R4Z0R49** [comment]
did you add wood to the fires to keep them lit?

**Comment by R4Z0R49** [comment]
Ask your server admin to check his logs for the fireplaces. My guess the server.pbo hasn't been updated. Soon as i get 2 mins ill double check the code make sure its not an issue on our side.

**Comment by VidKo** [comment]
I managed to light one up. Will report after next server restart which will be in appr. 2 hours.

**Comment by R4Z0R49** [comment]
Once the server restarts dont forget to add wood to the fire then start it again.

however i think there is a sound issue atm with fires spawned by the server its on my never ending list.

**Comment by R4Z0R49** [comment]
Ok this looks like it might be the server your playing we are working with the server admin to investigate.

**Comment by VidKo** [comment]
After restart, the base fireplace is gone.

**Comment by R4Z0R49** [comment]
yea this looks to be a server issue atm.

**Comment by vinyljunkie** [comment]
You can close this R4Z0R, I was using the wrong files. Fixed now.
Thanks for noticing and reporting it Vid!

**Comment by R4Z0R49** [comment]
K cool
