### ISSUE TITLE
Skin change makes you lose your backpack

### ISSUE THREAD

**Issue by GeryonTom** [DayZMod/DayZ#497]
Players are reporting that after a skin change their backpack is visible to them but to other players it's not.  After the server resets you will log back in with no backpack.

**Comment by R4Z0R49** [comment]
ok might have to do a hotfix for this one.

**Comment by R4Z0R49** [comment]
we have released a hotfix to server admins on slack while we wait to release an official hotfix.

**Comment by fazmond** [comment]
why is this not on the ftp for server admins ?? I don't really want to be signing up to this slack rubbish

**Comment by R4Z0R49** [comment]
Then you have to wait for the release.

**Comment by fazmond** [comment]
so we cant download it on slack then ?
