### ISSUE TITLE
there seems to be a typo in dayz_code\init\compiles.sqf

### ISSUE THREAD

**Issue by fgw-** [DayZMod/DayZ#5]
near line 128:

```
// 120 sec timeout
    while { _timeOut < 3000 && !dayz_clientPreload && !dayz_authed } do {

  ...

  sleep 0.1;
  }:
```

the comment suggests a timeout value of 120sec which already was increased from 40sec of previous version.

anyway, looking at the "sleep 0.1;" at the end of the loop, the value of 3000 in the loop control results in a 300sec timeout! is this intended?

**Comment by R4Z0R49** [comment]
Yes it is ignore the comment. We only use this to send msgs during the load screen now.
