### ISSUE TITLE
1.8.6.1 bugs: disappearing items

### ISSUE THREAD

**Issue by B73** [DayZMod/DayZ#502]
1.8.6.1 bugs: disappearing items (vanilla DayZ)

Fishing pole in middle of fishing. Just disappeared.

Animals (pigs, cows) disappear after they are killed. Usually takes 1-3 seconds. Happens daily. For some reason haven't noticed this happening with other animals.

Also friend told FN FAL with holosight disappearing from backbag. Happened twice to him, during log off/log in. Other weapons have stayded, and even plain FN FAL but attachments (holosight??) have something to do with the disappearings?

**Comment by TIC321** [comment]
The animals disappearing has been an issue for awhile from what I'm aware of. Sometimes when looking away from it, it vanishes in thin air. For me it happens to smaller animals more often like a chicken or rabbit.

Did this happen when the server restarted? If that's the case, you're more prone to losing stuff if you don't log out before the server resets. I've had that problem before with the new update from not logging out before restart and haven't lost items to anything else.

**Comment by WayFaer** [comment]
After combining srel a quiver that was almost full has disappeared, and the second where there were 3 left, no sound of lightning when another player opens your backpack, the player once said that the peace unbeknownst to me pulled out of my backpack gun and killed. before the sound was and could move quickly and not allow things to take.

**Comment by B73** [comment]
> Sometimes when looking away from it, it vanishes in thin air.

Now that you said it.. yes, last time I killed a cow and for a brief moment looked away it was gone. This all in 1-2 seconds maybe. Nowadays I keep my eyes on the pray all the time, and atleast last night animals didn't disappear.

> Did this happen when the server restarted? If that's the case, you're more prone to losing stuff if you don't log out before the server resets.

Nope, fishing pole disappeared from hands while fishing. Next restart was going to be in like 2 hours or so. My friend said he was stuck in "nibble nibble" for long time, and then fishing pole was gone.

Guns from my friend backbag disappeared during normal log off/log in, not server restart in those cases either. We tried to make that happen intentionally but didn't succeed so bug doesn't happen always. I assume that disappearing items from backbag could come from server lag also just like all gear lost situation*
- loose all gear except items in backbag, optics (binaculars,nvg,range finder) and weapon in hand when logging in. This comes from some kind of server lag, not from bug in dayz vanilla?

**Comment by WayFaer** [comment]
игрок не может быть услышан при открытии его рюкзак, не звук

2015-06-18 11:35 GMT+03:00 B73 notifications@github.com:

**Comment by WayFaer** [comment]
the player can not be heard when opening his backpack, no sound

2015-06-18 14:29 GMT+03:00 Семён Синченко wayfaer@gmail.com:

**Comment by Lartza** [comment]
I've had item disappears only on logoff. Animals are fine, but my friend has lost inventory 2-3 times after logging off. Nothing apparent in logs and not consistent so hard to troubleshoot.
