### ISSUE TITLE
Suggestion: Alice pack vs British Assault

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#506]
While I'm ecstatic the Alice pack was brought back a few updates ago, the change to 18 slots and the high spawn rate of them (I often see 2 or more in a single town) have made it too easy to carry a lot of loot and reduced the value of the 12 slot Assault Pack ACU, the 16 slot Survival ACU, and the 18 slot British Assault pack.

My first suggestion is to make the Alice pack more rare so that more people utilize the Assault ACU and Survival ACU.  My second suggestion is to make separation between the Alice and British pack.  Bump the British up to 20 slots maybe?

**Comment by AlStotz** [comment]
I think bumping to British Assault to 20 slots would be an great
separation. As well as the rarity of the Alice.

**Comment by Landbergaren** [comment]
Nice. I was just about to bring this issue. 
Its great that the Alice pack is back. But you have one wiithin 15 minute average. Thats just a bit crazy.

To make it all balanced you need to be able to find patrol packs and assault packs really easy. Finding Survival ACU and Alice pack should still be spawned in residential but the alice pack needs to be a lot rarer. Maybe just as rare as the Survival ACU is now. 

Also the Alice Pack needs to be nerfed to 16-17 slots or the british assault buffed to 19/20-slots. 

This way we wont have a chernarus filled with players having at least an Alice pack running around. All the backpacks gets used and you actually become thankfull for finding a Alice Pack. Finding one today is like "ye thought so.. second house and I got one".

**Comment by PatriotCZ** [comment]
I agree.

**Comment by vinyljunkie** [comment]
Jump on the test server and help the devs test 1.8.7 instead fellas. The loot system has been re-written meaning you are talking about a old version of the mod. Download 1.8.7 and give the devs feedback on the new loot system as they specifically are asking for just that. 

Here are the files needed to start testing: https://github.com/DayZMod/DayZ/issues/578

See you there.

**Comment by Landbergaren** [comment]
vinyl this thread is from june :).
The thread was legit. People are just trying to help.

**Comment by vinyljunkie** [comment]
Well, I know this but it was also commented today. Closed now though.
