### ISSUE TITLE
Some issues with 1.8.6.1

### ISSUE THREAD

**Issue by TIC321** [DayZMod/DayZ#508]
**Not able to drink out of lake at 057 112 (North of Chernogorsk)

While I was leaving Chernogorsk, I decided to head up north and my character was becoming thirsty so I've attempted to drink out of this lake and no prevail.

**Some loot south of Balota airfield at military camp won't let you pick it up.

I had 2 instances where I wasn't able to pick items off the ground or in a deer stand. This happened when I tried to pick up a camping tent from a deer stand and an M16a2 on the ground in one of the tents.

**Using melee weapons really decreases thirst value

While I was hacking away at some zombies from full thirst, I realized after awhile it went down to half very quickly.

**Items disappearing when you get kicked from an error

Happens when you have items in main inventory and sidearm slot. Disappears when you have an error such as "Wrong signature file"

**Comment by R4Z0R49** [comment]
**Not able to drink out of lake at 057 112 (North of Chernogorsk)
I'll look into it

**Some loot south of Balota airfield at military camp won't let you pick it up.
pics are always better

**Using melee weapons really decreases thirst value
New in 1.8.6.1 - Swinging an axe is going to have an impact on food and water. Your burning energy after all

**Items disappearing when you get kicked from an error
Not sure we can do much on this. Ill look into it

**Comment by TIC321** [comment]
Good point about the values. At first I thought of how extreme it was but forgot that your character will be running most of the time and with your character swinging at full strength, it makes sense.

I'll try to get a picture of it whenever I can.

**Comment by conrado-hub** [comment]
bug when equip the soldier clothing, ghille suit or cloating camo, I lose the backpack!

**Comment by R4Z0R49** [comment]
its a known issue we have a server side hotfix being tested with admins on slack.

**Comment by R4Z0R49** [comment]
Closed pending more info
