### ISSUE TITLE
G36 changes

### ISSUE THREAD

**Issue by Jbird206** [DayZMod/DayZ#509]
I've noticed the change in the g36k reticle, I get that.

Why not make it compatible with STANAGS any longer? This doesnt make sense to me. In fact, Why even have the separate mags to begin with? (not that it was your doing)

**Comment by bchawke** [comment]
I believe it's a realism thing.  IRL, you cannot fit a STANAG magazine into a G36 without an adapter:
https://en.wikipedia.org/wiki/STANAG_magazine

The two guns fire the same ammunition, but have different shaped magazines.  ArmA 2/DayZ mod cannot separate the ammo from mags like DayZ SA can.  If it could, you could share ammo between the guns if you found the appropriate magazines.

I'm sure that with some creativity there could be a jerry rigged method to emulate what you do in Standalone.  Maybe they could add an item that's a pile of .223/5.56 ammo that you can change Stanag mags or G36 mags into that you could then combine with a partially full magazine to fill it up.  Once that's added, fill up ammo boxes with the bare ammunition and start spawning magazines with only one round in them in various areas so you can combine that ammo with the magazines that only have one round to fill them up.  I know, sound convoluted, but just tossing out an idea.

**Comment by AsFoxy** [comment]
Biggest problem with the magazines is the duping issue whjch we can't really fix. Also while we could easily add empty magazines we can't have them stick around once depleted since afaik there is no event for magazine depletion.

**Comment by Jbird206** [comment]
TIL thank you.
