### ISSUE TITLE
M249 and other machine guns

### ISSUE THREAD

**Issue by jaydt183** [DayZMod/DayZ#51]
Hi,

I've found a bug...

Just found a M249 at a crash site. However when I picked it up it my backpack was removed as well as the slot.

I've not tested but guess this will be the case for other machine guns.

All the best,

Jay

**Comment by MattzFiber** [comment]
Its not for some machine guns that aren't configured for DayZ. It is normally hacked in.

**Comment by ghost** [comment]
I found the M249 at a crash site. Surely your backpack shouldn't be removed if you pick up an M249?

**Comment by icomrade** [comment]
The illegal M249 or M249_EP1 (NOT M249_DZ [the DayZ variant]) takes a weapon slot AND a backpack slot. It was an illegal/hacked in M249; it was not spawned in by DayZ but may have been a result of a wonky mod on the server or a hacker.
