### ISSUE TITLE
Devil's Farm POI includes 2 lootable M4A1 that BE kick

### ISSUE THREAD

**Issue by wriley** [DayZMod/DayZ#515]
One of my players found this and got BE kicked.
19.06.2015 17:38:17: PLAYER INFO HERE - #0 "M4A1" 0:0

In SQF/dayz_code/system/mission/chernarus/poi/DevilsFarm.sqf 2 weaponholders are created of class "WeaponHolder_M4A1". These are defined in SQF/dayz_equip/config.cpp to give weapon class "M4A1".

Should this be "M4A1_DZ"?

**Comment by R4Z0R49** [comment]
They should not exist in the first place

**Comment by wriley** [comment]
OK, Thanks. I wasn't sure what the intention was. It looks like there is also a jerry can at that POI - WeaponHolder_ItemJerrycanSide
