### ISSUE TITLE
LOW: Viewing inventory switches weapon fire rate selector on close

### ISSUE THREAD

**Issue by Comanche6** [DayZMod/DayZ#516]
1. Set a weapon to Burst or Full auto from Semi
2. Open inventory
3. Close inventory with UI [X] or ESC or bound inventory key
4. Weapon will be back on Semi

**Comment by Comanche6** [comment]
Inventory close also resets Zeroing on AK series.

**Comment by Comanche6** [comment]
Also occurs on switch weapons--mouse wheel or hotkeys.

**Comment by R4Z0R49** [comment]
This is something within the engine im not 100% sure we can do much about it
