### ISSUE TITLE
G36 Issues?

### ISSUE THREAD

**Issue by skigoggles** [DayZMod/DayZ#518]
G36K_Camo was a valid item in 1.8.5.  In 1.8.6, that item doesn't seem to be valid - it's now G36K_Camo_DZ I think. It was removed from my character on login, but stayed in a tent until I figured it out and edited it. I haven't tried the other G36 variants yet.

You used to be able to use STANAG in a G36, but now it won't. I'm assuming this is part of the new ammo-matches-gun features, but its the same ammo and historically there has been little to no G36 clips, giving the gun a limited lifespan.  Feature/bug?

**Comment by AsFoxy** [comment]
Intended feature. STANAG magazines can now be recombined into G36 magazines and vice versa.

**Comment by skigoggles** [comment]
sorry, missed the ammo part , but what about the type G36K_Camo becoming invalid and disappearing?

**Comment by AsFoxy** [comment]
G36K_camo is an Arma weapon class. G36K_Camo_DZ is the new Dayz class. Battleye with up-to-date filters should kick for G36K_camo but otherwise it shouldn't disappear. Not that it matters. That class is no longer used in Dayz.

**Comment by skigoggles** [comment]
not trying to be thick.
I have a player with a type G36K_Camo in hand. Login and its gone. It is removed from inventory.  I have a tent with a type G36K_Camo in it. Open tent, It doesn't show up, but it is not removed. I'm looking at character_data and object_data.

**Comment by AsFoxy** [comment]
Oh that class is actually banned (made unusable and uninteractable) by the mod now. Just use G36K_Camo_DZ instead.

**Comment by AsFoxy** [comment]
Oh that class is actually banned (made unusable and uninteractable) by the mod now. Just use G36K_Camo_DZ instead.

**Comment by skigoggles** [comment]
Understood, and I see that a number of weapons had _DZ added in 1.8.6. The issues is that these were valid  in 1.8.5 - Take a look at CfgBuildingLoot.hpp in the HeliCrashWEST class for instance - the FN_FAL, G36 and other weapons do not have _DZ appended.

In regard to your battleye comment, I was kicked from my own test server, so battleye works, but there is existing inventory.  What am I missing?

**Comment by R4Z0R49** [comment]
http://forums.dayzgame.com/index.php?/topic/225450-dayz-mod-1861/

Read under notes.

**Comment by skigoggles** [comment]
So sorry that I skipped right past that. Appreciate your patience. I hate to mention that although I'm not now, I was a hands-on developer for years.
