### ISSUE TITLE
Missing Backpack when wear clothings

### ISSUE THREAD

**Issue by conrado-hub** [DayZMod/DayZ#519]
when i wear soldier, camo clothing and ghille suit my player lose the backpack, this happen with the other players too! its a bug in this version, or what ? how can i fix it ?

**Comment by R4Z0R49** [comment]
Its a bug you will have to ask your server admin to message me on the dayz forums with email and name. I'll be able to invite into slack where we have a test fix going around.

**Comment by conrado-hub** [comment]
i'm the admin of my server! but idk how to fix this bug! i need help!

**Comment by R4Z0R49** [comment]
message me on the dayz forums with email and name. I'll be able to invite into slack where we have a test fix going around.
