### ISSUE TITLE
Invisible Vehicles.

### ISSUE THREAD

**Issue by CraftLourens** [DayZMod/DayZ#52]
All ok > Restart server and all vehicles just disappeared but they remain in the database
106400 beta patch,1.7.7.1.
I can post RPT log,but it not says anything.
Sorry for my bad english.

**Comment by crazykid1297** [comment]
Ok, you may want to try re-installing the full server files, and updating your server's mission file. This helped me when my server had the wrong files, as it was not loading object data from the hive.

**Comment by sharkiller** [comment]
first use 103718 as last beta, others are a bit bugged.
and you update properly the mission file?

**Comment by CraftLourens** [comment]
Latest from http://www.silentspy.net/p/dayz-mission-generator/

**Comment by CraftLourens** [comment]
Deleted and respawned all cars. Visible.

**Comment by icomrade** [comment]
There may have been an error in one of the column values, if you manually edit vehicles in your database then this may have caused it.
