### ISSUE TITLE
All vehicles/choppers spawn in working condition

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#520]
Not sure if it is intentional or a flaw in the new randomization of damage on vehicle spawns, but in the last week of playing, every vehicle and chopper we have found has been ready to drive or fly.  This is on US434.  Yes, parts have some damage, but we've yet to find a vehicle that needed any parts attached to make it drive or fly.  I made a feedback post on the forums, but I'm posting here as it may potentially be a bug rather than the intended result of the new spawn system. The game is feeling far too much like one of the derivative mods right now.

**Comment by AsFoxy** [comment]
On spawning all vehicle parts are given a uniformly ditributed random value in the range ]x,y[. x being 0 and y 1 by default on most parts. Vehicles generally becoming inoperable only around 0.8 for parts like wheels so there is only a ~20% chance of a wheel that is too broken to drive.

These min and max damages for each part are adjustable by the server admin, but thinking about it perhaps using a normal distribution would be better.

**Comment by bchawke** [comment]
I think the question needs to be asked, what was wrong with the original damage system?  I understand the idea of randomizing spawn locations, but with the original system, _all_ that was needed to get a car going before was 4 wheels.  Randomizing it only makes it easier than that, not harder or easier.  Maybe randomize the condition of the engine/hull/fuel parts, but always spawn vehicles with flat tires.  That way there is a randomized element that makes some vehicles spawn in better condition than others, but it still takes effort to get them going.

This brings up another topic for which I'll start a new thread which is how many variables are being left up to server admins these days.

**Comment by R4Z0R49** [comment]
Dont bother with the variables one admins wont more choice + it gives us a chance to quickly play with settings while under load of normal gameplay so stuff like range can be changed without needing patches once we get settings we are happy with we will hardcode them again for a later patch. Just saves us having to keep updating them each patch for now.

The old vehicle system was very old and needed a full rewrite + it wasn't ours. We used it  along time ago when private hives first started and had no choice once the official server went down. We really should have updated it before now to our own system. We are not allowed to distribute the original version from the official hive.

if you wont all the wheels damage ask the admins of the server to set them like that its not hard to do. update the vehicle_hitpoints and set wheels to be mindamage 1 maxdamage 1 as this is a new system we expect to have a few issues with it while we get feedback.
