### ISSUE TITLE
Discussion: server admin variables

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#521]
I know that because of my complete lack of programming or digital art abilities I am not able to contribute to the mod in a more tangible way, but hopefully, as an avid player and big fan of the mod this input is valuable.

I've noticed that over the last year there has been an increasing number of mechanics in DayZ mod that are variables that the server admin has control over.  I'm posing the question as to whether or not this is a good idea in the grand scope of what DayZ mod represents.  One of DayZ mod's most notable strengths as a game is that it is a consistent and unforgiving experience across what used to be public hive servers but are now "vanilla" private hives.  The beautiful thing about DayZ mod public hive servers was that you knew you were in for the same hardcore, deadly, intense, unforgiving experience that every other public hive server had.  There was no chance of ending up in a low gravity server (think Counter-Strike) or one that spawned players with AS50s or anything like that.  The game was consistent and unrelenting.

Now, it seems more and more features (like zombie damage, full moon, and vehicle spawn damage rate) are fully up to the admin.  This is a slippery slope that reminiscent of what we saw happen to private hives in 2013.  Remember how within months of private hives being enabled that the vast majority of them had 1,000 vehicles, self blood bagging, fully repaired vehicles on the coast, barracks everywhere, etc?

In my opinion, servers should be chosen based on how well they are run and how good the admins are, not by which one has the easiest settings (which doesn't always happen but is the typical trend).  I feel that DayZ mod looses it's integrity when each server has a very different experience.  I think that the fewer items the admins have control over, the better.  Currently, "vanilla" can mean both pitch black nights, super deadly zombies in huge numbers, and every vehicle needing 4 wheels to be repaired, _AND_ full moon nights, easy mode zombies in small numbers, and fully drivable vehicles spawning.  Those are vastly different experiences.

**Comment by R4Z0R49** [comment]
it gives us a chance to quickly play with settings while under load of normal gameplay so stuff like range can be changed without needing patches once we get settings we are happy with we will hardcode them again for a later patch. Just saves us having to keep updating them each patch for now.

**Comment by R4Z0R49** [comment]
There's really only two we allow to be changed that really need to be moved back to a hardcoded setting later on that's 

dayz_DamageMultiplier & dayz_attackRange

These two little settings are the ones we have had to edit time after time.
as far as we have seen so far no one has set anything really silly for those two.
