### ISSUE TITLE
Berezino spawn points are not active when spawn selection is disabled

### ISSUE THREAD

**Issue by VidKo** [DayZMod/DayZ#523]
On Europa, we noticed that Berezino spawn points are not working when spawn selection is disabled. The most norther spawn point that is working is the Solnichny factory.

Is it on purpose or a bug?

**Comment by R4Z0R49** [comment]
Random mimics the original spawn system berezino was added as part of that spawn selection system that's why we have left it out. It allows admins who choose to disable the spawn seletion to still keep the original spawn system.
