### ISSUE TITLE
Wooden Gate disassembly does not return items.

### ISSUE THREAD

**Issue by tiny11s** [DayZMod/DayZ#524]
When disassembling a Wooden Gate (Level 1) no items are returned.  I have tried this four times, all with same result.  Mod Version 1.8.6.1 (1.63.125548).

Here is a video:

http://www.dailymotion.com/video/k4NyLC1GzGTW1dbSuJ1

**Comment by R4Z0R49** [comment]
ok thanks ill try taking a look at some point today.

**Comment by tiny11s** [comment]
Does the Status Tag "status:wontfix" mean that this issue "won't be fixed" (now or ever) or does it mean it "wants to be fixed" and GitHub have spelled "want" incorrectly?

**Comment by kichilron** [comment]
It means:

Won't fix.

As in: I have tried, but at this point in time the bug won't fix / Doesn't want to fix.

**Comment by R4Z0R49** [comment]
ok tag updated.

**Comment by R4Z0R49** [comment]
#423
