### ISSUE TITLE
Mined Rough Stone Item Drop Location

### ISSUE THREAD

**Issue by tiny11s** [DayZMod/DayZ#525]
When mining Rough Stone, the dropped item is placed in locations in front of the player.  This can lead to the item being hidden by the rock, if the rock is large, making it impossible for the player to collect the Rough Stone item.

Can the mined Rough Stone item drop be located behind the player the same way that Wooden Logs are located when harvesting wood?

**Comment by R4Z0R49** [comment]
k soon as one of us gets a chance we can update this.
