### ISSUE TITLE
Additional Hatchet in Craft Menu List with Shotgun Shells Icon

### ISSUE THREAD

**Issue by tiny11s** [DayZMod/DayZ#527]
When a player has a Hatchet in the "Holding" slot and opens the "Craft" menu, the list of available items adds 1 Hatchet with an icon for Shotgun Shells.  I tested this with only 1 Hatchet in the player inventory (backpack was empty).  See pics.

![dayz mod crafting hatchet bug 01](https://cloud.githubusercontent.com/assets/13170437/8601083/b7b79aaa-2661-11e5-837a-8a58f3a7e74f.jpg)

![dayz mod crafting hatchet bug 02](https://cloud.githubusercontent.com/assets/13170437/8601084/c4f73c5c-2661-11e5-8bb4-928ed17057d0.jpg)

**Comment by kichilron** [comment]
That is the Hatchet-Ammo.

The way the Engine works is that a Hatchet is an actual weapon, because there's no Mellee in the base game. A Hatchet needs Ammo to be working properly, no way around that, I'm afraid.

**Comment by tiny11s** [comment]
Ahh, I understand, OK, thanks.
