### ISSUE TITLE
Launcher testing

### ISSUE THREAD

**Issue by R4Z0R49** [DayZMod/DayZ#529]
Two of the big problems we always see from new and old players 
1. trying to find a vanilla server to play on.
2. trying to work out the addons folder.

Hopefully the launcher should help in both case's.

This is a test version you guys can try.

Install DayZMod on steam.
1. Download arma2
2. Start arma2
3. Download arma2OA
4. Start arma2OA
5. Download DayZMod 
6. Install launcher

http://dayzmodlauncher.com

Drop us some feedback/thoughts.

**Comment by R4Z0R49** [comment]
Known bugs
1. Double clicking causes the launcher to crash,

**Comment by ghost** [comment]
Throwing a few whiteys

http://i.imgur.com/dlXWbfd.png

Amber, let me know if you want any sort of stack trace / log.

**Comment by AmberHelios** [comment]
Would be great mate, what were you doing at the time?, 

Nevermind fixed now

**Comment by kichilron** [comment]
http://i.imgur.com/fXqQwvy.png

**Comment by AmberHelios** [comment]
yeah its a pita, i think its a css transition messing with bootstrap. does not occur all the time
