### ISSUE TITLE
People turning into birds after server populations reaches 30+

### ISSUE THREAD

**Issue by AVendettaForYou** [DayZMod/DayZ#53]
"ERROR: server_playerSync: Cannot Sync Player dean [3334]. Position in debug! [-18702,25782.8,0.00143433]"

That's just one of the many players that are not getting sync'd even our regular players are joining and not getting authorized properly so they get turned into a bird. Is there any way to fix this?

**Comment by ghost** [comment]
When a player first joins the server they spawn in debug at the respawn_west marker. This is the first spot all players spawn to. When the server gets to a certain point in player setup that person gets (teleported?) to the location where they where before log out or to a new spawn location. While they are in debug the player can not save to the database. That is a diagnostic log from the server_code.pbo, there is nothing wrong with that line.

It will also appear when you go into debug normally or by being teleported, this is to prevent saving players in debug to the hive. AFAIK.

**Comment by facoptere** [comment]
I don't think 'position in debug' log is related to player spawning as a seagull.
There is no solution to prevent that, and the best is to force the player to reconnect.
