### ISSUE TITLE
Water bottle:boiled disappearing

### ISSUE THREAD

**Issue by michu415** [DayZMod/DayZ#530]
Hi, today I had a problem with my bottle- after I picked up too much items it disappeared instead of being dropped. Filled with boiled water bottles cannot be dropped? Or just "little" bug with getting under texture.

**Comment by R4Z0R49** [comment]
When you picked up too many items are you sure your bottle didn't just go into the object you picked up too much from?

**Comment by michu415** [comment]
It was only item on the floor, my character's inventory(not backpack) was full>it exchanged items. But there was no bottle anymore, I tried to catch item description (crouching rolling etc.) but with no result. It happened in the Berezino restaurant, maybe I was just unlucky and it glitched into the floor.

**Comment by Lukethero** [comment]
Items are weird in buildings, do not count on them dropping like that.
