### ISSUE TITLE
Large inventory (Ural) causing issues

### ISSUE THREAD

**Issue by ilganna** [DayZMod/DayZ#531]
I have one issue with a loot filled Ural (UralCivil):

With this Ural inventory:

---

[[["M16A2","Mosin_Nagant_broken","ItemToolbox","ItemEtool","Winchester1866","MeleeMachete","ItemHatchet","ItemCrowbar","ItemDIY_wood","Crossbow_DZ","MeleeBaseBallBat","AKS74U_DZ","PDW_DZ","SA58_CCO_DZ","ItemMap","CZ550_DZ","ItemKnife4","M4A1_DZ","LeeEnfield_DZ","Mosin_Nagant"],[4,3,1,2,2,1,5,2,2,2,1,4,1,1,3,1,1,1,1,1]],[["equip_nails","100Rnd_762x54_PK","20Rnd_762x51_DMR","Skin_Sniper1_DZ","PartEngine","PipeBomb","ItemJerrycan","PartGeneric","Attachment_BELT","ItemTrashPaper","equip_pvc_box","ItemPainkiller","equip_Crossbow_Kit","15Rnd_W1866_Slug","equip_metal_sheet","equip_2inch_metal_pipe","FoodbeefCooked","PartWheel","equip_rope","ItemSandbag","Quiver","ItemWire","transfusionKit","ItemTankTrap","equip_string","ItemSodaSacrite","Mosin_Nagant_Ammo","ItemMorphine","Attachment_FL_Pist","equip_lever","equip_hose","equip_herb_box","equip_duct_tape","FoodPistachio","ItemTent","ItemBandage","bloodBagAPOS","bloodBagABPOS","bloodBagBPOS","bloodBagOPOS","FoodCanRusPeas","TrapBear","FoodbaconRaw","FoodbeefRaw","ItemSodaLirik","FoodCanGriff","30Rnd_762x39_SA58","10Rnd_762x54_SVD","6Rnd_45ACP","equip_1inch_metal_pipe","FoodCanBoneboy","ItemCards","5Rnd_762x51_M24","FoodCanRusCorn","FoodCanBeef","Tranquiliser_Bolt","30Rnd_9x19_MP5SD","ItemSodaPeppsy","PartGlass","8Rnd_B_Beneli_Pellets","PartFueltank","5x_22_LR_17_HMR","30Rnd_545x39_AK","Attachment_GP25","30Rnd_556x45_Stanag","Attachment_FL","SmokeShellRed","ItemEpinephrine","Attachment_SCOPED","10x_303","emptyBloodBag","bloodBagABNEG","30Rnd_556x45_StanagSD"],[7,2,13,2,1,1,4,3,4,1,2,5,1,7,1,1,4,2,6,3,6,1,5,1,1,1,5,3,1,4,1,2,2,1,1,2,1,1,2,2,1,1,4,5,1,1,1,10,4,1,1,1,4,4,3,1,1,2,2,9,1,2,5,1,4,2,1,1,1,4,1,1,1]],[["DZ_ALICE_Pack_EP1"],[1]]][[["M16A2","Mosin_Nagant_broken","ItemToolbox","ItemEtool","Winchester1866","MeleeMachete","ItemHatchet","ItemCrowbar","ItemDIY_wood","Crossbow_DZ","MeleeBaseBallBat","AKS74U_DZ","PDW_DZ","SA58_CCO_DZ","ItemMap","CZ550_DZ","ItemKnife4","M4A1_DZ","LeeEnfield_DZ","Mosin_Nagant"],[4,3,1,2,2,1,5,2,2,2,1,4,1,1,3,1,1,1,1,1]],[["equip_nails","100Rnd_762x54_PK","20Rnd_762x51_DMR","Skin_Sniper1_DZ","PartEngine","PipeBomb","ItemJerrycan","PartGeneric","Attachment_BELT","ItemTrashPaper","equip_pvc_box","ItemPainkiller","equip_Crossbow_Kit","15Rnd_W1866_Slug","equip_metal_sheet","equip_2inch_metal_pipe","FoodbeefCooked","PartWheel","equip_rope","ItemSandbag","Quiver","ItemWire","transfusionKit","ItemTankTrap","equip_string","ItemSodaSacrite","Mosin_Nagant_Ammo","ItemMorphine","Attachment_FL_Pist","equip_lever","equip_hose","equip_herb_box","equip_duct_tape","FoodPistachio","ItemTent","ItemBandage","bloodBagAPOS","bloodBagABPOS","bloodBagBPOS","bloodBagOPOS","FoodCanRusPeas","TrapBear","FoodbaconRaw","FoodbeefRaw","ItemSodaLirik","FoodCanGriff","30Rnd_762x39_SA58","10Rnd_762x54_SVD","6Rnd_45ACP","equip_1inch_metal_pipe","FoodCanBoneboy","ItemCards","5Rnd_762x51_M24","FoodCanRusCorn","FoodCanBeef","Tranquiliser_Bolt","30Rnd_9x19_MP5SD","ItemSodaPeppsy","PartGlass","8Rnd_B_Beneli_Pellets","PartFueltank","5x_22_LR_17_HMR","30Rnd_545x39_AK","Attachment_GP25","30Rnd_556x45_Stanag","Attachment_FL","SmokeShellRed","ItemEpinephrine","Attachment_SCOPED","10x_303","emptyBloodBag","bloodBagABNEG","30Rnd_556x45_StanagSD"],[7,2,13,2,1,1,4,3,4,1,2,5,1,7,1,1,4,2,6,3,6,1,5,1,1,1,5,3,1,4,1,2,2,1,1,2,1,1,2,2,1,1,4,5,1,1,1,10,4,1,1,1,4,4,3,1,1,2,2,9,1,2,5,1,4,2,1,1,1,4,1,1,1]],[["DZ_ALICE_Pack_EP1"],[1]]]

---

When starting the server I have this error:

---

 0:01:32 "HIVE: Commence Object Streaming..."
 0:01:32 Error in expression <eering",0],["motor",0],["sklo predni P",>
 0:01:32   Error position: <>
 0:01:32   Error Missing ]
 0:01:32 Error in expression <eering",0],["motor",0],["sklo predni P",>
 0:01:32   Error position: <>
 0:01:32   Error Missing ]
 0:01:32 Error in expression <ray = call compile format ["%1",_data];
_resultArray
};

onPlayerDisconnected        >
 0:01:32   Error position: <_resultArray
};

onPlayerDisconnected        >
 0:01:32   Error Undefined variable in expression: _resultarray
 0:01:32 File z\addons\dayz_server\init\server_functions.sqf, line 158
 0:01:32 Error in expression <y call server_hiveReadWrite;

_status = _result select 0;
_myArray set [count _m>
 0:01:32   Error position: <_result select 0;
_myArray set [count _m>
 0:01:32   Error Undefined variable in expression: _result
 0:01:32 File z\addons\dayz_server\system\server_monitor.sqf, line 60
 0:01:32 "HIVE: Streamed 65 objects"

---

While having this Ural inventory (less items from a previous backup):

---

[[["M16A2","Mosin_Nagant_broken","ItemToolbox","ItemEtool","Winchester1866","MeleeMachete","ItemHatchet","ItemCrowbar","ItemDIY_wood","Crossbow_DZ","MeleeBaseBallBat","AKS74U_DZ","PDW_DZ","SA58_CCO_DZ","ItemMap","CZ550_DZ"],[2,3,1,1,2,1,5,1,3,2,1,3,1,1,2,1]],[["equip_nails","100Rnd_762x54_PK","20Rnd_762x51_DMR","Skin_Sniper1_DZ","PartEngine","PipeBomb","ItemJerrycan","PartGeneric","Attachment_BELT","ItemTrashPaper","equip_pvc_box","ItemPainkiller","equip_Crossbow_Kit","15Rnd_W1866_Slug","equip_metal_sheet","equip_2inch_metal_pipe","FoodbeefCooked","PartWheel","equip_rope","ItemLog","ItemSandbag","Quiver","ItemWire","transfusionKit","ItemTankTrap","equip_string","ItemSodaSacrite","ItemPlank","Mosin_Nagant_Ammo","ItemMorphine","Attachment_FL_Pist","equip_lever","equip_hose","equip_herb_box","FoodmuttonCooked","equip_duct_tape","FoodgoatCooked","FoodPistachio","ItemTent","ItemBandage","bloodBagAPOS","bloodBagABPOS","bloodBagBPOS","bloodBagOPOS","FoodCanRusPeas","TrapBear","FoodbaconRaw","FoodbeefRaw","ItemSodaLirik","FoodCanGriff","30Rnd_762x39_SA58","10Rnd_762x54_SVD","6Rnd_45ACP","equip_1inch_metal_pipe","FoodCanBoneboy","ItemCards","5Rnd_762x51_M24","FoodCanRusCorn","FoodCanBeef","Tranquiliser_Bolt","30Rnd_9x19_MP5SD","ItemSodaPeppsy","PartGlass","8Rnd_B_Beneli_Pellets","PartFueltank","5x_22_LR_17_HMR","30Rnd_545x39_AK","Attachment_GP25","30Rnd_556x45_Stanag","Attachment_FL","SmokeShellRed"],[7,2,13,2,1,1,4,3,3,1,2,3,1,7,1,1,5,2,5,2,3,6,1,4,1,1,1,3,2,3,1,2,1,2,2,2,1,1,1,2,1,1,1,1,1,1,4,6,1,1,1,10,4,1,1,1,4,4,3,1,1,2,2,9,1,2,3,1,2,1,1]],[["DZ_ALICE_Pack_EP1"],[1]]]

---

The error is not generated in the RPT.

Please note that on the first occurence the whole 200 spots are filled with items, while on the second one, 8 places are still free.

My server is a plain vanilla one, no extra mod or modifications.

I have .SQL backup files and logs available to troubleshoot.

Thanks

Edit: Forgot to add, as reported by Shogun338, that the Ural will be not spawning ingame.

**Comment by Shogun338** [comment]
I've experienced this many times. I removed all Ural and V3S spawns on our server until this could be handled. The Ural or V3S with too many items also causes it to not spawn in game on server start up.

**Comment by ilganna** [comment]
Thanks Shogun338, for the moment I will advise to not fill all spots of the Ural, but is there any other storage object that can hold 200 or more items?

**Comment by Shogun338** [comment]
I believe the top upgraded tent is about 180 magazines, 10 weapons. Haven't had any complaints about tents not spawning in or disappearing, and nothing in the RPT either.

**Comment by ilganna** [comment]
Thanks again! I hope the devs will recognize and fix this issue soon :)

**Comment by Shogun338** [comment]
No problem! and I'm sure they will when they have time.

**Comment by AlexAFlorov** [comment]
That was old problem, when there is limitation to length of inventory string hive dll can proceed. 

so you can broke even tent using many different long-named items.
