### ISSUE TITLE
Wooden Fence Lvl1 Does Not Fully Disassemble

### ISSUE THREAD

**Issue by tiny11s** [DayZMod/DayZ#532]
Wooden Fence Frame Lvl1 does not fully disassemble, it leaves the Wooden Fence Frame, with a message "Disassemble done. Missing   to disassemble buliding."  Only the Level 1 items are returned.  

When I try to disassemble the Frame, I get a message "Object is already disassembling".

I can upgrade the Frame to Level 1 again.

Happened on server "AGGRO US/EU".  (1.8.6.1, 1.63, 125548)

![dayz mod wooden fence disassembly fail 01](https://cloud.githubusercontent.com/assets/13170437/8673951/9f1bb394-2a32-11e5-8577-48802440b68b.jpg)
![dayz mod wooden fence disassembly fail 02](https://cloud.githubusercontent.com/assets/13170437/8673954/a828b98c-2a32-11e5-8734-934529fe6982.jpg)
![dayz mod wooden fence disassembly fail 03](https://cloud.githubusercontent.com/assets/13170437/8673959/b118fda4-2a32-11e5-868e-74d574162bd5.jpg)

EDIT:  Just found somebody posted similar issue:  foundation disassembly #423 , sorry forgot to search first :(

**Comment by R4Z0R49** [comment]
#423
