### ISSUE TITLE
Player able to pick up only one comfrey leave

### ISSUE THREAD

**Issue by AlexAFlorov** [DayZMod/DayZ#533]
After discovering comfrey "plant"  and gearing it i see 3 leaves, but after moving them to inventory gear closes and only one leave appears in inventory

**Comment by bchawke** [comment]
Once you do this, the other two leaves will be on the ground, you can look at them and bring up the inventory again to pick them up.  I've accidentally shot at the ground a couple of times by clicking on the "right" arrow of the comfrey leaves in the inventory, forgetting it closes immediately.
