### ISSUE TITLE
"z_policeman" Zombie doesn't appear to be spawning any longer, not sure since when.

### ISSUE THREAD

**Issue by pjohnson7** [DayZMod/DayZ#537]
I noticed the policeman zombie doesn't appear to spawn any longer like it used to, for example at NWAF.
Any chance we can get that zombie back for variety sake?

**Comment by R4Z0R49** [comment]
they still exist in military spawns. I'll check to see if they are indeed still spawning as they should. I'll reopen if it is indeed a bug
