### ISSUE TITLE
Feature:  Add Dog Companions to DayZMod?

### ISSUE THREAD

**Issue by pjohnson7** [DayZMod/DayZ#538]
Long ago, I recall dogs being talked about being added to the mod.  Any chance we can finally get dog companions added to the Mod?  It's already possible with a couple easy edits and then add the DOGS.SQF to the mission.  But it would be great if it became a legitimate "professionally done" addition to DayZMod.  Have it so you can toggle it on/off like the other stuff if Admin's don't want it.  Currently there is a DOGS.SQF that you can have the dog spawn from a doghouse, command it to stay, follow, hunt animals and It attacks zombies.  It's fun!

**Comment by R4Z0R49** [comment]
We looked at dogs sometime ago and they end more buggy then zeds are so we choice not to include them. 

If admins wont to add dogs they can there is plenty of scripts around adding them.

**Comment by PatriotCZ** [comment]
Seeing my doggy friend die would be the most sad thing that could ever happen in dayz.
