### ISSUE TITLE
Vehicles spawn undamaged

### ISSUE THREAD

**Issue by Lartza** [DayZMod/DayZ#539]
On 1.8.6.1 every vehicle spawned is undamaged, not like described in #520 
Fuel is being randomized correctly, but hitpoints are not.

MySQL is MariaDB 10.0.20 running under Linux. I've fixed casing issues with table names and can't figure a reason why damage won't work, no other issues with MySQL.

**Comment by AsFoxy** [comment]
Could you run this query and paste the results.

``` SQL
SET @i = (SELECT Hitpoints FROM vehicle_spawns WHERE Classname = "SUV_DZ" LIMIT 1);

SET @r = (SELECT GROUP_CONCAT("[\"", PartName, "\",", TRUNCATE(IF ((@r := MinDamage + RAND() * (MaxDamage - MinDamage)) < 0, MinDamage, @r), 4), "]")
    FROM vehicle_hitpoints
    WHERE ID = @i);

SELECT @i, @r;
```

**Comment by Lartza** [comment]
1 ["karoserie",0.4668],["motor",0.4619],["palivo",0.3892],["wheel_1_1_steering",0.7005],["wheel_1_2_steering",0.0429],["wheel_2_1_steering",0.1131],["wheel_2_2_steering",0.4368]

**Comment by Lartza** [comment]
My randomizeVehicleHitpoints doesn't actually match the .sql...

``` sql
BEGIN



    DECLARE Threshold DOUBLE DEFAULT 0.5;


    DECLARE Result varchar(2000);
    DECLARE Hitpoints_ID INT DEFAULT (SELECT Hitpoints FROM vehicle_spawns WHERE Classname = class LIMIT 1);

    IF (ISNULL(Hitpoints_ID)) THEN
        RETURN "[]";
    END IF;

    SELECT GROUP_CONCAT("["", PartName, "",", TRUNCATE(IF ((@r := MinDamage + RAND() * (MaxDamage - MinDamage)) < Threshold, MinDamage, @r), 4), "]")
        INTO Result
        FROM vehicle_hitpoints
        WHERE ID = Hitpoints_ID;

    RETURN CONCAT_WS("", "[", Result, "]");
END
```

**Comment by AsFoxy** [comment]
Change `Threshold` to `0.01` and paste the result of running `randomizeVehicleHitpoints` with `"SUV_DZ"` as the argument.

**Comment by Lartza** [comment]
[[karoserie,0.9118],[motor,0.0253],[palivo,0.3384],[wheel_1_1_steering,0.0201],[wheel_1_2_steering,0.8316],[wheel_2_1_steering,0.0977],[wheel_2_2_steering,0.9938]]

And it even does random hitpoints with Threshold 0.5

I might have just fixed it but not sure how... might have been a privilege problem

**Comment by Lartza** [comment]
I believe this might be an issue with the DEFINER being different than the user you get put under.

I think that's the only change I did, I had both dayz@% and dayz@myhomeip users, with all privileges to the dayz database. DEFINER to the function was dayz@% but my USER() would match dayz@myhomeip and not allow me to even look at the CREATE PROCEDURE of the function, and it  silently failed to work correctly when I ran pMain.

I removed the dayz@homeip user completely and it seems to have spawned four vehicles with damage now. Can't think of any other changes.

Is this possible?

**Comment by AsFoxy** [comment]
Can you paste an example of the `Hitpoints` field when the vehicle is undamaged.

**Comment by Lartza** [comment]
I can't get it to fail anymore, even when I tried, and every vehicle that is in the database has been spawned from the hive at least once so they might not be what they were when created.

Currently the undamaged vehicles in the database look like this:
`[["karoserie",0],["motor",0],["palivo",0],["wheel_1_1_steering",0],["wheel_1_2_steering",0],["wheel_2_1_steering",0],["wheel_2_2_steering",0]]`

But it might be that they were created by pSpawnVehicles as:
`[[karoserie,0],[motor,0],[palivo,0],[wheel_1_1_steering,0],[wheel_1_2_steering,0],[wheel_2_1_steering,0],[wheel_2_2_steering,0]]`

Or possibly even with damage I missed somehow.

In any case, this problem has been fixed somehow. Thank you
