### ISSUE TITLE
Locked Gate Issue

### ISSUE THREAD

**Issue by 1Macready** [DayZMod/DayZ#540]
Once I have upgraded to gate level 2 using the padlock, I am unable to either set the lock code or unlock the gate. Choosing either option causes the combination lock UI to show very briefly (< 1 second) and then disappear without accepting input.

I have confirmed with another user on the same server that they are having the exact same issue. Is this possibly a server issue?  Server is vanilla but customized (extra buildings for example).  Is there a particular setting or file I can ask the server admin to check?

**Comment by 1Macready** [comment]
Possibly (probably) important: server is running Infistar.

**Comment by CoftSock** [comment]
Infi blocks alot of hpps or dialogs from loading. (aswell as allowing backdoors in to hack)

**Comment by ghost** [comment]
I stopped using infistar altogether. There is so much to fix and check and in my experience it breaks a lot of stuff. On the other side it is super convenient...
