### ISSUE TITLE
Weapon sights too rare?

### ISSUE THREAD

**Issue by thcNox** [DayZMod/DayZ#544]
We've recently launched a new first person server a couple of weeks back so it's been a lot of farming of loot for myself and my friends. While I have found plenty of DMR's, NVG's, Rangefinders and even 3-4 satchel charges I haven't seen a weapon sight. I have heard of someone finding a cobra that's it. Maybe you don't want the sights to be too prevalent but this seems a tad excessive. Maybe I've had a run of colossal bad luck but I've been looting A LOT :p

**Comment by R4Z0R49** [comment]
the loot system is random however it depends where your looking.

Generic attachments can be found pretty much all buildings, however sights are limited to crashsites east and west.

```
attachmentsGeneric[] =
{
    {"Attachment_BELT",0.03},
    {"Attachment_SCOPED",0.01},
    {"Attachment_FL",0.02},
    {"Attachment_FL_Pist",0.02}
};

attachmentsEast[] =
{
    {"Attachment_Kobra",0.01},
    {"Attachment_PSO1",0.01},
    {"Attachment_SupMakarov",0.03},
    {"Attachment_SupBizon",0.02},
    {"Attachment_Sup545",0.01},
    {"Attachment_GP25",0.01}
};

attachmentsWest[] =
{
    {"Attachment_CCO",0.01},
    {"Attachment_Holo",0.01},
    {"Attachment_Ghillie",0.02},
    {"Attachment_M203",0.01},
    {"Attachment_Sup556",0.01},
    {"Attachment_Sup9",0.03}
};
```

**Comment by thcNox** [comment]
Yes I am aware of where they spawn, and I have been looting primarily heli crashes as well. Having found 10-15 ghillies I would have expected to have found atleast one or two holo/cco sights

**Comment by R4Z0R49** [comment]
it will be looked into with the new loot system inbound soon. The new loot system should give us a bit more control over the random weighted system we have now.

**Comment by R4Z0R49** [comment]
209a6a7ee479dea7584d7a473f4b116528f577ba

for reference.
