### ISSUE TITLE
1.8.7-dev2 - No zombies spawning at crashsites

### ISSUE THREAD

**Issue by dayzjarhead** [DayZMod/DayZ#546]
Crashsites do not spawn zombies, when approached by foot.

Loot spawns fine, though.

**Comment by CoftSock** [comment]
you sure you didnt teleport right ontop of it? worked fine the last one i went to

**Comment by AlStotz** [comment]
"when approached by foot."

Sometimes, bugs don't appear every time Coftsock.

And I would assume that it would be most likely due to a high server load.
Try to post a more detailed report Alex. What time did this happen at? How
many players were online? Etc.

**Comment by dayzjarhead** [comment]
This was on the most recent dev build (hence the title) and I was the only tester on the server. 

I scouted for crashes by chopper to test them and approached three by foot from about 1km distance to be sure, found loot, but no zombies. Going to reproduce it tonight.
