### ISSUE TITLE
1.8.7-dev2 - Fireplace can not be built

### ISSUE THREAD

**Issue by dayzjarhead** [DayZMod/DayZ#547]
if (_booleans select 0) e>
  Error Undefined variable in expression: fn_nicespot
File z\addons\dayz_code\actions\player_makefire.sqf, line 20
"SpawnCheck Local.Agents: 10/15, NearBy.Agents: 10/30, Global.Agents: 33/1000, W.holders: 7/80, (radius:300m 59fps)."
"SpawnCheck Local.Agents: 10/15, NearBy.Agents: 10/30, Global.Agents: 33/1000, W.holders: 7/80, (radius:300m 15fps)."

**Comment by R4Z0R49** [comment]
https://github.com/DayZMod/DayZ/commit/3d588dd013deb1b5a35df987fcb9a39098475f2f

Resolved.
