### ISSUE TITLE
Bug  Stable Gate Brake in not releasing the locks.

### ISSUE THREAD

**Issue by R4Z0R49** [DayZMod/DayZ#549]
After a successful brake in there is a bug that never release's the locks.

**Comment by denisio** [comment]
I confirm this. You can not open the gate (1.8.7).

**Comment by R4Z0R49** [comment]
Ok looks like we have a bug in the selfActions and an issue with the breakin im going to test this now to get it fixed for the next hotfix/patch

**Comment by denisio** [comment]
I can't open the gate if I enter the correct code. Just set up a code again and again...

**Comment by R4Z0R49** [comment]
This should be fixed in 1.8.8
