### ISSUE TITLE
backpack contents not saved/restored on server restart when backpack is put into vehicle

### ISSUE THREAD

**Issue by fgw-** [DayZMod/DayZ#55]
tried this with an offroad, but assume its the same for all vehicles.

putting a backpack with some gear in it into a vehicles gear works fine. if this backpack is removed from the vehicle later all the contents of the backpack are still in the backpack.

but it looks like the contents of the backpack are not saved to the database when the backpack is put into a vehicle. if a server restart happens while the backpack (with gear in it) is in a vehicle, the backpack contents are not restored. 

thus, when the backpack is removed from the vehicle after the restart, the backpack is empty.

**Comment by thevisad** [comment]
This has always been the case, backpacks are saved, but it's contents are not when placed into a vehicle. It's how the vehicle inventory system works.
