### ISSUE TITLE
I can stay hydrated.

### ISSUE THREAD

**Issue by TheAliGamer** [DayZMod/DayZ#550]
This problem has pissed me off for so long. I just can't stay hydrated. I can drink 4 sodas and 2 min later il be again in a situation where i need to kill some poor dude for his drinks or i need go in elektro or some big city where im 99% gonna die. I dont know if the drinking bar is suppose to be like this but in real life if i drank 5 soda cans i would be taking the world longest piss. I dont understand why dont just stick with the normal food bar and drinking bar. Why u got to mess it up. Its not realistic at all.

**Comment by R4Z0R49** [comment]
If you take 5 mins to read the change-log you will see its being updated in the next patch.

Food and water is linked to speed & backpack load.
