### ISSUE TITLE
Another scripting error

### ISSUE THREAD

**Issue by vinyljunkie** [DayZMod/DayZ#555]
Also this shows up every now and then.
Thought you wanted to know.
![2015-08-21_00002](https://cloud.githubusercontent.com/assets/8300577/9424950/d7dc54b8-48ff-11e5-801e-906a08ee53b9.jpg)

**Comment by vinyljunkie** [comment]
This is on 1.8.6.1 stable.

**Comment by R4Z0R49** [comment]
Hopefully resolved.
