### ISSUE TITLE
Loot issue: Multiple items spawn in the same spot. 

### ISSUE THREAD

**Issue by vinyljunkie** [DayZMod/DayZ#558]
Hey, I have seen this a couple of times now. This is from Cherno, close to the southern supermarket. I have seen it by the Balota tents and deer stands as well. It seems to happen in places where there is a lot of traffic. It's hard to pick up the loot as you have to loot the items one by one to get to the one you actually want. In the picture is a sandbag, wooden planks and a duct tape. This is stable 1.8.6.1
![2015-08-28_00001](https://cloud.githubusercontent.com/assets/8300577/9551603/7b61811a-4db2-11e5-994e-9fc4c9ebdb03.jpg)

**Comment by AlexAFlorov** [comment]
It happens cos theese wrecks (and camps like near Balota and Stary Sobor) are locally generated objects on clients.  So every player nearby could genereate own loot in same place

**Comment by bchawke** [comment]
I've seen this a lot playing on US434.  Didn't seem to be an issue until recently.  It's annoying because you can only access one of the objects at a time, and it makes loot spawn areas OP because of how much stuff you can get.

**Comment by R4Z0R49** [comment]
Ok im not so worried about this. If we get this issue on the dev server reopen this. The dev build has a new loot system.
