### ISSUE TITLE
Cannot refuel fishing boat

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#559]
This has actually been an issue as long as I can remember playing DayZ mod and I was wondering if something could be done about it.  The fishing boat can only be refueled at the large docks in Cherno/Elektro because the player with the jerry can needs to be near the upper level of the boat to refuel.  Anytime a fishing boat runs out of fuel while away from the docks it becomes permanently immobile.  I honestly can't remember the last time I saw any players using the fishing boat in DayZ mod because of this issue.

**Comment by VidKo** [comment]
It can also be refuelled from the rocks above. But yes, it is a big issue.

**Comment by ebaydayz** [comment]
This does not appear to be a problem anymore. I can refuel it both while swimming and on a low dock in balota.
![20160428170443_1](https://cloud.githubusercontent.com/assets/7761693/14901556/fa435e9c-0d63-11e6-961a-274a0936a53e.jpg)
![20160428170313_1](https://cloud.githubusercontent.com/assets/7761693/14901564/fe37f454-0d63-11e6-8158-69a0878da085.jpg)

**Comment by skigoggles** [comment]
ok, I was interested in this one and took a look. The ability to refuel, fix and other things requires the distance between the target and player to be less than 4. After that, the distance between the fuel (i assume this is the vehicle fueltank) has to be less than 1.

if (!isNull _cursorTarget and !_inVehicle and (player distance _cursorTarget < 4) and _canDo) then { 
...
if(_hasFuel20 and !_isZombie and !_isAnimal and !_isMan and (_isVehicle or _isGenerator) and (fuel _cursorTarget < 1) and !a_player_jerryfilling) then {

I've been playing around with it and I think its a combination of both values needing to be greater 8 or 10 for cursortaget and 4 for fuel).   

ebay - looks like EPOCH has this fixed already for the cursorTarget:
// Increase distance only if AIR or SHIP
_allowedDistance = if ((_cursorTarget isKindOf "Air") or (_cursorTarget isKindOf "Ship")) then {8} else {4};

if (!isNull _cursorTarget && !_inVehicle && !_isPZombie && (player distance _cursorTarget < _allowedDistance) && _canDo) then {

but doesn't do anything about the fuel distance...maybe I just messed up on that check.

**Comment by ebaydayz** [comment]
Good catch @skigoggles . I overlooked that the allowed distance was changed for boats. The other condition is the actual fuel amount in the vehicle needs to be less than one (100%).

I will go ahead and make it eight meters for the fishing boat only, since vanilla doesn't have the other big boats and planes that Epoch does.

**Comment by skigoggles** [comment]
duh on me for the  (fuel _cursorTarget < 1). staring at code too long.

**Comment by bchawke** [comment]
Awesome, thanks for the fix guys!
