### ISSUE TITLE
small issue backpack duping alt-f4

### ISSUE THREAD

**Issue by Veltro-pm** [DayZMod/DayZ#562]
With this I like to report an issue that I found in server_playerSync.sqf regards to duping backpack after pressing alt-f4. I was doing some duping tests on a local test server trying to dupe a weapon which I failed to do so I tried a (empty) backpack and this worked every time. So I started wondering why it was so much easier to dupe the backpack in comparison to a weapon. I turned on debug line 185 and eventually I found that line 184 (_key = format["CHILD:201...) fails to send new backpack information (always sending []) and this does not refresh the backpack in the database.
So I setup a test and copied lines 88 and 89 right in front of line 184 (so that backpack information is always send)
_backpack = unitBackpack _character;
_playerBackp = [typeOf _backpack,getWeaponCargo _backpack,getMagazineCargo _backpack];
_key = format["CHILD:201...
After trying to use the same dupe method again (move backpack into tent, press alt-f4) I can see now that instead of sending [] now ["",[],[]] is being send. This resulted in a cleanup in the database and now when I login the backpack is not duped.
I know this probably will not fix all the duping, but I think it is worth looking into this anyway.
I would like to do some more tests on a live server sometime though to see if it also works with a full backpack or moving items from the backpack to the storage.
Best regards, Veltro

**Comment by R4Z0R49** [comment]
system updated thanks.
