### ISSUE TITLE
Quick Block Needed - Apartments Glitch Spot

### ISSUE THREAD

**Issue by HeroSmurf** [DayZMod/DayZ#563]
I'm terrible at block-item placement. 

Can someone take a look at this and put the appropriate item/block in the way so you can't behind the ladder in the squat apartments found in Cherno and Berezino?

http://dayzknights.com/video.html

**Comment by VidKo** [comment]
This glitch works only in the new building in Cherno. It doesn't work in Berezino.

**Comment by R4Z0R49** [comment]
Replaced both small apartment blocks in cherno.
