### ISSUE TITLE
Feature Request: ability to empty jerry cans

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#564]
The change log for 1.8.7 mentions adding the ability to empty water bottles.  A number of people have mentioned the idea of being able to empty jerry cans.  This would allow players to siphon fuel from vehicles and dump it out.  Good for various things.

**Comment by R4Z0R49** [comment]
Would it not just be better to take the fuel tank and dump it or drain the fuel tank?

**Comment by R4Z0R49** [comment]
Im not sure this would serve any purpose, but i can look at damaging the fuel tank on vehicles.

**Comment by KPanicEKS** [comment]
I think it's for the purpose of stashing cars... If there was a bunch of
extra jerry cans in the gear it would be nice to pour them out before
stashing. probably not the most environmentally friendly thing to do but
after all this is the zombie apocalypse ;-)
