### ISSUE TITLE
Wooden splint lasts forever and you cant give antibiotics to others

### ISSUE THREAD

**Issue by Landbergaren** [DayZMod/DayZ#567]
Hello!
At the moment in this patch the wooden splints will stay in your inventory on use. And you will be able to reuse it. I believe it never disappears but have not really checked if its only a few times that you can use it. Anyway its not working as it should. 

Also I would like to mention that you cant scrollwheel on a sick player and give him antibiotics in this patch. 

Thank you for your time and keep up the excellent work on the mod!

**Comment by R4Z0R49** [comment]
What server do you play on?

**Comment by Landbergaren** [comment]
DayZ Europa And the Elite (fps only server from Europa)

**Comment by R4Z0R49** [comment]
rgr thanks trying to get this verified we seem to be getting conflicting info. Some are saying there working as they should some are saying there not.

**Comment by bchawke** [comment]
Not sure about splints, but with antibiotics you can apply a _full_ box to another player, but as soon as it changes to a box with a quantity (5 or less) you cannot.

I'll try using splints on 434 this weekend to see what happens.

**Comment by R4Z0R49** [comment]
Antis should be fixed still waiting for info about the splint
