### ISSUE TITLE
Small wishlist

### ISSUE THREAD

**Issue by B73** [DayZMod/DayZ#568]
Wishlist
1. backbags could be dropped and used as a stashes (they would remain server restarts just like stashes/tents)
   You could also craft your own backbag and upgrade it.
2. antibiotics would be rare, like 1% chance to find them
   Nowadays no need to boil water for example, because antibiotics are common. Infection should be something to be feared about, something that could actually kill the player. Maybe hits from zombies should infect more often?
3. "textures" from stashes away, for example just an empty tin can on the ground indicating there's a stash in that place
   Now you have to glitch stashes inside objects (rocks, small shacks etc.) if you want to hide them, same goes with the tents so they both are quite useless for stashing goods.
4. from the previous wishlist, flying contraptions should be easily shot down - couple of bullets for example from Winchester or AK to rear rotor and it's gone.
   They would be suited for scouting and/or moving fast from place to place. Biplanes would go down also from couple of shots to engine.
5. take away bullet proof glasses from MI-17
   Oh the frustration when you see MI-17 on the ground and pilot sitting there, aim to the head with 7.62 weapon and bullets won't go thru the glass :D
6. semi-automatic rifles away
   More balanced that way.
7. common items could be used as traps
   Gas can on the road, car hits it and explodes. Works like C4. Empty tin can on the road, car drives over it and tires break. Traps are actually fun to make, but why are they so visible, for example rope and empty tin cans indicating there's a trap. It's too visible.
8. last one seems more of a dream (restrictions in Arma engine) but I'd wish to see bigger map. It's now 225 square kilometres, 1000 or more would be better. Then you would actually have a chance to hide your bases etc. Map nowadays is just too small for more than 30 players (IMHO), if you try to avoid other players for some reason, like when building a base. You can basically run thru map in short notice. That's the reason also why cars for example aren't needed at the moment. Bigger map = cars etc. vehicles are must to have. Or prepare to run like hours, or stay in nearest city you respawned to.

Keep up the good work guys! It's your fault, been spending 1000+ hours enjoying Dayz Vanilla instead of doing "something resonable" ;D

**Comment by bchawke** [comment]
Just some comments on a few of these:
1. That would probably destroy servers.  People would be leaving backpacks full of items everywhere.  There would _have_ to be some sort of cleanup time on these, like 24 hours or something
2. Devs are already talking about this.  Antis should be more rare once the new loot system is released.  I agree, infection from zombies should be much more common.  I think I've only gotten the sepsis warning 2 or 3 times in the last couple months of playing
3. The problem with this is that tin cans stick out like crazy.  I can see them from 100's of meters away (I've tracked players that leave cans laying around after eating).  I've made the suggestion of having the stash disappear at the same distance as grass.
4. That doesn't make much sense.  Vehicles should be difficult to take down.  Odds of taking something like an AN-2 down with regular firearms are really slim.
5. I agree you should be able to knock out cockpit glass with a few shots.  Once a player unloaded a 20 round mag of M14 point black at my head when I jumped in a chopper.  I didn't even get a scratch.
6. Really?  REALLY?  I think you're really misjudging DayZ mod's player base.  If you removed semi-auto rifles (and by that I'm assuming you'd want full-auto weapons removed) there would only be a few guns left in the game.  Double barrel, winchester, enfield, mosin, pump shotguns, CZ550 and bolt action sniper rifles would be the only thing people would be carrying.
7. There are traps that already exist in the game, but I believe they're bugged and don't work right now.  Press "i" or "j" to open your journal and click on the "craft" menu at the bottom.
8. Obviously tech limitations throw this one out.  Either way, increasing the map size is a bad idea unless you up the player count to 100+.  Just look at Standalone, they haven't increased the sq mileage of the map, but by adding several cities and towns and hundreds of new buildings and houses that you can loot, they've effectively increased the size of the map significantly, and you rarely _ever_ see other players outside of the coast.

**Comment by Jbird206** [comment]
all dumb except for 5

**Comment by R4Z0R49** [comment]
Thanks for the wishlist not really a detailed feature or an issue might be best placed on the dayz forums?
