### ISSUE TITLE
Why remove progression?

### ISSUE THREAD

**Issue by pSAJKD** [DayZMod/DayZ#569]
DayZ has allways been, and will allways revolve around how you progress your character.
Why would you think it would be a good idea to nerf the damage of the "top-tier" weapons such as
DMR, M40A5 etc.

Why run north at all when you can get the most powerful rifle of them all (CZ) in cherno?

DMR/M40/FN/MK/M14/M24 should all deal 8000 damage if its not a headshot to make these weapons
desireable, why else would you run north, farm crashsites to "upgrade" your gear, if the gear you are upgrading to is not better.

Just had an "awesome" fight today where i manage to follow a guy for over 10 minutes, sneak up close behind him and put 2 M40A5 rounds into him (100m distance), inb4 he manages to run around a bush and mindlessly spray me down through it with an MK48..

**Comment by R4Z0R49** [comment]
Sorry what damage are we talking about?

I cant think of any damage values that have been changed.

**Comment by ericandersen** [comment]
pSAJKD; what you experienced was most likely a combination of lag or mistaken hits vs misses. 

Due to the logs below what I said above is rendered uterly wrong. Sorry for assuming

**Comment by vinyljunkie** [comment]
These are the logs from the situation: 

First hit:
21:49:44 "P1ayer PID#146(XXX) hit by PID#174(Pariah) with M40A3_DZ/B_762x51_noTracer <ammo left:5> from 88 meters"

and from publicvariable.log: 

27.10.2015 21:49:44: XXX - #10 "PVDZ_sec_atp" = [<NULL-object>,<NULL-object>,"with M40A3_DZ/B_762x51_noTracer <ammo left:5>",88]
27.10.2015 21:49:44: XXX - #2 "PVDZ_hlt_Bleed" = [<NULL-object>,"Pelvis",1.41592]
27.10.2015 21:49:44: XXX - #2 "PVDZ_hlt_Bleed" = [<NULL-object>,"aimpoint",1.74275]
27.10.2015 21:49:44: XXX - #2 "PVDZ_hlt_Bleed" = [<NULL-object>,"lelbow",0.680781]

Second hit:
21:49:46 "P1ayer PID#146(XXX) hit by PID#174(Pariah) with M40A3_DZ/B_762x51_noTracer <ammo left:3> from 89 meters"

and from publicvariable.log: 

27.10.2015 21:49:46: XXX - #10 "PVDZ_sec_atp" = [<NULL-object>,<NULL-object>,"with M40A3_DZ/B_762x51_noTracer <ammo left:3>",89]

Hit from opponent: 

21:50:13 "P1ayer PID#174(Pariah) hit by PID#146(XXX) with Mk48_DZ/B_762x51_Ball <ammo left:84> from 8 meters"

and from publicvariable.log: 

27.10.2015 21:50:13: Pariah (IP) GUID - #10 "PVDZ_sec_atp" = [<NULL-object>,<NULL-object>,"with Mk48_DZ/B_762x51_Ball <ammo left:84>",8]
27.10.2015 21:50:13: Pariah (IP) GUID - #2 "PVDZ_hlt_Bleed" = [<NULL-object>,"aimpoint",1.98574]
27.10.2015 21:50:13: Pariah (IP) GUID - #2 "PVDZ_hlt_Bleed" = [<NULL-object>,"relbow",0.92313]
27.10.2015 21:50:13: Pariah (IP) GUID - #2 "PVDZ_hlt_Bleed" = [<NULL-object>,"LeftFoot",0.804657]
27.10.2015 21:50:13: Pariah (IP) GUID - #2 "PVDZ_hlt_Bleed" = [<NULL-object>,"Pelvis",1.67792]
27.10.2015 21:50:13: Pariah (IP) GUID - #2 "PVDZ_hlt_Bleed" = [<NULL-object>,"lelbow",1.01697]
27.10.2015 21:50:13: Pariah (IP) GUID - #7 "PVDZ_plr_Death" = ["271443",0,<NULL-object>,"76561198007608197"]
21:50:14 "Player UID#765XXXXXXXXXXXXX CID#271443 PID#174(Pariah) as Camo1_DZ died at Stary Sobor [58:81]"

I don't really know what to make out of it but it seems the second hit from Pariah's M40A3 doesn't hurt the opponent at all.
