### ISSUE TITLE
Backpack Proxies

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#570]
I have created a backpack proxie on O2, but I cannot seem to find the character models' ( or any model for that matter) location so I can go about merging them. Does anybody know how to and where to find them, specifically the OA ones?

**Comment by AsFoxy** [comment]
https://community.bistudio.com/wiki/Public_Data

**Comment by Lukethero** [comment]
@AsFoxy These are just the sample models, I need some more, specifically some more of the PMC skins, how would I go about finding those?

**Comment by AsFoxy** [comment]
I'm not sure what you're asking for. That link contains downloads to virtually all (some stuff like UI compass and GPS models aren't included) assets used in Arma 2 and Operation Arrowhead.

**Comment by Lukethero** [comment]
@AsFoxy Which particular one?

**Comment by Lukethero** [comment]
@Asfoxy As in which of those downloads contains all the models, because there are several.

**Comment by AsFoxy** [comment]
If you read the contents it says `Creatures - characters and animals` under the A2SM APL package. I guess if you're looking for character models you'll want that one.

**Comment by Lukethero** [comment]
Okay so I think I have found the issue, so for the list I am looking at at has these different models for the individual soldiers(https://community.bistudio.com/wiki/ArmA_2_OA:_Infantry), in this case, the PMC soldier. Any idea how to access the variations for the main model?
![image](https://cloud.githubusercontent.com/assets/10010221/10809901/b3e875e4-7dd1-11e5-8c7f-dedb360c687b.png)

**Comment by AsFoxy** [comment]
There is only one PMC soldier model and you seem to have found it. There's a bunch of different textures that can be applied to it at runtime if that's what you're thinking of? Those can be found in the ALDP A2OADLC package.

**Comment by Lukethero** [comment]
Are they just textures or model changes, because some models to change a little? For example, the PMC soldier, some of the "textures" have shin pads and a different vest

**Comment by AsFoxy** [comment]
Have you looked at Asano/Dixon/Frost/Gracenko at all? Those are the rest of the PMC skins they just have names corresponding to the characters in the PMC storyline.

**Comment by Lukethero** [comment]
I will look when I get home, but I believe those all just have 1 p3d in them.

**Comment by Lukethero** [comment]
So once I edit the model, how to I go about viewing it in bulldozer, and then do I need to bunarize it or something, or just drop as is into a pull request and edit the bandit and hero skin values?

**Comment by Lukethero** [comment]
And obviously add the referencing to the skins and renaming it.

**Comment by AsFoxy** [comment]
Okay i don't mean to be blunt but right now i suggest you take a step back. First you should familiarize yourself with the tools and Arma asset development. You should create a small addon to test things with in Arma. There's a lot of tutorials and guides floating around on the [BIS forums](https://forums.bistudio.com/forum/93-arma-2-amp-oa-modelling-o2/) and [Armaholic](http://www.armaholic.com/plug.php?e=faq&q=36) for example. Once you feel confident in your abilities we can discuss what is and what is not a good fit for Dayz before you spend a lot of time on a specific asset.

**Comment by Lukethero** [comment]
Yeah valid point, I have only worked on arma 3 model editing, figured I would just be able to transfer it over but it some things are different and file conversion tools are not outdated as crap.
