### ISSUE TITLE
Base fire issues

### ISSUE THREAD

**Issue by BushmillsLover** [DayZMod/DayZ#571]
Hi,

I play on Europa Elite (1st person view only)
2 issues/questions here:
- Can a base fire (permanent fireplace) be removed ?
  I have toolbox, crowbar, eTool, Pickaxe in my inventory, no Remove menu appears when scrolling.
  I also tried hitting it with a hatchet, stopped after 80 strokes, nothing happened.
- Also, I tried storing a woodpile in an UNLIT base fire before logging off. When I logged back in, a couple of days later, woodpile was gone. Is this supposed to do that or is it broken?

Thanks

**Comment by R4Z0R49** [comment]
System will be removed as part of the base system removal.
