### ISSUE TITLE
M4a4 not spawning

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#575]
In 1.8.6 the m16a4 does not spawn, not sure if this has been fixed in 1.8.7 due to the new attachments, but I have not seen it yet in my very light testing of the update.

**Comment by AsFoxy** [comment]
If you mean the old desert camo M4A3 with the CCO and flashlight that has been removed since 1.8.6.

**Comment by Lukethero** [comment]
Whoops meant m16a4, renamed the issue.

**Comment by AsFoxy** [comment]
It's in the loot tables same as anything else if you 've found any weapons at all in military buildings i'm going to conclude you've simply not found an M16A4 yet.
