### ISSUE TITLE
pCleanup issue

### ISSUE THREAD

**Issue by cikez** [DayZMod/DayZ#576]
When running pCleanup I get the result:

/\* Affected rows: 0  Found rows: 0  Warnings: 0  Duration for 1 query: 0.281 sec. */

But when I look in my object_data table I still see several vehicles, tents, etc.. with 1.00000 damage. It does not seem to be deleting objects with damage at 1.00000.

Is this a bug or am I missing something?

**Comment by kichilron** [comment]
You will have to call pCleanup on the instance you're running your server on. 

For example, if all your object_data is stored in instance 1337 and you call pMain(23), it will only clean up instance 23, not 1337.

**Comment by R4Z0R49** [comment]
I'm not sure whats happening on your system but this seems to be the first report of it happening.

the code used is very simple you don't need anything special.

#remove damaged objects
        DELETE
                FROM object_data
                WHERE  Damage = 1;

**Comment by cikez** [comment]
Ok. How exactly does pcleanup go about removing damaged vehicles using the CleanupTime in vehicle_spawns?

**Comment by R4Z0R49** [comment]
oh ok your running the new system.

It wont cleanup old vehicles until that vehicle hits the timeout in the vehicle_spawns. This turns the spawning systems back into the original system we used on the official hive some time ago.
