### ISSUE TITLE
My point of view on balancing the lootrate

### ISSUE THREAD

**Issue by Landbergaren** [DayZMod/DayZ#577]
I think some of the big items could need some tweaking in the spawnrate. All the LMG's spawn pretty frequently. But I've heard rumors that you are already planning on balancing them. 

So moving on. I think the huntingtowers/deer stands are pretty much ignored by most of the players at this state. Something that could make them a little bit more interesting could be to make the cz spawn a liiiitle bit more frequently. Just a small tweak since they are very hard to find and to me it feels like it should be the most casual sniper. Or maybe its enough to make the cz-mags spawn a bit more frequent. I like that they are rare in farms though. 

Also the Alice pack is way to easy to find atm. They should not be easier to find then the Brittish assault -pack if you ask me. Maybe limit them to castles and perhaps deerstands? Or make them as rare as the Survival ACU is. Recently its hardly a task to get a good backpack. You expect to have 18 slots when leaving the first town. Its too easy and removes a bit of the looting-aspect of the game. Also it have put the Brittish Assault pack in some shadow. 

Thanks for some great job and good luck with the next patch-release!

**Comment by AsFoxy** [comment]
All loot spawning has been rewritten from scratch, including loot tables, meaning observations from the current stable version are out of date. You can try out the new version on the test server.
