### ISSUE TITLE
DayZMod Dev-06f563f-PreRelease

### ISSUE THREAD

**Issue by R4Z0R49** [DayZMod/DayZ#578]
Full change log and source can be found here.

https://github.com/DayZMod/DayZ/releases/tag/Dev-06f563f

Download links
http://se1.dayz.nu/latest/.testsystem_1.8.7/@Client-DayZMod-Dev-06f563f-Full.rar

Post updated 30/11/2015

**Comment by AsFoxy** [comment]
Scroll menu action to switch to weapon on back shows the wrong text.

**Comment by thisisgeoff** [comment]
Winchester ammo has no name in gear menu and cannot be used.

**Comment by thisisgeoff** [comment]
Tripwires - I was only able to get the smoke tripwire to activate after being placed initially. Disarming and rearming the trap allows all tripwires to activate.

Bear traps - Flare and smoke needed to be disarmed and rearmed before being able to be activated.

All traps once disarmed/rearmed remained armed after logging out.

**Comment by thisisgeoff** [comment]
With UK-59 -

"Cannot load texture dayz2\dayz2_weapons\uk59\data\uk59_co.paa"

Ammo has no name/text in the inventory, but the gun can be fired.

**Comment by R4Z0R49** [comment]
CyrilFDZ - Its one we have fixed already d80bf915b304a5943ed09be65bef60350f7a2d44

thanks

**Comment by thisisgeoff** [comment]
When giving antibiotics to another player it does not take an antibiotic pill away.

Also the text says "You have taken antibiotics" instead of "You gave antibiotics"

**Comment by Fenwick101** [comment]
On low blood im going into Knockout , i can see the knockout timer but can still move around and change weapon etc... after timer is complete char is back in prone position.

Also there is a sort of 'fall' animation possibly because of low blood you go prone then are able to stand  back up WITHOUT a timer .. is this new feature or a bug in the Knockout animation ?

**Comment by R4Z0R49** [comment]
sounds like a bug

**Comment by Fenwick101** [comment]
Apart from that Knockout bug were you can still walk around, the patch looks Legit GG R4Z0R49 cant wait. Quick question ... is the new ACOG able to be swapped between the G36 , M4 , M16 or are they tied to each weapon I.E "ACOG M4 cannot be attached to G36" or vice versa ?

**Comment by AsFoxy** [comment]
There is one ACOG that fits all applicable weapons.

**Comment by Fenwick101** [comment]
Good cheers Bud :)

**Comment by PatriotCZ** [comment]
Gosh, this "new" attachment system is getting better and better :3 great feature. Also, are these pre-releases only for server owners or are there some servers I can join. :)

**Comment by Fenwick101** [comment]
check the link in the 1st post by R4Z0R49 scroll to bottom DL and IP for test server is all there

**Comment by PatriotCZ** [comment]
Ah.. Thank you, kind sir.

**Comment by AsFoxy** [comment]
It's for testing, the patch isn't quite ready to go public yet.

**Comment by vinyljunkie** [comment]
I have trouble boiling water. I have two water bottles and an empty tin can but won't get the option when by a fire place. Also I have tried with different tin cans as I remember one of them being bugged earlier. No difference.

**Comment by Lukethero** [comment]
@Fenwick101 The falling buy not getting knocked out is just a feature while low blood. As for the moving while knocked out, I am pretty sure that has been in the game ever since they tried fixing it so you could not move while knocked out, obviously it did not work. I think it might occur more when blood levels are lower, but that could be wrong.

**Comment by R4Z0R49** [comment]
All links updated for new.build

**Comment by Rayboy13l7** [comment]
2rnd Slugs and 2rnd Gauge share the same name and image: 2 Rnd. Slug

**Comment by R4Z0R49** [comment]
Dev-06f563f Released with many fixes.

Thanks

**Comment by Detoeni** [comment]
tried the above version on the fragnet dev server but returns incorrect mod version message. is there another server up for testing?

**Comment by R4Z0R49** [comment]
The current server is running a different version just now. The new version will be up at the weekend.
