### ISSUE TITLE
add simple sliding log/plank lock that can only be operated from inside

### ISSUE THREAD

**Issue by texoft** [DayZMod/DayZ#579]
Having to have a padlock to make lockable gate is very limiting especially after you base was raided. You can spend weeks looking for another padlock.

Instead I propose to have an upgrade that would create (as some ancient/medieval castle gates had it) have a plank acting as barricade that can be operated by anyone, but only from inside.

**Comment by R4Z0R49** [comment]
this should be possible.

**Comment by Flamberg** [comment]
Door latch? Crossbar? Bolt?

**Comment by texoft** [comment]
Yes, something like this: https://en.wikipedia.org/wiki/Latch_(hardware)#/media/File:Asso,_chiavistello_porta_Magnocavallo.JPG

**Comment by ghost** [comment]
great idea, both wood and metal versions.  nice.
this should encourage more base building, as padlocks are too hard to come by.
would also ease frustrations regarding the base build system-  patience is tested when padlocks are so hard to come by.
