### ISSUE TITLE
instant respawn breaks survival gameplay

### ISSUE THREAD

**Issue by texoft** [DayZMod/DayZ#580]
Being able to instantly respawn after you have died causes many players to even kill themselves to get better spawn or rush to pick-up gear from their corpse after they have died. This breaks survival immersion as it favors suicidal gameplay styles - after you have died you should be dead for some time (say couple hours or a day).

**Comment by ghost** [comment]
Yeah, like you should be kicked out of the game "say couple of hours or day" if some prick shoots you in the face in Balota two minutes after spawning at the coast. Really?

**Comment by R4Z0R49** [comment]
Its not a realistic system of gameplay.

thanks for feedback.

**Comment by texoft** [comment]
Thanks for bashing. :(

**Comment by texoft** [comment]
@dayzjarhead

I'm aware of bambi hunting, but on most good servers this shouldn't be much of an issue. If the server has bambi killing en masse I don't want to play there anyways.
Plus you could be given say a 5 minute grace period after respawn where you wouldn't get kicked if you got killed by someone else. 

I just don't like your attitude - instead you could've said: "was tried, didn't work because of X".

**Comment by ghost** [comment]
Ah, sorry for sounding dickish. Normally not my kind of talk.

**Comment by R4Z0R49** [comment]
@texoft It's not something we have tried but id expect it to cause alot of problems who prefer to play on certain servers. However it might be something the hardcore gameplay crowd would like to see.

So ill reopen see what info we get back on this.

**Comment by texoft** [comment]
Thanks guys! :)
Came here from dayzeuropa forum post, so I didn't realize this would be taken for dayz in general. It should definitely be a server option, not enforced on everyone.

**Comment by skigoggles** [comment]
Assuming this is an issue, you could tweak it and fix some of it. Make it that you can't respawn within so many meters of your body. Can't fix everything 100%

**Comment by R4Z0R49** [comment]
Thanks for the feedback im going to close this. Its not something we are looking to do for now.
