### ISSUE TITLE
New clothes

### ISSUE THREAD

**Issue by PatriotCZ** [DayZMod/DayZ#581]
I know probably something simillar was mentioned already, but' I'll post it again. The same way we can find army and ghillie clothing, it could be cool if we could find more variants. I am not talking about making clothing the same way it's done in SA. but about just being able to find skins. Arma 2 already has a lot of cool looking ones...

http://www.clan-ado.fr/wiki/images/upload/article_35/l_35_1366024644.jpg

And a little more "bandit like" looking
http://ttp2.dslyecxi.com/images/iff_inf_chdkz.jpg

excuse my english :)

**Comment by R4Z0R49** [comment]
The problem with alot of the models they do not contain any backpack proxy's.

**Comment by PatriotCZ** [comment]
Ah, I see...
Is it complicated to add them?

**Comment by R4Z0R49** [comment]
You would need someone who knows what they are doing model wise.

**Comment by R4Z0R49** [comment]
Going to close this one till we have someone willing to do the proxy's

**Comment by Lukethero** [comment]
@R4Z0R49 @PatriotCZ  I have added proxies to multiple skins, just figuring out how to binarize and add it in. I will update as I go along.

**Comment by Lukethero** [comment]
Also buldozer is a bitch and does not work on my PC, so I have to use blender, which is proving a hassle.

**Comment by PatriotCZ** [comment]
Yes, great news man.. I tried myself to do it. But I didnt understand how the heck i should use those programs. I hope you get it working and ready to be added. I wated this feature so for long already

**Comment by Lukethero** [comment]
Yeah, heads up though, I think they will be used for different levels of bandits/heroes, not as pickup items. That is all if I can relaern true and false statements for programming. @PatriotCZ
