### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by PatriotCZ** [DayZMod/DayZ#582]
Title says it all. Different animations for basiclly everything,, Hard work but it would definitely improve atmosphere. I am sure there are many animation that could be used already, in ArmA. I remember some of them when I was making my own missions in ArmA.

**Comment by AsFoxy** [comment]
Some already exist and we might use in the future, but making new animations for Arma is not very easy.

**Comment by PatriotCZ** [comment]
Glad to hear that.
