### ISSUE TITLE
Changeable FOV

### ISSUE THREAD

**Issue by PatriotCZ** [DayZMod/DayZ#583]
I am not entirely sure if this has anything to do with DayZ mod, probably not. 
Default FOV is making me crazy. Most of the time I am playing with double tapped "zoom out" (-) button, but that doesn't work everytime. For example when I am in car, in first person, game is just not letting me toggle zoom out. Is it possible to make some sort of slider that allows player to adjust FOV as needed? It should probably be ArmA feature, right?

**Comment by AsFoxy** [comment]
You can change it in %userprofile%\documents\arma 2\arma2oa.cfg i believe.

**Comment by kichilron** [comment]
I suggest you try googling first, as this is a well documented tweak for ARMA 2 and has nothijg to do with DayZ.

DayZ is just a mod, remember.

**Comment by PatriotCZ** [comment]
Well, I knew about some of the tweaks, But I wasn't sure if it would let me join server. Didn't want to risk to get banned.
