### ISSUE TITLE
Request, leave base building items in the files

### ISSUE THREAD

**Issue by Jbird206** [DayZMod/DayZ#584]
as an admin, it was really fun to play with the shantyhouse, shack and other base building options. I see you are removing all in the next patch but, could you reimplement them in the files for some of us to enjoy?

**Comment by PatriotCZ** [comment]
Me personally, I would leave them in game.. It's fun, I haven't built any but, right now on 1 server I am preparing an attack. And that what's entertaining about them for me :) Breaking in

**Comment by R4Z0R49** [comment]
They will no longer be able to be built. But they will still exist
