### ISSUE TITLE
Zombies around dead bodies not attacking

### ISSUE THREAD

**Issue by ghost** [DayZMod/DayZ#585]
While its awesome that z's gather around dead bodies,  It kinda sucks that they don't attack while doing so.
It makes sense that some would stick around and feed, but not all.  
Also the feeding animation seems to not work all the time.

For example:  https://youtu.be/BHTxO_zvVfM?t=206

**Comment by Lukethero** [comment]
Well I do like the fact that they primarily feed on the body. If you think about it realistically, why would they chase after somebody else if they are preocupied shoving their faces into some perfectly good meat? When you do get close enough though I am pretty sure they swat at you.

**Comment by R4Z0R49** [comment]
ok it looks like the reset to loiter state is broken ill take a look.

**Comment by ghost** [comment]
sweet

**Comment by R4Z0R49** [comment]
Hopefully fixed
