### ISSUE TITLE
Arming hatchet from inventory is quicker than using scroll wheel

### ISSUE THREAD

**Issue by ghost** [DayZMod/DayZ#587]
When arming hatchet from inventory (already on back) by clicking the arrow, the hatchet is armed immediately.  When using the scroll wheel however, it is not.

It would be much better if the arm time was the same for the scroll wheel as it is the inventory method.
Also the time it takes seems to vary when using scroll wheel.

i.e. it is quicker to bring up the inventory and hit the arrow, then close the inventory than it is to use the scroll wheel.

**Comment by R4Z0R49** [comment]
Use the hotkeys?
