### ISSUE TITLE
Post processing effects when severely hurt is a bit excessive in 1pp

### ISSUE THREAD

**Issue by ghost** [DayZMod/DayZ#588]
Should atleast be able to see enough to escape.  I agree with some blur at low blood levels/shock, but not so much you cant look to replenish health.  I have my PP set to low- at low health i just end up switching it off so I can actually see well enough to find what i need to heal.
Current state is discouraging use of postprocessing in 1pp.  Which is a shame because it really adds to the immersion factor.

**Comment by vinyljunkie** [comment]
Agreed, this is how it looks: https://youtu.be/46dDCdo8vBw?t=42s
