### ISSUE TITLE
FN FAL fire rate

### ISSUE THREAD

**Issue by Comanche6** [DayZMod/DayZ#589]
Should be SEMI or AUTO, not BURST. Reference:

https://en.wikipedia.org/wiki/FN_FAL

**Comment by AsFoxy** [comment]
Sure thing. 06248e3

**Comment by Comanche6** [comment]
Thanks. Sorry if I was unclear in OP:

FN FAL is SEMI and AUTO (not BURST)
L1A1/C1A1 etc. are SEMI only.

**Comment by AsFoxy** [comment]
Yes i know what you meant. Thanks.
