### ISSUE TITLE
Mosin Issues/Possible Remove

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#593]
The mosin serves very little purpose in the game as it is.

 The gun's sound is pretty broken and does not have good distance fall off. When the gun is fired, a player 200, 300, 400... meters away hears it the same just as the player firing it would. On top of this the player x meters away can hear the bolt being cycled, which is incredibly silly. 

The recoil of the gun is HUGE, too much so to even consider taking a follow up shot. This is most visible using the scope because the thing jumps like you were hipfiring a 50. cal. The sight picture on the scope is also incredibly small and the reticle sucks making precision hard.

This is an easier fix but just adds to the pointlessness of it. All the broken mosins just fill the loot spawns with pointless gear, because it is not able to fixed.  The ammo belts also are extremely common and are just junk at this point, and basically do nothing but improve the reload by an almost unoticable difference.

The accumulation of the bugged sounds, broken recoil and scope, and saturation of the loot spawns leads to a gun that nobody uses and has no practical use. It is for these reasons why I believe the gun should just be removed, because the effort that would need to going into fixing all this is just a waist of time. The loot problem might be fixed in the new patch due to new system (have not been able to test the new patch), but the issue still stands. Guns in the mod should feel real and unique, not just copy pasted into the game.

**Comment by AsFoxy** [comment]
None of these issues seems particularly difficult to fix. You were talking about doing models before, how would you like to contribute by modeling a [PU scope](https://www.preciseshooter.com/blog/MosinSniperPart6/Mosin%20Ukrainean%20sniper.jpg) for the Mosin?

**Comment by R4Z0R49** [comment]
If we remove everything because of a bug the mod would have stopped years ago. Its an alpha and will remain an alpha report issues if we can fix we will try our best to do so.

Your more then welcome to help out with testing before broken items get added to the stable builds.

Thanks for the report i'm sure foxy will have it fixed up in no time.

**Comment by Lukethero** [comment]
The sound having to be redone is the biggest issue. I can do the scope though, bulldozer hates my PC for some reason, so I have to wait for new PC parts come in,  but after that, sure.

**Comment by R4Z0R49** [comment]
recoil fixed, sound falloff fixed, ammo belt reduces the reload time by 2.8 (ie the reload time of the magazine)
.

Not sure whats wrong with the current pu scope?

**Comment by Lukethero** [comment]
I assume being able to hear the bolt being cycled will always be a problem unless the sound is redone? And the current PU scope is not horrible, just was a little nasty , adding a minor reason for why it was pointless. 

Next biggest thing I would say, besides the bolt cycle sound, is remove the broken versions from the loot spawns. Other than that, it might be a semi-viable gun now!

All this talk of the PU scope gave me an idea, opening a new issue.

**Comment by AsFoxy** [comment]
We have someone making a new scope model.

All broken Mosins are being removed until such time that a proper degradation system is implemented.

The sound needs to, and is being replaced to fix the bolt audibility.

**Comment by Lukethero** [comment]
What is wrong with the current PU scope model? The lack of mildot is accurate to the real life counterpart. The only issue I can see with it is that it seems like your character is holding it 2 feet from his face, so maybe just have it choked up on the sight a little more to improve viewing angles?

**Comment by AsFoxy** [comment]
There is no current PU-scope. I previously posted a picture of one. You can compare that to the ingame one.

**Comment by Lukethero** [comment]
What scope is in the game currently? Whatever it is looks very similar to the PU scope.

**Comment by AsFoxy** [comment]
Apart from the reticle it looks nothing like a PU scope. Either way it's being remodeled.

**Comment by Lukethero** [comment]
Just did a little research. The item sprite is obviously a PSO-1 scope, just like that of the Dragunov, but the world model is clearly something different, and same with the reticle. It appears to be a PEM scope (http://mosinnagant.net/sniper%20section/images/GECOoffmount.jpg). Apparently.it is very similar to the PU scope, just varries a little in magnification. http://www.calguns.net/calgunforum/archive/index.php/t-384197.html
