### ISSUE TITLE
Issue with Backpacks

### ISSUE THREAD

**Issue by tacticalforce** [DayZMod/DayZ#6]
I think I may have found a bug or if its something that you guys added in on purpose. But I went into editor and created my own test mission to preview some of the new items. I placed backpacks on the ground so I can test picking them up. I can pick up one and than I go to drop the backpack from the gear menu and then I try to go pickup another backpack it will not let me pick it up. The menu option is there but it doesn't do anything. Is this possibly a bug?

**Comment by R4Z0R49** [comment]
I'm not 100% on this but as its not effecting game play ill make it as invalid and verify.

Just in case someone gets time to check.

**Comment by MattzFiber** [comment]
I am quite sure this is due to some models not being able to use backpacks (Arma thing)
I tried with 2 bags and was unable to reproduce
