### ISSUE TITLE
pCleanupOOB() not parsing worldspace correctly

### ISSUE THREAD

**Issue by skigoggles** [DayZMod/DayZ#601]
I believe the parsing of worldspace in pCleanupOOB is broken(since 1.8.6.1).

The splitting of the worldspace column is one of those crazy lines of code, IMO:
SELECT REPLACE(SUBSTRING(SUBSTRING_INDEX(@rsWorldspace, ',', 2), LENGTH(SUBSTRING_INDEX(@rsWorldspace, ',', 2 -1)) + 1), ',', '') INTO @West;
SELECT REPLACE(SUBSTRING(SUBSTRING_INDEX(@rsWorldspace, ',', 3), LENGTH(SUBSTRING_INDEX(@rsWorldspace, ',', 3 -1)) + 1), ',', '') INTO @North;

Upon researching , it's basically the same as found here: http://stackoverflow...into-temp-table
When I run through each step on paper it seems to be correct.

Finally, after debugging for a while I'm seeing that the @West value is generally not being set correctly.  I created a log file and added this to pCleanupOOB() - just decomposed pieces of the code above. The bold/ text are the values from my log file:

insert into aalog values  (@rsObjectUID,  **130279766221295**
@rsWorldspace,  **60,13027.9,7662.17,-0.01**
SUBSTRING_INDEX(@rsWorldspace, ',', 2),  **60,13027.9**
SUBSTRING_INDEX(@rsWorldspace, ',', 2 -1), **60**
LENGTH(SUBSTRING_INDEX(@rsWorldspace, ',', 2 -1)) + 1,  **3**
SUBSTRING_INDEX(@rsWorldspace, ',', 2),  **60,13027.9**
SUBSTRING(SUBSTRING_INDEX(@rsWorldspace, ',', 2), LENGTH(SUBSTRING_INDEX(@rsWorldspace, ',', 2 -1)) + 1),   **13027** 
@West, **13027**
@North, **7662.17**
@Height);  **-0.01**

This is a simple case that loses the .9, but there are others. When its decomposing the worldspace, the @West variable string thats extracted includes the leading comma, so the number doesn't always get converted properly.  The solution seems to be :

from this

> > LENGTH(SUBSTRING_INDEX(@rsWorldspace, ',', 2 -1)) + 1
> > to this:
> > LENGTH(SUBSTRING_INDEX(@rsWorldspace, ',', 2 -1)) + 2

I was a software developer for years, so I like it when a good "+1" just fixes it, but I'd like to hear from someone else that's noticed this.  Has anyone else seen this code cleanup OOB items?

If you'd like to see for yourself, I've attached a new version of pCleanupOOB() that logs the data and the SQL for the simple log file
[pCleanupOOB.txt](https://github.com/DayZMod/DayZ/files/69238/pCleanupOOB.txt)
[aalog.txt](https://github.com/DayZMod/DayZ/files/69239/aalog.txt)

 You'll see I added @Height to pickup the Z value since I wanted to look for helis left on buildings.  Also, I have 2 inserts into the log file - the first with the original values and the  second with the +1.

**Comment by R4Z0R49** [comment]
Do you wont to submit a fix for this.
