### ISSUE TITLE
randomizeVehicleInventory() - MagazineClasses is too short

### ISSUE THREAD

**Issue by skigoggles** [DayZMod/DayZ#602]
This is for 1.8.6.1(I know, I'm late to the game here).

I wrote my own inventory spawn code and its not too hard to end up with a MagazineClasses string that is longer that 255, especially ig you put a bunch of stuff in a URAL.

Anyway, I changed to:
    DECLARE MagazineClasses     VARCHAR(512);

**Comment by R4Z0R49** [comment]
Can you submit a fix for this.
