### ISSUE TITLE
Arma 2 Update Ruins Medical Boxes

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#604]
Not sure the technical reasons for it, and cannot claim to know what they changed in the patch, but currently the medical boxes are broken. I think if you even run in the proximity of the medical boxes, they will disappear, but it is 100% confirmed that at least inspecting the loot will make them go away. On top of this, if you do manage to look in the box, there will be nothingnspawned inside. Probably will sound like a complete idiot, but maybe it has to do something with the magazines?

This is the biggest change that I think cane with the patch besides a few rifles gaining some zeroing. Feel free to open a new issue for any problems that anybody encounters.

**Comment by fgw-** [comment]
this should be fixed already in the next beta patch! lets see if it works as supposed ...

unfortunately i have no idea how to workaround this from within dayz, thus i'm still running old beta on my test server

**Comment by R4Z0R49** [comment]
Fixed in new patch
