### ISSUE TITLE
Any plans to add vehicle spawn inventory?

### ISSUE THREAD

**Issue by skigoggles** [DayZMod/DayZ#605]
I added a bunch of custom code based on the 1.8.6.1 framework. Is there going to be a vanilla version of it?

**Comment by R4Z0R49** [comment]
yea at some point im going to redo the default gear.

**Comment by skigoggles** [comment]
My bad, I should have attached the version I created. Some vehicles and groups of vehicles have a 
theme loadout. Take a look and I'm happy to tweak it to something agreeable, if you have a plan. In the vehicle_spawns file I may have messed with other column values, but only the FK to vehicle_inventory is important.

[vehicle_inventory_CUSTOM.txt](https://github.com/DayZMod/DayZ/files/83440/vehicle_inventory_CUSTOM.txt)
[vehicle_spawns_CUSTOM.txt](https://github.com/DayZMod/DayZ/files/83441/vehicle_spawns_CUSTOM.txt)

**Comment by R4Z0R49** [comment]
Thanks ill take a look soon as i get a little time.

**Comment by skigoggles** [comment]
added to github
