### ISSUE TITLE
DomeTentStorage holds 150 items while DomeTentStorage0 holds 100

### ISSUE THREAD

**Issue by skigoggles** [DayZMod/DayZ#607]
DomeTentStorage holds 150 items while DomeTentStorage0 holds 100, Given the progression is +25 from DomeTentStorage0 [100] to DomeTentStorage4 [100], I'm guessing the original DomeTentStorage should actually be 75.

**Comment by R4Z0R49** [comment]
Ill add it to my list of stuff thanks.
