### ISSUE TITLE
Problems with repairing vechicles

### ISSUE THREAD

**Issue by Erandon** [DayZMod/DayZ#61]
There are some problems with repair system:
1) Status shown from driver seat is other that status shown by parts seen in repair window with toolbox. Example: UAZ was all orange/red from driver seat but all part looked repaired from repair box (had toolbox) or a bike that from driver apeared to be all green while through repair look all orange

2)There is some issue with repairing motocycle. You cant see rapair option for weels even when they are damaged or broken

**Comment by facoptere** [comment]
Can you still see these problems after a fresh restart while you are alone on the server? 
I mean, how do you ensure that a cheater never tweaked the vehicle before you get in?

The problems related here are desyncs between vehicles variables stored by DayZ Mod (what yo can see in the menus) and ArmA2 engine vehicle damages (what you can see on the vehicle). We can't get parts damage from the engine, we can only ask the vehicle owner to set them according to our variables.

**Comment by Erandon** [comment]
I have done some more tests and here are results:
On 3 official server i found heli in devils castle (M17 military) unrepairable from pilot wiev all things except hull is red from repair window i cant see anythink so looks like this patch have sth with it.

Also tried on few serwers motocycle cant have wheels repair instead they are repaird with serwer restart so after braking wheels in motocycle you have to wait for next serwer restart to ride it again

Thing that i could not repair car (UAZ) that was red and cant be rapaired didnt happen again to me so it may be some cheater think

**Comment by facoptere** [comment]
Maybe there is a bug in this helicopter part definition.
For other issues, I assume the vehicle has been cheated, or the server needed a restart (server should restart every 3 hours, ).
I don't have any feeds back from the players on my server about repair issue, neither on dayzmod forum.
