### ISSUE TITLE
SVD zeroing/CZ550 no zeroing

### ISSUE THREAD

**Issue by Jbird206** [DayZMod/DayZ#610]
I'm not sure what happened but, in the last few months there has been some weapon tweeking. With the above mentioned and the G36k. Was this an arma patch or update i missed? there shouldnt be any zeroing on an SVD.

**Comment by AsFoxy** [comment]
Yeah there was a patch for Arma. Silly Bohemia and the community patch screwing up all the things. What is the issue with the G36K you mention?

**Comment by Jbird206** [comment]
Nothing huge, they just removed burst mode.

**Comment by skigoggles** [comment]
fyi: here's the bohemia post with details, discussions and arguments: https://forums.bistudio.com/topic/186695-a2a2oa-patch-18122015/

**Comment by R4Z0R49** [comment]
e70a559b89abeaedc041bdc73868ef1fc6ff8c8d

Updated.
