### ISSUE TITLE
base_fire last_updated is never set / base fires are never cleaned up

### ISSUE THREAD

**Issue by skigoggles** [DayZMod/DayZ#611]
starting to notice base fire proliferate and would like to see them cleaned up like sand bags and other similar items.  Would need to set last_udpated, whenever the last fire was started and then add some removal code to pCleanup() like this:
# remove base fires older than twenty one days

```
    DELETE
            FROM object_data
            WHERE Classname = 'Base_Fire_DZ'
                    AND DATE(last_updated) < CURDATE() - INTERVAL 21 DAY;
```

**Comment by R4Z0R49** [comment]
Your welcome to push that into the code :-)

**Comment by skigoggles** [comment]
Sorry I wrote a mess there - I meant to say should be cleaned up, say 21 days after last used.  

last_updated in the object_data table isn't set when a fire is started, only on creation of the base_fire. I've been looking for the right place - is it player_makefire.sqf?   [i'm more comfortable with the DB than the other code structure]

**Comment by R4Z0R49** [comment]
last_update should be filled in by mysql. Let me check on that

**Comment by R4Z0R49** [comment]
We have a new system in pcleanup to remove base fires after 5 dayz if the original char who placed it dies.
