### ISSUE TITLE
possible splint bug

### ISSUE THREAD

**Issue by ghost** [DayZMod/DayZ#612]
yesterday i accidentally broke my mates leg with a hatchet and went searching for string and wood to make a splint, after the splint was made i thought i would give a go at putting the splint on him myself, when i looked at him the option i was given was to give morphine, once this was done his leg was fixed !

is this a mislabeled menu option or an actual bug, one of the two splints was missing as would normally be the case ?

**Comment by R4Z0R49** [comment]
Morphine also fixes broken bones.

This will be updated later on so only splint's will fix bones and morphine will be used for pain.

**Comment by ghost** [comment]
i didn't have any morphine at the time just 2 splints, that's why i couldn't understand it.

**Comment by R4Z0R49** [comment]
Ok thanks fixed.
