### ISSUE TITLE
Suggestion: Weapon on your back.

### ISSUE THREAD

**Issue by Takisehejter** [DayZMod/DayZ#614]
So i played some DayZ mod, and i found a cool feature that is not able to use (for now). When you have a hatchet and a gun, you can switch the hatchet to your hands, and then, replace it with a weapon. You have now two weapons, one in your hands, one on your back. The only thing that destroy it, is that the game dont wont You to carry two guns at the same time....... Why you han handle a hatchet, but you cannot a weapon? What is the difference? I suggest to fix that and implement to the game.

**Comment by kichilron** [comment]
There's no plan for implementing that at the moment. Even though the hatchet looks like it's massive in the game, it's a hatchet after all (which means it's onehanded) and not an axe. Thus, only a pistol would be the size of the hatchet.

It's a compromise that has to be made, being able to carry one mellee- and one primary weapon.
