### ISSUE TITLE
Pickup (PK) in 1.8.7 spawns without Ammo 

### ISSUE THREAD

**Issue by vinyljunkie** [DayZMod/DayZ#615]
Also, the PKM mag I had on me couldn't be used. And trying to use the PK turns the engine of the Pickup on. Not sure that is a feature or a bug.

**Comment by kichilron** [comment]
If I remember correctly that's because the turret is theoretically not being turned by manpower, but with the power of the jeep.

**Comment by vinyljunkie** [comment]
Fair enough. Thanks!
