### ISSUE TITLE
Backpack in stashes

### ISSUE THREAD

**Issue by LO0TC1F3R** [DayZMod/DayZ#618]
with Base building gone in 1.8.7 (which I appreciate immensely since it killed the "Never be sure about keeping your gear" - feeling of dayz that I loved so much) and the old issue being closed I would like to once again ask the question wether storing a backpack in a stash is a possibility in the near future?

The arguments for it are the old ones: storing in tents is too risky because of the rendering distance and from the point of realism it makes sense that a backpack would fit in an upgraded stash. Now it would also probably console the players that will miss the security of their bases a little.

**Comment by KPanicEKS** [comment]
I totally agree with this request. it would be nice to be able and throw a
backpack in a stash being that they are small and could be folded up IRL.

Maybe 1 for a small stash and 2 for large stashes?

**Comment by Inurosen** [comment]
Agree with this one. Medium stashes should be able to keep one backpack inside.

**Comment by R4Z0R49** [comment]
Ill look into it for medium
