### ISSUE TITLE
1.8.7 Release

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#619]
For one I would like to know when the release of the new update is coming. I know it was in the works and almost out before the whole Our_mine thing, but that is over now. Lots of people are looking foreward to this and an update on the situation would be apriciated.

Secondly, I would have posted this on the forums, but it seems to be broken and people cannot reply on threads posted there. Might want to check that out.

**Comment by ghost** [comment]
What is the Our_mine thing?

**Comment by kichilron** [comment]
We (Mod-Devs and Moderators) haven't had access to the Forum for about a month now.

That's why we will not be able to respond to anything posted on there. Might change in due time, but who knows.

**Comment by kichilron** [comment]
Wring button & on the phone. Sorry guys...

**Comment by Lukethero** [comment]
Our_mine are theguys who hacked Bohemia Interactive. But yeah, the more important thing, any news on the update?

**Comment by R4Z0R49** [comment]
Pushed to steam.
