### ISSUE TITLE
Dayz launcher

### ISSUE THREAD

**Issue by vitalzus** [DayZMod/DayZ#620]
i load up launcher and it say i need to update it so i do then it still says i need to update when i have updated it a few times already i reinstalled it and still did the same thing

**Comment by R4Z0R49** [comment]
due the webpage getting dossed im not sure the update system will work. I'm not sure if the site will return.

**Comment by vitalzus** [comment]
well now my other launcher stopped working to and i miss dayz so much

**Comment by KPanicEKS** [comment]
there was a pretty extensive write up posted to the forums for installing
dayz mod. Check it out here:

https://forums.dayz.com/topic/225729-easiest-method-of-installing-dayz-mod-and-other-relevant-information/

**Comment by R4Z0R49** [comment]
We have now asked all servers to switch to using DayZMod on steam this should improve the way you join servers.

Thanks
