### ISSUE TITLE
freeTarget vs. OpenTarget

### ISSUE THREAD

**Issue by rvett** [DayZMod/DayZ#621]
In dayz_code\compile\player_humanityChange.sqf I see a variable called "freeTarget" which exists only there. Shouldn't this be "OpenTarget" like everywhere else?

**Comment by vasama** [comment]
I believe `freeTarget` is related to an older, failed system.

**Comment by AsFoxy** [comment]
I believe `freeTarget` is related to an older failed system.

**Comment by R4Z0R49** [comment]
yea i think its part of the old broken system. ill comment them out.

thanks
