### ISSUE TITLE
Bugged crafting entries

### ISSUE THREAD

**Issue by rvett** [DayZMod/DayZ#623]
![bugged_crafting](https://cloud.githubusercontent.com/assets/6949874/13548617/93990258-e2f4-11e5-8740-d8e06c20a604.jpg)

Found this while playing 1.8.7 today. I did not have those items in my inventory.

**Comment by Lukethero** [comment]
Same here.

**Comment by bittedanke** [comment]
Can confirm: This happens once you switched to a melee weapon, and so this appear to be the melee magazines. They also stay in "magazines player" after the melee weapon is deselected AND/OR is no longer in the inventory of the player, once it was selected as primary weapon.

**Comment by ebaydayz** [comment]
Fixed https://github.com/DayZMod/DayZ/commit/f2e1623ba1430d79b65b241023caffbefe4df4e1
