### ISSUE TITLE
Switch between melee and rifle

### ISSUE THREAD

**Issue by rvett** [DayZMod/DayZ#624]
One cannot switch between a melee weapon and a rifle directly using either the mouse scrollwheel or the 1/3 keys, one always has to equip the pistol in between. If one doesn't have a pistol, the switch works only through the inventory.

**Comment by Inurosen** [comment]
Yeah, this is very frustrating.

**Comment by R4Z0R49** [comment]
ok tested this 200 times, with a pistol and without in all positions and i'm unable to recreate.

**Comment by R4Z0R49** [comment]
Ill leave this open for more info.

**Comment by rvett** [comment]
Might be a server issue. It's working properly on Europa, but not on Dead Man Walking Vanilla (100% reproducible for me). Will report back upon finding out more. US434 has instantaneous switch between primary and melee for some reason.

**Comment by AsFoxy** [comment]
The instant switch is a server setting. The US434 admins must have enabled this. As for the Dead Man Walking server, perhaps they're using some incompatible custom code. I don't know who their admins are, so you might want to ask them to come talk to us on the DayZMod Discord at https://discord.gg/0bcNYiZIEmHtQfIc .

**Comment by Inurosen** [comment]
@AsFoxy Could you please tell the name of that setting?

**Comment by AsFoxy** [comment]
In `init.sqf`

`dayz_quickSwitch = false; //Turns on forced animation for weapon switch. (hotkeys 1,2,3) False = enable animations, True = disable animations`
