### ISSUE TITLE
Making stashes, etool and shovel in 1.8.7

### ISSUE THREAD

**Issue by B73** [DayZMod/DayZ#627]
ver 1.8.7

Click on sandbag -> create stash = says "missing etool"

Click on shovel -> create stash = stash is created without allowing player to place it

**Comment by R4Z0R49** [comment]
Do you have an etool?

**Comment by rvett** [comment]
Can confirm this, I get the same behavior. Have no Etool.

**Comment by B73** [comment]
Had no etool back then... had to find one because with shovel you can only make small stash (without option to position it), need etool to upgrade after making stash with the shovel. When I finally found etool I dropped shovel so that it would not mess things up.  Made other stash with etool and could position stash and upgrade it as normal.

**Comment by R4Z0R49** [comment]
Ill update this for the next patch, The shovel just now only places a small stash, the etool allows you to have a better placement system.
