### ISSUE TITLE
Food doesn't restore blood at all.

### ISSUE THREAD

**Issue by Inurosen** [DayZMod/DayZ#629]
As the title says.

Tried it with any food, it restores hunger, but has no effect on blood.

**Comment by R4Z0R49** [comment]
Ok what makes you think its not working ?
What server do you play on?

The reason i ask is admins can disable this by setting classic or with custom presets.

**Comment by Inurosen** [comment]
Well, i see no effect on blood at all. There is no blood regen icon upon eating and blood value doesn't change on ingame debug monitor. I'm playing on vanilla server http://www.gametracker.com/server_info/195.88.208.28:2302/
Maybe there is some kind of variable that was added on last update?

**Comment by R4Z0R49** [comment]
When you eat food is your hunger bar filled instant ?

**Comment by Inurosen** [comment]
Yes

**Comment by R4Z0R49** [comment]
Your admin has the food system disabled.

Closing no issue.

**Comment by Inurosen** [comment]
Thank you for your fast reply, i will tell our admins now.
