### ISSUE TITLE
Making DayZ Streamable

### ISSUE THREAD

**Issue by That1Drifter** [DayZMod/DayZ#63]
Here is all you need to make DayZ streamable, meaning no name on map and gear menu. Also sign the ra_chat_off.pbo and make it optional for them. All the work is done here. https://www.dropbox.com/s/rxqf2dqcsyhum83/Streamable_DayZ.zip

Rocket likes streamers and maybe it would help breathe some life back into the vanilla mod.

**Comment by AlbyBDPK** [comment]
What did you change in dayz_code?
