### ISSUE TITLE
meat doesn't restore health / dayz_nutritionValuesSystem

### ISSUE THREAD

**Issue by elDoudou** [DayZMod/DayZ#631]
Since the introduction of dayz 1.8.7, health is no more restored when you eat, especially meat.

After reading the logs, it seems than this new server variable dayz_nutritionValuesSystem is the culprit, because it's new variable and set at false by default.
But most if not all servers let meat restore health and so that new variable confuse server administrators. 
It should either be at true by default, or renamed in a more meaningfull way

**Comment by R4Z0R49** [comment]
Or you can just use the preset system rather then messing with custom (settings you don't understand)

If you don't have any idea what the settings do use the preset system and enable custom or vanilla. They both have different systems. However as its new id expect one or two issues with the system.

Renaming one or two of them is on the list as well as fixing the health regen from food when using classic options.

**Comment by elDoudou** [comment]
You know than most custom server use their own preset, don't you ?
