### ISSUE TITLE
M1014 Ammo

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#633]
Ammo for the m1014 in our stash would not actually work in the m10. It said m1014 slugs and m1014 buckshot.If I remember correcty, this is not what they were called before, and secondly, the slug rounds have the same sprite as the m1014 buckshot. I am not sure if this is an issue with legacy ammo types that were in our stash, or if it just turnes into this bugged ammo when you convert or pick it up from the ground. Again, big issue, probably needs looking at.

**Comment by R4Z0R49** [comment]
If its old ammo then id say try again with new found ammo. 

Some old ammo has been left in place to resolve issues for servers who haven't done a db wipe.

If you find new ammo and still have the issue please report.
