### ISSUE TITLE
Knockout Bolt Ammo Bug

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#634]
Had a tranquilizer bolt and a crossbow, and there was no scroll option presented to load the crossbow with it. I would assume this is the same for the explosive bolts, and possibly the actuall crossbow ammo. This tranquilizer bolt was in a stash that carried over the update, but I think the principle should still stay the same if it is a fresh one.

**Comment by R4Z0R49** [comment]
This is not a bug the old ammo types no longer work, They have been replaced for new ones. If you find a new one if loot. Please update this again and ill reopen.

**Comment by bittedanke** [comment]
I noticed, that bolts picked up from dead bodies, after you killd the bodies with that bolts, these bolts do not work in the same crossbow anymore. Also then these bolts combines to quiver do not work with the crossbow anymore. I had wooden arows.

**Comment by R4Z0R49** [comment]
OK I'll reopen this.

**Comment by R4Z0R49** [comment]
This has been resolved thanks.
