### ISSUE TITLE
Perpetual Pain

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#636]
I believe if you are put into pain once you still have the pain status effect, atleast till you log out. Was full water and full blood, had just taken 2 painkillers, and still my screan sway persisted.The same happened with my friend. This one is a big need to fix.

**Comment by Lukethero** [comment]
Multiple people confirming this to me.

**Comment by vinyljunkie** [comment]
Video: https://youtu.be/fpYAKkltPvE

**Comment by R4Z0R49** [comment]
Details, Was you in a vehicle when you took painkillers, did another player give them you.

We need as much info as you can give.

**Comment by R4Z0R49** [comment]
We are working on this. Just not sure just now what is causing it.

**Comment by vinyljunkie** [comment]
I just tested it again and no difference even if just taking painkillers. I have not been in a vehicle when taking the painkillers. Here is my RPT if it helps:
http://pastebin.com/qgfi7qp7

**Comment by Lukethero** [comment]
No vehicle. Preety sure the the system itself is broken.

**Comment by R4Z0R49** [comment]
yea, looks like it.

**Comment by KPanicEKS** [comment]
Is there any known workaround that we know of? Relogging doesn't seem to do
anything. Does it reset on death at least?

**Comment by Lukethero** [comment]
Believe death resets it, yeah.

**Comment by R4Z0R49** [comment]
I'm going to try a a quickFix this weekend to sort issue. I have an idea whats happening im just not sure why its started to happen now.

**Comment by bittedanke** [comment]
**r_player_inpain = true;** 

https://github.com/DayZMod/DayZ/commit/a42427f0b38d1128ebb0285690bf71c2babceecb

**Comment by R4Z0R49** [comment]
We have already fixed this ty. Ill close once pushed :-)
