### ISSUE TITLE
O- Rarity

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#637]
O- has become super common with he whole medical box spawns. We found over 20 in 3 hours. I can just see now how the hero skin is going to be completely worthless. Combine this with the lack of trasnfusion kits and you basically just get an easy 250 humanity. I cetrainly think none should spawn in the medical boxes, but rather have blood testing kits spawn there. O- should be commodities, not like cans of food.

**Comment by rvett** [comment]
I have traveled the map all day long, and haven't found a single one of them. Medboxes are super rare now as far as I've experienced it, even in Cherno with 70 players online. (Also they don't seem to spawn in small medical tents anymore.) You must have gotten super lucky.

BTW, github issues don't seem to be the right place to discuss balance.

**Comment by Lukethero** [comment]
This is not really a debate, more of a bug. Everyone I know is saying they spawn everywhere. Also, I know for a fact that the medboxes are not rare. They are extemely common at heli crashes and have found numerouse carepackages litered around with them. Tents also  them as well, not just hospitals. Preety sure I found one at rangers outpost yesterday with SIX -Os. That is basically an instant hero skin right there

**Comment by R4Z0R49** [comment]
rgr i've forward this onto foxy.

**Comment by R4Z0R49** [comment]
ac1d7ce67e4da8256ffd2f32c3b4a172c4170e68

Updated.
