### ISSUE TITLE
[Request] Face paint

### ISSUE THREAD

**Issue by PatriotCZ** [DayZMod/DayZ#638]
I think it would be pretty cool, to be able to find face paint colors,
maybe in industrial buildings or army tents. It shouldn't be hard to do since you can change entire skins. It would basicly just change your face skin to another which would have painted textures. I saw some tutorials but I think it would be better without any workarounds and 3rd party stuff.

**Comment by KPanicEKS** [comment]
Feature requests and such should probably be best discussed on the forums (
https://forums.dayz.com/forum/6-dayz-mod/) Ideally, git should primarily be
used for reporting bugs and suggestions to existing systems already
implemented in the game.

**Comment by Lukethero** [comment]
Plus you can already do this using a little config magic. Probably can find a tutorial somewhere. I got my guy with a nice old green stripe pattern.

**Comment by R4Z0R49** [comment]
This can already be done using the squad system.

Thanks.
