### ISSUE TITLE
Chance system wrong way around!

### ISSUE THREAD

**Issue by bittedanke** [DayZMod/DayZ#640]
https://github.com/DayZMod/DayZ/commit/6925182f282ba6e78cf3b8244bc972087402ad70

This will not decrease loot from 30% to 10%. In fact it will increase the loot from 70% to 90%.

**if (0.9 > random 1) then** shoud be **if (0.1 > random 1) then** to make it 10%, or **if (0.9 < random 1) then**, whatever you prefer.

**Comment by R4Z0R49** [comment]
Aye my bad miss read, thanks

**Comment by R4Z0R49** [comment]
ps you don't need to create issues just make a comment on the commit :-)

**Comment by bittedanke** [comment]
Thank you, did not know :)
