### ISSUE TITLE
fn_dropItem displaces existing weaponholder under the players feet

### ISSUE THREAD

**Issue by bittedanke** [DayZMod/DayZ#646]
The following code from
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_code/compile/fn_dropItem.sqf
first has a comment in line 23 that makes no sense ;)

Also, in line 27 it displaces an existing weaponholder (and so all the stuff on the ground) under the players feet. This makes stuff move to the player from 2 meters away. Since it makes sense to displace a new or a found, empty weaponholder, please add a check to only move it, if it is empty. Like this for example:
27 if( (
28  (count ((getWeaponCargo _holder) select 0)) +
29  (count ((getMagazineCargo _holder) select 0))  +
30  (count ((getBackpackCargo _holder) select 0)) ) == 1 ) then {

23 //Add the item to the newly created holder or to the new holder.
24 _holder addMagazineCargoGlobal [_item,1]; 
25 
26 //Make sure the holder spawns behind the physical location of the player 
27 _holder setPosATL (player modeltoWorld PILE_PLAYER_OFFSET); 

Suggestion: at line 20 check if the player can actually SEE the weaponholder before selecting it for output, since it could be on the other side of a wall:
20 _holder = _nearByPile select 0;
21 _objects = lineIntersectsWith [getPosASL _holder, getPosASL player, player, _holder, true];
22 if ((count _objects) > 0) then {
23  _holder = createVehicle ["WeaponHolder", _pos, [], 0, "CAN_COLLIDE"];
24 };

**Comment by R4Z0R49** [comment]
Thanks, your welcome to fork and make the changes. Otherwise I'll try looking over it the weekend.
