### ISSUE TITLE
[Request] Leg Shots / Non Fatal shots result in lower loss of humanity.

### ISSUE THREAD

**Issue by ghost** [DayZMod/DayZ#650]
There should be more opportunity to defend yourself pre-emptively without risking a massive loss of humanity.  I think the leg shot would achieve exactly this.  Considering it is non fatal the penalty should be way less than it currently is.

While I really welcome the new humanity system, as it stands my approach to the game now is 'Well, I just have to avoid everyone otherwise I lose humanity'.  
My logic here is by the time im shot/hit (i.e. able to retaliate without losing humanity) its likely too late to defend myself anyway.

It would be nice if being shot AT (rather than actually being shot) would trigure the new humanity system, but obviously this would be a complicated system to implement, and would need to support warning shots too.

I feel that a significantly reduced humanity penalty for legs shots is the answer, and if playerbase is aware of this then it would really change the interaction dynamics (i.e. increase non fatal encounters / holdups)

At the end of the day, irl if you didnt wish to kill, you would take the legs or the arms.  It's a lot more humane than killing.  The humanity mechanics should reflect this.  

Interested to see what the devs and people think and if anyone can expand on the concept.

**Comment by Lukethero** [comment]
Would be in agreal, if it wasn't so freeking easy to get humanity in this patch.

**Comment by R4Z0R49** [comment]
Id love the idea but doing it in arma damage Handler that runs for every body part each time. It makes it very hard to be 100% sure what got hit.

To explain it a little more here
https://forums.bistudio.com/topic/108931-handledamage-eh-explained-poor-mans-gethit/
