### ISSUE TITLE
[Request] Random Dynamic Event Chance

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#654]
Currently I have heard lots of people saying how commonly they find crash sites. I find the things every other field I come to. I think the chance should be downed a bit. Heli crashes should be a pleasant suprise with respectove loot for that rarity. On top of this are the care package drops. I sorta like how they are more common now, possibly down the chance a very slight amount. My problem with this is that medboxes are super common at these so bloodbags are really common, but I will split this into another issue.

**Comment by R4Z0R49** [comment]
Crash sites spawn thought out the game at random times.
