### ISSUE TITLE
[Request] Dynamic Event Spawns- Care packages

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#655]
The medboxes are EXTREMELY common at the care package drops. Many of the preexisting heroes are really quite ubset at how easy it is to get humanity in this patch. I ran into Electro the other day and saw 3 heroes running completely seperately and only 1 bandit. 

The point of hero is to be a challenge and a complete style change. On US 434, a new term has arrissen over sidechat which is "fake hero."  It has gotten so bad that heroes are just roaming around and shooting survivors without a care because they can just regain it in a couple of minutes. It is affecting the other pre-patch heroes who actually play like heroes by the bad rap the other ones have given the skin itself. Tons of players say they just shoot heroes on sight because they roll like bandits and with bandits anyways. Also the pre-patch heroes feel cheated because they had to put so much work into their skins, but the new guys get an easy pass.

So yeah, got a little ranty there, but it is important to understand the core problem caused by the medboxes. I do believe that greatly decreasing the spawn chances of these bloodbags will fix the issue. The heroes who are not truely devoted to the play style will die out after they shoot a survivor or two and will go back to their bandit ways. Especially now that transfusion kits are gone, bloodbags should be more of a commodity than ever.

**Comment by R4Z0R49** [comment]
Same issue again. #657 

Bloodbags have already been updated.
