### ISSUE TITLE
Request] Dynamic Event Spawns- Helicopter Crash Sites

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#657]
In the current build it is incredibly hard to find decent weapons at crash sights, which might be in part due to the high chance of them spawning, but like I said in the other issue, the spawn amount of them should be decreased. For example, I have found on 2 seperated occasions, 3 pp bizons at a fresh crash and another with all AK 74Us'. If you can find those at firestations (and even barracks, but I will get into that in a different issue), then why even bother? I am not saying completely get rid of these items from the tables, but me, and many others just find them so often it is getting tired. I absolutely love how high tier weapons are more rare, so do not change that ( unless you down heli crash spawns, then you might want to boost the spawn chance a wee bit) but rather up the chance of otherwise hard to find itens or non-coastal weapons like western attachments, 9 mil supressors, or the elusive hand grenades. It would be cool to get some suggestions from people, because I have seen some heli only weapons like the g36 and such at the crashes, but more often than not it is guns that I could have found within 5 minutes of spawning on the coast. 

What has everyone else experienced, have you been finding medium tier weps like the stanag variants or Russian lmgs, or are me and the groups I talk to just super unlucky? I am aering with the side of slightly tweaking it, but I might be completely wrong.

**Comment by R4Z0R49** [comment]
Its more about the chance you can find other weapons rather then 100% being able to find something better.

The loot tables work hand in hand you cant lower one without directly effecting the other. Maybe once we start getting more models in game we can change stuff to be more varied. Based on each location

Maybe we can try changing the class related to the buildings. Rather then changing the actual loot spawning at each class.

**Comment by R4Z0R49** [comment]
Bloody close button

**Comment by R4Z0R49** [comment]
The loot system isnt perfect but we are getting closer.

Thanks for the feedback.
