### ISSUE TITLE
[Request] Change Barracks' Loot Tables

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#658]
This is a simple one. A bud pointed out to me when the patch first came out that all he found at barracks were guns he found on the coast with the new loot system. As the weeks have progressed I have realized this more and more. All I find there is some m4s, aks, bizons and maybe throw a couple skins and backpacks in there. Lots of people are just opting out going to the north for the barracks because they could get almost literally all of that at the fire stations and tents. I am not sure if the high tier weapons spawn there still and it is just a very low chance because I have not gotten to checking the tables but basically, some buffing to the barracks have to happen.

**Comment by R4Z0R49** [comment]
Same issue as before. #657
