### ISSUE TITLE
Request to use / utilise DayZ 1.7.7.1 code and content in DayZ Overwatch

### ISSUE THREAD

**Issue by scrumbee** [DayZMod/DayZ#66]
I would like permission to use the dayz mod code in new mod.

I will include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future release i do and im willing to backport code/models/sfx/animations to the official if requested.

Understand that im only allowed to edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

All other pbos are forbidden due to license issues and tools used to create you must seek BIS/Deans permission to edit any other pbo.

**Comment by R4Z0R49** [comment]
DayZ Overwatch AKA scrumbee - 02/07/2013 - Your good to go.

#60 < requested on the 2nd.

Thanks
