### ISSUE TITLE
Open target timer last until restart

### ISSUE THREAD

**Issue by B73** [DayZMod/DayZ#660]
When someone comes open target it would be great if status stays until next restart. Finding the murderer (open target) can take long time, especially if open target is moving with a vehicle around the map.

Would be nice to see hunts for open target(s), but now it's way too short time.

**Comment by R4Z0R49** [comment]
The time is set by your serverAdmin

**Comment by KPanicEKS** [comment]
how does the open target system work? I haven't noticed any note of it in
the changelog?

**Comment by R4Z0R49** [comment]
if someone shoots you they become an open target to everyone, killing the open target does not reduce humanity.

Basically and it was in the change log :-)
