### ISSUE TITLE
[BUG] Dome tents are invisible when you place them and non existient once build is complete

### ISSUE THREAD

**Issue by KPanicEKS** [DayZMod/DayZ#661]
Packed a dome tent from a Infected camp and tried to place it. When I placed the tent it was not showing up on the screen but it still allowed me to "Complete Build" once the build was complete there was no tent.

**Comment by R4Z0R49** [comment]
ok ill look into this thanks.

**Comment by thcNox** [comment]
I have looted about 20 dome tents from infected camps since 1.8.7 came out and I have never seen this.

**Comment by ebayShopper** [comment]
can not reproduce

**Comment by KPanicEKS** [comment]
I couldn't reproduce it either after the initial bug. Could have been
something bugged with the session. If I experience it again I will let you
know.
