### ISSUE TITLE
 House Restriction Bug

### ISSUE THREAD

**Issue by Lukethero** [DayZMod/DayZ#664]
You can now place  buildables like stashes, tents, ect inside of buildings. Big issue here that I think needs some attention. The griefers have gotten smart and are now placing camo nets in places like barracks so nobody can enter it, especially because they are not able to be removed except by unconventional means. This will start to get real bad real fast unless it it is treated.

**Comment by rvett** [comment]
IMO camo nets need to be destructible like tents.

**Comment by LO0TC1F3R** [comment]
@Lukethero totally agree. but which way of fixing this do you think is better? making camo netts destructable or removing the possibility to put buildables inside of buildings? because I dont even know why putting stashes and tents into rocks, buildings etc needs to be an option.

**Comment by R4Z0R49** [comment]
We have a new collision system for buildables coming in 1.8.8 hopefully this should solve the issue.

This is currently in testing on the test server
