### ISSUE TITLE
Wrong handler for PVDZ_Server_processCode

### ISSUE THREAD

**Issue by denisio** [DayZMod/DayZ#665]
I found wrong handler in "publicEH.sqf":
"PVDZ_Server_processCode" addPublicVariableEventHandler {(_this select 1) call pvs_processSetAccessCode};

If you are trying to open the gate that you just set the new code again and again...

To fix this you need to restore the old code for "PVDZ_Server_processCode".

**Comment by R4Z0R49** [comment]
Ill have a look once we we enable the fence system again.

Thanks
