### ISSUE TITLE
Right-clicking inventory items brings up wrong menu

### ISSUE THREAD

**Issue by rvett** [DayZMod/DayZ#666]
Sometimes (not sure when exactly) right-clicking any item in the main inventory brings up the hatchet sebmenu instead of that of the item clicked. The only workaround I have found for this so far is relogging.
![rightclickbug](https://cloud.githubusercontent.com/assets/6949874/14250607/898f3e10-fa7f-11e5-9adc-9f5cfece57df.png)

**Comment by Lukethero** [comment]
I believe you can fix this by switching your weapons around or adding your melee to your toolbelt or something like that.

**Comment by rvett** [comment]
Thanks, I'll try that next time it happens.

**Comment by KPanicEKS** [comment]
the devil is in the details.. this is gonna be one hell of a bug to track
down (sorry couldn't help it)

I've seen this bug too but could never replicate what causes it.

**Comment by AsFoxy** [comment]
That's why i rewrote the whole thing. Have to wait until next patch though.

**Comment by kichilron** [comment]
It's better to have this issue closed when people start gtalking about the devil in issue #666

**Comment by bchawke** [comment]
Just saw this today, so sorry for chiming in late, but the workaround for this is simple.  Just right click on your hatchet, then right click on the item you wanted to use in the first place again.  It should be back to normal.  Right clicking on the hatchet fixes it.
