### ISSUE TITLE
Requests to balance weapons

### ISSUE THREAD

**Issue by B73** [DayZMod/DayZ#667]
Latest patch made CZ uber-weapon, it's very common also. By lowering (alot!) chances to find ammo for CZ would balance situation. Or just remove the second zoom level. That would make difference between M24 and CZ. And what about M40a3...

Also hope to see SKS in mod, it would be between Enfield and M14 sort of. Only with iron sights.

Zeroing to Enfield would be nice. Also Enfield should be much more common, sort of basic weapon for all.

**Comment by Lukethero** [comment]
All they changed was the zoom but that came in the arms 2 oa patch. Have not looted enough barns to have an idea of the rarity.

**Comment by R4Z0R49** [comment]
No other reports closing.
