### ISSUE TITLE
Tent/stash capacity not shown when primary or melee weapon drawn

### ISSUE THREAD

**Issue by rvett** [DayZMod/DayZ#668]
The weapon/item/backpack capacity of tents and stashes is correctly shown when one has a secondary weapon drawn, but not with a melee or primary weapon. It that case, it is shown as "n/a" for a split second and then it disappears.

![capacitybug1](https://cloud.githubusercontent.com/assets/6949874/14256379/1c83cf88-fa99-11e5-8b41-0ebe06a3eb30.png)
![capacitybug2](https://cloud.githubusercontent.com/assets/6949874/14256386/2310e084-fa99-11e5-8652-b0b3477942f6.png)

**Comment by Lukethero** [comment]
That is not 100% of the time right?

**Comment by rvett** [comment]
Not sure, but it's been very reproducible for me in the last two months or so. Can't remember a single time it worked.

**Comment by R4Z0R49** [comment]
Was you looking at the tent when you opened your inventory?

**Comment by rvett** [comment]
Not sure exactly what you mean. To get the gear symbol and eventually to access it, I have to look at it, right?

**Comment by Lukethero** [comment]
Sometimes I move a little and readjusting fixes it, might be wrong though.

**Comment by rvett** [comment]
So here's a curious observation: On my primary account (hero) I get the behavior as described above. With my secondary character (survivor), however, I cannot reproduce the problem. Could this be clothing-related? It could also be related to the exact kind of primary or melee weapon, as I have used different ones with the two characters.

**Comment by AsFoxy** [comment]
Currently to find the opened container the game simply takes object you're looking at and compares the names to see if it's the right one. So you should try readjusting your camera and holding still while opening the gear. I also looked into improving the search and it might be possible to fix it properly.
