### ISSUE TITLE
Readme about how to build and test

### ISSUE THREAD

**Issue by mczero80** [DayZMod/DayZ#669]
As a interested developer, but with no knowledge about Arma/DayZ modding, I am stuck.

The first step for me with every patch is to get the build setup running. 

So I would appreciate a readme in the root folder of this project, containing which tools are needed, how I must adapt BuildScript.bat (I see that there are some dirs to adapt, but I have no plan where and what exactly) and how do I test it (how do I setup a test server and what do I have to consider).

I could imagine, that a proper build and test readme could attract more developers to help out with further development of the mod.

**Comment by Lukethero** [comment]
Well what specifically are you trying to do?

**Comment by AsFoxy** [comment]
Be sure to join us on Discord at https://discord.gg/0bcNYiZIEmHtQfIc for more direct help.

**Comment by mczero80** [comment]
First I want to build it "as is", then I want to experiment with the Zombie A.I.. Improving it,

**Comment by R4Z0R49** [comment]
experiment in what way?

download pboProject build your p: drive using arma tools then package dayzMod.

If you jump on discord other will be able to give more help.
