### ISSUE TITLE
Invisible walls for zombies

### ISSUE THREAD

**Issue by LOLWORKED** [DayZMod/DayZ#67]
Well there's an invisible wall whenever you are near the coast and you find a certain kind of pavement. I have found this at 3 different locations so far: one in Cherno (video), the giant dock of Elektro, and some small town just east of Elektro. So apparently these olympic hurdle jumpers found it difficult to clear this highly fortified street curb, and this combined with the 20 mile range of the hatchet made it really easy to kill them.

On a side note, the other issue I didn't point out is that the temperature meter on the right side is always red, which gives a player no insight as to what their real temperature is. It stays that way when in rain for an hour, or when you apply a heat pack. I don't even know if red means high or dangerously low.

Here is the video: http://www.youtube.com/watch?v=IdzxZVw-rbk

**Comment by thevisad** [comment]
This has always been the case in these locations, this has to do with the way the Ai is handled.  

Red means normal in the thermometer, this was changes from the previous setting and has been this way for a while.

**Comment by DrClaw-** [comment]
thats not true its the very structure of the engine that allows zombies to walk through certain walls
its obvious, its a bleak engine thats what makes the zombies so broken

also even i was able to get through a wall in military barracks
i glitched through the damn thing for christs sake all i did was continue to hit v against the wall and made it out
