### ISSUE TITLE
[Feedback] My impressions of 1.8.7 so far

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#671]
Hey I just wanted to provide some feedback on 1.8.7.  I was AWOL for a couple months after it came out but I've been able to get back on and try it out some the last couple of weeks.

First off, overall I'm really liking the patch:
- The new heli crash locations and types have made the game a lot more interesting!
- Love the increased options with weapon attachments.
- Zombies are finally a challenge again which is great, but they still seem to run away from you before coming at you.  On the 1.8.7 test server they did a pretty good job of aggroing directly at you.  Not sure what has changed there.
- Not sure if this is limited to a US434 setting but zombie spawns seem to be working much better.  A lot of zombies spawn around you now, feels much more like a horde
- PvE survival seems to be at a pretty good balance (I like it to be more challenging but the current numbers make it so that food/water/warmth are a concern but not so much that it deters new players).
- Really liking the player movement changes like having a raised weapon after getting off the ladder and being able to jump with no weapon in hand
- Haven't been able to test it out yet, but the new humanity code seems really cool
- Though it's only temporary (and highly controversial), removal of base building has had a massive positive impact on player activity on the map.  We're now getting into fights with people at Lopatino, Grishino, Gorka, Orlovettes/Polana, NEAF and other places like back in 2012 DayZ mod days.  Squads are actually moving around, and it's made the game 100% more interesting.  Granted, this is just a side effect of a temporary removal of a system, but I'm putting it in the pros of 1.8.7 just because of how big the impact has been.  I'm sure the increased spawn radius of heli crash sites has contributed to this as well.
- New loot system has made mid-tier guns much more valuable.  People are really digging into the weapon attachment system now.  I'm seeing a lot of G36 CCO silenced guns, AK PSO w/ grenade launcher, etc etc.  I really enjoy getting into gunfights with a variety of weapons rather than everyone having an M14/DMR, M14/M24, or LMG/DMR combo.

The last point above moves me on to the negatives:
- Weapon spawns: While I LOVE the fact that top tier weapons are harder to find and there's more assault rifle battles than there were in the past, it's a double edged sword and there's a potentially very damaging side effect.  NWAF and even heli crash sites have drastically lost their value.  They're still very dangerous places to be, but the reward is not worth the risk.  I've been looting airfields for two weeks now and have yet to find a gun worth risking my neck over.  Heli crashes have been slightly better but the best sniper rifle I've found at one since 1.8.7 is an SVD. The only decent sniper rifles I've found have been looted off of players.  The big problem with this is that NWAF might start looking like DayZ Standalone NWAF.  Ghost town!  Why risk going there if all I'm going to find is an AK-74 and a can of beans?  I completely understand this is a very tough thing to balance, but there really has to be a good reason to go to the dangerous military areas.
- Blood bags - too many O- blood bags are spawning.  I'm really happy with the removal of transfusion kits seeing as the blood types add sufficient difficulty, but we've been toting around a lot of O- blood bags and have yet to find the need to use a blood test kit.
- MRE spawn rate is really high.  Takes away from the necessity of hunting animals for a good nutrition source
- This one comes from one of my squad mates, not me personally since I haven't looked for this too much yet, but he says that it's really hard to find wheels now.  He looted industrial sites for a couple of hours just looking for one or two wheels to get a car going.

Overall a great update!  DayZ mod hasn't been this fun in a long time.  Lots of good PvP action all over the map and seeing a lot of people with customized assault rifles is great.  Props to the devs and all the people on Discord helping test, admin, and further develop the game.  Great to see the recent progress!

**Comment by Lukethero** [comment]
Agree with BC on almost if not all of these points. The big ones for me are the NWAF issue and the O-. Really no reason to go to the baracks across the map if you can find preety much everything that spawns there elsewhere. I really have no idea what could be done besides just throwing the high tier guns into the tables again. Possibly taking the US attachments and putting them into the barracks,  but that does not seem like big enough of an incentive by itself. A unique group of items needs to be added (or an existing group of items  in the game) and made unique to baracks. I have found a few good guns at heli crashes, so I suppose those could be left alone.

O- is a more simple fix. Medboxes in general are far too common at dynamics events and the goods inside of them are too numerous.

**Comment by R4Z0R49** [comment]
O-bloodbags have already been fixed.

**Comment by rvett** [comment]
I agree with almost all of this. MREs are a bit too common, car wheels perhaps a tad too rare. I have also noticed that zombies often run away from you at first, which is odd. Overall a great update.

About the bloodbags, could you push the reduction into the next quickfix? People are becoming heroes within a couple of days only, because the 0- bloodbags are so ubiquitous.

**Comment by bchawke** [comment]
Agreed, there's far too many hero hit squads running around right now.

**Comment by bchawke** [comment]
@R4Z0R49 , just for clarification, has the O- fix already been applied via one of the quick fixes?  If so, it wasn't enough because O- bags are still very plentiful as of a few days ago.  If instead you mean that it's been fixed internally and yet to be implemented in the game, then nevermind.  Thanks!

**Comment by R4Z0R49** [comment]
No it hasn't

**Comment by R4Z0R49** [comment]
Thanks for the feedback. The next patch is going to look at fixing a few of the lingering issues we have. Before we bring in a more simple building system again. Then hopefully the new rewrite dayz base code should be ready for release.
