### ISSUE TITLE
1.8.8 Changes WIP

### ISSUE THREAD

**Issue by R4Z0R49** [DayZMod/DayZ#673]
WIP change Log

Added, players can now rest at tents they don't own, but infection cure chance is reduced 50%
Added, Temperature should now show arrows for raising and falling.
Added, Lower sound effects volume hotkey (F1) and status UI icon.
Added, M16A2 added to attachment system (m203 support),
Added, New loot locations.
Added, Journal Kills will only update during the session on confirmed Kills (study dead body).
Added, Player-list no longer shows who's in lobby or ingame.
Added, Fuel stations now have limited amount of fuel each restart. (max amount controlled by admins dayz_randomMaxFuelAmount),
Added, More possible causes of death to study body: fell, ran over, shot, melee hit, zombie hit
Added, Players can now manually push stuck planes backwards to free them.
Added, Main weapon is now automatically selected after throwing.

Fixed, Player Always being in pain,
Fixed, Unconscious Animations sync across network,
Fixed, AI Animations sync across network,
Fixed, Switch Weapon bug,
Fixed, Infectious Waterholes being random on each client the server will now set these,
Fixed, siphon fuel taking empty can and returning 0 liters,
Fixed, some blank remove attachment text on L110, M4 and M240,
Fixed, SA58_RIS_FL_DZ no entry config\bin error,
Fixed, trees not falling down after chopping wood and related RPT error,
Fixed, hatchback and sedan enter and exit sound not playing with related RPT error,
Fixed, melee magazines visible in crafting UI,
Fixed, tearing clothes no longer yields anything if clothes are dropped in the process,
Fixed, Reload issue while holding flares/cemlights.
Fixed, Player Damage Handler will now allow damage from more sources,
Fixed, Crossbow ammo should now work correctly again, (combine quivers, Refill quivers, Pickup arrows),
Fixed, SelfBloodBags no longer yields humanity gain.
Fixed, Study body cause of death showing "blood loss" when it shouldn't.
Fixed, Study body message saying his/he on female players.
Fixed, Fishing boat can now be refueled normally
Fixed, Attempting bunny hops in quick succession no longer results in a bunny hop followed by a vault or invisible weapon switch glitch when the player has no weapon in hand.
Fixed, Humanity hit is now applied correctly to players shooting from vehicles.
Fixed, SVD_DZ alternative (/) iron sight. Camo variants still do not have visible iron sights.
Fixed, Boathouse loot.

Updated, AI Line of Sight, Spawn Methods, Loot Drop rate,
Updated, Player Death logging,
Updated, Nutrition (water consumption values back to 1.8.6, Removed 10 from food consumption values).
Updated, Temperature variables (positive(Moving,Sun), Negative(Nights,Wind,Rain))
Updated, String-tables for items/Attachments,
Updated, GhostMode will no longer try to sync the player character (we think this is the cause of the location reset)
Updated, 9mm silencer can be now attached to M9, G17, MP5, Bizon,
Updated, Changed splint recipe (ItemPlank,equip_string,equip_duct_tape), Splints also now require two inventory slots.
Updated, Rope convert to 2 strings in place of 3,
Updated, Build collisions now updated should block buildables being placed in other objects
Updated, POI tree directions.
Updated, Lowered Nutrition Values for refueling (Per Can) (20,40,15, Old) - (0,1,3,0 - New),
Updated, Upgrade stashes can now hold backpacks. (Lvl 1 = 0, Lvl 2 = 0, Lvl 3 = 1, Lvl 4 = 1)

Removed, Mi-7 Helicopter removed from database,
Removed, Power lines from spawning loot & Zeds,
Removed, Salvage option from bicycles

**Comment by Inurosen** [comment]
> Updated, Player Death

Any more information on this please? :)

**Comment by R4Z0R49** [comment]
Just some cleanup. I just need to update the line.

**Comment by Lukethero** [comment]
Can we be expecting basebuilding soon? I know many of my friends who are waiting on it and will not come back until it is in. It really adds the extra playability that vets who have been playing for years. 

I, along with others, believe it is priority #1.

**Comment by R4Z0R49** [comment]
How long is a piece of string?

Once we are happy with the changes we will release.

**Comment by AndrewEscocia** [comment]
will the shovel be brought in as a base building tool or will it be still the e tool that is the main building tool?
also please take as long as you need to get everything in 1.8.8 right and stick to your vision, dayz is a game that rewards both patience and boldness in equal measures.
thanks for all your hard work.
