### ISSUE TITLE
Zombie spawn..waste of zeds..spawn issue!

### ISSUE THREAD

**Issue by higgedi** [DayZMod/DayZ#675]
hi guys.

maybe u know there r any problems with the zombie spawn if the servers r full.
no zombies spawning in cities and other places.

so my suggestion is : Delete the powerline zed spawns ! 

for every powerline tower u spawn 3-4 zeds each ! thats way tooo much..so on some spots u spawn 30+ zeds and more ...alone ! so with 20 ppl on the server max limit of zeds is reached if the server has 600max zeds !

i think its allright if they spawn on deerstands , buildings crashed cars, crashsites and other ´´normal´´ spawns.

if u change that , the game will be more fun im 100% sure ! u will have much less problems with zed spawns in towns and ppl can move better on the map , without spawning zeds on ever fucking place ;D 

hope u will think about that ...
[http://imgur.com/8P7ppUW](url)

thx for ur time ! higgedi

**Comment by kichilron** [comment]
Been removed already.

https://github.com/DayZMod/DayZ/commit/b577424e50f1d7916f29e2250b362af42ceaf98f
