### ISSUE TITLE
Sepsis bandages cannot be used to stop other people's bleeding

### ISSUE THREAD

**Issue by rvett** [DayZMod/DayZ#683]
Sepsis bandages can be used to stop your own bleeding, but not other's. The option to bandage wounds does not appear in the mousewheel menu when you have sepsis bandages in your inventory but no normal bandages.

**Comment by Lukethero** [comment]
Can confirm

**Comment by R4Z0R49** [comment]
#680 

This is not a bug.

**Comment by rvett** [comment]
I think you're confusing two different things here, R4Z0R49. Sepsis bandages can be used for two things. #680 is about healing sepsis on other players, #683 is about stopping their bleeding.

**Comment by R4Z0R49** [comment]
They both serve the same system really. We we give the badge one system it would make sense to give it both.
