### ISSUE TITLE
No loot at boat houses

### ISSUE THREAD

**Issue by T-E-X** [DayZMod/DayZ#685]
Been looking to get a pole but never see any loot at the boat houses. And yes I have been looking under the boat house where the loot appears. I think the tides determine if the loot was below the boat house or up where it belonged... But at the moment I am seeing no loot at all.

**Comment by KPanicEKS** [comment]
Previously reported. Pretty sure it's already been addressed in the dev
build as the original ticket is closed.

**Comment by rvett** [comment]
This has been fixed: https://github.com/DayZMod/DayZ/commit/0e20239d0f3104a20454ddce5fa2e61e762e1dc6

**Comment by T-E-X** [comment]
So does that mean it will be fixed in 1.8.8?

**Comment by R4Z0R49** [comment]
Should be
