### ISSUE TITLE
[Request] Chevrons for temperature

### ISSUE THREAD

**Issue by rvett** [DayZMod/DayZ#688]
It would be nice to have chevrons indicating if you're cooling off or warming up, like when eating food or bleeding. In real life, you notice easily if you're getting cold or hot. In the game you have to check your temperature repeatedly to be able to tell the direction it's going, and how fast.

**Comment by AlexAFlorov** [comment]
https://www.youtube.com/watch?v=Q-hEoc2pUho&feature=youtu.be

**Comment by rvett** [comment]
Looking really great! 

One small thing: why do they look slightly different than those for blood for instance? I would have guessed that it would make sense for them to look the same, just for visual consistency.

**Comment by AlexAFlorov** [comment]
Idea was not to warn player with extra big arrows alltime.. it is not bloodloss ;)

first lvl up/down small sized, second - medium sized, third - big sized markers

**Comment by AsFoxy** [comment]
Looks fine, but use the same chevrons as blood for consistency.

**Comment by AlexAFlorov** [comment]
we tried same style, but it was looks nasty

**Comment by KPanicEKS** [comment]
Neat system but I'm with the others. The same chevrons that are used for blood
and health should be the standard. Consistency is key.

**Comment by R4Z0R49** [comment]
e89176d565b5f71479baf5f4ae8daad4108e00c3

Done

Pending Icon changes maybe**
