### ISSUE TITLE
DayZ the way it's meant to be played...

### ISSUE THREAD

**Issue by sapioit** [DayZMod/DayZ#690]
Hi,

In this topic I am trying to list a few minor changes I think would make a DayZ server on Arma 2 much better than the current servers. Also, this example would be on Lingor Island, due to the multitude of islands and existing bridges.

First things first, fill the bridges with stuff so one can only use a bike, motorcycle or barely an ATV on a bridge. And make the bridges to the north-east only accessible by boat and helicopter. To go with this, all the tanks should be unlocked, but very expensive. Also, you could make the junk on the bridges to leave enough space for a tank with tracks (no wheels) to be able to make it to the other side.

But the pvp would become unpleasant, so I think the zombies should be buffed. They should be able to hear you walking from 100 meters away, walking with shift from 10 meters away and crawling from 4 meters away. And their numbers should be lower the more people are in a place. Let's say you have 20 zombies for a player in a 500x500 m area. for every other player you would have with 5 zombies less than the previous level. So it would go like this: [players => zombies_added] 1 => 20; 2 => 15; 3 => 10; 4+ => 5. That would translate to [players:zombies_around] 1:20, 2:35, 3:45. 4:50, 5:55. 6:60, 7:65, 8:70, etc. This way not only will be easier to deal with the zombies (because you can have eachother's back), but also have less zombies per player to deal with. [players => zombes_per_player] 1 => 20; 2 => 17.5; 3 => 15; 4 => 12.5; 5 => 11; 6 => 10; 7 => 9.28; 8 => 8.75; 9 => 8.3; 10 => 8; 11 => 7.72; 12 => 7.5; 13 => 7.3;

Alright, now that we have the main points out of the way, how should the traders be placed? Well, for start, there should be 4 trader cities: 

Now that the easy part is done, here is something bigger for the DayZ devs to do: Craftable vehicles (which can't be set on fire; in exchange, they drop Lumber, Plywood, the engine and the items inside them).

Well, before that, we will need something for it: Door without a wall. Also, We should be able to create a key upgrade for the vehicle with a Combination Lock, allowing us to lock/unlock vehicles like we would a door. Same would go for the vehicles. Just a simple 3 rows with maybe the following character: 0123456789abcdefghijklmnopqrstuvwxyz. That would mean 36^3 = 46656 possible combinations. Let's say you can check multiple combos without exiting the menu, with a delay of a second for the animation to end. So every 1 second you would check one combination, making it possible to bruteforce a door (to a car or a base) with only 777.6 minutes, or 12.96 hours. Okay, if you want to make it easier to crack it, just remove the 0123456789 and you would have 26^3 = 17576 combos, which would equal 292.93 minutes or 4.9 hours. Well, if you add zombies and other players to that time, you might have a pleasant surprise for the players: Not only would they be able to lock vehicles, but also they could open locked vehicles, if they put in the time and maybe a small team to deal with the zombies. So a real-life day might be enough to break into a base. But is it worth it?

Seats / Item / Weapon / Backpack / On-Road / Off-Road / Fuel Capacity (Cans, 1 Can = 20L, 1 Fuel Barrel = 200L)
The following crafting recipes are for Epoch, because i have not played the DayZ Mod without Epoch in a long time, because of the lack of craftable vehicles and lockable items. I'm sure you can translate them into something for the normal DayZmod.

Recipe Wooden Bike Wheel: 2 Plywood Packs
Recipe Wooden Car Wheel: 2 Wooden Bike Wheels
Small Vehicle Frame: 2 Lumber Packs, 1 Plywood Pack
Medium Vehicle Frame: 5 Lumber Packs, 3 Plywood Packs
Large Vehicle Frame: 10 Lumber Packs, 6 Plywood Packs
Small Fuel Tank: 2 Cans
Medium Fuel Tank: [ 5 Cans / 1 Fuel Barrel (makes two) ]
Large Fuel Tank: [ 10 Cans / 1 Fuel Barrel ]
Manual Boat Engine: [ 1 Canvas / 1 Scrap Metal / 1 Lumber Pack ], 2 Lumber, 2 Plywood Packs

---
- **_Land Vehicles**_
  _________________________________

**Wooden bike**

any 1 hit to disable
recipe: 2 Wooden Bike Wheels, 1 Small Vehicle Frame
repair: 1 plywood pack + 1 lumber
1/2/0/0/50/30/-

**Wooden Motorcycle**

3 pistol bullets / meele hits to disable
recipe: 2 Wooden Car Wheels, 1 Small Vehicle Frame, 1 Engine, 1 Can
2/5/1/0/70/35/1

**Wooden ATV**

6 pistol bullets / meele hits to disable
recipe: 4 Wooden Car Wheels, 1 Small Vehicle Frame, 1 Engine, 1 Small Fuel Tank,  1 crate/box
2/20/3/1/90/55/2

**Wooden Car**

10 pistol bullets / meele hits to disable
recipe: 2 Wooden Car Wheels, 1 Medium Vehicle Frame, 1 Engine, 1 Medium Fuel Tank, 2 crates/boxes
4/40/5/2/90/55/5

**Wooden Offroad**

10 pistol bullets / meele hits to disable
recipe: 4 Wooden Car Wheels, 2 Medium Vehicle Frames, 1 Engine, 2 Medium Fuel Tank, 2 crates/boxes
2/40/10/2/110/75/5

**Wooden Ambulance**

10 pistol bullets / meele hits to disable
recipe: 4 Wooden Car Wheels, 2 Medium Vehicle Frames, 1 Engine, 3 Medium Fuel Tank, 3 crates/boxes
6/60/15/3/90/55/5

**Wooden V3S**

20 pistol bullets / meele hits to disable
recipe: 8 Wooden Car Wheels, 1 Large Vehicle Frame, 1 Engine, 1 Large Fuel Tank, 5 crates/boxes
2/100/30/5/90/55/10

---
- **_Air Vehicles**_
  _________________________________

**Wooden Autogyro**

4 pistol bullets / meele hits to disable
recipe: 4 plywood packs or 2 scrap metal (for the propellers), 1 Medium Vehicle Frame, 1 Engine, 1 Medium Fuel Tank, 1 crat/box
2/5/3/1/60/60/5

**Wooden Mozzie**

4 pistol bullets / meele hits to disable
recipe: 10 plywood packs or 5 scrap metal (for the propellers), 1 Medium Vehicle Frame, 1 Engine, 1 Large Fuel Tank, 1 crat/box
1/5/3/1/60/60/10

**Wooden LittleBird**

10 pistol bullets / meele hits to disable
recipe: 20 plywood packs or 10 scrap metal (for the propellers), 2 Medium Vehicle Frames, 1 Engine, 2 Large Fuel Tanks, 3 crates/boxes
4/30/10/2/80/80/20

**Wooden Mi-17**

20 pistol bullets / meele hits to disable
recipe: 30 plywood packs or 15 scrap metal (for the propellers), 2 Large Vehicle Frames, 1 Engine, 4 Large Fuel Tanks, 5 crates/boxes
8/50/20/5/80/80/40

---
- **_Water Vehicles**_
  _________________________________

**Wooden Floater**

3 pistol bullets / meele hits to disable
recipe: 1 Half Floor, 1 Manual Boat Engine
2/5/1/0/40/40/-

**Wooden Small Storage Floater**

3 pistol bullets / meele hits to disable
recipe: 1 Half Floor, 1 Manual Boat Engine,  1 crate/box
2/20/3/1/40/40/-

**Wooden Large Storage Floater**

3 pistol bullets / meele hits to disable
recipe: 1 Floor, 1 Manual Boat Engine,  2 crates/boxes
2/30/10/3/40/40/-

**Wooden Boat**

6 pistol bullets / meele hits to disable
recipe: 1 Half Floor, 1 Small Vehicle Frame, 1 Engine, 1 Small Fuel Tank
2/5/1/0/60/60/2

**Wooden Small Storage Boat**

6 pistol bullets / meele hits to disable
recipe: 1 Half Floor, 1 Medium Vehicle Frame, 1 Engine, 1 Small Fuel Tank,  1 crate/box
2/20/3/1/60/60/2

**Wooden Large Storage Boat**

6 pistol bullets / meele hits to disable
recipe: 1 Half Floor, 1 Medium Vehicle Frame, 1 Engine, 1 Small Fuel Tank,  2 crates/boxes
2/30/10/3/60/60/2

**Wooden Small Fishing Boat**

6 pistol bullets / meele hits to disable
recipe: 1 Floor, 2 Lumber Packs, 4 Plywood Packs, 1 Medium Vehicle Frame, 1 Engine, 1 Medium Fuel Tank
4/5/1/0/60/60/5

**Wooden Medium Fishing Boat**

6 pistol bullets / meele hits to disable
recipe: 1 Floor, 2 Lumber Packs, 4 Plywood Packs, 1 Medium Vehicle Frame, 1 Engine, 1 Medium Fuel Tank,  1 crate/box
4/20/3/1/60/60/5

**Wooden Large Fishing Boat**

6 pistol bullets / meele hits to disable
recipe: 1 Floor, 2 Lumber Packs, 4 Plywood Packs, 1 Medium Vehicle Frame, 1 Engine, 1 Medium Fuel Tank,  2 crates/boxes
4/30/10/3/60/60/5

**Wooden Small Transport Boat**

6 pistol bullets / meele hits to disable
recipe: 2 Half Floors, 2 Medium Vehicle Frames, 1 Engine, 1 Medium Fuel Tank,  1 crate/box
6/20/3/1/60/60/5

**Wooden Large Transport Boat**

6 pistol bullets / meele hits to disable
recipe: 2 Half Floors, 2 Medium Vehicle Frames, 1 Engine, 1 Large Fuel Tank,  2 crates/boxes
6/30/10/3/60/60/10

And allow Machine Guns updates for every vehicle with a medium or higher Fuel Tank or large Vehicle Frame and you've got a lot more action.
Have this done and the game would yet again be in the top10 viewed games on Twitch/Hitbox (currently on the 33th place) and a lot of players who tried their luck with the standalone would come back to the mod, at least for a short while.

**Comment by AsFoxy** [comment]
This repo is for Dayz mod vanilla, not Epoch or whatever you're talking about.

**Comment by ghost** [comment]
Did he really talk about a wooden Mi-17?

Ah, why bother. Wrong repo.

**Comment by sapioit** [comment]
I said I have not played enough with vanilla dayz mod. The suggestions are not for Epoch, but I have used something I'm familiar with in terms of crafting requirements, instead of diving head-first into a crafting system I'm not familiar with.

Also, what's wrong about a wooden mi-17? It would be very useful for transporting people and resources. Sure, you might be taken out the sky with 20 bullets shot at you, but if you manage to avoid getting shot at, it would be a good vehicle. Much better than the Wooden Littlebird, anyway... And since the items would just be on the ground, in some boxes, on the closest piece of land without obstructions, you can still get your stuff back...

**Comment by ghost** [comment]
Ok, your suggestions sound very "Epochy". There is a clear distinction between DayZ Mod and Epoch in gameplay. While DayZ Mod is meant to be a survival sandbox with a strong emphasis on survival, Epoch is more about building, crafting, collecting and selling. Ultimately building a base as huge as possible. Crafting in DayZ Mod is more about tinkering and cobbling together basic items from scraps and bits. 

Both games have their place and shouldn't be mixed.

So, as much as I personally appreciate your obvious huge effort, your suggestions seem to be a little too far out for DayZ Mod in my opinion. But hey, different people, different opinions.

**Comment by mouziee** [comment]
http://i.imgur.com/KsYpXaP.gif

**Comment by mouziee** [comment]
http://i.imgur.com/KsYpXaP.gif

**Comment by sapioit** [comment]
I get what you're saying, but this would allow a different type of gameplay to be included. While in Epoch you're building bases, this additions would only make it easier for the players to create a vehicle to drive around, thus making the game more enjoyable. Sure, if it's too easy, the people will not like it, which is why I think one should have to spend at least half an hour to create a single bike, including the wood cutting and crafting. And since it's a one-hit-broken, it should take some 10 more minutes to create a kit to fix it. The motorcycle could take an hour, and ATV an hour and a half, a gyrocopter could take 3 hours, a wooden floater could take an hour. And that just to build them, The repair kits could take at least half as much, assuming you have all the resources beforehand. 

This would not only allow the people to work together, but also give them more reasons to fight: vehicles. And since those wooden vehicles would be easy to shoot down, the people will think twice before using them. I mean, if all the vehicles are already taken by dominating clans containing many people and safe inside their bases, you might not have a chance to take the vehicles from them. So you would just make your own paper-thin wooden vehicles and try to use them to attack those bases. This would allow for a lot more tactical gameplay than before. I mean, you might be able to use those vehicles for transport, but they not suited for combat at all, however, with some tactical gameplay, they could allow a group of players to take over a base. Just think about it: random people teaming up to take out a clan which currently dominates a server and they couldn't do that before because they had no means of getting inside their base or close enough to their base without being killed. Now, if you could have those paper-thin vehicles, you could use some autogyros or mozzies to get inside their base,  or take out the snipers, than use a mi-17 to move the people from where they're spawned to a temporary base, where they would take vehicles from and drive towards the "mission" (taking revenge upon the dominating clan). But getting even a single vehicle could take days (resources gathering included), so unless quite a lot of people team up, there won't be many vehicles around.

**Comment by R4Z0R49** [comment]
Thanks for taking the time to drop down some thoughts down but I'm afraid they fall outside of what we are trying to achieve In dayz. 

Thanks again.

**Comment by sapioit** [comment]
No problem! Have a good one!
