### ISSUE TITLE
a random number of rounds

### ISSUE THREAD

**Issue by vlados73** [DayZMod/DayZ#691]
Please I beg you, do so patrons appeared with a random number , it will make the game much more interesting , as it was before

**Comment by AsFoxy** [comment]
Are you talking about weapon magazine loot spawning? To my knowledge magazines have always spawned full, and this is because of technical limitations.

**Comment by vlados73** [comment]
that is, it can not be changed ?

**Comment by AsFoxy** [comment]
Possibly in the future, but it's not really something that the ArmA 2 engine is very well equipped for.

**Comment by vlados73** [comment]
it would be great and difficult

**Comment by AlexAFlorov** [comment]
that will have sense only after fixing backpack/reskin issue with correct saving magazines rounds value
