### ISSUE TITLE
 canonicity zombies

### ISSUE THREAD

**Issue by vlados73** [DayZMod/DayZ#692]
How about that would make zombies more canonical, I mean to make them slow , and that they died mainly from headshots. 
is this possible?

**Comment by AlexAFlorov** [comment]
Canonical zombie is a fictional undead being created through the reanimation of a human corpse.

"Our" zombie is infected human, according :

On 12 March 2013, a prion disease and spreads among the worlds population triggering a global pandemic The disease causes proteins in the brain to be replaced with prions ceasing regular function Most people progress to dementia and then death as the brain is replaced with ineffective sludge 86% of the worlds population die Some survive with the disease in a chronic state. Lacking regular brain function, they are scarely human. They are unable to communicate, driven by insatiable desire for violence, and attracted to the scent of those uninfected Society crumbles as the pandemic spreads rapidly
You are one of the 2% who are not infected yet

So there are no "storyline" reason to make them slow. Let em hurt players in survival game :) Do not make dayzmod pvp only
