### ISSUE TITLE
[Request] Heatpack effect should be slow rather than immediate

### ISSUE THREAD

**Issue by rvett** [DayZMod/DayZ#693]
Heating up from using a heatpack should take a short while rather than being instantaneous. I was thinking about 30 seconds perhaps, so that when you're shaking from hypothermia, you can't just take a heatpack and start shooting immediately.

**Comment by AlexAFlorov** [comment]
https://www.youtube.com/watch?v=Q-hEoc2pUho&feature=youtu.be

**Comment by rvett** [comment]
Very cool! (no pun intended)

What happens if you use multiple heatpacks at the same time?
Have you tested if the heating effect is sufficient to stay/get warm even in the coldest conditions (night/rain/windy)?

**Comment by AlexAFlorov** [comment]
you will be heated up 10 min (now) from last heatpack used time. heatpacks effect not stacked

not tested yet, but it is almost enough to swim safe in water ;)

**Comment by R4Z0R49** [comment]
e89176d565b5f71479baf5f4ae8daad4108e00c3

Done

**Comment by bchawke** [comment]
I understand this issue is closed, but I have a suggestion.  Make the 3 arrows the same size to match the visuals used for bleeding.  The increasing size of the chevrons looks strange and inconsistent.  Otherwise, a GREAT addition to the mod!
