### ISSUE TITLE
[Request] Moving knives/matchboxes from weapon to regular items

### ISSUE THREAD

**Issue by AlexAFlorov** [DayZMod/DayZ#694]
After adding "multiple times usable items" like matchboxes and knives there is some strange case:  

we are able to keep only different items on toolbelt like weapons

when they was one-time-use items - that had sense. but now it is better to move them to regular inventory.  

it is not hard to do (to add "new" items)- but one problem exist - what to do with "old"

we can add to old items only one menu  option like "remove form toolbelt" and add converting script for that.

after that we will able to operate with it. combining/splitting for example

what do you think?

**Comment by AsFoxy** [comment]
I would love to change them both into magazines, however not while duping magazine ammo is so easy. Fortunately we're getting pretty close to fixing that.

**Comment by AlexAFlorov** [comment]
sure thing magazines is the best way

but duping 

as far as i know that problem was "almost solved" for a long time...  couple of years? :p

how close are we now? is there any chance to fix it next update?

or we should try proposed way before?

**Comment by R4Z0R49** [comment]
We cant fix the issue with native commands from arma we have to redo the hiveDLL something we are in the middle of.

**Comment by AlexAFlorov** [comment]
Yes, Foxy brought me up to date his idea in private conversation. Sounds good and possible :)

**Comment by VidKo** [comment]
If that is true, I can't wait for it! :+1:

**Comment by R4Z0R49** [comment]
Im going to close this for now. We can reopen again once 2.0 hits. We should hopefully have some new systems in place then.
