### ISSUE TITLE
Consinstency of naming ammo

### ISSUE THREAD

**Issue by VidKo** [DayZMod/DayZ#695]
Consistency of naming the mags should be improved. For the moment we have for example:

100Rnd. M240
200Rnd. M249 belt
30Rnd. G36 SD
DMR mag
G17 SD mag
CZ 550 magazine

Much better would be uniformity like:

100Rnd. M240
200Rnd. M249 belt
30Rnd. G36 SD
20Rnd. DMR mag
17Rnd. G17 SD mag
5Rnd. CZ 550 mag

That way in the inventory all of the ammo would be at the start of the list and not dispersed around.

**Comment by rvett** [comment]
This is a good request, I second this!

**Comment by AlexAFlorov** [comment]
Smth like that?

![clip2net_160704145609](https://cloud.githubusercontent.com/assets/2822392/16559716/7ec5e8e8-41f7-11e6-8294-60afa1654167.png)

**Comment by R4Z0R49** [comment]
Looks like this issue is under way.
