### ISSUE TITLE
Resources still present in mod with no credit given

### ISSUE THREAD

**Issue by xyberviri** [DayZMod/DayZ#696]
Hello guys, Just a quick skim over the repo reveals that you all still have the inventory sounds in the mod that i created for when you open a bag/inventory. 

Specifically these files:
action_open_backpack_0.ogg - action_open_backpack_4.ogg
action_open_inventory_0.ogg - action_open_inventory_4.ogg
Located in dayz_sfx.pbo 
In folder: DayZ/SQF/dayz_sfx/effects/

referenced by these lines of code:
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_sfx/CfgSounds.hpp#L502-L536

I see you all have removed the function that would trigger this sound from the mod so It seems you have no use for them to remain.

These sounds were converted specifically for this mod, i kindly ask that these files also be removed since i still retain rights over them.

Thanks much.

**Comment by AsFoxy** [comment]
Those sounds are definitely still in use, though the code might have been changed. I'm not sure who implemented them, or why no credit has been given. Do you want us to stop using them, or will adding you to the credits be sufficient?

**Comment by xyberviri** [comment]
Hello AsFoxy, 

I was the original implementer of the sounds and added the code for the playing the sound when opening weapon holders or backpacks, which is the reason i know about them. I'm perfectly fine with Attribution, below the license for these specific files, please note while i realize the mod is under DML-SA only DayZ MOD itself is allowed to distribute the files. 

All Other mods/forks will have to request permission individually, they can find me on on gmail with the same username as here. 

License for the 10 sounds:

> The following files are works of https://github.com/xyberviri
> The DayZMod and only the DayZMod is allowed to use the following sounds for their mod under the following license: Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)
> 
> action_open_backpack_0.ogg
> action_open_backpack_1.ogg
> action_open_backpack_2.ogg
> action_open_backpack_3.ogg
> action_open_backpack_4.ogg
> action_open_inventory_0.ogg
> action_open_inventory_1.ogg
> action_open_inventory_2.ogg
> action_open_inventory_3.ogg
> action_open_inventory_4.ogg 
> 
> As the author of the files and not a member of the Arma community:
> I DO NOT acknowledge the Dayz Mod License Share Alike (DML-SA) license.
> No other mods/maps/missions/add-ons/etc are allowed to use the above sounds, If DayZMod has been used as a basis for another mod, then those mod authors will have to request permission to use the above files as this falls under "NoDerivatives".

**Comment by R4Z0R49** [comment]
I'm not quite sure why you havent been given credits for the sounds as you said you implemented them 😉 guess you forgot to give yourself credits 😀.

But yea not a problem I can sort credits out no issue at all.

**Comment by xyberviri** [comment]
Thanks Carl, Yeah i think your right, i don't ever remember going into that file and modify it myself. So also partly my bad too. I thought you all delete the functionality and the sound files so i never followed up with it.

**Comment by ebayShopper** [comment]
They are used here if you were wondering:
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_code/compile/object_speak.sqf#L35

On line 46 it appends a random 0-4. This runs when dayz_zombieSpeak is called in the gear code.

Are you okay with us using them in the next Epoch update @xyberviri? We've recently rebased [DayZ Epoch](https://github.com/EpochModTeam/DayZ-Epoch) on DayZ Mod 1.8.7+ in preparation for one last EoL patch. It is mostly a fork of this repo with Epoch on top now.

**Comment by xyberviri** [comment]
Ebaydayz thats fine, i just dont want end up in another overpochwatchception :+1:

**Comment by R4Z0R49** [comment]
I'm going to reopen this until i add the credits just so i don't forget.

**Comment by R4Z0R49** [comment]
Updated credits and license info, hopefully should be all good now.

Thanks.
