### ISSUE TITLE
Item stopping vehical from spawning from data base

### ISSUE THREAD

**Issue by fazmond** [DayZMod/DayZ#697]
so we had and v3s not spawn after server restart
so I checked the database and it was still in there 
I then removed all the items from it and restarted the server 
then it spawned empty OFC

so there must be an invalid item inside 
please advise

the items I removed was 
[[["ItemDIY_wood","ItemToolbox","ItemFlashlight","ItemSledgeHammerBroken","Mosin_DZ","ItemHatchet","ItemMatchbox","ItemPickaxeBroken","PKM_DZ","AKM_DZ","RPK74_DZ","RPK_DZ","SA58_DZ"],[3,1,1,1,2,1,1,1,1,3,1,1,1]],[["ItemSodaPeppsy","ItemWaterBottleSafe","ItemSodaFranka","ItemSodaLemonade","Skin_Survivor2_DZ","ItemJerrycan","FoodGoatRaw","ItemAntibiotic2","equip_nails","equip_metal_sheet","ItemSandbag","equip_duct_tape","PartFueltank","ItemPlank","PartEngine","5Rnd_762x54_Mosin","FoodCanRusMilkEmpty","equip_comfreyleafs","PartGeneric","ItemAntibacterialWipe","FoodCanRusUnlabeled","FoodCanCorn","FoodCanHerpy","ItemSodaCoke","PartGlass","30Rnd_545x39_AK","30Rnd_545x39_AKSD","75Rnd_545x39_RPK","ItemBandage","PartWheel","ItemSodaLirik","FoodMuttonCooked","equip_feathers","FoodChickenRaw","equip_hose","ItemPainkiller","FoodCandyChubby","FoodCandyLegacys","equip_lever","Attachment_BELT","ItemAntibiotic1","emptyBloodBag","bloodBagONEG","ItemMorphine","bloodBagOPOS","bloodBagBNEG","bloodBagBPOS","bloodBagABNEG","bloodBagANEG","ItemHeatPack","PartVRotor","Attachment_Ghillie","100Rnd_762x54_PK","ItemCamoNet","Attachment_SA58RIS","FoodCanDemon","FoodMRE","75Rnd_762x39_RPK","bloodTester","30Rnd_762x39_AK47","30Rnd_556x45_StanagSD","30Rnd_9x19_MP5","100Rnd_762x51_M240","30Rnd_556x45_G36","30Rnd_556x45_Stanag","1Rnd_HE_GP25","17Rnd_9x19_glock17SD","FlareGreen_GP25","30Rnd_9x19_MP5SD","30Rnd_762x39_SA58"],[2,1,1,2,1,18,4,1,2,3,7,6,4,5,2,2,1,3,8,4,1,1,1,1,5,4,4,4,4,3,2,1,5,2,1,3,1,1,2,1,1,1,1,4,2,1,2,1,1,1,1,2,2,1,2,1,1,1,1,2,1,2,1,1,1,1,1,1,1,2]],[["DZ_ALICE_Pack_EP1","DZ_TK_Assault_Pack_EP1","DZ_Czech_Vest_Puch"],[1,2,1]]]

**Comment by fazmond** [comment]
I think we narrowed it down to one of these items but I need some sleep now 

ItemSodaPeppsy","ItemWaterBottleSafe","ItemSodaFranka","ItemSodaLemonade",,"FoodGoatRaw","equip_nails","equip_metal_sheet","ItemSandbag","equip_duct_tape",,"ItemPlank","equip_comfreyleafs","ItemAntibacterialWipe","FoodCanRusUnlabeled","FoodCanCorn","FoodCanHerpy","ItemSodaCoke","30Rnd_545x39_AK","30Rnd_545x39_AKSD","ItemBandage"

**Comment by AlexAFlorov** [comment]
vehicles like Ural and V3S able to consist a lot of items

but hive cannot read very LONG strings when adding content to vehicle from database.

vehicle can be full for example:
 [[["PKM_DZ"],[50]],
[["FoodMRE"],[200]],
[["DZ_ALICE_Pack_EP1"],[8]]]
and will be loaded successfully
string of contents is approx 70 symbols length

your string is above 1600 symbols - system cannot read and process it

Temp solution - remove some items/weapons with long names from it (for example :"ItemSledgeHammerBroken" , "ItemAntibacterialWipe" etc (with corresponding value) 

and tell players not to fill vehicles/tents with many DIFFERENT items/weapons

better to have 200 same items than 50 different

**Comment by fazmond** [comment]
No no no we kept cutting the string by half to try find out which items could be causing the v3s not to load so was well under the limit your talking about . Also this was filled up in game not something we just added in via the database. If you read my second post that was all we had in it upon starting the server and it still didn't spawn in

**Comment by fazmond** [comment]
The point being if there Is something that's is causing an object not to spawn then it is a bug with the game and needs to be addressed . If there is a limit on what a object sting may contain then the game should check this and stop the player from over filling . And not leave it to a player guess when he's putting in items that are still within the limits of the inventory

**Comment by kichilron** [comment]
Is it a copy/paste error that you're missing a closing bracket at the very end in your initial comment?

**Comment by fazmond** [comment]
Forget what I posted here it's the items that's causing it

**Comment by AlexAFlorov** [comment]
http://clip2net.com/clip/m79064/7a7a2-clip-19kb.png?nocache=1

**Comment by AsFoxy** [comment]
The string in your second post is ill-formed. Have you seen any script errors in your server rpt log file? You might try this well formed string with the same items. `[[[],[]],[["ItemSodaPeppsy","ItemWaterBottleSafe","ItemSodaFranka","ItemSodaLemonade","FoodGoatRaw","equip_nails","equip_metal_sheet","ItemSandbag","equip_duct_tape","ItemPlank","equip_comfreyleafs","ItemAntibacterialWipe","FoodCanRusUnlabeled","FoodCanCorn","FoodCanHerpy","ItemSodaCoke","30Rnd_545x39_AK","30Rnd_545x39_AKSD","ItemBandage"],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]],[[],[]]]`

**Comment by fazmond** [comment]
I was just posting the items forget the I'll formed post we entered the strings correct

**Comment by AsFoxy** [comment]
I'll ask again then, have you seen any script errors in your server .rpt log?

**Comment by fazmond** [comment]
Will do more research tonight at work atm

**Comment by R4Z0R49** [comment]
This is a know limit of the strings used we are working to improve this.

Thanks.
