### ISSUE TITLE
Players don't take damage when hit by car

### ISSUE THREAD

**Issue by Inurosen** [DayZMod/DayZ#698]
Tested that many times with different cars. Players just being thrown away when hit and not taking any damage.

**Comment by ebaydayz** [comment]
@vinyljunkie mentioned on discord that this seems to be related to antiTP:

> Based on player reports and reading the RPT. Players that get run over appear to be teleporting instead. In the RPT we see teleport reverts. As we have a parser that catches teleport attempts over 250 meters, it bans the player for it. They contact us and they tell us they were being ran over by a car then got the ban message. If it all were working as intended they would have died instead.
or get serioulsy wounded.

And @skigoggles said:
> I find that you have to run over players twice to get a good kill.

AntiTP may be getting triggered if the knock back from the vehicle hit is too far. Another potential culprit is the exitWith zero damage for local explosions anti-hack by @facoptere:
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_code/compile/fn_damageHandler.sqf#L23-L26

It should be easy to narrow it down by testing with a diag_log added in the exitWith.

**Comment by Inurosen** [comment]
Tested this with antiTP feature disabled. The issue still persists. No damage take, but thrown to hundreds of meters away. Probably the're is some bug in damage handling.

**Comment by skigoggles** [comment]
tested this a bit lately - it seems to be at high speed that you are more likely to be thrown than killed.

**Comment by vinyljunkie** [comment]
I think this might be related to the same issue: https://youtu.be/EiOqbwbI1PA

RPT:

"DAMAGE: player hit by Survivor3_DZ in legs with  for 4.43739 scaled to 1109.35, Conscious true"
"RE rplaymovecode args:[<NULL-object>,Agent 0x29cde100,"ZombieStandingAttack8"]"
[233.422,"z\addons\dayz_code\system\scheduler\sched_gravity.sqf","freefall reset, final freefall height is dh:",0.99576,"dt:",1.39746,"gravity:",1.01978,"m.s^-2"]

"DAMAGE: player hit by Survivor3_DZ in legs with  for 3.80817 scaled to 952.042, Conscious true"
["z\addons\dayz_code\compile\fn_damageHandler.sqf","Legs damage registered from freefall, damage:",3.80817,"gravity:",9.81,"height:",6.2776,"blood loss",1539.58]
[234.827,"z\addons\dayz_code\system\scheduler\sched_gravity.sqf","freefall reset, final freefall height is dh:",7.70185,"dt:",1.40039,"gravity:",7.85465,"m.s^-2"]
