### ISSUE TITLE
Mission File Missing Option for Heli Crash Grass

### ISSUE THREAD

**Issue by Muppet1856** [DayZMod/DayZ#7]
- [NEW] - Clear Ground around loot at crash sites added but disabled by default, server admins can enable. Adds a small circle around each loot pile

HOW?  Didn't find in the mission pbo...

**Comment by R4Z0R49** [comment]
Server.pbo

compile/server_spawnCrashSite.sqf

Line 94 and 95

From
            //_clutter = createVehicle ["ClutterCutter_small_2_EP1", _position, [], 0, "CAN_COLLIDE"];
            //_clutter setPos _position;

to

```
        _clutter = createVehicle ["ClutterCutter_small_2_EP1", _position, [], 0, "CAN_COLLIDE"];
        _clutter setPos _position;
```

**Comment by Muppet1856** [comment]
Thanks..
