### ISSUE TITLE
Request to use / utilise DayZ 1.7.7.1 code and content in DayZ Sahrani

### ISSUE THREAD

**Issue by NonovUrbizniz** [DayZMod/DayZ#70]
We follow the rules and reference all original authors, map is currently the @Caa1 build of Sahrani by "Kju[PVPSCENE]" who approved the project, it is now being forward ported to A2 with source files licensed by Bohemia Interactive (Ota Vrťátko & Ivan Buctha).

No external models are used w/o express written permission.

Github is private, but you can reference here:

http://opendayz.net/threads/dayz-sahrani-mod-development-work-in-progress.7373/

and here is a post I made trying to help explain author's rights to DayZ Fans:

http://opendayz.net/threads/dayz-sahrani-license-information-authors-rights-briefing.11574/

I will be doing a full proper license with the next release, and we already do not modify any of the unapproved files, and keep the credits intact for DayZ.

**Comment by Skaronator** [comment]
Alright, thank you.
