### ISSUE TITLE
ATV_US_EP1 (1.8.7) (QF12)

### ISSUE THREAD

**Issue by Relic77** [DayZMod/DayZ#702]
Seems like the ATV is bugged. The repair engine option is invisible. But if you scroll down just before cancel (with everything else repaired) the highlight disappear and you can click and it will repair (not tested) but it said I was missing engine-parts so I assume it will repair if I had the parts. 
![20160713215615_1](https://cloud.githubusercontent.com/assets/20408065/16817906/47cdcd2e-4945-11e6-8549-c4b43ce24d91.jpg)
![20160713215311_1](https://cloud.githubusercontent.com/assets/20408065/16817907/47cfe1ae-4945-11e6-93db-36b37be1a22b.jpg)

.

**Comment by thcNox** [comment]
This bug is not specific to ATV's and can probably happen to any vehicle. Choppers seem especially prone to it in my experience

**Comment by R4Z0R49** [comment]
This is a known issue we are looking into the action system to see what we can to improve this for everyone.
