### ISSUE TITLE
[Request] Humanity for filling empty BBs rather than applying whole BBs

### ISSUE THREAD

**Issue by rvett** [DayZMod/DayZ#710]
I've always wondered why one should receive humanity for using a (previously filled) bag of whole blood on oneself. Like self-bandaging, that shouldn't count as a human act, it's just part of survival. Instead, what's human about self blood bags is the blood donation beforehand. So my suggestion is to move the 25 humanity reward from the application of whole blood bags to the filling of empty ones.

**Comment by R4Z0R49** [comment]
Bloodbags humanity has been changed for 1.8.8
