### ISSUE TITLE
Lost backpack upon logging in

### ISSUE THREAD

**Issue by kooj12** [DayZMod/DayZ#712]
Lost my backpack upon login. Had a backpack last time I played and the next day after logging in it had vanish. Did not cancal the login.

Common bug?

**Comment by Inurosen** [comment]
Why not try to solve this issue with server admin first?

**Comment by R4Z0R49** [comment]
Your best to speak with the admin of the server. If they feel its a bigger issue they will pass the info along with more info and logs.

Thanks.
