### ISSUE TITLE
[Request] Balance out worth between Wooden splint and morphine

### ISSUE THREAD

**Issue by Landbergaren** [DayZMod/DayZ#714]
Hello! I have a suggestion to the "morphine is hardly used today"-issue some people feel that they are having and I guess I can agree since on a populated server you instantly go for the easier to get wooden splint rather then the morphine (unless you get lucky with a spawnpoint close to a hospital and manage to get a spawned morphine). 

What about if applying wooden splint had a longer animation time then taking a morphine? That would still keep you going for the easy to get wooden splint but still be wanting to look for a morphine. No more morphines laying there asking "remember when I was a thing? ;/ ). This will also add a bit to the looting-game which basically defines DayZ. Also I think its a logical way to balance it since a wooden splint requires work to apply while the morphine has a auto-injector. 

What do you guys think?

**Comment by KPanicEKS** [comment]
+1

**Comment by AndrewEscocia** [comment]
make splints 2 slots ?

**Comment by bchawke** [comment]
Agreed on all the points above.  Another thought, could you eliminate a player's ability to sprint (double tap W) until they find morphine?  Or is that too harsh? (You can only sprint short distances anyways before it slows you down to the normal run, right?)  Splint could be a temporary solution in the wild until you find morphine.

**Comment by Landbergaren** [comment]
Andrew, I would go with that idea as well! 2 slots sounds logical.
