### ISSUE TITLE
G36A/K weapon and attachment

### ISSUE THREAD

**Issue by kooj12** [DayZMod/DayZ#718]
Putting silencer on G36K removes the visual zeroing appearance on your UI, is this something that can be fixed?
Red dot sight has zeroing 100meters and sniper scope has 200 as shown in the pictures, the weapon itself is not zeroable, but its a good indication of what scope you are in. http://imgur.com/a/LypSE 

Also another thing, it is possible to put 5.56 silencer on the K type but not on the A. Is this something that can be fixed aswell? I have not tested the G36C so on that weapon I dont know if it works.

**Comment by bchawke** [comment]
Pretty sure silencers work on the G36C.  I believe I recall a friend of mine putting a silencer and a CCO on one.  It looked badass.  =)

**Comment by tangohosts** [comment]
Hello, I'm hosting a DayZMod 1.9 server right now and have noticed and can demo that the G36K camo and the G36A camo do not accept the 5.56 suppressor attachment in the current patch. At the moment I'm not sure if the issue stems from my personal files or database but considering the result for attempting message stating that the attachment cannot be used with the weapon is still present like if it were tried with any other incompatible weapon.  Hoping that this can be hotfixed soon if this can be repeated on other servers.

Any other cases of this to help confirm?

**Comment by TermNCR** [comment]
Can confirm the G36K and G36C will take a 5.56 suppressor attachment in 1.9.0. One of our admins only uses this gun.

Hope this helps. 

https://cdn.discordapp.com/attachments/346302409103900676/406634706369511444/ArmA2OA_2018_01_27_03_20_19_985.jpg


https://cdn.discordapp.com/attachments/346302409103900676/406634713894354944/ArmA2OA_2018_01_27_03_20_12_628.jpg

**Comment by tangohosts** [comment]
I got it working as well, although I have to say that the exact cause
remains a mystery. I believe its possible that it was due to either an
outdated @hive/dayz_server or possibly somehow outdated dayz code

**Comment by tangohosts** [comment]
oh crap, and apologies for the necro. thanks for taking the time to post Term!
