### ISSUE TITLE
Journal - Humanity - value is not rounded in display

### ISSUE THREAD

**Issue by skigoggles** [DayZMod/DayZ#729]
player noticed this - the humanity is not rounded in the display, but the db humanity column is INTEGER, so if you view, log out, login, it will be different. 

I believe this is in \actions\playerstats\epeen_setText_Hournal.sqf

for example, blood, hunger, thirst and temp are all rounded, 
    (round(r_player_blood)),
    (round(dayz_thirst)),
    (round(dayz_temperatur)),

so presumably, the fix is just:

round((player getVariable['humanity', 0])),

**Comment by rvett** [comment]
Can confirm this. Noticed it many times. It's just a tiny little detail, but should be easy to fix.
