### ISSUE TITLE
[Request] Chevrons/arrows for blood transfusions

### ISSUE THREAD

**Issue by rvett** [DayZMod/DayZ#730]
This is yet another "would be nice to have" feature request that's probably easy and quick to implement for someone. Like the new chevrons/arrows indicating temperature changes, which I'm very much looking forward to, it would be great to have three arrows up during blood transfusions. Only in case of a working one of course. Just for the sake of completeness, because blood loss and recovery through eating or resting at tents already have them, but transfusions don't. Also it would help recognising if a transfusion actually works or not.

**Comment by R4Z0R49** [comment]
You get a big msg across the screen letting you know its in progress. I don't think anything else is needed.

**Comment by rvett** [comment]
Yes, but it still fails sometimes (bacause Arma, I guess). Anyway, that's not the main intention. My point is that it's a missing piece in the whole arrows thing. It would make sense to fill the gap, is what I'm trying to say.
