### ISSUE TITLE
typo? in dayz_code\Configs\CfgWeapons\Rifles\SA58.hpp

### ISSUE THREAD

**Issue by skigoggles** [DayZMod/DayZ#734]
player asked about SA58 and flashlight. While looking through the source to check, I noticed:
class SA58_RIS_FL_FZ : SA58_RIS_DZ

I can't think of any reason it would end in "_FZ".

**Comment by ebayShopper** [comment]
https://github.com/DayZMod/DayZ/commit/8ddf40d9070da46c78aaacd1e821c0a931d79a7f
