### ISSUE TITLE
Melee weapon behavior

### ISSUE THREAD

**Issue by rvett** [DayZMod/DayZ#736]
I'm sure this is very well known by most players, but I haven't found it documented anywhere. Of each melee weapon (hatchet, machete, ...) there are essentially two types: one when it is equipped like a primary weapon, and one when it is in the toolbelt.

In the former case, it will:
- appear high up in a container list together with other primary weapons
- require 10 slots in a backpack
- replace your primary weapon when picked up.

In the latter case, on the other hand, it will:
- be listed further down in container lists, together with other toolbelt items
- require only one backpack slot
- go to your toolbelt when picked up

That's not very logical. Is this something that can be improved? I'm wondering if it's done this way because of Arma's engine limitations. I think I would prefer them always behaving like toolbelt items (case 2).

**Comment by ebaydayz** [comment]
Basically you are requesting we:
1. Change the display names so they are close together in gear lists.
2. Automatically convert MeleeX (primary) version into ItemX (toolbelt) version when moving into backpack.

Those are both good ideas and not hard to do, but not high priority. 1.8.8 is about to be released, so we are pretty much feature frozen atm. You can expect this for 1.8.9 maybe.

**Comment by rvett** [comment]
Assuming that the Arma 2 engine requires two types to be present in the first place, (i.e., in oder to make melee weapons possible at all), I think what could eliminate the problem I described is indeed an automatic conversion from MeleeX to ItemX whenever the weapon is placed into a container (tent, stash, backpack, vehicle, ...) or dropped to the ground. No need to rename anything I think. The fact that they will always become toolbelt items should group them together in gear lists automatically, right?

1.8.9 is just fine with me. Looking forward to 1.8.8!

**Comment by ebaydayz** [comment]
The melee versions only take one slot when placed in a tent, vehicle, etc. The only place they take ten is in the backpack. But it wouldn't hurt to convert it for storage anyway.

We don't want to convert it when dropping to or picking up from the ground (WeaponHolder) because players with no weapon want to loot and have it in their hands immediately. Not to mention it would multiply the newbie not knowing how to right click his flashlight problem to every melee weapon.

**Comment by rvett** [comment]
True, they only take on slot in tens, vehicles etc., but that's not the problem I meant to describe. The problem is that there will be two kinds of hatchets in there (assuming there already was one of the other kind), when there should be only one, because a hatchet is a hatchet. When you find a tent with a hatchet in it, and you take it, you don't know if it will replace your rifle or go to your toolbelt. That has caused much confusion for me, including loss of ammo (because my rifle was placed in the already full container together with all ammo when all I wanted to do was pick up that melee weapon).

About the newbie looting thing: Melee weapons are always spawned as toolbelt items by the engine as far as I know, and that's a good thing. So whenever you pick up one that wasn't placed there by a player, it goes to your toolbelt. The same should be the case for dropped ones, to avoid confusion. The whole system would be much easier to understand if melee weapons always behaved the same way, in my opinion, also for newbies. This could all be done if MeleeX always got converted to ItemX when put anywhere.

**Comment by ebaydayz** [comment]
The melee versions are still spawned in the loot tables currently:
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_code/Configs/CfgLoot/Groups/Buildings/Industrial.hpp#L8-L10
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_code/Configs/CfgLoot/Groups/Buildings/Farm.hpp#L13-L14
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_code/Configs/CfgLoot/Groups/Buildings/Castle.hpp#L11-L12

I see your point though. For the sake of consistency we might want to change the loot tables to always spawn the toolbelt versions and convert the melee version to toolbelt anytime it is moved out of the player's hands. Newbies not knowing how to use it right away is not a huge deal.

**Comment by rvett** [comment]
Ah, interesting, my impression of the loot tables was wrong then. Well, anyway, my request stands. :) Thanks for giving it a thorough thought.

**Comment by AndrewEscocia** [comment]
Baseball Bat has no tool version, since it has no function as a tool?
Machete also has no tool function but still can be put into the tool belt. 
More of a consistency issue rather than a game breaker.
