### ISSUE TITLE
Some errors with Server-1.8.8-45e757e-FullDevelopment

### ISSUE THREAD

**Issue by denisio** [DayZMod/DayZ#753]
http://se1.dayz.nu/latest/1.8.8/181/%40Server-1.8.8-45e757e-FullDevelopment.rar

Error in expression <ion = ((selectBestPlaces [getMarkerPos (dayz_centerMarker select 0), (dayz_cente>
   Error position: <dayz_centerMarker select 0), (dayz_cente>
   Error Undefined variable in expression: dayz_centermarker
File z\addons\dayz_server\compile\server_spawnInfectedCamps.sqf, line 59
  "Spawning an infected camp (Camp1_Small) at any"
   String STR_EVAL_TYPENAN not found
Error in expression <os select 2} else {_z = 0};
_newPos = [_posX + (_newRelPos select 0), _posY + (>
   Error position: <_posX + (_newRelPos select 0), _posY + (>
   Error Undefined variable in expression: _posx
File ca\modules\dyno\data\scripts\objectMapper.sqf, line 149
  String STR_EVAL_TYPENAN not found

Error in expression <}
else
{
_rdm = 0;
};

if ((typeName _pos) != (typeName [])) exitWith {debugL>
   Error position: <_pos) != (typeName [])) exitWith {debugL>
   Error Undefined variable in expression: _pos
File ca\modules\dyno\data\scripts\objectMapper.sqf, line 38
 String STR_EVAL_TYPENAN not found
Error in expression <ate["_PosX","_PosY","_isFlat"];
_PosX = _X + (_maxDistance - (random (_maxDistan>
  Error position: <_X + (_maxDistance - (random (_maxDistan>
  Error Undefined variable in expression: _x
File z\addons\dayz_code\compile\fn_selectRandomLocation.sqf, line 15
String STR_EVAL_TYPENAN not found

Error in expression < _compositionObjects;

{
_objectPos = [_position, 8, 13, 5] call fn_selectRando>
   Error position: <_position, 8, 13, 5] call fn_selectRando>
   Error Undefined variable in expression: _position
 File z\addons\dayz_server\compile\server_spawnInfectedCamps.sqf, line 81
 String STR_EVAL_TYPENAN not found

**Comment by R4Z0R49** [comment]
did you replace your mission file?

**Comment by denisio** [comment]
Yes, I updated mission file.

**Comment by R4Z0R49** [comment]
Search "dayz_centermarker" (0 hits in 0 files)

Are you sure you have updated everything. The requested does not exist in server_spawnInfectedCamps.sqf

**Comment by skigoggles** [comment]
google "dayz_centermarker" and you'll see reference to older code(This was revised a few weeks ago), so looks like the server code is a few revs older. New code pulls coords from the center marker of the mission.

**Comment by denisio** [comment]
All works fine. I copied dayz_server.pbo to the wrong directory.
Thanks
