### ISSUE TITLE
1.8.9 Changes

### ISSUE THREAD

**Issue by R4Z0R49** [DayZMod/DayZ#756]
Added, Giving splints to another person now grants humanity. (25)
Added, All player names are now the same color in the lobby regardless of status.
Added, Streamer mode is toggleable by player in game options. Enabled hides server logo and rules feed.
Added, Military flashlight attachments
Added, Map markers are now automatically tagged with the name of the player who placed them.
Added, Ten second count down to abort button to improve reliability of player saving.
Added, Journal now shows game time rather than when the player was created.
Added, CZ550 now has bolt animation and secondary sight modeled by @Streatman.
Added, LeeEnfield now has bolt animation modeled by @Streatman 
Added, Disassemble of Fence,Gates no longer returns Nails,Stone, All other parts have a 30% chance to be returned.
Added, Fence & Gates now take damage from bladed melee weapons (foundation level to level 4)
Added, Four new POI (NWATentCamp, ElektroWells, GvozdnoMilitaryBase, Shakhovka) and updated Trains 

Updated, New Ai node if the agent dies during chase.
Updated, Bat damage increased to crowbar level. Nailed and barbed bats increased to the same as hatchet.
Updated, Inventory and Hitpoints retrieval no longer using format (due to the 2048 characters limit), Should fix big inventory's like the ural. 
Updated, Changed tool break chances for harvesting from 4% per run to 9%.
Updated, infectious Waterholes are now chosen by the server and spawned local to each client.
Updated, Hold breath is now blocked if more than one control is assigned to it at once.
Updated, Turbo is now blocked on foot. Players are prevented from assigning any control to it.
Updated, Renamed DZ_Czech_Vest_Puch --> DZ_Czech_Vest_Pouch
Updated, Rolling messages now use cutRsc instead of cutText to display lower on the screen.
Updated, AI Movement systems (no longer move while in attack range,No longer keeps running position updates while loitering)
Updated, Reverted pain effect to old violent shaking instead of subtle gun sway.
Updated, Spawn as seagull due to 144 west groups being exceeded should occur less often now.
Updated, Flies now spawn ten minutes after death instead of right away.
Updated, Increased head shot damage for normal hits (non-zombie and non-melee)
Updated, Slightly increased damage from vehicle run over
Updated, Renamed r_action_count --> dayz_actionInProgress (now true/false instead of 1/0)
Updated, Fence build requirements, Fence damage Handling
Updated, AI behaviour, Speed,
Updated, RIS can now be removed from SA58_RIS.
Updated, Loot Balance changes (barracks,Military,Crash Sites),
Updated, Build requirements for fence and gates.
Updated, Maintenance mode for fences updated,
--- Level 1-4 = 7 days to set then for each 3 days in MM reduce level.
--- Level 5-7 = 14 days to set then for each 6 days in MM reduce level.
Updated, Disabled use of non-SD magazines in SD assault rifles.

Fixed, Spamming sleep at tent no longer runs under some circumstances.
Fixed, Melee weapon ammo being removed after certain actions.
Fixed, Classic nutrition values regenerate blood again.
Fixed, Removed nutrition hit for pushing a plane.
Fixed, Maintenance action should now disappear after maintaining a fence.
Fixed, Tranquilizer and Melee knockouts should now last for the intended time of 20s-80s.
Fixed, Removing traps not returning anything to the player and throwing script errors on the server.
Fixed, No damage from tripwire grenade trap.
Fixed, Vehicles appearing to repair when taking first damage from a fully repaired state
Fixed, Antibiotics not reducing when given to another player, also giving antibiotics to another player no longer removes infection from the player giving the antibiotics.
Fixed, Players no longer get the option to give bloodbag to a player with full blood.
Fixed, Several errors with loading and unloading unconscious players from vehicles.
Fixed, Animals sometimes being deleted right next to players.
Fixed, Field hospital tent misplaced behind Cherno factory.
Fixed, Floating loot.
Fixed, Flies occasionally spawning where player logs out.
Fixed, Giving Painkillers to another player no longer removes inpain from the player giving the painkillers.
Fixed, WoodenArrowF and some other weapon holder objects catching fire when destroyed.
Fixed, Damage log not showing in server RPT when player is shot with a vehicle weapon.
Fixed, issue with decaying fences from  WoodenFence_1_frame to WoodenFence_1_foundation.
Fixed, issue with some base objects being damage above 1 and never cleaned up.
Fixed, If a player force kills their game immediately after dying their body will no longer disappear.
Fixed, Player_craftItem not exiting when action is already in progress.
Fixed, Players can no longer pack a tent while sleeping.
Fixed, Panic sounds will no longer overlap when the player is attacked by zombies while low blood.
Fixed, Melee weapons will no longer be eaten when attempting to add them to a full toolbelt.
Fixed, Sky on fire bug again with updated Core Patch BIS_Effects thanks to Sa-Matra.
Fixed, When a land vehicle explodes the driver and all passengers are now ejected.
Fixed, When a helicopter or plane explodes the pilot and all passengers are now ejected and killed.
Fixed, Combining M24 or 2Rnd shotgun ammo can no longer be abused to dupe mags.
Fixed, G36C ACOG attachment
Fixed, Trees at POIs can be chopped down now.
Fixed, All traps now need to be armed after placing. This fixes them not triggering right after building.
Fixed, Smoke and grenade tripwires now require a grenade to rearm after triggering.
Fixed, Player no longer does medic animation after triggering a single use trap.
Fixed, Removing a trap with no room in your gear will no longer delete the trap.
Fixed, The unconscious wake up animation can no longer be skipped by using a bandage.
Fixed, Knives and matches sometimes eaten after use, combine or sharpen with more than one on toolbelt.
Fixed, Save is now called correctly when the abort menu is opened. It was previously using the wrong time.
Fixed, Mysql db some vehicles assigned to the wrong vehicle group.
Fixed, Melee weapons can no longer be duplicated by double clicking and right clicking them simultaneously.
Fixed, A crash related to the binoculars animation.
Fixed, Pickup_PK_INS can now be reloaded.
Fixed, Fence and Gate Now takes damage from explosive Arrows.
Fixed, Readded crossbow reload sound
Fixed, Actions like cook, gather meat, repair, etc. are now interrupted properly if the player vaults, moves or enters a vehicle during the medic animation.
Fixed, An issue with reload and camshake causing a horrible visual bug.
Fixed, Input was not always fully disabled during a knock out.

Removed, WireFence Due to issues with some players and graphic glitches this item has been removed.

Notes
ServerAdmins, Must install 2015 redist for the new hive.dll changes.

**(QF1) Released**
Fixed, Players being ejected from vehicles when changing to hero or bandit,

**(QF2) Released**
Fixed, Player and vehicle not taking physics damage from crashing,
Fixed, Driver will not get a humanity hit for damaging passengers in a vehicle crash,
Updated, Breakin chance of tools breaking,

**(QF3) Released**
Fixed, Confirmed Kills limited to one time use,
Fixed, Confirmed Kills now displays kills correctly,
Fixed, Player name and cause of death occasionally showing "unknown" on study body when they shouldn't.
Fixed, Hit processing running twice when it shouldn't causing legs to break more quickly when hit.
Updated, Humanity from Death/Damage reset back to 1.8.6 (Death, nKills \* 33.3%, Damage, nKills*3.33%),

**(QF4) Released**
Fixed, Maintenance action should now disappear after maintaining a fence.
Fixed, Maintenance PVS to replace object causing an error. 

**(QF5) Released**
Updated, Fence damage lowered to 1 c4 from 2.
Updated, Gate Breakin chances by double from .04 to .08
Updated, Gate breakin tool chance divided by 2 from 30% for sledge to 15%, and from 20% crowbar to 10%
Fixed, Maintenance action should now disappear after maintaining a fence.

**(QF6) Released**
Reverted, Gate Breakin chances .04 From QF5
Reverted, Gate breakin tool chance to 30% for sledge and 20% for crowbar from QF5
Added, Player now plays an animation during change clothes,

**(QF7) Released**
Reverted, Player now plays an animation during change clothes from QF6 Test

**Comment by bchawke** [comment]
Looks great @R4Z0R49 !  Quick suggestion Streamer mode, though, F12 is used by most people to take screenshots as it's the default for screenshots in Steam.  Possibly another key for that?

**Comment by R4Z0R49** [comment]
F12 atm is just the default keys we are using. 

b7X1nvuodl1rVIdLnCrCfM7ex6yltpFp0ba1eJfVz6txuSCIpH3d5ZAL5iC7Y6NEvxlhkD2xCsMZyjETBkWUHjOQJKTCho2Uj_elV_f4jfCMc.XWE6WmdocFt1NwJj3URANNN0jb4

**Comment by R4Z0R49** [comment]
F12 atm is just the default keys we are using.

https://images-2.discordapp.net/.eJwFwdkNhCAUAMBeKIB3cGozhiBBNyoEnl-b7X1nvuodl1rVIdLnCrCfM7ex6yltpFp0ba1eJfVz6txuSCIpH3d5ZAL5iC7Y6NEvxlhkD2xCsMZyjETBkWUHjOQJKTCho2Uj_elV_f4jfCMc.XWE6WmdocFt1NwJj3URANNN0jb4

**Comment by kooj12** [comment]
Maybe continue on the F-keys road? Since earplugs are on F1

**Comment by ebaydayz** [comment]
Unfortunately the chat list does not appear to be toggleable on the fly, because it is a display with no accessible controls. So it needs to be manually set off screen in its config (like DayZero did) or covered up.

For now streamer mode will just toggle the server logo and rules feed. It will be available in `options > game options` and can be changed in-game or on the main menu before you join any server. It saves to your player profile like all other game settings, so you don't need to enable it again every time you join a server. b22a8af

**Comment by Detoeni** [comment]
says above that wirefence has been removed but the kits are still spawning, or does not mean the buildable ones?

**Comment by R4Z0R49** [comment]
You cant build.
