### ISSUE TITLE
[Suggestion] Open Target Hearbeats

### ISSUE THREAD

**Issue by kooj12** [DayZMod/DayZ#759]
Every day you hear gunshots, encounter players and one may claim they killed in self defense, yet you have no idea what happend. Therefore I'd like if Open Target players got heartbeats for their Open Target duration when aiming at them just as it works right now with Bandits.

**Comment by AndrewEscocia** [comment]
maybe as a server option ? I feel like some would feel its "easy mode" and "taking away split second decision making" .

**Comment by R4Z0R49** [comment]
I'm not sure we should really do this the idea behind the openTarget is as Andrew says making that split second decision.

Closed but feel free to reply if others have thoughts about this topic.
