### ISSUE TITLE
New fuel limitations render helo ops impractical

### ISSUE THREAD

**Issue by erkmacgurk** [DayZMod/DayZ#761]
The new fuel changes are a disaster.  Whatever the default dayz_randomMaxFuelAmount is, its way too low. I have yet to get more than 50 litres out of an fuel source, which mean running a UH-1Y is not viable. In fact, even if the tanks had unlimited fuel, the new animation for each jerrycan means it takes one person approx forty five minutes to fill a huey. Was this intentional?

**Comment by R4Z0R49** [comment]
dayz_randomMaxFuelAmount is set by admins of the server you play on. If you be leave its too low contact your server admin and talk it over them them.

**Comment by erkmacgurk** [comment]
the default is too low at an average of 125 litres. Fix it, don't deflect your errors onto the server admins.

**Comment by erkmacgurk** [comment]
It's time to get rid of you. No one is impressed.

**Comment by kichilron** [comment]
Thank you for your great input.

**Comment by R4Z0R49** [comment]
Our default is a random amount upto the max of 250 for dayz_randomMaxFuelAmount 

https://github.com/DayZMod/DayZ/blob/Development/SQF/Missions/dayz_1337.chernarus/init.sqf#L14
as seen here.
