### ISSUE TITLE
1.8.8 is a very poor release. How about a rollback?  

### ISSUE THREAD

**Issue by erkmacgurk** [DayZMod/DayZ#762]

**Comment by erkmacgurk** [comment]
Its rubbish. It done much harm than good. The refueling changes alone make the bicycle the most desirable artifact in dayz, which is absurd.

**Comment by ghost** [comment]
Having, using and maintaining a chopper in DayZ Mod is kind of an endgame goal and should be a group effort. And providing constructive criticism is a virtue that is not mastered by some people. If you want to move the mod forward, give constructive suggestions. Behaving like a troll will not get you anywhere. Good day, sir.

**Comment by erkmacgurk** [comment]
I am not behaving like a troll, and I resent your cheap shot. I believe you have made a mistake by making fuel so expensive in terms of time and risk. I believe you did it as an error. I would gladly, as a result of your poor design decisions swap my Uh-1H for a bicycle. I ask again, was this your intention, or did you fuck this up?

**Comment by ghost** [comment]
Again. Your hostility will get you nowhere.

**Comment by kichilron** [comment]
We're happy to talk to you about ways you suggest resolving this issue, however complaining in this aggressive manner will not even be taken seriously.

Step back for another hour or two, calm down and come back if you managed to.

**Comment by R4Z0R49** [comment]
You can choose anytime the version you like just select it in steam.
