### ISSUE TITLE
So at risk of being deleted again by the devs, can we discuss the pros and cons of rolling back, given the gameplay issues of 1.8.8?  

### ISSUE THREAD

**Issue by erkmacgurk** [DayZMod/DayZ#763]

**Comment by R4Z0R49** [comment]
I'm pretty sure your comments where just closed not deleted as seen here https://github.com/DayZMod/DayZ/issues?q=is%3Aissue+is%3Aclosed

Anytime you wish to roll back in steam right click dayzmod, select properties, select tab betas, select the version in the list.
