### ISSUE TITLE
My friend in england just skyped me to say it took him 30 minutes grinding to fill his UAZ one quarter full and it ran out of gas in 7 minutes. Admit it, you fucked up.   

### ISSUE THREAD

**Issue by erkmacgurk** [DayZMod/DayZ#764]

**Comment by R4Z0R49** [comment]
User has been removed due to spamming issues. You already have 3 issues in regards to this.

User will be unbanned in one hour and we can retake this up.

You can also carry on this discussion on discord.
https://discord.gg/93dHt
