### ISSUE TITLE
Pellets are green when on floor

### ISSUE THREAD

**Issue by Landbergaren** [DayZMod/DayZ#765]
Plain and simple the pellets have the slugs screen (green) when put or spawned on the ground. When you have them in inventory they look just fine. This have actually managed to trick me and my friends that the pellets have been superrare all through 187 :p. 

http://imgur.com/a/FwPGo

**Comment by R4Z0R49** [comment]
Thanks its been brought up here
https://github.com/DayZMod/DayZ/issues/760
