### ISSUE TITLE
New global update

### ISSUE THREAD

**Issue by WayFaer** [DayZMod/DayZ#768]
Hi, I suggest a global update that it needs? Let's go:
1. Add more buildings where you can go in and find things to take buildings from dayzero, where many buildings did the interior and improve them. This is a great empowerment and diversity in the search.
2. The clothing system as in originsmod, Yes it would be just the perfect variety which will have more functionality.
3. Improve medicine and disease in originsmod, the desired functionality for the theme of survival.
4. Mechanics of repair of originsmod for gathering and transportation, its value will increase significantly.
5. Cars textures to make a more old and rust a little, and a couple of cars to enter would be well under the theme of the course.
6. Increase in cities with paragraph 1.
7. The fog from the braking point of Arma 2, atmospheric piece.
8. Vapor when you breath in cold weather.
9. The limit in weight for the rig.
10. More weapons and better model, unfortunately this model mosinka not very high quality. There is a better model.
11. The opportunity to surrender, with this command, another player can pick up all the things not killed or leaving the faint player, I hope this will give more types of play things for the sake and survival. Need appropriate animations.
12. To return radio messages on green mountain, having the radio at night on the green mountain will be a message that was removed from the game for a very long time, this part of the world of fashion, and the highlight of the intrigue about the beginning of the disaster.
13. If possible with leg injuries to introduce animation to limp.
14. Block for a high range of brightness. Night should be night.
15. The helicopter for it requires special fuel, not regular gasoline. The presence of such airfields, and military bases.
16. Change the mechanics of throwing items and grenades from ACEmod, the native system is awful.
17. Continue to develop the mechanics of modular weapons. I believe such changes are necessary fashion, it will give new life to fashion and will make waiting more pleasant individual games will arouse interest in buying a separate game after game in an updated fashion.

Dear developers, what is this really add to our favorite vanilla mod? Thank you for attention

**Comment by R4Z0R49** [comment]
Now for the ppl who dont play other mods can you explain in detail what they all are.

**Comment by WayFaer** [comment]
Hello, for example, has Dayzero on the map there are many buildings in which you can enter, and worked well inside the design. Also modified existing buildings in terms of additional rooms. I like how some of the mechanics implemented in Originsmade, for example medicine, there can be obtained even poisoning from proper nutrition, the pain is small and strong, to eliminate need either a small dose of pain killer, or a big, two small apply if there is no large packaging. Break the legs and injecting morphine. bones srostayutsya, but only gives the time to walk and run. to treat the bones need to craft a splint. Repair equipment there, too, that is, for every transport need your wheels, your engine. Yes, I understand the game is difficult, but it looks first., secondly the value of technology grows significantly. Another would be to add an overload, and the characters carry a lot of things that it is not possible to carry and run with weight. If it really was to make the extension of the buildings where you can enter, and you can extend the functionality of the clothing as originsmod, it really looks well, very cool headwear. to shoes, things change there. How do you want your fashion to see the guys. So more clothing is different, one is warm, the gloves make safer food consumption and the transfusion of blood mixed with antibiotics gives a chance to safe blood transfusion. without intrusion. And as for the mechanics of the throws items in ACEmod this mechanic better. This mod improves the mechanics of ARMA2 in many aspects. From there would be shots of items to take, and the fact that right now in the native game, it's terrible. The fog of BreakingPoint for ARMA2. he was so atmospheric and creepy. OSU to throw the video link if interested.I hope I clearly described what was meant, sorry if poorly understood, I use a translator, I do not know English. But it was a pleasure to speak on the topic of DAYZ. Tell me if it is possible to do in fashion. I will wait for a response, thank you for your attention.

**Comment by R4Z0R49** [comment]
If you try SA it has most of these features.

I'm going to close this but feel free to reply

Thanks.

**Comment by WayFaer** [comment]
then leave it in my wet dreams) good luck to you guys. and I hope the updates and new features will still in the future. Thank you.
