### ISSUE TITLE
Bloodbag Without Testing Kits

### ISSUE THREAD

**Issue by SecretsUSA** [DayZMod/DayZ#769]
Players blood bagging each other always causes the player receiving the transfusion to get knocked out.

The only way to have this not happen is by using a blood test kit to "find" the players blood type or by using an o- I believe.

**Comment by R4Z0R49** [comment]
Using an o- type should always work other wise you must find out what blood type they require before giving them blood.

We don't have any plans to change this just now.

**Comment by SecretsUSA** [comment]
Why is this a thing then, why even give the players the option if it is just going to knock them out anyways? I know nobody who had an issue with how it was before. Before if your friend was in dire need of blood you could just give them an o+ and be farely safe in doing so, but run the risk of infecting/ knocking them out. Now you will need to find a blood testing kit, which might I add is rarer than the bloodbag itself, to be sure? There is no good reason to keep any other bags on you other than o- in that case. If it Isn't broke, why fix it?

**Comment by R4Z0R49** [comment]
Pretty confused just now our blood bag system has not changed in a long time you have always needed to know the player blood. giving a random blood bag will knock the player out.

Ill look at the drop rate for test kits.

**Comment by SecretsUSA** [comment]
Uhm, I will ask arround, but I am 95% sure that is not how it worked before this update.

**Comment by R4Z0R49** [comment]
Now i'm home just had a quick look there has been 8 changes to that file since Dec 11, 2014,

https://github.com/DayZMod/DayZ/commits/Development/SQF/dayz_code/medical/transfusion.sqf

None of them look major.  But linked above for you to check.

**Comment by KPanicEKS** [comment]
I haven't noticed any chances to the bloodbag system in this update. Still
functions as it did in the last 2 patches minus not needing tkits from 2
versions ago..
