### ISSUE TITLE
Request to use/utilize DayZ 1.7.7.1 code in DayZ Mercury

### ISSUE THREAD

**Issue by Powder5** [DayZMod/DayZ#77]
I would like to get permission to use/edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets for my project called DayZ Mercury
I understand and agree that all other pbos are forbidden due to license issues and tools used to create I must seek BIS/Deans permission to edit any other pbo. Also I understand and agree that I have to include all DayZ Credits and recreate a new issue post every 3 month requesting to continue editing the main 5 pbos.
Thank You

**Comment by Skaronator** [comment]
alright thanks
