### ISSUE TITLE
New Spawn Points?

### ISSUE THREAD

**Issue by EOldOne** [DayZMod/DayZ#770]
DayZ is a fun game with many exciting aspects. 

Players have a variety of cities they can begin playing in.

Although, some servers prefer having to disable spawn selection to make the game more realistic and a bit harder. 

I would like to suggest an in-between to be added. A spawn selection with 3 choices: South, East, Random. 

This way the players can select on what side of the map they want to play without overpopulating a specific city.

It shouldn't be enabled by default, but it should give the server owners a choice in the middle.

Let me know what you guys think.

**Comment by R4Z0R49** [comment]
We dont have any plans to change this just now.

Thanks.
