### ISSUE TITLE
More survival

### ISSUE THREAD

**Issue by WayFaer** [DayZMod/DayZ#772]
Hello, how do you look at improvement in survival mod? 
1. To remove treatment bone morphine, and to make their treatment bus. 
2. Morphine let gives time to make the hero able to walk. 
3. Add to the overload of equipment. players have to think what is more important for them to take for survival. 
4. So it would be more realistic. if filling techniques air was only possible at the airports and military facilities(use airplane fuel, not gasoline). 
5. Another would be to introduce the analogue of vodka as a pain killer. but with the effect of intoxication at the time. 
6. Another zombie that was a little more resistant to weapon damage. 
7. Vapor in the exhalation in cold weather or rain. 
8. Production of meat macheti or axe, but at least a limited number of 60% less pieces of meat. 
9. Minimum ocalenie thirst from the rain. 
10. Managed parshat when landing from height. 
11. To fix the problem with the shots of the subjects in the supine position, the character gets up after the animation of the throw, and then throws the subject standing upright. 
12. Damage from fire, if possible, and then standing in the fire or from burning technique with no damage, that is not correct. 
13. Please radio program on the green mountain, a very atmospheric piece. 
14. To make the crafting of the barrels of water that you can fill up for camp, or after rains so it's a bit filled. 
15. Would improve the texture of the Mosin rifle, and optics to it. 
16. To make broken glass for hospitals, for occurred the fall of the world, and the glass intact. 
17. Mist, I understand that it's not so important, but if you make such a fog, that atmosphere of a night time will be much higher. The fog is a link to YouTube at the end of the list.
https://www.youtube.com/watch?v=HbZgmPfRRr4 
Thank you for your attention and hope you something from the list like you want to implement in the future. This will give the fashion of the new colors in survival, some of the points made by the admins on some servers. And it really adds atmosphere DayZ in the world. Thanks again. really looking forward to your commentaries. I love knowing what you think about it.

**Comment by R4Z0R49** [comment]
is there any difference from this topic to the one we closed ? #768

You could have just carried on the topic in the closed thread.

**Comment by WayFaer** [comment]
Sorry to tired. but in this list I mean about expanding fashion, and in the past taking the basics of the other mods.
