### ISSUE TITLE
Clan Bases

### ISSUE THREAD

**Issue by EOldOne** [DayZMod/DayZ#775]
Ever since the 1.8.8. patch people are building massive bases to protect their gear. Although it's hard to rely on only one person to be online in order to build the base. Since the patch, you cannot build a wall next to another wall you don't own. This forces the people that play in groups and build bases, to wait for a specific member of their group to login in order to continue placing new walls. 

I believe it would be a nice addition to allow every person with the same squad xml to be able to place their walls next to other walls placed by their squad members. If a person gets kicked from the squad, then their old walls stay, but they are no allowed to build near their old teammate's walls.

Let me know what you think, any input is appreciated.

**Comment by R4Z0R49** [comment]
once we have the base system fully complete ill extend out to allow others.
