### ISSUE TITLE
DayZ icons copyright

### ISSUE THREAD

**Issue by Codingboy** [DayZMod/DayZ#78]
Hello,

I am currently developing a framework for ArmA 3 that makes it possible for everyone (even those who are not familiar with the missioneditor or scripting) to create missions in the style of the Hunger Games. My framework has absolutly nothing to do with DayZ. But I would like to use the icons from DayZ for food/water/health/temperature.
I would prefer not to credit everyone from the complete dayz creditlist. I would prefer only crediting the designer of the icons but I would credit all if I have to...

I hope to get the right to use the icons!!!

Best regards,
Daniel Tkocz

Links:
http://en.wikipedia.org/wiki/The_Hunger_Games#Plot
https://github.com/Codingboy/HGFramework

**Comment by Codingboy** [comment]
If you have problems contacting the designer to ask him for the copyright I would change my request as follows.
I would like to know who the author of the icons is.
I would like to get a usageright on the whole dayz project.
I will credit all people whos content I use.
I delete the whole content except the icons.
The result would be I can use the icons and therefore credit the designer.

**Comment by R4Z0R49** [comment]
Sorry it takes a while to track everyone down. If the icons are being used in only the Arma games i don't see any issue with you using them just make sure you provide all credits.

**Comment by Codingboy** [comment]
That sounds nice! I really have to copy all the credits or do you mean it takes time to check who edited the icons and I shall credit all of them?

**Comment by Codingboy** [comment]
Ok, now I credited all. Surely it is only for use in arma.
