### ISSUE TITLE
Duplicate Stashes in the Db

### ISSUE THREAD

**Issue by skigoggles** [DayZMod/DayZ#785]
Infrequently, you get stashes in the same exact location(WS). One will be an older (smaller) and one will be a newer (larger) stash. The contents of the older one seems to depend on when the issue occurred. Could be from the first upgrade, then its empty. Could be on the 3rd, then you see 2 stashes with the same items.

Other admins have confirmed this. I'm guessing since there isn't a "classname update" in the hive, the stash is being recreated and deleted and maybe there is a timeout. 

script to show it - I recently cleaned them up, but I just got some more.
`select * from object_data where worldspace in (
    select worldspace from (
        select worldspace, count(*) as cc from object_data  group by worldspace
    ) as tmp1 
    where cc >1 
);`

**Comment by Inurosen** [comment]
Confirmed

**Comment by cikez** [comment]
Confirmed as well.

**Comment by R4Z0R49** [comment]
nothing is jumping out in the scripts. 

Get the id of the dupe object and see if you can see any log in your server.rpt 

DELETE: Deleted by ID:
DELETE: Deleted by UID:
