### ISSUE TITLE
Request to use DayZ 1.7.7.1 content and code in DayZ Despair

### ISSUE THREAD

**Issue by AlexAFlorov** [DayZMod/DayZ#80]
Requesting for permission to utilize the 1771(and beyond) code in a new mod called DayZ Despair. We will post all credits and only edit the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx, dayz_comunityassets.

**Comment by Skaronator** [comment]
Here is our [complete Permission Request](https://github.com/DayZMod/DayZ/wiki/License-and-permission-to-use).
If you fine with the this info just reply or if you have any other questions regarding the license plz reply.

**Comment by AlexAFlorov** [comment]
Yes, i'm fine with this info.  Ty.

**Comment by Skaronator** [comment]
Alright

**Comment by AlexAFlorov** [comment]
request to update permission
