### ISSUE TITLE
Give the British Assault Pack a purpose.

### ISSUE THREAD

**Issue by Borges80** [DayZMod/DayZ#809]
The military British assault pack currently has the same slot value as the residential alice pack. Both give 18. Give the BAP +2 slots? There is currently no 20 slot bag.

**Comment by bchawke** [comment]
Agreed.  It's been talked to death on Discord, but IMO these three things would greatly improve backpacks overall:

1. Reduce Alice spawns and/or make people travel farther for them (QuickZ and Skigoggles are working on an idea to achieve this I believe)
2. Buff British to 20 slots
3. Reduce British spawn rate, make them really rare (but slightly less rare than Coyote/Czech)

This would add balance *and* give the British pack a purpose in the game.  It should be a coveted backpack.

**Comment by Borges1091** [comment]
Well said. I don't think BAF spawn rate should be reduced as it's still pretty rare. I hardly ever find them at military spawns. Alice should be reduced.

**Comment by skigoggles** [comment]
Our thought was to document each pack, each size and spawns locations/chance and look to see if there was a some balance to be added.

**Comment by devguy91** [comment]
Czech and Coyote also have the same slots right? I think one of them should be buffed for the same reasons.

**Comment by AndrewEscocia** [comment]
I don't understand why this is still going round and round, its painfully obvious that the Alice pack spawns to often in to many places and the Brit pack is only good as a skin change. 
The issue has been brought up many times so the is clearly something people are picking up on and the is an appetite for change. 
The solution BC suggested would fit the bill perfectly and would be an easy fix, no 3d art work needed only value changes in the data base.  
The Czech and Coyote spawn in the same buildings at the same rates, if the same was true for the Alice and Brit then the would not be the same need for change.

**Comment by Borges80** [comment]
@blackflarez No because 24 is max slot for packs to keep balance. Alice spawns at residential fairly commonly and british assault pack spawns only at military spawns quite uncommonly, with the same item capacity.

The Czech and Coyote spawn at the same locations and same % chance, so making one 22 slots for example wouldn't make sense. However one has more weapon slots than the other so it functions differently. This is true with BAP and Alice regarding weapon slots but the BAP is technically a step up from the alice and should be treated as such. If I currently have an alice pack and find a BAP I just take it cause I think it looks cooler. I don't feel rewarded anyway and I think adding +2 slots would definitely fix that.

**Comment by rvett** [comment]
I also think it's a good idea to give the BAP 20 slots.

**Comment by R4Z0R49** [comment]
we have a pull request soon ill look over it once i get a sec.
