### ISSUE TITLE
Permission Grant

### ISSUE THREAD

**Issue by ghost** [DayZMod/DayZ#81]
Spoke with Carl quite sometime ago about 2017 using community content around the time SA was starting out. We put in a ticket to make it official too, but this was on the old public repository.

Having said that DayZ 2017 is no more, and is a separate mod now with its own content and code. So it might not be so important.

Regards,

shin

**Comment by R4Z0R49** [comment]
Hi skinkicker, 

Drop me a line on Skype i'm not 100% sure what you asking but DayZ 2017's group have always had permission.
