### ISSUE TITLE
server_function.sqf / fa_coor2str is hardcoded to chernarus

### ISSUE THREAD

**Issue by skigoggles** [DayZMod/DayZ#812]
I believe this is just used for logoff/death msgs
_res = format["%1 [%2:%3]", _town, round((_pos select 0)/100), round((15360-(_pos select 1))/100)];

The 15630 is the chernarus map offset.

I found a reference that suggested these were the offsets for other maps, Napf looks correct but need to verify.
Taviana=25600
Panthera=10240
Namalsk=12798
Lingor=0
Napf=20479

Might be best to move this to the mission file as well since it is map specific.

**Comment by ebayShopper** [comment]
Updated.

Also the check @facoptere added in sched_playersHiveSync uses the same, but is mostly pointless. All it does is check if a player is within 2km of this position: `[10500,-5460,0]` and kills them if they are. I see no benefit to a cheater teleporting there. Also playerSync has already been changed to not save players who are off map:
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_server/compile/server_playerSync.sqf#L144

I removed that check, but please leave a comment if there is some good reason for it I'm missing @facoptere.

**Comment by R4Z0R49** [comment]
If i'm not mistaken we don't use Sched_playersHiveSync

**Comment by skigoggles** [comment]
I think it is used. I was caught up on this on NAPF. I was having trouble placing the respawn(debug) coords and players swimming so I stuck it on a random little island. That islands coords just happened to be near those absolute coords.[10500,-5460,0]. western part of napf and then the player wouldn't save to the db

**Comment by skigoggles** [comment]
and then the play stopped updating position.

**Comment by R4Z0R49** [comment]
https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_server/system/scheduler/sched_init.sqf

Line 6 and 14 are both commented out. I'll check a bit later but i'm sure its disabled.

**Comment by skigoggles** [comment]
you are correct. I should have taken better notes when I debugged, but I know it was something of this nature - absolute coords for cherno against napf. No big deal, we'll find it again
