### ISSUE TITLE
[Request] Start fire with wooden planks, not logs

### ISSUE THREAD

**Issue by rvett** [DayZMod/DayZ#814]
It's a bit unlogical that one can start a fire with a log, but not with a wooden plank. It should be the other way round.

**Comment by R4Z0R49** [comment]
its more of a limit atm we dont have an ether or system in place yet.

**Comment by rvett** [comment]
I'm afraid I don't understand what you wrote. According to player_makefire.sql, players can start a fire with either a wood pile or a log. What I'm suggesting is to change this into wood pile or wooden plank, i.e., replace the ItemLog with ItemPlank.

**Comment by oiad** [comment]
@romanongit Why not all 3? Anything wood in theory should be able to start a fire "in real life"

**Comment by rvett** [comment]
Because you're gonna have a very hard time lighting up a whole log just by holding a burning match under it. "In real life" you always need some kind of smaller, thinner piece of wood to start a fire. Logs take forever to actually catch fire.

**Comment by R4Z0R49** [comment]
Yea sorry i miss read. We could just fully change it over but i think id rather wait and redo the system to allow more types of stuff to create the fire. (pending Models) Atm the model for the fireplace is logs seems kind of silly to convert logs to planks to start a fire to see model of the fire with logs.

At least leaving as it is your imagination can fill in the blanks (you used parts of the bark to start the fire but the log was split down to create the surrounding).

Just my thoughts really.
