### ISSUE TITLE
1.8.8 disappearing items

### ISSUE THREAD

**Issue by MarcT** [DayZMod/DayZ#818]
Items and weapon mods occasionally disappear from inventory after logout. Items in backpacks or stashes/tents are fine.
I was playing on a server the other day and picked up a flashlight mod for a G17, applied it to it. I also picked up a hose in to my inventory. I then picked up some food and magazines and put them in to my pack and 20 mins later logged out. When I logged in later the flashlight was no longer on my pistol, and the hose was gone, but the items in my pack were still there.
Similar thing happened again today, same server, I had an AK in my stash that I had been keeping there and modding when I found parts. I had 4 SD mags for it and 8 regular but was running around with an M16A4. I randomly found a silencer for it, so I went back to my stash swapped weapons and added the silencer. I also took the 4 SD mags and decided it was time to go in to town and look for medicine and I needed more matches.. But then I got a work call and had to log.. when I logged back in 20 mins later the silencer was missing and all the mags lost the SD identifier.
Really not sure why the last part happened, but I went back to my stash and I had no more SD mags for it.

**Comment by Inurosen** [comment]
Contact your server admin and try to resolve your issue with him.

**Comment by skigoggles** [comment]
this sounds more like server lag and the db being too busy to save the latest character  updates.

**Comment by R4Z0R49** [comment]
We are aware of some issues with items disappearing.

thanks
