### ISSUE TITLE
TrapTripwireSmoke & TrapTripwireGrenade don't disappear after they've been triggered

### ISSUE THREAD

**Issue by skigoggles** [DayZMod/DayZ#819]
If I follow the code correctly, it looks like dayz_code\Configs\CfgVehicles\Traps.hpp contains the class definition which has a "singleuse" element. It looks like this is correctly set to 0 (false) for bear traps and cans, but should be 1 for grenades and smoke, which could also cause it to be removed.

need to test

**Comment by Borges1091** [comment]
I don't think changes should be made. Too many random zombies trigger traps.
