### ISSUE TITLE
No humanity after killing survivors/heroes

### ISSUE THREAD

**Issue by bchawke** [DayZMod/DayZ#820]
I've been hearing from players on US 434 that if you die after killing heroes/survivors you do not end up losing the humanity for killing them.  They also mentioned that if you log out shortly after a kill you will not lose the humanity.  Additionally, a *lot* of players have been reporting not losing humanity when killing survivors/heroes while in fights with them and assumed that the open season code meant that you can kill anyone who has shot near you rather than someone who has wounded/killed a survivor/hero.  434 has been overrun with people in hero skins that kill survivors and heroes on a regular basis.  We were assuming that they were all spamming each other with blood transfusions to regain humanity (434 even made a rule to stop people from doing it), but it seems that more often than not players are simply not losing humanity when they should.

**Comment by R4Z0R49** [comment]
We already know about this issue its listed on the problems.
