### ISSUE TITLE
Fix for Topolka Dam glitch

### ISSUE THREAD

**Issue by Bruce-LXXVI** [DayZMod/DayZ#826]
Hi

On my server I found that some players are storing a lot of stuff unser water at the topolka dam north of Elektro.  
![image](https://cloud.githubusercontent.com/assets/12216842/22617844/c3e6a54a-eace-11e6-9b3f-320b63468c84.png)

One possible quick fix is to just put a "MAP_pond_big_01" at the same position as the water level.

```
createVehicle ["MAP_pond_big_01", [10299.095, 3659.8674, 2.4993041], [], 0, "CAN_COLLIDE"];
```

**Comment by ebayShopper** [comment]
Yup, it works. Nice find.

Added 8e8662f.

**Comment by ebayShopper** [comment]
allows air swim glitch via vault on back side of dam
