### ISSUE TITLE
Official Hive. Past, present and future

### ISSUE THREAD

**Issue by Ameo-Koradi** [DayZMod/DayZ#83]
Hello guys,

I made this thread because I would like to discuss with you about the Official Hive.
I already spoke with Faco about this subject, and I think we are both of us ok with that: something have to be done.

The Hive is no more maintained, still there, but not maintained. this situation brings to us some problems.

We've all experienced the time-out problems recently, and it took weeks to be resolved, not because it was a big problem, because nobody was in charge anymore.
We had to multi-post on the official forums, and finally Razor helped us.

Now Ander is out, so, who's next ?

Another problem is the white-lists / blacklists of official servers.

I understand you don't allow any more servers on it but, for example, if you rent a server and the hoster change your IP address, you're doomed (happened to us with the LU511 (RIP)).
Non-Legit servers. We all know that some servers don't respect the rules, for many reasons: white-listed, no PVP, allow hackers to generate stuff etc...

There are more hackers/scripters, more work to do than private servers, but for many admins and players, this is the only way to play DayZ.
We'll stay and fight for the Official Hive.

Can nothing be done, once and for all ?

To end, I'd like to thank the whole devs team, for their hard works to provide us one of the best surviving game.

Ameo

**Comment by R4Z0R49** [comment]
We are trying we just don't have any real pulling power on the hive. I think i'm the only one who stills does any maintenance on the hive and i only have SQL access nothing more.

Ill speak with Dean after the 16th and see what we can get sorted out if anything.

**Comment by Ameo-Koradi** [comment]
This is a great news, many things can be done.
Thank you.
