### ISSUE TITLE
Regarding walls and gates degrading

### ISSUE THREAD

**Issue by VeteranPioneer** [DayZMod/DayZ#830]
Hey everyone, **(small thanking prologue following)** 
Even though i have been playing this amazing mod for years, i have never ever been on github as a member and i have never thanked the creator and his team for their overally amazing work , so thank you for putting time into making this mod so fun-to-play. @R4Z0R49 

**On to the main reason i made a github account.** 
 I like base-building. I like working hard on something and watching it grow over time. And i like enjoying the fruit of my labor (the base itself). Due to something that happened the last 8 days i was unable to play at all therefore the base started degrading. All of it. When was this introduced ? Is it a new feature ? The admin of my server informed me that it's probably a feature that existed since _ 1.8.6.1_ but it might also be in the admin's power to turn that feature off. **The following rant assumes that the admin does not have the ability to turn the degrade feature off :**  
 I had a base 4 times its size for months on the previous patch when bases were active and no degrading happened whatsoever. The problem with degrading occurs when you (or i and a few other veteran players in the server in this case) have a really big base in terms of layers and complicated layout which we will have to maintain. Putting aside the fact that it requires nails and planks to maintain the walls and gates, how do you expect me to maintain a base with 100 or more walls (which once again i made on my own unaware of the degrading feature) and coming back to it roughly a week later and finding some of my walls and gates trickling down the level scale ? 
 It's unacceptable for walls and  gates to degrade after just 1 week. For once, i am an adult and i have responsibilities and work , studies as well as a family (as i m sure you do too) and i cannot spend my time maintaining every last piece of walls and gates during my limited play-sessions. I just don't have the time and the will to keep maintaining it after building so much of it on my own. W
 You wish to have a degrade feature for structures in order to help the performance and the load of the server ? That's amazing and i'm with you , but 1 week ( and subsequently 3 days for each level from what i m told by the admin) is too little time. That's the core of my issue. The degrading process starts too fast. Make it a couple months or at least 1 month. But 1 week is just **not enough**
As a second question: 
**Could an admin thoroughly fill me in regarding the whole degrading-of-walls-and-gates issue ? I'd love to hear it from a trusted source**

Thank you for taking the time to read my post , have a great day!

**Comment by R4Z0R49** [comment]
Degrade starts 7 days after you last updated your wall segment then every 3 days after the segment will downgrade by one level.

These levels can be updated by server admins as well as fully disabling the system. Granted its not as easy to do just yet but it is possible with a small amount of SQL knowledge. Now the one item everyone seems to miss is you don't have to be the owner to maintain a wall segment anyone can do it. You only have to be an owner to unlock the buildlock status and too pull down the wall.

Our fence system is very much WIP and will keep changing overtime to bring it inline with our/community views.

Thanks and welcome :-)

**Comment by skigoggles** [comment]
I've been part of this conversation before and I feel the need to add a few points.  Basebuilding was in 186 and now back in 188.  Bases(small or large) aren't supposed to be easy and if you can spend time creating them, then you can spend time maintaining them.  

Think of the flip side - you are a casual player but you can't find a vehicle, especially not a heli, because the couple of clans on the server built a large, multi-ringed base and now it can sit there for a month without being touched.

The balance is good right now.
