### ISSUE TITLE
Vehicle-repair not getting saved properly 

### ISSUE THREAD

**Issue by Landbergaren** [DayZMod/DayZ#831]
Repaired parts of a vehicle will revert back to not being repaired at next restart of the server. It will only save and get stored to next restart if a player jumps in to the vehicle before the restart hits.

**Comment by skigoggles** [comment]
finally tested this. tried with 2 vehicles, set to be pristine, no damage, server restarted.

* hitpoints = [["glass1",0],["glass2",0],["glass3",0],["glass4",0],["wheel_1_1_steering",0],["wheel_1_2_steering",0],["wheel_2_1_steering",0],["wheel_2_2_steering",0],["fueltank",0],["engine",0],["sklo predni P",0],["sklo predni L",0],["karoserie",0],["wheel_1_4_steering",0],["wheel_2_4_steering",0],["wheel_1_3_steering",0],["wheel_2_3_steering",0]]

destroyed a wheel with a hatchet, no damage recorded in db
ran around, waited a few minutes, no damage recorded in db

entered the vehicle
["wheel_1_1_steering",1]

This function looks like it should do it "sched_vehicleshivewrite", but I can't seem to find where its called.

**Comment by oiad** [comment]
@skigoggles https://github.com/DayZMod/DayZ/blob/Development/SQF/dayz_server/system/scheduler/sched_init.sqf is where the sched_vehicleshivewrite is called from but it's commented out so it's not running

**Comment by R4Z0R49** [comment]
We don't use that system at all.

But soon as i get chance ill have someone take a look if im not mistaken im sure i looked at this when you brought it up on discord and im sure there is a mistake in the script.

**Comment by ebayShopper** [comment]
92ab8fe
