### ISSUE TITLE
pCleanupOOB only checks for WEST and NORTH boundaries

### ISSUE THREAD

**Issue by skigoggles** [DayZMod/DayZ#835]
Is there an island to the south? I forget. Either way, there is plenty of ocean for players to move boats into the middle of noplace to never be found.

I will submit the SQL change, just wanted to have an issue to match.

**Comment by Brockerino** [comment]
There is an Island a couple of kilometers to the south east of the map, I think the kids these days are calling it debug island.

**Comment by skigoggles** [comment]
I thought so and on another server someone flew all the aircraft there. It's just too much playing to prevent others from playing.
