### ISSUE TITLE
Suggestion: Camouflage Net maintenance.

### ISSUE THREAD

**Issue by Brockerino** [DayZMod/DayZ#838]
It's come to my attention that camo nets have become a integral part of base building/planning, acting as a 
a substitute for the lack of player made roofing. It limits players vision into the base , but more importantly stops people from dropping into the base via helicopter.

My suggestion is to allow players to maintain their camo nets with either small camo netting (to fix the canopy itself) or two inch metal pipes and string/two inch metal pipes (to repair the support posts) or a combination of both.

By having these items a requirement to maintain the camo nets it forces people to loot industrial areas for the required materials, as well as military areas and crash sites for the small camo netting, while also addressing everyone's biggest concern.....griefers/trolls by requiring some effort to keep the netting up.

**Comment by skigoggles** [comment]
I'm confused as to what problem is being solved?  Why shouldn't a camo net act somewhat like a roof?  Having to find a small camo net at a heli crash to maintain a camo net is far too much work - all of the other materials are common(nails, wood,stone).

Can you explain "everyone's biggest concern.....griefers/trolls"?  Is this related to the fact that you have to drive over a net to get it down?

**Comment by ebayShopper** [comment]
I agree with skigoggles. Maintenance on simple things like tents and camonets seems like needless complexity.
