### ISSUE TITLE
Suggestion: Backpack type differentiation

### ISSUE THREAD

**Issue by sqlfoxhound** [DayZMod/DayZ#839]
Back in December/January there was a big debate regarding backpacks as a whole plus BP and ALICE being the same in function. As my position was more of a "lets make backpacks different based on function and not just slots", I made a simple visual suggestion in a form of a high-tech mspaint file, never got to post it. 

Since things tend to stay afloat here better than they do in Discord, Ill post it here instead.

http://imgur.com/a/DCRWJ

Red area notes 10slots used/usable for primary weapons. Backpacks with no red areas mean they can only store 1 slot items and no weapons. Czech and Coyote backpacks were puzzling in the sense that they were very different in design/looks which already differentiated them, in my opinion, by function.

**Comment by AsFoxy** [comment]
Seems unintuitive and with the way inventory management works in A2 i could see this resulting in a lot of frustration.
