### ISSUE TITLE
1.8.9-731b957(191) Issues.

### ISSUE THREAD

**Issue by R4Z0R49** [DayZMod/DayZ#846]
Any issues found with build 189 plz post here.

**Comment by skigoggles** [comment]
pcleanupOOB() change for NSEW OOB check is syntactically wrong. Can use 188 version. Will checkin fix.

**Comment by skigoggles** [comment]
* floating loot over cranes

**Comment by skigoggles** [comment]
* trying to upgrade a wall from lvl 4 to lvl 5 - "missing screws to upgrade". Not sure if that is correct

**Comment by skigoggles** [comment]
* load uncon player into vehicle. works, but then immediately ejected.

**Comment by skigoggles** [comment]
* shot player with tranq - double msg

**Comment by skigoggles** [comment]
* panalak needs to block glitching int wall - 63,216 / 127,52 / 128, 52 /

**Comment by skigoggles** [comment]
* NWAF poi barrels on top of tanks 039,042

**Comment by vinyljunkie** [comment]
Crossbow is missing sound for reloading.

**Comment by Landbergaren** [comment]
Alive duration in journal adds 1 hour and 30 minutes on logout.. Instantly. So if you log out and back in again you will get 90 extra minutes.

**Comment by R4Z0R49** [comment]
Another issue with alive timer, Escalated https://github.com/DayZMod/DayZ/issues/849

**Comment by vinyljunkie** [comment]
Box of screws cant be split and there is also a typo in the inventory action; "spilt" instead of split.
![20170507131515_1](https://cloud.githubusercontent.com/assets/8300577/25780908/cfc6d51a-3330-11e7-99a7-d55124b78804.jpg)

**Comment by vinyljunkie** [comment]
Dropped broken hatchet has the look of a generic Ammo pouch on the ground.
![20170611165329_1](https://user-images.githubusercontent.com/8300577/27011934-dff074e4-4ec6-11e7-8e56-59bb0e6ff912.jpg)

**Comment by R4Z0R49** [comment]
Yea we need to sort out a model for that
