### ISSUE TITLE
LootTable Zero Divisor

### ISSUE THREAD

**Issue by Kazyyk** [DayZMod/DayZ#86]
When running the server, I'm encountering this error.

Error in expression <find _iClass;
_weights = dayz_CLChances select _index;
_cntWeights = count _weig>
18:49:01   Error position: <select _index;
_cntWeights = count _weig>
18:49:01   Error Zero divisor
18:49:01 File z\addons\dayz_code\compile\spawn_loot.sqf, line 31

Any ideas?

**Comment by R4Z0R49** [comment]
Looks like an error in the loot table. The weights must have an error some place.

**Comment by Kazyyk** [comment]
Right - but the thing is I didn't modify the loot table. That's straight from @DayZ

**Comment by R4Z0R49** [comment]
Ok np might just be an error on our side.

**Comment by Kazyyk** [comment]
Well - other servers are apparently online. Unsure what's going on with mine. Thoughts? If there's a fix, I could move the files to the mission folder.

**Comment by R4Z0R49** [comment]
oh you getting that every server start up?

**Comment by Kazyyk** [comment]
Yeah - it's halting server authentication. I've tried re-DLing the files to no avail.

**Comment by R4Z0R49** [comment]
Can you send over your server log

**Comment by Kazyyk** [comment]
It's 200,000+ lines of the above error, so I'll just send you everything from before that error if that's okay? Or do you want the full log anyway?

**Comment by Kazyyk** [comment]
Here's the partial. I can give you the full if you want.

http://pastebin.com/vbJkWk0K

**Comment by R4Z0R49** [comment]
I'm not sure its not a default hive from the looks of it.

18:49:01 "CRASHSPAWNER: Spawning 'Crashed UH-1Y' with loot table 'HeliCrashWEST' at Vybor [43:65]"

im guessing the error is in here but don't ask where the hive isn't an official one so i cant really help

**Comment by Kazyyk** [comment]
That's not a default setting? Ohh... Oh! Wait, is the issue with the faction? HeliCrashWest? or the crash itself? I did enable random wrecks on the Reality setting just because. Is that incompatible?

**Comment by Kazyyk** [comment]
I wasn't aware that that wasn't standard behavior. Thank you for your help, regardless.

**Comment by R4Z0R49** [comment]
Np ill speak with visad tomorrow he might be able to shed some light on this.

**Comment by thevisad** [comment]
After looking over your log file and such, it appears that this is coming from dayz_code itself. The item is erroring out on the item below in the spawn_loof.sqf file. Reality does not touch these files as it is only a server side aspect. Are you changing anything and have you verified you updated everything properly? 

_index = dayz_CLBase find _iClass;

**Comment by Kazyyk** [comment]
I resolved the issue by re-transplanting the Mission file. I can only assume then that during my first fusion of my old Mission file with the new one, I messed up somehow. This issue is no longer present.

Thank you for all your assistance.

Reccomended solution for future encounters: Re-application of Fresh Mission file.

**Comment by R4Z0R49** [comment]
Ill get the creator to check the site over again i've seen a few random bugs.
