### ISSUE TITLE
1.9.0 Changes

### ISSUE THREAD

**Issue by R4Z0R49** [DayZMod/DayZ#867]
New, DayZero enterable buildings provided by Tansien and Zac https://zombies.nu/
New, Land_houseV_2T2 is now enterable. Interior modeled by @Streatman
New, Added loot positions for new enterable buildings
New, Added L115 (.338 Lapua Magnum) sniper
New, Added L85 attachments totaling 24 variants, new models by @Streatman 
New, SVD scope attachments can now be removed, new models by @Streatman 
New, Added basic server-side authentication to hive object creation/deletion for improved security
New, Added option to toggle status icons in "Game Options" menu and via F3 hotkey

Fixed, Stashes no longer need etool to upgrade they now use shovel.
Fixed, Wall maintenance mode again ;-)
Fixed, Removed floating flame for missing Cherno docks fire barrel
Fixed, Character sometimes duping when morphing skins during combat (after a humanity change).
Fixed, Public variable value kick when exiting a vehicle near a base object.
Fixed, Updates to humanity and player stats after a skin change not always saving in hive (server_getDiff)
Fixed, Blocked another A2OA script execution bug from improperly cleared eventhandlers
Fixed, Missing shadows on some _DZ weapons. Thanks @Streatman 
Fixed, Loot not spawning at Gvozdno POI barracks
Fixed, Reverted a change to damage handling that was causing legs to break twice as often.
Fixed, Zombies should no longer get stuck at the position where a player entered a vehicle.
Fixed, Fresh spawns running on login if they died while running
Fixed, Death camera height incorrect when player dies above terrain level

Updated, Added Priority to building actions, Should keep disassembly on the bottom of the action list.
Updated, Chance system for BreakinIn, ChopWood, mineStone to run only once rather than each loop
Updated, Increased the coverage angle of headlights on land vehicles and added a headlight to the bicycle
Updated, The huey searchlight and gunner seat now have improved visibility in first person view.
Updated, AH6, removed camera and computer, added search light and fixed animation source turret errors
Updated, Stashes have new lods to reduce the visibility at range.
Updated, Lowered build requirements for level 4-6 walls (1 screw in place of 2)
Updated, Military and MilitarySpecial loot
Updated, MilitarySpecial to spawn L115 0.1 chance
Updated, EU Crashsite to spawn L115 0.5 chance
Updated, EU2 AmmoBox to spawn L115 ammo
Updated, ItemScrews chances (Updated, Construction chance to 4 from 1.5, Updated, Industrial chance to 3 from 1.5,Added, Supermarket chance 3).
Updated, Zombies should run more direct to players now.
Updated, Added prevention for a dupe involving disconnect and change clothes
Updated, Reverted PVDZ_sec_atp logs to human readable form for server admins
Updated, Player is no longer set in combat for throwing a flare or chemlight

Removed, Server control panel, because it is abused by players and not currently used by admins
Removed, Tent Ghost objects for better placement during hiding.
Removed, PoliceCar due to model errors

Known issues:
- Ladder directions are wrong in Land_Mil_House
- ATC and hospital have lights on top and on the soda machines

TODO:
- [ ] show hits to vehicles in rpt.
- [x] Repair not saving to db.
- [x] humanity change issue causing clones.
- [x] Add break in Log back
- [x] C4 changes removed from crashsite, lowered in barracks.

**Comment by Rohanbad** [comment]
Bro, but why does the etool no longer work for building stashes? Seems legit that it should still do the same job?

**Comment by skigoggles** [comment]
its all about the shovel

**Comment by KPanicEKS** [comment]
makes no sense...

**Comment by Rohanbad** [comment]
..finally found a shovel. Etool can be stashed.

**Comment by rvett** [comment]
Missing on the todo list: floating loot (see #865)

**Comment by WayFaer** [comment]
Guys, how to get to the test server?

**Comment by offc001** [comment]
Just a couple of thoughts.... maybe a little random, My wife keeps asking why there are no hero skins for female players. 
Also the new 'enterable' buildings, are these going to be the ones that popped up in a Cherno retextured mod a couple of years back ? ie hospital, factories etc ? If so the textures were fantastic, blood spatters in shops etc...
Looking forward to the new developments

**Comment by R4Z0R49** [comment]
We really dont have anyone willing to do female skins. No idea on the enterable buildings i dont really play other mods.

**Comment by offc001** [comment]
Could you import suitable female skins from someone elses mod with their permission ? if not no worries - keep up the good work.

**Comment by R4Z0R49** [comment]
we could yes long as they contain backpack proxys.

**Comment by Streatman** [comment]
~~i added shadows for the silencer to weapons that didnt have it~~ -- Added to OP --ebayShopper
