### ISSUE TITLE
Request to use DayZ 1.7.7.1 content and code in DayZ Battle Royale

### ISSUE THREAD

**Issue by lazyink** [DayZMod/DayZ#87]
I would like permission to use the DayZ mod code in a new mod DayZ Battle Royale.

I will include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future releases I make.

I fully understand the limitations of editing only the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx & dayz_comunityassets.

I will seek BIS/Deans permission to edit any other pbo.

**Comment by AlbyBDPK** [comment]
Accepted, thank you.
