### ISSUE TITLE
[Request] Option to hide visibility/audibility HUD elements

### ISSUE THREAD

**Issue by rvett** [DayZMod/DayZ#876]
I think it would be neat to have an option to hide the visibility and audibility HUD elements. I never use them. Ever. It could be a video option like streamer mode, which I have always enabled. I like a minimal HUD for maximum immersion.

![visibility_audibility](https://user-images.githubusercontent.com/6949874/27997269-2731c10c-64f5-11e7-8334-6b49daa54dcb.jpg)

**Comment by AndrewEscocia** [comment]
I loved them at first but i agree that for the more experienced players they are pretty pointless.

**Comment by ebayShopper** [comment]
44bb49e

**Comment by rvett** [comment]
Thank you ebayShopper, I appreciate your work.

**Comment by rvett** [comment]
After playing 1.9.0 for the first time today, I realized that the new option removes also all other status icons (temperature, blood, hunger, thirst). I was intending to have the option to hide only the visibility and audibility icons, as shown in my original post. With everything removed, unfortunately this feature is useless for me... @ebayShopper
