### ISSUE TITLE
Proposals for changes

### ISSUE THREAD

**Issue by B73** [DayZMod/DayZ#894]
Could do some changes

Have seen alot considering been playing mod since 2012. Some major changes I'd suggest to vanilla:

1 - Choppers replaced by civilian airplanes
Will resolve many "problems", such as bases without roofs. Servers (or mod itself) could implement rule that building base(s) to block any kind of item spawn is denied. Now people make bases to barns etc. buildings you can enter because they need a roof to keep away people jumping out of choppers. If someone manages to jump out of airplane to base, that's acceptable - atleast it's efford, with suicide option included :)

Other "problems" are smaller but still annoying; choppers wander around map searching tents/stashes/vehicles, with airplanes it's still manageable but planes gotta land also at some point to get they guy(s) on the ground. Also removes option to fly around the coast with choppers killing freshspawns or engage vehicles from the air and there's basically nothing you can do. Not many times people drop down huey with stanag-weapons from the ground, if chopper is like 200 metres up in the air shooting at you - which vunerable parts of chopper can you hit? No need to say MI was the biggest cancer to the mod, not gonna miss that.

2 - Melee weapons should be able to bring down any kind of base wall. Just put lots of "hitpoints" to the wall if needed, but don't make walls breakable only with explosives. If it takes 30-45 minutes to hatchet down fully upgraded wall then it's certainly efford to be recognized when someone does it. Melee weapons should also be more powerful, damages redone. Like who would - and why make any upgrades to baseball bat, because it doesn't do damage alot even if modified. Would need like "machete, insta broken leg" and "hatchet, insta death" things. Baseball bat could work like tranquilizer dart, 1 hit and you're out for 2 minutes or so.

3 - Hide stash-option; seen that in non-vanilla server and it was brilliant. Nothing can be seen on the ground, completely invisible stash. You need etool/shovel to get stash visible and accessable again. There are players who quit playing after stash(es) with "couple mosins and medical supplies" are found. Meaning efford and time spent to get gear and then loosing it because there is no way to store them safe lacks. This would keep more new/not so hc players in the game, for some hoarding might just be the reason to play the game in the first place.

4 - Boats with machine gun, minimum 2. Preferable 4 :) Nowadays only fear is huey for sunday fishermans out there. Would make action to ocean also, just the feeling that there could come across (another) armed boat(s) somewhere.

5 - Take away chance to heal infection with resting and/or with herbal drink. Antibiotics are very common, infection is not as bad thing as it supposed to be. Or it was. There was a time when I made suicide after getting infected, because it was "just a matter of time". Time when antibiotics were very rare. It would make them valued, tradeable items and valuable assets for heroes. Also put chance to get infection from well, nowadays drinking from wells is safe and there are too many of them basically. Who needs to boil water in the first place?

6 - Increase number of vehicles a lot (twice?) it is now. Also every spawned vehicle should be drivable, "in bad condition but still moves" kind of thing. Now many of the vehicles are stored inside bases and the ones that aren't are just too time consuming to fix, not worth the efford. This adjustment would move mod away from "running simulator" thing, which might not appeal to some players. Could also put more armed vehicles, meaning basically cars with .50 cals. Action, action...

**Comment by rvett** [comment]
Agree with the general idea of 2 (I don't like the safety bases offer) and 5 (infections are no real threat).
Disagree with 3, 4 and 6.
Don't know about 1, never cared much about choppers apart from the fact that I also think that they are giving the powerful squads even more power over casual players, which I don't like.

**Comment by R4Z0R49** [comment]
1, choppers is a hard topic to cover
2, Melee weapons already take down walls its only curtain levels of walls get explosive only options.
3, Stash system is already being changed however we wont be using the hide option we plan to change the LODS of the models to make them invisible at range. (too some degree).
4, Id have to look if arma has any water vehicles with guns.
5, Heal chance from tents has got a bit changed over the years it was only meant to be from your own tent set up within the generation your playing not all tents. This needs to be updated/fixed.
6, admins can change this already we don't need to do anything.

Thanks for your thoughts
