### ISSUE TITLE
RPT spam with debug messages

### ISSUE THREAD

**Issue by Swiss-Sarge** [DayZMod/DayZ#9]
Hey guys,

just a short notice: why don't you make the rpt logging optional ?

As it is atm, there is a lot being logged, and this clutters up the client and server rpt.

cheers, Sarge

**Comment by fgw-** [comment]
second that!

during update and modification of my addons i rely heavily on debugging info in the rpt logfiles. its a real pain having that much messages in there ...

would be nice to be able to disable all the "informational" stuff.

**Comment by facoptere** [comment]
Could you give some examples of lines to remove? I can't see so many differences on server side.

**Comment by fgw-** [comment]
you'r right, just restarted the server and it doesn't look that bad.

only messages i can see after restart has finished are

18:04:31 "TIME SYNC: Local Time set to [2012,6,6,11,4]"
18:04:31 "DEBUG FPS  : 50.1567"
18:04:31 "CLEANUP:TOTAL 24 LOOT BAGS"

where just the cleanup msg come in once a minute ...

on the client there are mainly the following three messages coming in.

"Survivors:1, FPS:20, FPSMin:19"
"z\addons\dayz_code\compile\player_spawnCheck.sqf Loc.Agents: 0/22. Models: 0/43 W.holders: 0/43 (radius:200m 19fps)."
"z\addons\dayz_code\compile\player_spawnCheck.sqf End. Buildings checked:0, newly zombied:0, already zombied:0, negative timestamp:0."

guess i can disable this messages at my own also. at least during my own testing. its up to you if you prefer to leave this in the mod or not ...

**Comment by Swiss-Sarge** [comment]
put a variable dayz_DEBUG in your init.sqf, and query that before putting out a diag_log, way more elegant.

I did overwrite the function definitions in my init.sqf that log too much like this:

// redefine some functions
if(initialized) then {

```
if(!isServer) then { // client side overwrites

    // spawncheck overwrite
    player_spawnCheck =         compile preprocessFileLineNumbers "addons\fixes\player_spawnCheck.sqf";

};

// client and serverside overwrites

// overwrite vehicle damage handler
fnc_veh_handleDam = compile preprocessFileLineNumbers "addons\fixes\veh_handleDam.sqf";
```

};

And added a query for the debug state in those two files.

Sarge

**Comment by Swiss-Sarge** [comment]
sry misklicked, and seem to have issues with correct formatting of code .-)

**Comment by MattzFiber** [comment]
These logs are quite important server information if something does go wrong and the dev group are trying to fix an issue, it also just gives you an indication of how your server is doing, I do not see it being removed

**Comment by Swiss-Sarge** [comment]
well, i didnt mention to remove them. I mentioned to set a variable to switch them on or off.

that's a major difference.

Sarge

**Comment by dayz10k** [comment]
I will go through and set some #ifdef statements around some debugging code in the SERVER SQF at least.  See how that goes and then work on mission as well.

**Comment by dayz10k** [comment]
merged this as a toggle-able feature in the server PBO

// comment this out if you don't want any LOGIN related debug
#define LOGIN_DEBUG

// comment this out if you don't want any VEHICLE/TENT/OBJECT related debug
#define OBJECT_DEBUG

// comment this out if you don't want any PLAYER (WORLDSPACE/INVENTORY/ETC) related debug
#define PLAYER_DEBUG

// comment this out if you don't want any misc SERVER (ZOMBIE, LOOT, CLEANUP) related debug
#define SERVER_DEBUG

**Comment by Swiss-Sarge** [comment]
thx for the implementation, that already helps a bit.

you missed:

client rpt:

player_spawnCheck.sqf, line 65
player_monitor.fsm, line 1233 (fps client logging)

server rpt:

veh_handleDam.sqf, line 68

cheers, 

Sarge
