### ISSUE TITLE
problem with dmr m14 very high ratting spawn and stash bug

### ISSUE THREAD

**Issue by Yugomen** [DayZMod/DayZ#90]
and dayz should have new sounds for weapon and table loot like dayzero.hoow is posible find military loot on hunter deer stand,or dmr,m14 have very high rating spawn.dayz need big stash,for 3 gun and fix because box of matches or  hunter knife(compas,flashlight,map) takes weapon slot and just one can put in stash,also i can put 10 wheels and 10 engine together in one stash.thats so stupid,that need fix.tools must use 1 item slot.its seriosly problem.please do something about that,mod would be much better :)

**Comment by AlexAFlorov** [comment]
there is no "military" loot on deer stands now. m14 and dmr spawn was lowered too in 1.8
