### ISSUE TITLE
Problems with gutting animals/accessing gear

### ISSUE THREAD

**Issue by Sondre123** [DayZMod/DayZ#91]
Me myself had a problem gutting animals, while others can't take meat of the corpse.

**Comment by dlatz** [comment]
Well, I have same problem, regarding accessing gears on gutted animals.

On the character that was created in 1.7.7.1 survived transition to 1.8 I had no problems with gutting and accessing gear to taking meat in 1.8. But when I die and created new character now I have problems with gear menu not showing up on gutted animal (Cow).

**Comment by Macomber** [comment]
Our 1.7.7.1 > 1.8 players are 100% able to gut an animal, but often they do not have access to take the meat. They are only offered the choice of "hide" or "study" (or weapon change). If we are quick and access the "gear" immediately when it appears in the scroll menu without waiting for the gut animation to end we seem to be successful. If we wait until the animation is over most of the time it fails although the white message text does appear telling us the meat is on the carcass. This happens on any animal.

**Comment by wolf-van-eden** [comment]
Can I just confirm that you do not have to pick up the loots from hunted animals. You can gut the animals but it lacks the dropdown menu to the loot. Although the message is the x pieces of meat are there.

**Comment by Macomber** [comment]
@wolf-van-eden We've done some more hunting and it varies: We are always able to "gut animal" (and so far have always received the message "x pieces of meat") but sometimes lack the context menu to access the loot/meat. The "gear" menu option is sometimes not there even if we scroll while the "gut" animation is still running. If we have no context menu at all we can zoom in and back and it will appear, but without the option to take the loot/meat. Again, sometimes it will be there and we can take loot/meat normally. Doesn't seem to matter which of us do any of the actions (we have each tried to do the whole job, different guys gutting and different guy looting, different animals) and so far have not been able to determine a pattern. A guy who is successful will not be successful next animal, and a guy who has not been successful will be able to take the next one.

**Comment by icomrade** [comment]
The problem has been identified and fixed, wait for the hotfix.
