### ISSUE TITLE
Some wanted changes

### ISSUE THREAD

**Issue by B73** [DayZMod/DayZ#928]
Wishlist for 2018

1. Change player normal temperature from 42 to 37. Inside houses or car (motor running btw) player temp should go up to normal in couple of minutes, now it takes like 45 minutes temp to go up to normal inside house or a car (standing still, no motor running) when having cold.

2. Even 20 players is enough to cap zombie limit (300-350) in servers, with 40-60 players online lack of zombies up north is disturbing. Maybe changing zombie spawns in south (coastal cities) so that they spawn only 1/3 amount? Meaning in north more zombies from single spawn than in south where players spawn. Would also like zombies to be able infect player more, like 20% chance to get infection from every hit you take. Getting rid of infection is way too easy, rest/have antibiotics/herbal drink. I'd remove resting atleast, even herbal drink. 

3. Lack of vehicles due to bases (which can hold even up to 5-7 vehicles). Increase default value of vehicles in mod and let server admins decide if they really want to decrease it from default.

4. Mod needs more vehicles with weapons (pickup PKs & UAZ DShKM and RHIB2Turret to have "naval" fights). Because now there's only few of them they're all locked inside bases and basically static for base defences. Number of armed vehicles should be around 20 or so. If it's like 10 it's most certain they're all locked inside bases. With 20 (or more) there might be a chance some of them isn't sitting static in bases.

5. Gas economy (stockpiling). So many places where you can get fuel, lower litres values would be nice. Too often see >100 litres left. And now that we're talking about gas, why can't player burn a tent with 5 litres can?

6. All (land) vehicles should be drivable from the start. Maybe in bad shape, but drivable. Parts to fix car to premium condition and lack of gas would slow down player, not finding a missing wheel to even move the car in the first place.

7. Instead of hatchets breaking all the time maybe wooden log should take like 10 slots from inventory. Breaking sledgehammers, crowbars, pickaxes etc. doesn't feel real. Maybe mod needs lockpicks which break after each attemp?

**Comment by R4Z0R49** [comment]
You haven't really said anything admins cant already edit if they desire.

1, We need to look over this system the temp system isn't the best atm.
2, Vanilla cap is 500 admins edit this. (Keep in mind vanilla max player count is 45 not 60-70)
3, Admin controlled.
4, We really don't plan to add more armed vehicles due to the issues with ammo.
5, Fuel limits are edited by admins.
6, Admins can edit this if they desire.
7, For now we need to make sure tools are breaking so you do have to replace maybe overtime we can improve this with items like lockpicking.

Thanks
