### ISSUE TITLE
Industrial loot north

### ISSUE THREAD

**Issue by B73** [DayZMod/DayZ#930]
Lack of industrial loot up north makes people lootcycle places like Cherno and areas around spawn places at coast. This lack of loot up north surely adds freshspawn killing (people from north with good gear vs freshspawns with Winchesters). Like Polana factory is most northern decent industrial loot place? Easier to find screws for example from Cherno than anywhere up north. Maybe industrial loot should be increased a lot up north, airports and new military areas included?

It's not like finding one to two boxes of screws when you need 50 of them. Better lootcycle south and coast heavily to save precious time.

**Comment by thcNox** [comment]
Your best source for screws is trains which may not be a problem in itself, in fact it's the only use for the train loot group we have currently and I don't believe that should change however it does make it an issue for the distribution of screws through out the map as obviously currently trains are only found on the coast.

Adding more industrials to the north is probably not a good answer either as the drop chance for screws in them while not poor certainly can't compete with the trains. So one would have to add a lot of industrials before a location would start to contest with the coastal regions for screw farming.

If one could come up with a a way to get a train or a train yard to fit some how in the north somewhere that would be good fix potentially.

**Comment by thcNox** [comment]
https://vignette.wikia.nocookie.net/play-rust/images/4/4e/Trainyard_Overview.jpg

A location such as this would be cool to add to the north. However the problem remains that the rail has to go somewhere. If only there was model for a tunnel opening. then one could just have the rail dissappear into a mountain or something like that.

**Comment by thcNox** [comment]
I have designed a junkyard next to veresnik that features both trains and some industrials.
https://www.dropbox.com/s/gs8nl0h090rq86b/junkyard_01.jpg
https://www.dropbox.com/s/xbhbxl1gy71zyu0/junkyard_02.jpg

**Comment by Inurosen** [comment]
Some fixes to it: https://github.com/DayZMod/DayZ/pull/944
Also there is no loot on trains. Is it intended?
