### ISSUE TITLE
New recipes GPS and screws

### ISSUE THREAD

**Issue by TermNCR** [DayZMod/DayZ#936]
New recipes to use up some unused in-game items.

**Metal Screws**
```
class Blueprint_screws : Recipe {
    displayName = "Metal Screws";
    input[] = 
    {
        {"equip_metal_sheet_rusted","CfgMagazines",1}
    };
    output[] = 
    {
        {"ItemScrews","CfgMagazines",2}
    };
    required[] = 
    {
        {"ItemToolbox","CfgWeapons",1}
    };
};
```

**Crafted GPS**
```
class Blueprint_CraftedGPS : Recipe {
    displayName = "Crafted GPS";
    input[] = 
    {
        {"ItemCompass","CfgWeapons",1},
        {"equip_scrapelectronics","CfgMagazines",1},
        {"equip_pvc_box","CfgMagazines",1}
    };
    output[] = 
    {
        {"ItemGPS","CfgWeapons",1}
    };
    required[] = 
    {
        {"ItemToolbox","CfgWeapons",1},
        {"ItemMatchbox","CfgWeapons",1}
    };
};
```
**{"equip_d_battery","CfgMagazines",1}** Could also be used in the recipe for Crafted GPS but it does not spawn in 1.9.0.

Both work in game and provide the output.

**Comment by Inurosen** [comment]
To be honest i can't come up with any idea how compass an pvc box can be turned into some kind of technically complex device like gps. Even with some scraps.
Also i definately would not use rusted metal to make screws and any other type of parts used to join stuff together.

**Comment by TermNCR** [comment]
Good feedback, 
The GPS would have been better with *ItemRadio* and the *equip_d_battery*, however these things do not spawn in dayz by default.

However I think scrap electronics is a very loose term, as in it could be anything, could include a battery/screen. 

I dont think a bit of oxidation would put me off maintaining my base in the zombie apocalypse however.

Thanks.
