### ISSUE TITLE
Civilian Ural passengers are BE-kicked for PublicVariable Value Restriction #1 when running over evergreen trees

### ISSUE THREAD

**Issue by LinusLeonard** [DayZMod/DayZ#937]
Okay here's a pretty funny issue. Whenever I have a player in the passenger seat of my yellow civilian Ural and run down evergreen trees, the player is kicked by BattlEye for PublicVariable Value Restriction #1. 

RPT: 
```
13:10:06 NetServer::SendMsg: cannot find channel #448344447, users.card=1
13:10:06 NetServer: users.get failed when sending to 448344447
13:10:06 Message not sent - error 0, message ID = ffffffff, to 448344447 (testgubbe)
13:10:07 "INFO - Player: PID#4(testgubbe)(UID: blahblah /CID:89) Status: LOGGED OUT, Location blahblah
```

Public variable log: 
```
#9 "PVDZ_sec_atp" = [<NULL-object>,<NULL-object>,"with Ural (Civil)",2,"",0.0180267]
Value Restriction #1 "PVDZ_sec_atp" = [<NULL-object>,<NULL-object>,"with Ural (Civil)",2,"",0.0180267]
```

Can't blame them really, I would also bail from a truck if it was speeding into a tree ;)

This only seem to affect the passenger seat in the front. Nothing out of the ordinary happens when players are riding on the platform benches in the back of the truck. Also, it only seems to affect civilian Urals, perhaps because they have parenthesis in their names. Tried a military ural as well and everything seems fine. Haven't yet tried other vehicles with parenthesis in their names, like the Gaz (Blue) etc.

Server is 1.9.0, not yet upgraded to QF2. Using stable BE-filters tagged with 1.9.

**Comment by ebayShopper** [comment]
already fixed
https://github.com/DayZMod/DayZ/commit/83bf13c786a94e24b609958b5d2b73c473a3e3d9#diff-97289e7c3a225f4db3dcdcd61f32cfc9L170

https://github.com/DayZMod/DayZ/issues/925
