### ISSUE TITLE
Few things found

### ISSUE THREAD

**Issue by DarthRogue** [DayZMod/DayZ#95]
I'm getting an error in my RPT log.

9:04:06 Warning Message: Script z\addons\dayz_server\compile\server_publishBuilding.sqf not found
 9:04:06 Warning Message: Script z\addons\dayz_server\compile\server_heliCrash_dzn.sqf not found
 9:04:06 Warning Message: Script z\addons\dayz_server\compile\server_medical_ckg_dzn.sqf not found

I have verified that the files are not present in any available server builds.  Including the one listed here, the one from Pwnoz0r and Bliss.  Are these really needed?  If so, where can we get them?

I have also noticed that when you try to repair a vehicle, the entire vehicle gets repaired automatically without having to go through the repair animation and without using any parts from your inventory.

When bandaging, you cannot abort the operation and move around.  Your are frozen until it is done.

Happy bug squashing!  :P

**Comment by Skaronator** [comment]
```
9:04:06 Warning Message: Script z\addons\dayz_server\compile\server_publishBuilding.sqf not found
9:04:06 Warning Message: Script z\addons\dayz_server\compile\server_heliCrash_dzn.sqf not found
9:04:06 Warning Message: Script z\addons\dayz_server\compile\server_medical_ckg_dzn.sqf not found
```

This is custom stuff and has nothing to do with DayZ Mod.

**Comment by DarthRogue** [comment]
I don't believe it's custom.  I used the standard Bliss install package for this server.  And I don't use any mods that call those files.  Even if so, that still leaves two other issues.

**Comment by AlexAFlorov** [comment]
Just do it :)   Trust Skaro!

**Comment by Skaronator** [comment]
Offical DayZ Mod hasnt have this files.
![img](http://stuff.skaronator.com/20130918154148827.png)

**Comment by DarthRogue** [comment]
Ok.  Good to know it's not serious.  I will find where those files are being called and remove the references.  Thanks!  :)  Should I create a different issue ticket for the other two problems?

**Comment by thevisad** [comment]
Please open this on the Reality repo

**Comment by DarthRogue** [comment]
Will do.  Thanks!

**Comment by thevisad** [comment]
FYI, I found and corrected this issue, so download the latest version prior to opening the issue.

**Comment by DarthRogue** [comment]
Will test again tonight. Thanks!
