### ISSUE TITLE
Request to use DayZ 1.8 code in DayZLife

### ISSUE THREAD

**Issue by JamieD1** [DayZMod/DayZ#96]
I would like to ask permission to use DayZ's code and content in the mod i develop called DayZLife. I fully understand the limitations of editing only the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx & dayz_comunityassets. I will include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future releases I make. Cheers looking forward to the decision.

**Comment by Skaronator** [comment]
You must include all Dayz Credits and recreate a new issue post requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested. If you fine with the this info just reply or if you have any other questions regarding the license plz reply.

**Comment by JamieD1** [comment]
I accept the above.
-Jamie Digweed

**Comment by Skaronator** [comment]
alrighty

**Comment by JamieD1** [comment]
Sorry just requesting if this could be put on the license page
