### ISSUE TITLE
issues? Hmmm maybe like arma 2 dayz mod i cant get it to work!

### ISSUE THREAD

**Issue by neil501** [DayZMod/DayZ#961]
i try to add this and i get "no entry bin\CFGWorlds_9"  It says something like that, i cant remember exactly what it said anyway so fed up i'm getting ready to uninstall the entire arma 2 and everything that goes with it! At this point i'm so sick of this not working and going in circles as there is no help for this anywhere i'm told to look at the same old websites that are over 10 years old that have nothing to do with my issue! I used to play this and had no problems i'll just stay with my dayz stand alone version and blacklist arma 2 and anything that goes with it! No reason why they should have made this so difficult to add and play

**Comment by neil501** [comment]
well i decided not to bother! The dayz arma 2 mod no longer works!!! and Hasn't worked in a very long time!! I've been playing on dayz stand alone and it's been getting better and better all the time! I missed the boats and aircraft on dayz mod but it seems they are bringing it all back on dayz standalone! So i sum this up as a loss but standalone as a very big win! RIP DAYZ MOD!!!

**Comment by oiad** [comment]
DayZ mod definitely still works.



On 6 July 2020 9:03:07 am NZST, neil <notifications@github.com> wrote:
>well i decided not to bother! The dayz arma 2 mod no longer works!!!
>and Hasn't worked in a very long time!! I've been playing on dayz stand
>alone and it's been getting better and better all the time! I missed
>the boats and aircraft on dayz mod but it seems they are bringing it
>all back on dayz standalone! So i sum this up as a loss but standalone
>as a very big win! RIP DAYZ MOD!!!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/DayZMod/DayZ/issues/961#issuecomment-653938892

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
