### ISSUE TITLE
Tutorials explaining how to setup a server

### ISSUE THREAD

**Issue by xbelanch** [DayZMod/DayZ#971]
Not a bug, just lack of information or any form of step-by-step guide to help to setup a server. If anyone can provide me a site, youtube video or just a forum post explaining that I'd appreciate it.

**Comment by unhappytroll** [comment]
https://www.google.com/search?q=google+how+to+setup+dayzmod+server

**Comment by xbelanch** [comment]
As far this is the better explanation I've found after googling ;-) @unhappytroll: https://helpthedeadreturn.wordpress.com/2015/12/01/how-to-create-your-own-dayzmod-vanilla-server/

**Comment by unhappytroll** [comment]
just remember, this mod is deprecated and not actively developed for three or four years. and most probably won't be.

**Comment by xbelanch** [comment]
I aware of that. Part nostalgia part preservation I like to host games in my own little server that were significant during the 2010s (like Rust legacy). My thorn in my side is still Origins Mod...
