### ISSUE TITLE
Hi these are just some questions about stuff in general. I'm a newbie

### ISSUE THREAD

**Issue by MrBunnyBunn** [DayZMod/DayZ#974]
So my dad loves this game and for his birthday, he asked if I could to try to mod his server for him and his friend, I have never done this before, and he's giving me like some apps and videos and discords to go to and login on, to learn. I have basic knowledge of Java and Python, and I'm working with HTTPS right now as well, along with dabbles in other languages such as JavaScript, Lua, C++, etc.

Questions: 
1. How hard is it? 
2. How hard is it to code some mods? 
3. How hard is it to implement mods into the game? 
4. Do I actually need to know a lot about code to implement mods if it's basically already made for me? 
5. What type of code do I need to know?

Again, this is for my dad's birthday and stuff and he said he would pay me so any advice/tips or anything is welcome

I have no idea what I'm doing so sorry if this sounds dumb, I haven't done any prior research myself because I just got grounded and I am using my school computer to write this, and all the sites my dad sent me are blocked and I just want to know what I'm getting myself into

If this isn't the right place to be asking these questions, I would like to know where to go when I have questions.

Thank you.

**Comment by unhappytroll** [comment]
don't bother yourself, this mod is long dead and buried.

**Comment by ghost** [comment]
What unhappy troll says. You‘re about 10 years late to the party. I ran several quite successful servers, vanilla to heavily modded, the whole shabang. It is a time consuming mess. The code is pretty accessible, though, but you might do a lot of trail and error. I guess you can still find videos on how to set up a server and such. But I would recommend not to do it for the sake of your sanity.

**Comment by MrBunnyBunn** [comment]
Right. Thank you.
