### ISSUE TITLE
Request to use 1.8 code for DayZ Civilian (Will be renamed to Quarantine)

### ISSUE THREAD

**Issue by Purplish** [DayZMod/DayZ#98]
I would like permission to use the DayZ mod code in DayZ Civilian (Will be renamed to Quarantine)

I will include all DayZ Credits and recreate a new issue post every 3 month requesting continued use of all assets for all future releases I make.

I fully understand the limitations of editing only the 5 main pbo's dayz_code, dayz_anim, dayz_server, dayz_sfx & dayz_comunityassets.

I will seek BIS/Dean Hall's permission to edit any other pbo.

**Comment by Skaronator** [comment]
You must include all Dayz Credits and recreate a new issue post requesting continued use of all assets for all future release you do and be willing to backport code/models/sfx/animations to the official if requested. If you fine with the this info just reply or if you have any other questions regarding the license plz reply.

**Comment by Purplish** [comment]
I agree to the above.

**Comment by Skaronator** [comment]
k ty
